### ISSUE TITLE
升级后的腾讯云收费标准是什么

### ISSUE THREAD

**Issue by feilongproject** [qkqpttgf/OneManager-php#1]
原谅我眼瞎，不知道怎么看收费标准_(:3」∠)_
大概每月是收多少费？

**Comment by qkqpttgf** [comment]
用SCF这个计算加上API网关，这里面有几个地方要收费：
1，SCF的运行资源，你的运行内存*运行时间，单位GBs，腾讯免费40万GBs，超出按量计费；
2，SCF的调用次数，就是每次访问，腾讯免费100万次，超出按量计费；
3，SCF主动访问外网时的流量，对于我们，就是SCF去问一下微软这个文件的直链是啥，一次几十字节吧，但也要算的，无免费额度，香港区1元/G，1小时内累积到0.01元就有帐单，不然就记着，大概200-300次访问的样子吧；
（微软返回给SCF的流量，不收费；）
（SCF返回给API网关的流量，不收费；）
4，API网关返回给浏览器的流量，香港区1元/G，一次大概20-100K左右，应该也是1小时内0.01计帐，API网关虽然收费了，但对于新用户，第一年每个月有1G的免费流量；
5，API网关的调用次数，忘了怎么收费了，也是新用户第一年每个月100万次。
我目前已经扣了我2毛了，一小时内不要一直点（DDCC就…………）

**Comment by feilongproject** [comment]
> 用SCF这个计算加上API网关，这里面有几个地方要收费：
> 1，SCF的运行资源，你的运行内存*运行时间，单位GBs，腾讯免费40万GBs，超出按量计费；
> 2，SCF的调用次数，就是每次访问，腾讯免费100万次，超出按量计费；
> 3，SCF主动访问外网时的流量，对于我们，就是SCF去问一下微软这个文件的直链是啥，一次几十字节吧，但也要算的，无免费额度，香港区1元/G，1小时内累积到0.01元就有帐单，不然就记着，大概200-300次访问的样子吧；
> （微软返回给SCF的流量，不收费；）
> （SCF返回给API网关的流量，不收费；）
> 4，API网关返回给浏览器的流量，香港区1元/G，一次大概20-100K左右，应该也是1小时内0.01计帐，API网关虽然收费了，但对于新用户，第一年每个月有1G的免费流量；
> 5，API网关的调用次数，忘了怎么收费了，也是新用户第一年每个月100万次。
> 我目前已经扣了我2毛了，一小时内不要一直点（DDCC就…………）

了解了，这玩意我为了调试，一个小时之内已经耗了几分钱了_(:3」∠)_
