### ISSUE TITLE
ShareUrl共享链接不能对接世纪互联

### ISSUE THREAD

**Issue by dhlun** [qkqpttgf/OneManager-php#100]
对接世纪互联就会出错！求解决，因为世纪互联没开放api！
下一个版本能否加上此功能！
![image](https://user-images.githubusercontent.com/68416145/88818332-2cf81200-d1f1-11ea-9b02-7c824e4ea97b.png)

**Comment by qkqpttgf** [comment]
这个功能在世纪互联用不了，下下下下个版本也加不上。
你哪个域的世纪互联，是不能用你自己的id&secret的还是限制了其它所有程序？
你换号吧~~~
