### ISSUE TITLE
I can't use this tools fluently

### ISSUE THREAD

**Issue by LeeKonyu** [qkqpttgf/OneManager-php#101]
Hello~! I have a stuipid question about how to use this tools smoothly.
HOW CAN I sign in my OneDrive in this tools?
I only have A MicroSoft account.

**Comment by LeeKonyu** [comment]
![image](https://user-images.githubusercontent.com/47234009/88932204-5af05b80-d2b0-11ea-8143-345badebd9bb.png)

**Comment by LeeKonyu** [comment]
I had an other question about
```
访问 scfonedrive.github.io 的请求遭到拒绝您未获授权，无法查看此网页。
HTTP ERROR 403
```

**Comment by qkqpttgf** [comment]
where u install this program, heroku?
u will install first, after that, u visit the web, and login, then goto setup.
u can add onedrive in setup.

the scfonedrive.github.io may not show this, can u make sure your network to this?
u can visit it, it will show 'code error' and so on.

**Comment by LeeKonyu** [comment]
My way to use this tools on Tecent SCF.
Now when i sign in OneDrive, 'scfonedrive.github.io' also can't be Redirect , but i can fluently go to some foreign website , like 'youtube.com'.

---Original---

**Comment by qkqpttgf** [comment]
你不能直接访问scfonedrive.github.io那我也没办法了啊，正常直接打开这个网址是弹出没有code报错，但你报403我就不知道你网络什么情况了。
要不你开全局试试。

**Comment by LeeKonyu** [comment]
> 你不能直接访问scfonedrive.github.io那我也没办法了啊，正常直接打开这个网址是弹出没有code报错，但你报403我就不知道你网络什么情况了。
> 要不你开全局试试。

我没有直接访问，是在onedrive网站跳转的时候，出现的无法访问…

**Comment by qkqpttgf** [comment]
> > 你不能直接访问scfonedrive.github.io那我也没办法了啊，正常直接打开这个网址是弹出没有code报错，但你报403我就不知道你网络什么情况了。
> > 要不你开全局试试。
> 
> 我没有直接访问，是在onedrive网站跳转的时候，出现的无法访问…

我是说，请你直接访问试试能不能出现【Code error】的提示！！！

**Comment by LeeKonyu** [comment]
> > > 你不能直接访问scfonedrive.github.io那我也没办法了啊，正常直接打开这个网址是弹出没有code报错，但你报403我就不知道你网络什么情况了。
> > > 要不你开全局试试。
> > 
> > 
> > 我没有直接访问，是在onedrive网站跳转的时候，出现的无法访问…
> 
> 我是说，请你直接访问试试能不能出现【Code 为空】的提示！！！

试啦，不行😭谢谢你啦

**Comment by LeeKonyu** [comment]
> > > > 你不能直接访问scfonedrive.github.io那我也没办法了啊，正常直接打开这个网址是弹出没有code报错，但你报403我就不知道你网络什么情况了。
> > > > 要不你开全局试试。
> > > 
> > > 
> > > 我没有直接访问，是在onedrive网站跳转的时候，出现的无法访问…
> > 
> > 
> > 我是说，请你直接访问试试能不能出现【Code 为空】的提示！！！
> 
> 试啦，不行😭谢谢你啦

**哇塞，太感谢了，我刚刚到家试了一下，开全局可以，感谢！！！**
