### ISSUE TITLE
关于heroku的超时问题

### ISSUE THREAD

**Issue by Ecalose** [qkqpttgf/OneManager-php#102]
最近发现若在一个文件夹存较多的文件，当点击28页以后的内容则出现错误
“An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details. You can do this from the Heroku CLI with the command”
我在云函数中测试了同样的问题，发现云函数只要把超时时间增长则不会出现这个问题，所以在heroku中能否增长超时时间呢

**Comment by qkqpttgf** [comment]
呃，28页，好多
因为我程序没有办法将OD的目录结构保存下来，所以翻页是程序一页一页的翻，翻完28页，时间就超了……
我看看有没有其它方法。

**Comment by Ecalose** [comment]
> 呃，28页，好多
> 因为我程序没有办法将OD的目录结构保存下来，所以翻页是程序一页一页的翻，翻完28页，时间就超了……
> 我看看有没有其它方法。

okk

**Comment by mouyase** [comment]
> 呃，28页，好多
> 因为我程序没有办法将OD的目录结构保存下来，所以翻页是程序一页一页的翻，翻完28页，时间就超了……
> 我看看有没有其它方法。

Heroku supports HTTP 1.1 features such as long-polling and streaming responses. An application has an initial 30 second window to respond with a single byte back to the client. However, each byte transmitted thereafter (either received from the client or sent by your application) resets a rolling 55 second window. If no data is sent during the 55 second window, the connection will be terminated.

If you’re sending a streaming response, such as with server-sent events, you’ll need to detect when the client has hung up, and make sure your app server closes the connection promptly. If the server keeps the connection open for 55 seconds without sending any data, you’ll see a request timeout.


有没有可能利用这个防止他超时呢（
