### ISSUE TITLE
能不能把搜索功能加上，然后把这个功能限制为只能在没启用加密路径的时候由用户手动开启？

### ISSUE THREAD

**Issue by ctq333** [qkqpttgf/OneManager-php#103]
我想只要把这个功能限制为在没有启用加密路径的时候才能启用，应该就不用担心加密路径下的文件被索引了，毕竟人家就没用加密路径。而且文件一多，说实话没有搜索功能会对翻找文件带来不便。

**Comment by qkqpttgf** [comment]
不，你理解有误。
我的程序，本地并不存储onedrive的目录结构，所以程序没法以本地内容来搜索，不像其它程序，把目录结构存在本地，只要一句话就能查找了。
#10 ，看这个。
