### ISSUE TITLE
关于自定义mp4播放器

### ISSUE THREAD

**Issue by tomyput** [qkqpttgf/OneManager-php#104]
我通过分析发现您的onemanager通过调用js使用Dplayer播放mp4。
这很棒。
但是Dplayer对于老设备和差网络的支持并不是很好
可用问一下怎么修改默认播放器吗
不甚感激

**Comment by qkqpttgf** [comment]
换nexmoe1或nexmoe2试试？
或者你把默认主题拿去改改~~~
