### ISSUE TITLE
关于自己申请应用ID和机密，不用默认的

### ISSUE THREAD

**Issue by mone520** [qkqpttgf/OneManager-php#108]
所需要哪些权限，或者是直接的还是委托的呢？所有权限都是Microsoft Graph中的吗？

**Comment by Ecalose** [comment]
我也很好奇

**Comment by qkqpttgf** [comment]
应用程序权限，Microsoft Graph 下的 Files.ReadWrite.All及Sites.ReadWrite.All就可以了

**Comment by mone520** [comment]
> 应用程序权限，Microsoft Graph 下的 Files.ReadWrite.All及Sites.ReadWrite.All就可以了

谢谢 thanks

**Comment by Ecalose** [comment]
> 应用程序权限，Microsoft Graph 下的 Files.ReadWrite.All及Sites.ReadWrite.All就可以了

soga

**Comment by Ecalose** [comment]
> 应用程序权限，Microsoft Graph 下的 Files.ReadWrite.All及Sites.ReadWrite.All就可以了

十分感谢

**Comment by cryzlasm** [comment]
新问题, 回调地址应该写哪个呢? 我这边好像是回调地址不对, 然后失败了

**Comment by qkqpttgf** [comment]
> 新问题, 回调地址应该写哪个呢? 我这边好像是回调地址不对, 然后失败了

已经特意提供给你了，你复制不就好了…………还是你用的旧代码看不到？？

**Comment by cryzlasm** [comment]
> > 新问题, 回调地址应该写哪个呢? 我这边好像是回调地址不对, 然后失败了
> 
> 已经特意提供给你了，你复制不就好了…………还是你用的旧代码看不到？？

找到了, 因为那会用的是以前注册的应用, 设的 localhost, 所以回调失败.  `https://scfonedrive.github.io`

**Comment by JellyCooker** [comment]
e5,申请自己的id和密钥，跳转获取token时，弹出 "Error! 有误！No code from MS! 微软code为空！",回调地址已填写https://scfonedrive.github.io 请问是什么原因?

**Comment by qkqpttgf** [comment]
> e5,申请自己的id和密钥，跳转获取token时，弹出 "Error! 有误！No code from MS! 微软code为空！",回调地址已填写https://scfonedrive.github.io 请问是什么原因?

你这样我也不知道原因的。弹出这个，说明填对了。
只能知道你没获取到code。应该有一长串英文啊，这才是正确的问问题要提供的……

**Comment by JellyCooker** [comment]
> > e5,申请自己的id和密钥，跳转获取token时，弹出 "Error! 有误！No code from MS! 微软code为空！",回调地址已填写https://scfonedrive.github.io 请问是什么原因?
> 
> 你这样我也不知道原因的。弹出这个，说明填对了。
> 只能知道你没获取到code。应该有一长串英文啊，这才是正确的问问题要提供的……

错误代码error_description=AADSTS50194。截图如下，麻烦看一下，谢谢!
<img width="765" alt="err" src="https://user-images.githubusercontent.com/23012535/90487199-b786be00-e16c-11ea-958b-e738a722a996.png">

**Comment by qkqpttgf** [comment]
你选应用类型时选的单租户了吧……

**Comment by wsa01378** [comment]
@qkqpttgf 

> 已经特意提供给你了，你复制不就好了…………还是你用的旧代码看不到？？

我也遇到这个大坑，
网上提到SharePoint，清一色提示输localhost，github本首页或wiki完全没提要输https://scfonedrive.github.io

**Comment by qkqpttgf** [comment]
> 网上提到SharePoint，清一色提示输localhost，github本首页或wiki完全没提要输https://scfonedrive.github.io

在你填client id跟secret的时候，有提供那个return uri的。其实用localhost也行，到时按他们教程，把localhost替换也行的。

这种东西都是手动玩才需要的，默认认为你们知道怎么玩了。

**Comment by puppet6** [comment]
手动获取和默认的有什么区别呢

**Comment by xxx854** [comment]
默认的用的人多了，可能会卡

**Comment by puppet6** [comment]
> 默认的用的人多了，可能会卡

那正常上没区别吗

**Comment by xxx854** [comment]
对啊，只不过是应用程序所属人不同而已

**Comment by puppet6** [comment]
我自己弄机密添加一直失败淦

**Comment by puppet6** [comment]
求一个教程文档555

**Comment by xxx854** [comment]
https://login.microsoftonline.com/organizations/oauth2/v2.0/authorize?redirect_uri=https%3A%2F%2Fportal.azure.com%2Fsignin%2Findex%2F&response_type=code%20id_token&scope=https%3A%2F%2Fmanagement.core.windows.net%2F%2Fuser_impersonation%20openid%20email%20profile&state=OpenIdConnect.AuthenticationProperties%3DIBrDbsPr7V-yngiBvMd37qV0dg11SV4_3uDdYTKQeWAa_g3rsYZzsX2udiihFBaCpr3EobVh7MLJ3wkUjY03cqZEpo_PU9dXnQXQJaISu8SWrPlLeAwZOdMa4TTY0lSyR1qQ74NLYunO2SUM49rdgBkrnLTL-sNiq9nfNzlrpOybM_AxRlvZPMOeJp56yB6o2DIRfBbxrOjfjQL8V63b1ivR3VlMaeSvQEGMGvHnVl9jiYUQVxnqLqctVHeMnYvRLXd647V-225qNlFqihf-EYdvZS_EEE6PeP_TbyJQfAWej_NaT3MhYgSzAu5OU8Gp_eIXDvT8GXIf_qqnVzw5Uy47hBZjYiNnpvatGSeQjT88UzFswa934ufpjD3Qp0R2Yx7u2Dx0eKVAwvidt3xJMA&response_mode=form_post&nonce=637635759161502299.Y2NiNGQ1OGQtNzVjNy00NDNiLTg4ZDYtZTQxMTUyZjA2YWRkNjhlZjM2M2EtY2JhYi00ZjZkLWFjODktYjZmODNjMTBhNjc4&client_id=c44b4083-3bb0-49c1-b47d-974e53cbdf3c&site_id=501430&client-request-id=4950f117-158e-41e8-af54-610cad62a840&x-client-SKU=ID_NET472&x-client-ver=6.11.0.0

**Comment by xxx854** [comment]
这个是网址

**Comment by xxx854** [comment]
登陆后点击应用注册，点击新注册，然后名字随便取，接着选择（任何组织目录(任何 Azure AD 目录 - 多租户)中的帐户和个人 Microsoft 帐户(例如，Skype、Xbox）），然后重定向url看上面的回调地址，接着点注册，然后点击API权限，然后在看上面，弄好后，就好了

**Comment by puppet6** [comment]
多谢

**Comment by puppet6** [comment]
选账户的那里我手贱选了第二个，能行吗

**Comment by puppet6** [comment]
不行我就重来

**Comment by xxx854** [comment]
可以，只是个人账户可能用不了这个程序

**Comment by puppet6** [comment]
那我重新来过

**Comment by xxx854** [comment]
你要用的是什么账户

**Comment by puppet6** [comment]
？e5

**Comment by xxx854** [comment]
果然

**Comment by puppet6** [comment]
api权限要改吗

**Comment by xxx854** [comment]
应用程序权限，Microsoft Graph 下的 Files.ReadWrite.All及Sites.ReadWrite.All就可以了

**Comment by xxx854** [comment]
改成这个，作者说的

**Comment by xxx854** [comment]
反正就是文件的读写，你要想也可以加点别的

**Comment by Donny8611** [comment]
回调地址前的“选择平台”选择哪一个呢？

**Comment by puppet6** [comment]
> 回调地址前的"选择平台"选择哪一个呢？

scfonedrive.github.io
