### ISSUE TITLE
话说，能不能设置防盗链啊

### ISSUE THREAD

**Issue by aierlma** [qkqpttgf/OneManager-php#109]
如果设置文件加密，那么自己的网站也没法加载图片了。。。能不能设置防盗链，或者反向代理啥的？小白一只，不是特别懂。或者说，有没有什么类似的东西能实现类似的功能呢

**Comment by aierlma** [comment]
或者，如何才能防止别人看到我的网站上的图片，顺藤摸瓜到我的onemanger进行资源获取啊（捂脸）

**Comment by qkqpttgf** [comment]
防盗链的话，我其实没打算弄，以后再说。
防止顺藤摸瓜？你外链了，肯定能访问到你这个网站的。
你可以去设置里面慢慢看，有一个可以设置，是只加密目录还是目录文件都加密。

**Comment by aierlma** [comment]
啊，我知道了，是不是那个在磁盘选项里的那个设置里，目录内文件可不需要密码下载啊
