### ISSUE TITLE
file_get_contents

### ISSUE THREAD

**Issue by aanbox** [qkqpttgf/OneManager-php#11]
Warning: file_get_contents(https://raw.githubusercontent.com/qkqpttgf/OneManager-php/master/version): failed to open stream: Connection refused in /www/wwwroot/pan.9204.fun/function/common.php on line 266

**Comment by aanbox** [comment]
上传大文件报错，小文件就OK。等待缓存很久！
Warning: file_get_contents(https://raw.githubusercontent.com/qkqpttgf/OneManager-php/master/version): failed to open stream: Connection refused in /www/wwwroot/pan.9204.fun/function/common.php on line 266
{"@odata.context":"https://graph.microsoft.com/v1.0/$metadata#microsoft.graph.uploadSession","e

**Comment by qkqpttgf** [comment]
你可能是安装在国内机器上？连不上raw.githubXXXXXXXX，就会报警。

**Comment by aanbox** [comment]
问题已经解决。果然要放到国外去！
