### ISSUE TITLE
感觉heroku版的速度好慢啊，有什么办法加快吗？

### ISSUE THREAD

**Issue by aierlma** [qkqpttgf/OneManager-php#110]
我是菜鸡，不懂就问。heroku慢的原因是onedrive本身慢还是因为heroku慢啊？换到国内云函数能加速一点吗

**Comment by Ecalose** [comment]
能

**Comment by aierlma** [comment]
又尝试了几次，感觉加载jpg文件的速度明显快于加载png格式，但是腾讯云函数和heroku感觉速度没差啊

**Comment by qkqpttgf** [comment]
1，你连你网站的速度，
2，你网站连微软的速度，
以上是你打开网站的整体速度，

3，你连微软Onedrive的速度，
这个是你下载东西的速度。
