### ISSUE TITLE
无法识别文件夹大小

### ISSUE THREAD

**Issue by a2396837** [qkqpttgf/OneManager-php#111]
感谢作者大大提供这么好的程序！
但是目前我的heroku版本碰到一个问题，如图，只能识别文件的大小，却不能识别文件夹大小
![](https://cdn.jsdelivr.net/gh/a2396837/CDN@latest/images/2020/08/13/2c0473f35c86e2e655a4e255a51bb343.png)
![](https://cdn.jsdelivr.net/gh/a2396837/CDN@latest/images/2020/08/13/ef037e2fd3ebd27b14022b3c6a346cff.png)

**Comment by a2396837** [comment]
heroku版本

**Comment by qkqpttgf** [comment]
可能要等等，过几个小时
