### ISSUE TITLE
设置站点图标和添加评论模块

### ISSUE THREAD

**Issue by wallleap** [qkqpttgf/OneManager-php#112]
### 1、站点图标
将favicon.ico放到第一个盘中即可。

### 2、valine评论支持
按valine官网教程，修改好appId和appKey之后，将代码保存为foot.omf，把这个文件到想要放置评论的文件夹(Onedrive中)内。

**Comment by qkqpttgf** [comment]
评论模块本来就没加。
只是增加了可以放js的head.omf与foot.omf文件，与head.md，readme.md一样使用就好。
这个文件又不是只能放评论。

**Comment by wallleap** [comment]
> 是只能放评论。

嗯嗯
