### ISSUE TITLE
关于腾讯云函数，阿里云函数，华为云函数，百度云函数哪个最便宜？

### ISSUE THREAD

**Issue by Winyer** [qkqpttgf/OneManager-php#116]
如题，有用过的老哥知道的么？我只用过腾讯云函数，三天两头的收费，不知道怎么会这么多计费，还有exe/zip/7z等格式为什么不走直连呢，这个在哪设置啊，打开exe的url后面还跟了个?preview，有什么方法可以自动去掉这种非视频格式后面的?preview么？？

**Comment by qkqpttgf** [comment]
收费问题，可能你访客有点多。这几个severless，收费都差不多的，计算资源有免费额度，但输出的流量没有(腾讯第一年有1G，百度有1G)，自己用一般没问题，用的人多就会扣钱了。
要不你用heroku吧。
preview这个问题，前几天在QQ群跟一个人纠结了很久，说人家oneindex点进去自动判断。我只想说个人风格问题，我觉得我这样对程序友好。
多习惯一下就好了。

**Comment by Winyer** [comment]
好的，我还是去买个vps或者买个虚拟空间吧，感谢大牛热心回答，对了，exe等格式文件无直连显示还是?preview怎么办呢
