### ISSUE TITLE
反代后在线播放的链接问题

### ISSUE THREAD

**Issue by Sonniferi** [qkqpttgf/OneManager-php#117]
![image](https://user-images.githubusercontent.com/29766602/91627260-cbda7e80-e9e8-11ea-9b3b-e86ef6fe1382.png)
![image](https://user-images.githubusercontent.com/29766602/91627276-ea407a00-e9e8-11ea-988e-bb296f8088a1.png)

在后台填写了反代地址  在线发布的地址依然是SharePoint的源地址  搭建的方式是无函数

**Comment by qkqpttgf** [comment]
主题用默认哟，其它的没改

**Comment by Sonniferi** [comment]
哦哦好的
