### ISSUE TITLE
BadRequest

### ISSUE THREAD

**Issue by sayviness** [qkqpttgf/OneManager-php#118]
Unable to retrieve user's mysite URL.
权限都添加了，回调地址也用的安装步骤里的。然后显示这个。

BadRequest
返回首页

Unable to retrieve user's mysite URL.
返回

**Comment by qkqpttgf** [comment]
这种一般是你的onedrive被微软做掉了，虽然你帐号在，但用不了onedrive。

**Comment by sayviness** [comment]
> 这种一般是你的onedrive被微软做掉了，虽然你帐号在，但用不了onedrive。

haha，后来进onedrive发现了，都没注意翻车了。谢了兄弟

**Comment by yhyedu4521** [comment]
![image](https://user-images.githubusercontent.com/58435972/162256295-d62c9fda-d8c8-4926-b147-75f5c889a96a.png)
我登陆了自己的世纪互联，是可以登陆的，而且OneDrive也能正常使用

**Comment by yhyedu4521** [comment]
https://service-krpk7xs4-1252613227.hk.apigw.tencentcs.com/release/sjhlOD/
但是腾讯云也不能用

**Comment by yhyedu4521** [comment]
应该是微软或者管理员关闭了程序权限？

**Comment by qkqpttgf** [comment]
#40 ，
