### ISSUE TITLE
游客上传文件后，名字变成乱码

### ISSUE THREAD

**Issue by Eight-God** [qkqpttgf/OneManager-php#119]
![image](https://user-images.githubusercontent.com/52270086/92598284-2faf5200-f2db-11ea-8a2c-4c6216703589.png)
上传以后名字没了，这是后台设置
![image](https://user-images.githubusercontent.com/52270086/92598374-481f6c80-f2db-11ea-9cf3-c5ad1b5ceaac.png)
想请教一下大大，这是我的设置问题么，
然后还有之前做游客上传，这样设置是可以的
![image](https://user-images.githubusercontent.com/52270086/92598704-bebc6a00-f2db-11ea-85c5-c86f79abbd9f.png)
然后今天后台点了更新了系统，然后删了一下盘添加上就不行了，设置的路径貌似是无效的？只有根目录这个字符是有效的。只是想做好游客上传功能自己平常当网盘用着方便点。想请问一下大大，如果想做游客上传需要怎么操作比较好。希望大大能解惑。

**Comment by qkqpttgf** [comment]
游客就是游客，游客只能保存成md5。
[什么时候md5叫乱码了，没见过乱码吗……]
关于这个路径，并没有改动什么，你再试试（设置后静置5分钟再看，有时候反应不过来）。

**Comment by ColderCoder** [comment]
@qkqpttgf 是否能让游客上传的文件保留原文件名呢？

**Comment by qkqpttgf** [comment]
> @qkqpttgf 是否能让游客上传的文件保留原文件名呢？

定位是个人分享网站，只是具有图床功能，不想做多人帐号上传，更不想做作业上传点。
