### ISSUE TITLE
加密问题

### ISSUE THREAD

**Issue by aanbox** [qkqpttgf/OneManager-php#12]
我想加密一个目录
passfile 设置为admin.txt
然后在目录里面 点击 管理 加密 输入密码为admin.txt 但是没有加密。
还有 缓存可以在宝塔里面设置自动刷新吗？每次要自己点

**Comment by qkqpttgf** [comment]
加密了的，你等1小时就好了，或者，进去那个目录，点刷新缓存，要进去那个目录再点刷新缓存。
其它程序是过个10分钟或半小时，把所有的目录结构都缓存到本地，
我这边只有当访问的时候才缓存本目录1小时，1小时后缓存就死掉，点了刷新缓存的话，把当前目录的缓存杀死，重新缓存。
