### ISSUE TITLE
视频显示字幕

### ISSUE THREAD

**Issue by odtest09** [qkqpttgf/OneManager-php#120]
可能让视频显示字幕吗？

**Comment by mone520** [comment]
默认支持dplayer，建议自己添加字幕

**Comment by yubanmeiqin9048** [comment]
同问外挂字幕

**Comment by yubanmeiqin9048** [comment]
> 默认支持dplayer，建议自己添加字幕

添加字幕是指外挂还是压到视频里面？

**Comment by jimao233** [comment]
楼主解决了吗

**Comment by yubanmeiqin9048** [comment]
> 楼主解决了吗

potplayer://直链，就可以了（前提是你的视频内挂字幕）

**Comment by jimao233** [comment]
这样太麻烦，而且不是所有视频都内置字幕。我看dplayer原本好像有这个功能，但是被阉割了？

**Comment by yubanmeiqin9048** [comment]
> 这样太麻烦，而且不是所有视频都内置字幕。我看dplayer原本好像有这个功能，但是被阉割了？

我说的是你自己MKVTOOL封装上去

**Comment by jimao233** [comment]
我知道，但是很多视频都不是mkv格式，而且字幕后续还需要调整，要是能直接外挂字幕的话会非常方便

**Comment by yubanmeiqin9048** [comment]
> 我知道，但是很多视频都不是mkv格式，而且字幕后续还需要调整，要是能直接外挂字幕的话会非常方便

MKV只是一个能塞各种各样东西的容器而已，你直接把MP4丢MKVTOOL也是一样

**Comment by 1219099256** [comment]
[http://www.mvpsliu.tk/od/img/Snipaste_2021-03-04_21-24-36.png](url)
打开链接，然后添加字幕即可

**Comment by zjboy1984** [comment]
> ![Snipaste_2021-03-04_21-24-36](https://user-images.githubusercontent.com/63403797/109980031-75a11c00-7d3a-11eb-8a4a-a8b4c99db98f.png)
> 打开链接，然后添加字幕即可

这是什么播放软件？

**Comment by 1219099256** [comment]
> > ![Snipaste_2021-03-04_21-24-36](https://user-images.githubusercontent.com/63403797/109980031-75a11c00-7d3a-11eb-8a4a-a8b4c99db98f.png)
> > 打开链接，然后添加字幕即可
> 
> 这是什么播放软件？

potplayer[http://potplayer.daum.net/?lang=zh_CN](url)可能需要科学
