### ISSUE TITLE
关于回调url

### ISSUE THREAD

**Issue by wangjiale1125** [qkqpttgf/OneManager-php#123]
回调url一定要用提供的吗？能不能使用自己的url

**Comment by qkqpttgf** [comment]
你可以使用localhost，
但如果用这个项目的话，最好用我提供的那个github的url，这样操作过程是一路自动跳转的。

**Comment by wangjiale1125** [comment]
> 你可以使用localhost，
> 但如果用这个这个项目的话，最好用我提供的那个github的url，这样操作过程是一路自动替换的。

那如果要用localhost的话需要修改哪些位置呢？

**Comment by qkqpttgf** [comment]
> > 你可以使用localhost，
> > 但如果用这个这个项目的话，最好用我提供的那个github的url，这样操作过程是一路自动替换的。
> 
> 那如果要用localhost的话需要修改哪些位置呢？

改很多……你用其它程序就按他们的来，用我的就按我的，这样比较方便，一路火花带闪电的跳转就结束了。
