### ISSUE TITLE
不能对接OneDrive

### ISSUE THREAD

**Issue by masterbiu** [qkqpttgf/OneManager-php#124]
设置完id和secret后跳转界面就是这样，setup界面就要求重新添加，试过几次了都是这样
![Snipaste_2020-09-25_19-42-13](https://user-images.githubusercontent.com/28528778/94263228-499d9580-ff67-11ea-9df4-e523103722e8.png)

![Snipaste_2020-09-25_19-44-45](https://user-images.githubusercontent.com/28528778/94263412-95503f00-ff67-11ea-9342-afa1f3d99e91.png)

**Comment by qkqpttgf** [comment]
MS365?这是群里的吧，还在改呢，而且只能浏览不能管理。
有问题群里说就好，这里提issue应该要针对master的。

**Comment by masterbiu** [comment]
我没加群。。。

**Comment by qkqpttgf** [comment]
> 我没加群。。。

那这个安装包你从哪来的……

**Comment by masterbiu** [comment]
直接用的master下的源码

**Comment by qkqpttgf** [comment]
> 直接用的master下的源码

好吧，我看错了。
我仔细看了下，知道你问题出在哪行代码，但我目前不知道你为什么会出问题……

**Comment by qkqpttgf** [comment]
现在怎么样了？
