### ISSUE TITLE
建议增加“是否代理”的选项

### ISSUE THREAD

**Issue by Seeger0216** [qkqpttgf/OneManager-php#125]
作者你好，如题，我部署在了我的vps上，但是下载仍然是my-SharePoint.com，建议增加这个选项，可以让vps和cdn反向代理，加快下载速度。

**Comment by Taixiaopeng** [comment]
自己看看管理界面 仔细阅读

**Comment by qkqpttgf** [comment]
早就有这个功能了，
程序可以将微软网址替换成你填的，那边怎么设置就是你的事情了。

**Comment by Seeger0216** [comment]
> 早就有这个功能了，
> 程序可以将微软网址替换成你填的，那边怎么设置就是你的事情了。

我知道有这个功能，但是不会配置那边啊……能不能有一个一键替换的功能，直接让程序经过程序所在的vps进行代理

**Comment by qkqpttgf** [comment]
> > 早就有这个功能了，
> > 程序可以将微软网址替换成你填的，那边怎么设置就是你的事情了。
> 
> 我知道有这个功能，但是不会配置那边啊……能不能有一个一键替换的功能，直接让程序经过程序所在的vps进行代理

抱歉，
首先，可能我技术不行，没想到怎么从php里面控制nginx或其它，
另外，这个项目是基于severless的，不可能做个不通用的功能出来。
VPS上其它项目已经很强大了，竞争不过。

**Comment by Seeger0216** [comment]
> > > 早就有这个功能了，
> > > 程序可以将微软网址替换成你填的，那边怎么设置就是你的事情了。
> > 
> > 
> > 我知道有这个功能，但是不会配置那边啊……能不能有一个一键替换的功能，直接让程序经过程序所在的vps进行代理
> 
> 抱歉，
> 首先，可能我技术不行，没想到怎么从php里面控制nginx或其它，
> 另外，这个项目是基于severless的，不可能做个不通用的功能出来。
> VPS上其它项目已经很强大了，竞争不过。
> #121 可参考这个issue。

抱歉我是个萌新，只是会简单的搭建而已……请问您有没有合适的Nginx配置文件？#121的文件即使改成了我的组织名也无法使用……提示DNS_PROBE_FINISHED_NXDOMAIN
