### ISSUE TITLE
目前 SCF 有理想的反代方法吗？

### ISSUE THREAD

**Issue by QingxuMo** [qkqpttgf/OneManager-php#127]
腾讯云 SCF 自定义域名需要备案，我今天试了一天 Cloudflare Workers 反代都是 500。好奇有没有什么可用的反代方法实现自定义域名。

**Comment by qkqpttgf** [comment]
项目中已经自带一个workers代码……

**Comment by QingxuMo** [comment]
> 项目中已经自带一个workers代码……

已解决，感谢😂

**Comment by jimao233** [comment]
腾讯云scf选择香港服务器不是不要求备案吗

**Comment by RimuruW** [comment]
我这选香港也要求备案……可能是我操作有误吧😂

腾讯云已经砍掉每月免费额度了，已经放弃了

**Comment by jimao233** [comment]
砍掉了吗，为啥我在scf里看还有额度
![image](https://user-images.githubusercontent.com/24926585/105047759-a535e680-5a62-11eb-9228-771446afc24e.png)

**Comment by RimuruW** [comment]
现在好像把按月的免费额度改成免费一年了

**Comment by jimao233** [comment]
在站内信里看到了调整通知，但是在控制台里到处都找不到还剩多久免费时间...
