### ISSUE TITLE
如何屏蔽爬虫

### ISSUE THREAD

**Issue by 1049066154** [qkqpttgf/OneManager-php#130]
![屏幕截图 2020-10-11 204254](https://user-images.githubusercontent.com/46583730/95678946-5cb89280-0c02-11eb-9e02-9bd4bf70df49.jpg)
谷歌的爬虫频繁的抓取我的页面，没加密码的话几分钟就来一次，加了密码就半小时一次，有没有办法屏蔽，或者能不能实现robots.txt文件的功能

**Comment by qkqpttgf** [comment]
你以前robots.txt是怎么让google不爬，那现在一样啊
