### ISSUE TITLE
关于在azure函数上搭建

### ISSUE THREAD

**Issue by Seeger0216** [qkqpttgf/OneManager-php#132]
偶人看到azure免费服务的有一项“函数”，是不是也是serverless服务器呢？是否可以适配或者给个简单的教程？谢谢

**Comment by qkqpttgf** [comment]
是说那个闪电图标的函数应用？
我记得我瞅过一眼，不能php。

**Comment by srcenchen** [comment]
那个那个那个 https://portal.azure.com/#create/Microsoft.WebSite
这玩意 可以 php 但是我配不了rewrite
叫 Web 应用 也免费

**Comment by qkqpttgf** [comment]
> 那个那个那个 https://portal.azure.com/#create/Microsoft.WebSite 这玩意 可以 php 但是我配不了rewrite 叫 Web 应用 也免费

我，没权限玩它

**Comment by srcenchen** [comment]
那玩意永久免费把
