### ISSUE TITLE
为啥设置好了密码文件，但用文件内的密码就是不对呢？

### ISSUE THREAD

**Issue by nethawkhu** [qkqpttgf/OneManager-php#134]
为啥设置好了密码文件，但用文件内的密码就是不对呢？

**Comment by qkqpttgf** [comment]
你是直接上传密码文件的，还是在管理功能里面加密的？
另外，加密功能先用默认主题测试后再换成其它主题

**Comment by nethawkhu** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        我是原来 OneIndex 用户，所以本身里面放了密码文件的。
        
    
        
            
        
    
    
        
        

        
    

    在2020年10月21日 17:26，qkqpttgf<notifications@github.com> 写道： 




你是直接上传密码文件的，还是在管理功能里面加密的？

另外，加密功能先用默认主题测试后再换成其它主题

**Comment by qkqpttgf** [comment]
OneManager不默认使用.password文件
需要你去后台设置一个文件名来使用
请！没！事！多！去！设！置！里！面！瞅！瞅！

**Comment by nethawkhu** [comment]
我当然在后台设置过了的，否则我的问题不是文件内的密码不对，而是问设置了密码但没有提示输入密码。你的配置内容又没几个，我当然是全部看完了再提问的。

**Comment by qkqpttgf** [comment]
> 我当然在后台设置过了的，否则我的问题不是文件内的密码不对，而是问设置了密码但没有提示输入密码。你的配置内容又没几个，我当然是全部看完了再提问的。

是用的默认主题吗？

**Comment by qkqpttgf** [comment]
现在怎么样了？

**Comment by tengxunkuku** [comment]
曾经遇到过这个问题，应该是个bug
