### ISSUE TITLE
文件夹内文件过多，但只能显示第一页

### ISSUE THREAD

**Issue by EIGHTfs** [qkqpttgf/OneManager-php#136]
虽然onemanager会分页，但是除了第一页什么文件都看不见

**Comment by qkqpttgf** [comment]
是用的默认主题吗？

**Comment by EIGHTfs** [comment]
> 是用的默认主题吗？

https://cdn.jsdelivr.net/gh/kizx/onemoe-theme/onemoe.html

用的这个
我试试换个主题

**Comment by EIGHTfs** [comment]
> > 是用的默认主题吗？
> 
> https://cdn.jsdelivr.net/gh/kizx/onemoe-theme/onemoe.html
> 
> 用的这个
> 我试试换个主题

试了各种主题，都不行，heroku搭建的

**Comment by qkqpttgf** [comment]
我这边正常，不知道你什么情况，又不给我看。

对了，你是不是用什么CDN了，比如CF。
