### ISSUE TITLE
带空格路径的文件在预览时无法下载

### ISSUE THREAD

**Issue by BloveDawn** [qkqpttgf/OneManager-php#137]
带空格路径的文件在点击预览进入预览界面后下载失败

错误报告：

```JSON
{
"error_msg": "The API does not exist or has not been published in the environment",
"error_code": "APIG.0101",
"request_id": "33*******32*****41*3*****89***a9"
}
```

**Comment by BloveDawn** [comment]
此类文件在未预览时，也就是文件夹页面中可以正常下载

**Comment by qkqpttgf** [comment]
我在heroku的demo，世纪互联里面的歌就是有空格的，能正常下载。
这个报错，似乎是API网关的报错，另外你用的主题是哪个，换默认主题试试？

**Comment by BloveDawn** [comment]
我测试了一下发现没有问题了  
可能是我之前的更改导致的  
原来我将API路径设置为`/pan`，整体路径是`https://pan.example.com/pan`  
现在我改成了`https://pan.example.com/`这样的形式  
我对WEB不太了解，但是我觉得这应该是导致它变好了的原因
