### ISSUE TITLE
上传文件 会出现多出现一个 .tmp的文件

### ISSUE THREAD

**Issue by FeiYuab** [qkqpttgf/OneManager-php#138]
使用OneManager网页上传文件 上传成功后会多出一个.tmp文件
![0](https://user-images.githubusercontent.com/62853935/97470567-a0d9c000-1982-11eb-9fe8-e71dd708c62f.png)
![1](https://user-images.githubusercontent.com/62853935/97470572-a2a38380-1982-11eb-8ef1-dc7ca3f0baa8.png)
![2](https://user-images.githubusercontent.com/62853935/97470574-a33c1a00-1982-11eb-86ca-d893b164e9eb.png)

**Comment by FeiYuab** [comment]
部分模板会出现
classic.html就没有这种情况
tfo_mdtr.php会出现
其他模板未测试

**Comment by qkqpttgf** [comment]
这个.tmp文件，是程序用来保存上传链接的，以便于断点续传，正常会在上传成功后删除。
有些主题很久没更新了，可能删除失败，
共享链接（shareurl）方式的盘，可能删除失败。

**Comment by Huiaei** [comment]
在后台管理页面上传也会出现这个文件

**Comment by qkqpttgf** [comment]
> 在后台管理页面上传也会出现这个文件

哪个后台管理

**Comment by Huiaei** [comment]
> > 在后台管理页面上传也会出现这个文件
> 
> 哪个后台管理

就是管理员登录后的默认页面。后面发现好像是因为文件上传到一半卡住不动后重新上传导致的。
