### ISSUE TITLE
在选择语言后出现 504 Gateway Time-out

### ISSUE THREAD

**Issue by parozhao** [qkqpttgf/OneManager-php#14]
流程：

添加 SecretId 和 SecretKey
点击<u>API网关触发器</u>中的<u>访问路径</u>
**显示	Error	refresh_token not exist, click to install.**
点击 <u>click to install</u>
在选择语言界面选择<u>中文</u>，填写<u>管理密码</u>，点击<u>确认</u>

此时，如果把<u>超时时间</u>设为3s，

则显示	**{"errorCode":-1,"errorMessage":"Task timed out after 3 seconds"}**

如果把<u>超时时间</u>设为5s+，

则显示	**504 Gateway Time-out	apigw/1.0.16_1.3.3**

**Comment by HuaienYao** [comment]
我也是出现这个问题，SCF香港

**Comment by HuaienYao** [comment]
> 流程：
> 
> 添加 SecretId 和 SecretKey
> 点击API网关触发器中的访问路径
> **显示 Error refresh_token not exist, click to install.**
> 点击 click to install
> 在选择语言界面选择中文，填写管理密码，点击确认
> 
> 此时，如果把超时时间设为3s，
> 
> 则显示 **{"errorCode":-1,"errorMessage":"Task timed out after 3 seconds"}**
> 
> 如果把超时时间设为5s+，
> 
> 则显示 **504 Gateway Time-out apigw/1.0.16_1.3.3**

Heroku版可以正常用，SCF也会产生费用，还是用Heroku或者VPS吧

**Comment by qkqpttgf** [comment]
昨晚试了一下，由于没有获取到正确的region，所以程序死循环了（笑哭
等腾讯3月做好吧。

**Comment by qkqpttgf** [comment]
直接做了下拉菜单，继续等腾讯做好
