### ISSUE TITLE
大大您好，加密疑问

### ISSUE THREAD

**Issue by GillianJiao** [qkqpttgf/OneManager-php#141]
您好作者，就是咱们这个加密可不可以只加密文件夹，不加密内容，

说下我遇到的情况，我把视频直链放到网站上面视频不能播放了，发现是设置了密码出现的问提，

程序是加密了，直链文件也需要输入密码，放到网站播放就出不来，

希望大大能加一个只加密文件夹的文件夹内的内容不连带加密

谢谢大佬，期望能采纳

**Comment by qkqpttgf** [comment]
这就是不看设置的结果，去设置里面慢慢找。
