### ISSUE TITLE
搭建完之后，打开网站很正常，如果登出网站之后再打开就是会变成如图所示

### ISSUE THREAD

**Issue by bgghue** [qkqpttgf/OneManager-php#142]
![微信图片_20201107165408](https://user-images.githubusercontent.com/52739095/98436917-e1230600-2119-11eb-94b5-37276d20c78e.png)

我已经试过很多次搭建了，手机端打开也是显示这个界面

**Comment by qkqpttgf** [comment]
我觉得这玩意跟我无关？
这是啥东西…………

**Comment by bgghue** [comment]
> 我觉得这玩意跟我无关？
> 这是啥东西…………

我也不知道啊，我现在重新搭建一波，会不会是因为我用了自带的主题

**Comment by Zkycardistry** [comment]
> > 我觉得这玩意跟我无关？
> > 这是啥东西…………
> 
> 我也不知道啊，我现在重新搭建一波，会不会是因为我用了自带的主题

你是不是来错地方了，这里是onemanager

**Comment by qkqpttgf** [comment]
> > 我觉得这玩意跟我无关？
> > 这是啥东西…………
> 
> 我也不知道啊，我现在重新搭建一波，会不会是因为我用了自带的主题

你在哪搭建的？

**Comment by bgghue** [comment]
> > > 我觉得这玩意跟我无关？
> > > 这是啥东西…………
> > 
> > 
> > 我也不知道啊，我现在重新建造一波，会不会是因为我用了自带的主题
> 
> 你在哪建造的？

heroku

**Comment by bgghue** [comment]
> > > 我觉得这玩意跟我无关？
> > > 这是啥东西…………
> > 
> > 
> > 我也不知道啊，我现在重新建造一波，会不会是因为我用了自带的主题
> 
> 你在哪建造的？

![微信截图_20201107171029](https://user-images.githubusercontent.com/52739095/98437322-2f390900-211c-11eb-9bee-528d77aee69b.png)
你看，我换了这个主题，然后我登出，再刷新一下，再进入我问题发的那个截图的画面了

**Comment by qkqpttgf** [comment]
设置里面给我瞅瞅，heroku后台给我瞅瞅。
我demo没这样。

**Comment by bgghue** [comment]
> 设置里面给我瞅瞅，heroku后台给我瞅瞅。
> 我demo没这样。

大佬，我找到问题在哪了，我只要这里设置一下，网页就开始发神经
![微信图片_20201107171812](https://user-images.githubusercontent.com/52739095/98437467-3ca2c300-211d-11eb-95fa-9655114f9f5c.png)

**Comment by qkqpttgf** [comment]
我猜到为什么了，OneManager遇到某个目录有index.html的时候，会以静态网站来显示index.html，就不列目录了。

**Comment by bgghue** [comment]
> 我猜到为什么了，OneManager遇到某个目录有index.html的时候，会以静态网站来显示index.html，就不列目录了。

不愧是大神

**Comment by bgghue** [comment]
> 我猜到为什么了，OneManager遇到某个目录有index.html的时候，会以静态网站来显示index.html，就不列目录了。

就是这个鬼问题，裂开
