### ISSUE TITLE
建议给domainforproxy功能增加一个更多设置的选项

### ISSUE THREAD

**Issue by ifloppy** [qkqpttgf/OneManager-php#143]
我用PHP做迫真反向代理，不会写这个伪静态规则(笑哭)，所以能否改一下，把这个下载地址放进一个PHP网页的GET参数里

**Comment by qkqpttgf** [comment]
没看懂需求

**Comment by ifloppy** [comment]
我正在用PHP写反向代理程序，~~方便薅BYET的羊毛~~方便利用一些免费的虚拟主机做反向代理
我写了一个简单的PHP反向代理脚本(https://github.com/ifloppy/phpSimpleProxy)，想拿来在虚拟主机上做反代，代理OneDrive
希望给domainforproxy增加一个选项，让我可以把OneDrive返回的下载地址放入反代脚本的参数中

**Comment by Crazy-White** [comment]
这个也许满足你的需求  
https://github.com/Crazy-White/unpkg-proxy/tree/master/lib/pathHandler  
或者直接 `$_SERVER['PATH_INFO']`
