### ISSUE TITLE
nginx,php7.4,sqlite3,openwrt一键更新失败

### ISSUE THREAD

**Issue by Xunflash** [qkqpttgf/OneManager-php#145]
报错
Deprecated: strpos(): Non-string needles will be interpreted as strings in the future. Use an explicit chr() call to preserve the current behavior in /mnt/sda1/xzz/common.php on line 1251

Fatal error: Uncaught Error: Class 'PharData' not found in /mnt/sda1/xzz/platform/Normal.php:289 Stack trace: #0 /mnt/sda1/xzz/common.php(1766): OnekeyUpate('qkqpttgf', 'OneManager-php', 'master') #1 /mnt/sda1/xzz/common.php(244): EnvOpt(1) #2 /mnt/sda1/xzz/index.php(41): main('/Apks/') #3 {main} thrown in /mnt/sda1/xzz/platform/Normal.php on line 289

**Comment by qkqpttgf** [comment]
Class 'PharData' not found，你家php没有PharData，重装php或重新编译php吧
我程序不用数据库，sqlite用不上

**Comment by Xunflash** [comment]
> Class 'PharData' not found，你家php没有PharData，重装php或重新编译php吧
> 我程序不用数据库，sqlite用不上

算了算了，自己覆盖更新了，可能由于路由器上面搭的，系统适配问题，或者是我安装出毛病了，总之能用就行吧。还有一个问题，移动文件一直显示400错误
![image](https://user-images.githubusercontent.com/71567536/98492758-c6fd3b00-2273-11eb-9df1-0008a85b8397.png)

**Comment by qkqpttgf** [comment]
这个，你用默认主题还是哪个主题？
其它主题可能不再维护了，用默认主题也有问题再找我吧。

**Comment by Xunflash** [comment]
> 这个，你用默认主题还是哪个主题？
> 其它主题可能不再维护了，用默认主题也有问题再找我吧。

![image](https://user-images.githubusercontent.com/71567536/98505029-4817fa80-2293-11eb-9fcb-91fb67f7798a.png)
还是有问题啊，但是信息那一栏不一样了

**Comment by qkqpttgf** [comment]
在我DEMO测试了很多，没有这个问题……中文文件，中文目录，都可以……
所以不清楚你哪里有问题……

**Comment by Xunflash** [comment]
> 在我DEMO测试了很多，没有这个问题……中文文件，中文目录，都可以……
> 所以不清楚你哪里有问题……

我刚刚又测试了，使用默认主题是可以进行移动操作的，但是不能往上一级目录移动，向上一级移动就会出现invalidrequest提示。

**Comment by qkqpttgf** [comment]
> > 在我DEMO测试了很多，没有这个问题……中文文件，中文目录，都可以……
> > 所以不清楚你哪里有问题……
> 
> 我刚刚又测试了，使用默认主题是可以进行移动操作的，但是不能往上一级目录移动，向上一级移动就会出现invalidrequest提示。

微软应该是对/../表达上级目录做了限制，其实用/../，微软可以识别（理由：上级目录有相同文件名时，这个文件向上级目录移动会提示名称已经存在），但到最后一步时，微软不给你移动……
以前可以这么操作的。
刚刚改好了，你更新试一下吧~

**Comment by Xunflash** [comment]
> > > 在我DEMO测试了很多，没有这个问题……中文文件，中文目录，都可以……
> > > 所以不清楚你哪里有问题……
> > 
> > 
> > 我刚刚又测试了，使用默认主题是可以进行移动操作的，但是不能往上一级目录移动，向上一级移动就会出现invalidrequest提示。
> 
> 微软应该是对/../表达上级目录做了限制，其实用/../，微软可以识别（理由：上级目录有相同文件名时，这个文件向上级目录移动会提示名称已经存在），但到最后一步时，微软不给你移动……
> 以前可以这么操作的。
> 刚刚改好了，你更新试一下吧~

可以了，我刚刚测试了，感谢
