### ISSUE TITLE
作者关于api请求限制优化

### ISSUE THREAD

**Issue by GillianJiao** [qkqpttgf/OneManager-php#146]
管理我给世纪互联的技术打电话他们说没有明确的api请求限制，

Best practices to handle throttling
Reduce the number of operations per request
Reduce the frequency of calls
Decorate your traffic so we know who you are (see section on traffic decoration best practice more on that below)
Leverage the Retry-After HTTP header
If you do run into throttling, we require leveraging the Retry-After HTTP header to ensure minimum delay until the throttle is removed.

大佬能不能加一个这个请求头

这是他们的官网文档：https://docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-avoid-getting-throttled-or-blocked-in-sharepoint-online#why-cant-you-just-tell-me-the-exact-throttling-limits

**Comment by qkqpttgf** [comment]
仔细看过了文档，这个retry-after不是我加的，这个是微软返回给我们的，告诉我们应该在XXX时间后再重试，如果在这个时间内，微软就丢掉。
以后可能加上对这个的处理，但我自己的网站调用少，微软不会给我发这个头，只能尽量处理下。

**Comment by GillianJiao** [comment]
好呢 麻烦大佬给怎么好的软件给我们使用啦

**Comment by qkqpttgf** [comment]
现在遇到429就不再请求了，你有试过？
