### ISSUE TITLE
classic.html Theme 列表最后一个文件的管理选项无删除按钮

### ISSUE THREAD

**Issue by clevezhang** [qkqpttgf/OneManager-php#147]
列表其它文件正常

**Comment by qkqpttgf** [comment]
被挡住了而已，又不是没滚动条，不会滚一滚吗……

**Comment by clevezhang** [comment]
谢谢大佬, 还真是滚动可见.
主要是就算只有一个文件, 它也得滚动才行.
已经自己在 .listtable 里加了 "margin-bottom:30px;" 可以完整显示了.
