### ISSUE TITLE
强烈建议大佬把皮肤换一下（我推荐一个）

### ISSUE THREAD

**Issue by X-Crack** [qkqpttgf/OneManager-php#148]
https://github.com/DirectoryLister/DirectoryLister

大佬把这个皮肤扒下来，不出一个月马上爆火了！

程序再好，也要有一个好的皮囊。

**Comment by qkqpttgf** [comment]
你帮我扒吧

**Comment by X-Crack** [comment]
> 你帮我扒吧

我没技术啊大佬，我是小白！ 😂

**Comment by qkqpttgf** [comment]
> 我没技术啊大佬，我是小白！

我不会扒……你看有个官方onedrive蓝白扒皮还是dev……都做不下去了。
