### ISSUE TITLE
在文件名包含空格的时候，视频在线播放会播放失败

### ISSUE THREAD

**Issue by kukume** [qkqpttgf/OneManager-php#149]
在文件名包含空格的时候，视频在线播放会播放失败，但是下载没有问题

**Comment by qkqpttgf** [comment]
换默认主题

**Comment by kukume** [comment]
是默认主题

**Comment by qkqpttgf** [comment]
经测试，正常播放，
请看demo，Theme下mp4目录里面有个带空格的，可以播放。
可能你那个视频编码不太对。

**Comment by kukume** [comment]
用f12看了一下，视频播放失败的链接，响应码是404，跟视频编码应该是没有关系的
这是下载链接：https://pan.kuku.me/kuku/%E6%B2%B9%E7%AE%A1_%E9%BB%83%E6%98%8E%E5%BF%97%20Namewee%20&%20%E4%B8%89%E4%B8%8A%E6%82%A0%E4%BA%9E%20Yua%20Mikami%E3%80%90%E4%B8%8D%E5%B0%8F%E5%BF%83%20I%20Shot%20You%E3%80%91%40%E4%BA%9E%E6%B4%B2%E9%80%9A%E6%89%8D%202020%20Asian%20Polymath%20%2822%20-%201280x720%20%28720p%29%29.mp4
是可以正常下载的
这是通过f12捕获的视频播放链接：
https://pan.kuku.me/kuku/%E6%B2%B9%E7%AE%A1_%E9%BB%83%E6%98%8E%E5%BF%97%20Namewee%20&amp;%20%E4%B8%89%E4%B8%8A%E6%82%A0%E4%BA%9E%20Yua%20Mikami%E3%80%90%E4%B8%8D%E5%B0%8F%E5%BF%83%20I%20Shot%20You%E3%80%91@%E4%BA%9E%E6%B4%B2%E9%80%9A%E6%89%8D%202020%20Asian%20Polymath%20(22%20-%201280x720%20(720p)).mp4
响应码404，
貌似是括号没有url编码？

**Comment by qkqpttgf** [comment]
是文件名里面有&符号的原因，classic主题已经修复
