### ISSUE TITLE
含有中文等非英文字符的文件访问出错

### ISSUE THREAD

**Issue by KarlcxChina** [qkqpttgf/OneManager-php#151]
含有中文等非英文字符的文件访问出错
在别人直接打开含有中文等字符的文件下载链接时出错。
![IMG_20201128_163112](https://user-images.githubusercontent.com/63567314/100497551-28d80300-3197-11eb-8699-d4db4515c13b.jpg)

**Comment by qkqpttgf** [comment]
可以肯定不是中文字符的问题，是某些特殊字符，url中有特殊意义，才会这样
我demo又不是没有中文名文件，完全正常的
（你这种截图还不如不放出来）

**Comment by KarlcxChina** [comment]
谢谢批评，截图已修改。
我更新以后无法复现这个bug了，此issue关闭。
另外我发现了一个新的bug，已在多次测试中出现，我将新开一个issue。
