### ISSUE TITLE
登陆后在文件夹下上传文件时给出的链接错误

### ISSUE THREAD

**Issue by KarlcxChina** [qkqpttgf/OneManager-php#153]
在登陆以后在文件夹中上传文件，上传完成后给出的下载链接（图中红框按钮）是有问题的。

![IMG_20201128_164738](https://user-images.githubusercontent.com/63567314/100497923-8e2cf380-3199-11eb-81e4-b6be35f6a1d0.jpg)

比如我在/T-0文件夹上传文件，正确的下载链接应为
http://domain/T-0/FileName
但是点击按钮复制的链接却为
http://domain/FileName
导致了itemNotFound错误。

P.S.我怀疑上一个issue是因为把这个bug误认为了中文字符导致的错误。

**Comment by qkqpttgf** [comment]
旧版本主题~
应该修复了，更新试试。
