### ISSUE TITLE
上传文件问题

### ISSUE THREAD

**Issue by sunnyhu2003** [qkqpttgf/OneManager-php#16]
文件上传后，会有一个.tmp文件死活删不掉，要进onedrive里面删，在onemanager里删报502。是最近版本才出现的

**Comment by qkqpttgf** [comment]
我刚刚去试了一下，最新版本，无论游客上传还是登录后上传，.tmp文件都可以删掉的。

**Comment by sunnyhu2003** [comment]
我的也是最新版本，会不会是世纪互联的问题？

**Comment by sunnyhu2003** [comment]
> 我刚刚去试了一下，最新版本，无论游客上传还是登录后上传，.tmp文件都可以删掉的。

刚刚又去试了一下，世纪互联配SCF及最新版上传依旧会残留.tmp文件。而且删不掉
图片地址：https://ftp.bmp.ovh/imgs/2020/02/7fd32ac8a6f51fbd.png
