### ISSUE TITLE
关于上传API（?action=upbigfile）的上传鉴权问题

### ISSUE THREAD

**Issue by zxy19** [qkqpttgf/OneManager-php#162]
在上传文件时，没有开放的文件夹时不能直接上传的，但是在正常上传过程中使用的api可以直接对没有开放的文件夹进行上传操作
复现方法如下：
调用：https://domain.domain/path-to-root/?action=upbigfile&upbigfilename=[Name]&filesize=[size]&lastModified=[TimeStamp]
分析返回数据：
```json
{"@odata.context":"https://graph.microsoft.com/v1.0/$metadata#microsoft.graph.uploadSession","expirationDateTime":"2020-11-30T09:16:24.188Z","nextExpectedRanges":["0-"],"uploadUrl":"https://suyan-my.sharepoint.com/personal/karlcxchina_suyan_onmicrosoft_com/_api/v2.0/drive/items/01JVBKQFV4ORX......./uploadSession?guid='b14e9eb9-.......'&path='~tmpD9_cover0.png'&overwrite=False&rename=False&dc=0&tempauth=eyJ0eXAiOiJKV1QiLCJh......."}
```
与微软Graph给出的api对比得到，该返回为
![)@EQH649MJL4)~)JJK 1H@D](https://user-images.githubusercontent.com/23428495/100589425-104e2100-332e-11eb-9ada-a8fe8dfa21b9.png)
获取uploadSession的返回

参照api方式对UploadUrl进行调用，成功；

访问https://domain.domain/path-to-root/[Name]
可以访问。

希望开发者能对该接口进行限制，避免滥用

**Comment by qkqpttgf** [comment]
前些天没理解，应该是直接手动指定上传路径了？这几天改下。
