### ISSUE TITLE
群晖docker版，不显示文件。

### ISSUE THREAD

**Issue by liubangjain** [qkqpttgf/OneManager-php#166]
我用的是群晖docker版，添加了od后，管理后台显示是正确，但是首页就是不显示od里面文件。
https://registry.hub.docker.com/r/peng4740/onemanager-php/builds
请问是我的设置的问题？还是这个docker的问题？

**Comment by qkqpttgf** [comment]
docker我不会，不知道谁弄的。
所以不好判断哪里问题。
