### ISSUE TITLE
想把背景设置成随机图片，请问这部分的php代码应该放在哪个位置

### ISSUE THREAD

**Issue by accelerate12138** [qkqpttgf/OneManager-php#175]
首先感谢大佬做的这么好的项目！也感谢一直在维护和修复问题~

目前背景只支持贴一张图片的url，但我想把背景设置成每次刷新都会出现一张新的图片（目前我有一些图片，并且有存到图床上获取的图片链接）于是我在网上找到了这段代码，
https://github.com/accelerate12138/OneManager-php/blob/master/index_background.php
但是我不会php，不知道该放到代码的哪个位置才会出来这样的效果……能不能请大佬指点一下( •̀ ω •́ )✧
使用的是heroku平台……

（或者大佬知不知道其他可以实现随机图片的更好的方式也可以呀😁）

**Comment by accelerate12138** [comment]
已解决，不好意思打扰了XD

**Comment by qkqpttgf** [comment]
你要把这个url弄成可变图片，每次访问都不一样。
你可以说说你的方法。

**Comment by accelerate12138** [comment]
> 你要把这个url弄成可变图片，每次访问都不一样。
> 你可以说说你的方法。

是的，后来我意识到在设置里把“背景url”那一栏改成一个可以返回随机图片的api接口就可以实现目的😂
实际借用了这位大佬开发的项目（）：https://github.com/Crazy-White/Random-Picture，把他的项目挂载在Vercel上，就可以通过访问./api跳转至图片地址，
