### ISSUE TITLE
 nexmoe1下无法播放视频

### ISSUE THREAD

**Issue by CuteCatXiao** [qkqpttgf/OneManager-php#178]
# nexmoe1主题下视频只有声没有画面
换了好多视频还是这样👇
![image](https://user-images.githubusercontent.com/62191675/103393580-4dd8e080-4b5e-11eb-928d-2bacb1e0fe7c.png)
```Edge Chromium 浏览器``` ```MP4视频``` ```中国联通```

**Comment by qkqpttgf** [comment]
其它主题呢？可能是dplayer不支持？

**Comment by CuteCatXiao** [comment]
其他主题用Dplayer都可以
还有m3u8也不🉑
