### ISSUE TITLE
配置错误

### ISSUE THREAD

**Issue by CreamK** [qkqpttgf/OneManager-php#179]
输入secretid和sectretkey之后这个错误{"message":"There is no api match uri '\/SCFOnedriveIndex-1xxxxxxxxx0' host 'service-cnxxxxxxxxxxxx6.sh.apigw.tencentcs.com'"}

**Comment by qkqpttgf** [comment]
应该是你对API网关做了什么，从头开始弄呢？
（对了，不要看其它地方的教程，只看我的readme）

**Comment by QhPRC** [comment]
我也遇到了这个问题，然后我把触发器的请求方法改成ANY就没问题了
