### ISSUE TITLE
部署时出错

### ISSUE THREAD

**Issue by Discover999** [qkqpttgf/OneManager-php#180]
已经部署成功过，出问题了又部署一次，已有id密钥，最后一步提示Forbidden
You don't have permission to access this resource.

**Comment by qkqpttgf** [comment]
应该是昨晚我动了中转页面的原因，你现在再试试

**Comment by Discover999** [comment]
> 应该是昨晚我动了中转页面的原因，你现在再试试

今天已经可以了，又搭建了一次
