### ISSUE TITLE
增加 略缩图 尺寸选项

### ISSUE THREAD

**Issue by shzxm** [qkqpttgf/OneManager-php#184]
增加 略缩图 尺寸选项

https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_list_thumbnails?view=odsp-graph-online#size-options

希望增加 略缩图 
![image](https://user-images.githubusercontent.com/9905297/103832135-8e81ae00-50b8-11eb-8138-3f47f2df9a96.png)

**Comment by qkqpttgf** [comment]
页面上已经很难看了，摆不下了……

**Comment by shzxm** [comment]
> 页面上已经很难看了，摆不下了……

啊啊啊.不是.是添加功能到 管理界面 给配置参数 可以自定义
我看现在就是

**Comment by qkqpttgf** [comment]
> > 页面上已经很难看了，摆不下了……
> 
> 啊啊啊.不是.是添加功能到 管理界面 给配置参数 可以自定义
> 我看现在就是

好的，收到，我理解了，但应该不会做出来…………或许你可以自己实现？

**Comment by shzxm** [comment]
> > > 页面上已经很难看了，摆不下了……
> > 
> > 
> > 啊啊啊。不是。是添加功能到管理界面给配置参数可以自定义
> > 我看现在就是
> 
> 好的，收到，我理解了，但应该不会做出来…………或许你可以自己实现？

啊啊啊.这个有点难./...

作者能不能指导下.目前的略缩图我看了下
`
https://southeastasia1-mediap.svc.ms/transform/thumbnail?provider=spo&inputFormat=jpg&cs=NzM0ZWY5MjgtZDc0Yy00NTU1LThkMWItZDk0MmZhMGExYTQxfFNQTw&docid=https%3A%2F%2Fshzxm%2Dmy%2Esharepoint%2Ecom%2F%5Fapi%2Fv2%2E0%2Fdrives%2Fb%21tqYYFtOIWEyz4Oezaw0DeAbJavOBTG1HhAlU%5F9XGGK159gVABQicS450Owe7y6n1%2Fitems%2F01ZCESLHNMZUSG2ZLUGJC32OZ6XDSSWTJT%3Ftempauth%3DeyJ0eXAiOiJKV1QiLCJhbGciOiJub25lIn0%2EeyJhdWQiOiIwMDAwMDAwMy0wMDAwLTBmZjEtY2UwMC0wMDAwMDAwMDAwMDAvc2h6eG0tbXkuc2hhcmVwb2ludC5jb21AY2ZjNTQwNTUtMjhkNi00MTAyLTgzZmItMTJmZmY4OWE5YzY0IiwiaXNzIjoiMDAwMDAwMDMtMDAwMC0wZmYxLWNlMDAtMDAwMDAwMDAwMDAwIiwibmJmIjoiMTYxMDAyMDgwMCIsImV4cCI6IjE2MTAwNDI0MDAiLCJlbmRwb2ludHVybCI6Ing1Rm95RlZhaVpJTEpqVXZwTE5yRWVxTEVZcldhUFRZUmpNNnpBK2wxRUE9IiwiZW5kcG9pbnR1cmxMZW5ndGgiOiIxNTYiLCJpc2xvb3BiYWNrIjoiVHJ1ZSIsInZlciI6Imhhc2hlZHByb29mdG9rZW4iLCJzaXRlaWQiOiJNVFl4T0dFMllqWXRPRGhrTXkwMFl6VTRMV0l6WlRBdFpUZGlNelppTUdRd016YzQiLCJhcHBfZGlzcGxheW5hbWUiOiJPbmVNYW5hZ2VyIiwiZ2l2ZW5fbmFtZSI6Iuadvua6kCIsImZhbWlseV9uYW1lIjoi5YiYIiwiYWMiOiJsfG18aCIsImFwcGlkIjoiNzM0ZWY5MjgtZDc0Yy00NTU1LThkMWItZDk0MmZhMGExYTQxIiwidGlkIjoiY2ZjNTQwNTUtMjhkNi00MTAyLTgzZmItMTJmZmY4OWE5YzY0IiwidXBuIjoibHN5QHNoenhtLmNvbSIsInB1aWQiOiIxMDAzMjAwMEYzNzAwMEM1IiwiY2FjaGVrZXkiOiIwaC5mfG1lbWJlcnNoaXB8MTAwMzIwMDBmMzcwMDBjNUBsaXZlLmNvbSIsInNjcCI6ImFsbGZpbGVzLndyaXRlIiwidHQiOiIyIiwidXNlUGVyc2lzdGVudENvb2tpZSI6bnVsbH0%2EUUE1RTFGYkxRa0ppNVBUdmVBQzJUOXkzTU5vMHRwUzV5eENPOUlCZXlMTT0%26version%3DPublished&width=176&height=176&cb=63745342922`


最后这个参数是在哪调整的...

就是项目里边在哪.我去调整下

**Comment by qkqpttgf** [comment]
你自用的话，直接在common.php里，function get_thumbnails_url函数下面把 thumbnails/0/medium中的medium改成一楼你图片中想要的词。
你想做成配置参数的话，就要改3个地方，不细讲了。

**Comment by shzxm** [comment]
啊，感谢大佬
