### ISSUE TITLE
passfile用法？

### ISSUE THREAD

**Issue by HustreLiny** [qkqpttgf/OneManager-php#189]
请问是把文件丢在主目录吗？还是哪里都可以？

**Comment by HustreLiny** [comment]
重新设置之后，发现之前加过密的文件夹里都有之前的passfile文件，但现在设置完passfile名称后，我加密了之前的文件夹，发现加密无效，依然可以访问

**Comment by qkqpttgf** [comment]
passfile，管的是当前目录，及所有下属目录
登录为admin后，无视加密。

**Comment by HustreLiny** [comment]
我明白了，感谢解答
