### ISSUE TITLE
部署失败

### ISSUE THREAD

**Issue by Yofo-me** [qkqpttgf/OneManager-php#190]
环境：
`Ubuntu 20.04 LTS with Apache 2.41`

操作说明：
- 1.下载这个源码并解压到网站根目录下`pan`文件夹下或者克隆这个仓库到网站根目录下`pan`文件夹下
- 2.正确设置文件夹权限及所有者
- 3.配置好网站相关配置 
- 4. 访问网站https://mydomain.com/pan，出现以下页面

![image](https://user-images.githubusercontent.com/55388087/104832015-df6b8080-58c8-11eb-9004-f6cf279339ec.png)

---

![image](https://user-images.githubusercontent.com/55388087/104832087-59036e80-58c9-11eb-9be1-73d035f90fc0.png)

---

网站目录正确的啊
![image](https://user-images.githubusercontent.com/55388087/104832070-3ffabd80-58c9-11eb-841c-325997fcb1dc.png)

**Comment by qkqpttgf** [comment]
尝试一下，把我文件清空，只放一个index.html或index.php呢？

**Comment by Yofo-me** [comment]
> 尝试一下，把我文件清空，只放一个 index.html 或 index.php 呢？

Ok了
