### ISSUE TITLE
阿里云盘无法下载文件

### ISSUE THREAD

**Issue by jimao233** [qkqpttgf/OneManager-php#193]
![image](https://user-images.githubusercontent.com/24926585/105037449-e378d900-5a55-11eb-867f-141690b5f6cc.png)

**Comment by qkqpttgf** [comment]
好几天前就这样了，阿里开防盗链了。
不想玩花活。

**Comment by jimao233** [comment]
为什么隔壁alist能用呜呜呜

**Comment by qkqpttgf** [comment]
> 为什么隔壁alist能用呜呜呜

他要么走服务器流量，要么在网页上加了禁止referer。

**Comment by qkqpttgf** [comment]
算了，给你加了no referer。
去用吧。
