### ISSUE TITLE
安装在vps上无法一键更新新版本

### ISSUE THREAD

**Issue by 1404939641** [qkqpttgf/OneManager-php#20]
我是安装在vps上的，但是无法使用一键更新功能，是权限什么的设置错误还是本来就不支持呀？

**Comment by qkqpttgf** [comment]
SCF跟heroku配置都在环境变量，更新的话，官方API把所有代码一覆盖就好了。
VPS上我还不知道怎么处理自己~~~写权限是个事，配置文件拿出来放回去又是个事，比较麻烦。
目前不想要太多权限。

**Comment by 1404939641** [comment]
明白了。

**Comment by qkqpttgf** [comment]
写了个sh脚本，直接运行它来更新吧~
