### ISSUE TITLE
关于图床功能的一些建议

### ISSUE THREAD

**Issue by ifloppy** [qkqpttgf/OneManager-php#203]
我用OneManager做图床自己用，希望针对图床进行一些优化：

1. 用QQ自带的截图截取的图片，直接ctrl+v粘贴到OneManager中上传
2. 自动给上传的图片改名，防止重名
3. 图片上传完毕后有一个复制图片链接的按钮

**Comment by qkqpttgf** [comment]
> 我用OneManager做图床自己用，希望针对图床进行一些优化：
> 
> 1. 用QQ自带的截图截取的图片，直接ctrl+v粘贴到OneManager中上传
> 2. 自动给上传的图片改名，防止重名
> 3. 图片上传完毕后有一个复制图片链接的按钮

1，拖拽或快捷键上传，是主题里面的功能，这个操作我不想学，等有大佬写吧
2，自动改名，目前游客上传不就是计算md5来命名的，你没上传过吗
3，目前游客上传不就有这个按钮？？

所以你到底有没有用过我的图床（游客上传）功能？？

**Comment by ifloppy** [comment]
1. 这个我觉得你可以借(chao)鉴(xi)一下这个图床软件：https://github.com/icret/EasyImages2.0
2. 上传过，没留神。我是想让它以数字命名图片
3. 那当我没说😂

所以我到底......(我好像不是游客欸，一直登着管理的)

**Comment by qkqpttgf** [comment]
忙不过来啦

**Comment by ifloppy** [comment]
还有个建议：图片水印

**Comment by qkqpttgf** [comment]
> 还有个建议：图片水印

这个建议我无法接受（.jpg
