### ISSUE TITLE
关于public_path设置目录后guestup_path失效的疑问

### ISSUE THREAD

**Issue by ymh1147** [qkqpttgf/OneManager-php#204]
今天安装了OM，其他功能都正常，但如果我添加了public_path目录A后，在A目录里创建guestup_path的B目录，游客进入B目录是无法上传的，删除public_path设置后，在OD的根目录设置guestup_path的B目录，游客上传是正常的。能否更新一下，在使用public_path设置目录后guestup_path设置也能使用？如果现有程序能满足，麻烦告知一下具体怎么设置，我是第一次使用OM，谢谢了！

**Comment by qkqpttgf** [comment]
可能你设置时的理解有误。
readme中有讲，xxx_path，都是指的，这个目录在你OD里面的路径。
比如你OD中长这样：
> 根->A->B
> 根->C

那你把公开目录设为/A后，游客上传目录应该设置为/A/B，而不是/B，更不应该是/C。

**Comment by ymh1147** [comment]
明白了，我原来设想的是 根->A->B 但设置后没有在guestup_path里加 A/ ，导致成为 根->B 
现在明白了，只需要在guestup_path里设置成 A/B 这样就正常了，已验证，谢谢！
