### ISSUE TITLE
功能请求

### ISSUE THREAD

**Issue by Micraow** [qkqpttgf/OneManager-php#206]
功能请求：希望支持Office文件（docs,pptx...)的预览支持，作者之前说放到office网页版就好了，我不会写php，也没理解，希望作者实现一下。

**Comment by qkqpttgf** [comment]
???????
你这个是在2019年6月发的请求吗？？

**Comment by Micraow** [comment]
不是啊，能实现吗？

**Comment by qkqpttgf** [comment]
> 不是啊，能实现吗？

现在应该说前年了，前年就能预览了啊！！！

**Comment by Micraow** [comment]
升级了，还是不行，一直显示正在检索文件

**Comment by Micraow** [comment]
显示

正在提取您的文件...
正在从 Internet 上的主页中检索您的文件，请稍候

**Comment by Micraow** [comment]
对了，上传文件能不能写个API接口？想与picsgo及我自己的程序结合。

**Comment by qkqpttgf** [comment]
> 显示
> 
> 正在提取您的文件...
> 正在从 Internet 上的主页中检索您的文件，请稍候

我这边也这样，未知问题在哪，可能无法解决

**Comment by qkqpttgf** [comment]
> 对了，上传文件能不能写个API接口？想与picsgo及我自己的程序结合。

你想要的API接口，是你上传给OneManager，然后由OneManager上传给微软，吧？
不行，没打算让文件流从我程序经过。
我这边的原理是，你告诉我要上传，所以我告诉微软要上传，微软给我一个url说你对着这个url上传吧，然后我就把这个url丢给你，你自己在浏览器中上传到那个url。

**Comment by Micraow** [comment]
> > 显示
> > 正在提取您的文件...
> > 正在从 Internet 上的主页中检索您的文件，请稍候
> 
> 我这边也这样，未知问题在哪，可能无法解决

我没找到问题在哪，但我有解决方案：
现在src=...后面跟的是sharepoint的地址，只要换成onemanager链接即可

**Comment by qkqpttgf** [comment]
> > > 显示
> > > 正在提取您的文件...
> > > 正在从 Internet 上的主页中检索您的文件，请稍候
> > 
> > 
> > 我这边也这样，未知问题在哪，可能无法解决
> 
> 我没找到问题在哪，但我有解决方案：
> 现在src=...后面跟的是sharepoint的地址，只要换成onemanager链接即可

ok，下午有空试下

**Comment by Micraow** [comment]
另外，zip文件也是支持预览的

https://docs.microsoft.com/zh-cn/graph/api/driveitem-preview?view=graph-rest-1.0

**Comment by Micraow** [comment]
试过了吗
