### ISSUE TITLE
用scf部署提示A value specified in `Region` is not valid, is unsupported, or cannot be used.

### ISSUE THREAD

**Issue by ZhaoKuanhong** [qkqpttgf/OneManager-php#21]
触发器给的网址是https://service-ee3xr1n2-1254045809.hk.apigw.tencentcs.com/release/dfs13a
环境变量我也添了条Region=ap-hongkong
还是不行

**Comment by qkqpttgf** [comment]
没用，我是从url读的，上周腾讯改了url，我没法读了，我又不想写个选择（那样要写很多），先用其它的平台吧，腾讯说3月会加上，到时我改代码。
