### ISSUE TITLE
目前无法处理此请求。

### ISSUE THREAD

**Issue by missmuxixi** [qkqpttgf/OneManager-php#210]
首次安装，设置完密码，输入密码登录后,提示成功，之后就跳转500
尝试删除文件先运行update.sh再重新安装，问题复现。
![tempsnip](https://user-images.githubusercontent.com/5107682/106557005-d252c080-655b-11eb-8a57-8620c3385082.png)
![屏幕截图 2021-02-02 142149](https://user-images.githubusercontent.com/5107682/106560649-4c864380-6562-11eb-826a-196a24a174a9.png)
![tempsnip2](https://user-images.githubusercontent.com/5107682/106557010-d5e64780-655b-11eb-9feb-55f1536796be.png)

**Comment by qkqpttgf** [comment]
呃，看不出来问题在哪

**Comment by qkqpttgf** [comment]
现在呢？

**Comment by dsmng54** [comment]
我也是这样的

**Comment by missmuxixi** [comment]
> 现在呢？

说下个人解决方法，debian 10下执行 sudo apt-get install php-curl 安装完后 再 php -m 看下列表里面有没有curl插件，有的话再刷新网页就可以了，依旧没有插件显示的话，就手动下载编译然后加载，debian 10 自带的php7.3居然没有自动安装curl的插件，ubuntu20无此问题

**Comment by qkqpttgf** [comment]
> > 现在呢？
> 
> 说下个人解决方法，debian 10下执行 sudo apt-get install php-curl 安装完后 再 php -m 看下列表里面有没有curl插件，有的话再刷新网页就可以了，依旧没有插件显示的话，就手动下载编译然后加载，debian 10 自带的php7.3居然没有自动安装curl的插件，ubuntu20无此问题

呃，好吧，辛苦了。
