### ISSUE TITLE
每隔一会，首次访问就会变的很慢，好像是缓存问题，如何能保持一直刷新

### ISSUE THREAD

**Issue by mycode233** [qkqpttgf/OneManager-php#211]
谷歌了下，似乎也有其他人提到，最后看别人说是因为缓存问题，有没有什么办法可以解决这个问题

**Comment by qkqpttgf** [comment]
我这边知识受限，只能想到隔几分钟访问一次。

**Comment by mycode233** [comment]
> 我这边知识受限，只能想到隔几分钟访问一次。

这个访问有什么要求吗，我的其他服务器用宝塔设置定时访问url，但是好像没什么效果

**Comment by qkqpttgf** [comment]
> > 我这边知识受限，只能想到隔几分钟访问一次。
> 
> 这个访问有什么要求吗，我的其他服务器用宝塔设置定时访问url，但是好像没什么效果

我也不太会了……
