### ISSUE TITLE
创建文件夹能加个二级确认就好了

### ISSUE THREAD

**Issue by BCYYSZ** [qkqpttgf/OneManager-php#212]
![QQ截图20210206142426](https://user-images.githubusercontent.com/52218948/107111012-6e940480-6887-11eb-9bcd-46e4189aa8ab.png)
创建文件夹单次点击会没反应，但实际上创建了，刷新能看到.但连续点击会创建多个文件夹（文件夹，文件夹1.......），不知道是不是bug，不是的话能加个二级确认，能避免多个文件夹的创建

**Comment by qkqpttgf** [comment]
你-->OneManager-->微软，这个过程还是比较漫长的，慢慢来，不要着急。
