### ISSUE TITLE
nexmoe1右下角切换宫格模式后无翻页功能

### ISSUE THREAD

**Issue by histion** [qkqpttgf/OneManager-php#214]
能看图了但却无法翻页，切换回列表模式又不能看图能翻页……希望增加翻页功能和查看原图模式，非常感谢~

**Comment by qkqpttgf** [comment]
尽量，下次一定

**Comment by histion** [comment]
> 尽量，下次一定

还有顺便说一下，有些flv视频会出现跨域错误，有些又不会。（ '▿ ' ）
