### ISSUE TITLE
能否手动调整上传分块的单块大小

### ISSUE THREAD

**Issue by Lolol954321** [qkqpttgf/OneManager-php#218]
上传小文件还好，但有些十几个G的大压缩包真的难顶。每次等待下个分块的时间都会远远超过上传时间（单个分块10MB），请问有没有办法解决？？

**Comment by qkqpttgf** [comment]
只能手动修改主题。
你可以在默认主题classic里找到 “分块” 2字，
默认5M，大于200M的文件是10M（下一行有个if），你可以改改看。
微软说最大60M，建议10M。

**Comment by jssycszyj** [comment]
> 只能手动修改主题。
> 你可以在默认主题classic里搜到 “微软建议” 4个字，
> 默认5M，大于200M的文件是10M（下一行有个if），你可以改改看。
> 微软说最大60M，建议10M。

oneindex命令行上传倒是支持100M分块，不知道怎么实现的

**Comment by Lolol954321** [comment]
> 只能手动修改主题。
> 你可以在默认主题classic里搜到 “微软建议” 4个字，
> 默认5M，大于200M的文件是10M（下一行有个if），你可以改改看。
> 微软说最大60M，建议10M。

var chunksize=5*1024*1024; // chunk size, max 60M. 每小块上传大小，最大60M，微软建议10M
                    if (totalsize>200*1024*1024) chunksize=10*1024*1024;
                    function readblob(start) {
好的，chunksize=后面就是分块大小对吧

**Comment by Lolol954321** [comment]
还有，如果是腾讯SCF的话怎么提交修改内容啊

**Comment by Lolol954321** [comment]
好了，谢谢

**Comment by lslqtz** [comment]
> > 只能手动修改主题。
> > 你可以在默认主题classic里搜到 “微软建议” 4个字，
> > 默认5M，大于200M的文件是10M（下一行有个if），你可以改改看。
> > 微软说最大60M，建议10M。
> 
> oneindex命令行上传倒是支持100M分块，不知道怎么实现的

经过实测实际上并不是最大 60M，我尝试分块 100M 上传 300M 的文件并在上传到 100M 时获得了一个卡顿 (下一个分块)，最终文件成功上传并未损坏。

**Comment by qkqpttgf** [comment]
> > > 只能手动修改主题。
> > > 你可以在默认主题classic里搜到 “微软建议” 4个字，
> > > 默认5M，大于200M的文件是10M（下一行有个if），你可以改改看。
> > > 微软说最大60M，建议10M。
> > 
> > 
> > oneindex命令行上传倒是支持100M分块，不知道怎么实现的
> 
> 经过实测实际上并不是最大 60M，我尝试分块 100M 上传 300M 的文件并在上传到 100M 时获得了一个卡顿 (下一个分块)，最终文件成功上传并未损坏。

是吗！那倒是个好消息，不知道确切上限是多少~~
