### ISSUE TITLE
能否手动调整上传并行任务数量

### ISSUE THREAD

**Issue by Lolol954321** [qkqpttgf/OneManager-php#219]
默认全部开始任务有点坑，对单个文件的上传效率有些低下从而导致可靠性不高（上传了一半的都是损坏文件）
onemanager里可不可以有队列机制？（虽然onedrive官方好像也没有）

**Comment by qkqpttgf** [comment]
js渣渣不会
文件损坏应该不会……

**Comment by qkqpttgf** [comment]
刚刚试着限制同时5个上传，你更新试试
