### ISSUE TITLE
界面建议

### ISSUE THREAD

**Issue by keli1973** [qkqpttgf/OneManager-php#22]
1.首先说一下现在默认界面就已经真心不错
2.因为考虑到手机浏览器横屏像素较少的缘故，能不能新加一个主题是可以把文件名单独一行，然后大小和创建时间放另外一行呢？这样大大避免文件名较长时，被拦腰截断只能在里面慢慢左拉才能全看到的情况，毕竟大部分人首先关心的是文件名。参考weiyun.com上手机显示界面。

**Comment by qkqpttgf** [comment]
这样的话，时间跟大小直接丢掉好了？
（但还是很多超长的文件名，常见的动漫文件名都很长~~）

**Comment by keli1973** [comment]
> 这样的话，时间跟大小直接丢掉好了？
> （但还是很多超长的文件名，常见的动漫文件名都很长~~）

你喜欢，但如果一行文件名都放不下那也是没办法，因为一般一个横屏放不下的文件名也比较少吧，而且应该在可见范围内基本都能知道是什么文件了。

**Comment by qkqpttgf** [comment]
已经隐藏，请关issue

**Comment by keli1973** [comment]
不好意思继续再弱弱问一下，如果是用https://heroku.com 上面开发的，你代码更新以后该如何升级？

**Comment by keli1973** [comment]
原来登录进去设置里面就可以升级，谢谢
