### ISSUE TITLE
MKV、MP4在线播放的问题

### ISSUE THREAD

**Issue by Lolol954321** [qkqpttgf/OneManager-php#222]
【Windows查看网页】
MKV文件（Matroska HEVC）黑屏只有声音（AAC），MP4文件（AVC）20分钟以下正常播放，20分钟以上只有声音（AAC）并且网页十分卡顿，画面黑屏
【Android端查看网页】
MKV文件（Matroska HEVC）黑屏只有声音（AAC），MP4文件（AVC）20分钟以下正常播放，20分钟以上不间断花屏并不时有明显色差，画面突变时（分镜）问题尤为严重

附：云函数内存已由2560MB调至最大问题仍然存在

**Comment by qkqpttgf** [comment]
具体的应该是dplayer的问题，但我不会。

另：这个跟程序内存无关，流量又不走程序。

**Comment by Lolol954321** [comment]
已经解决了，是视频编码问题，这里也给后人提醒一下，上传的视频无论长短必须是8bit，10bit视频无法解码

**Comment by Gladtbam** [comment]
> 已经解决了，是视频编码问题，这里也给后人提醒一下，上传的视频无论长短必须是8bit，10bit视频无法解码

啊这，我全是10bit的视频
