### ISSUE TITLE
希望可以设置全局的功能性文件

### ISSUE THREAD

**Issue by YidaozhanYa** [qkqpttgf/OneManager-php#224]
做得很好，
![](http://i0.hdslb.com/bfs/emote/0e98299d7decf5eaffad854977946075c3e91cb8.png@112w_112h.png)
但还希望增加一个选项：可以设置全局的HEAD/README.md、head/foot.omf。
（我的设想是：开启这个选项后，所有文件夹默认使用在第1个盘根目录的功能性文件，但如果这个文件夹里放置了功能性文件，则使用这个文件夹里的。）否则在每个文件夹里都放一遍foot.omf太麻烦了啊

![](https://cdn.jsdelivr.net/gh/volantis-x/cdn-emoji@1.0.0/weibo/xiaoku.png)

**Comment by qkqpttgf** [comment]
好想法，过几年再说吧。

**Comment by qkqpttgf** [comment]
加好了，关帖
