### ISSUE TITLE
删除文件或移动文件被提示403

### ISSUE THREAD

**Issue by 2200737807** [qkqpttgf/OneManager-php#225]
![image](https://user-images.githubusercontent.com/71483108/108654835-78af3780-7504-11eb-97da-4ab08e34d974.png)
![image](https://user-images.githubusercontent.com/71483108/108654874-895fad80-7504-11eb-97e7-e43b8ed5dbe2.png)

**Comment by qkqpttgf** [comment]
你这应该是共享链接sharelink吧？
