### ISSUE TITLE
最近SCF一键升级后出错

### ISSUE THREAD

**Issue by chututu** [qkqpttgf/OneManager-php#23]
{"errno":403,"error":"Invalid scf response. expected scf response valid JSON."}

**Comment by qkqpttgf** [comment]
最近把一些配置加密保存了（起因是背景图url有特殊&？=字符，不加密保存不了），
于是更新后，旧的配置经过解密操作，程序读出来运行就出问题了。

**Comment by chututu** [comment]
解决了，感谢

**Comment by Seryta** [comment]
> 最近把一些配置加密保存了（起因是背景图url有特殊&？=字符，不加密保存不了），
> 于是更新后，旧的配置经过解密操作，程序读出来运行就出问题了。

那请问该如何解决呢？

**Comment by qkqpttgf** [comment]
> 那请问该如何解决呢？

删掉配置，重新安装

**Comment by Seryta** [comment]
> > 那请问该如何解决呢？
> 
> 删掉配置，重新安装

好的
