### ISSUE TITLE
求onedrive的PHP单文件处理代码

### ISSUE THREAD

**Issue by eutk** [qkqpttgf/OneManager-php#230]
求onedrive的PHP单文件处理代码，类似这个https://github.com/pinalzala/oneDrive-PHP-API-Using-CURL

**Comment by qkqpttgf** [comment]
点过去看了一眼，他这也不是单文件啊，这么多文件。
我这个才是单文件。
但你不会php用不了，会php你可以参考他的或我的都行。

**Comment by eutk** [comment]
> 点过去看了一眼，他这也不是单文件啊，这么多文件。
> 我这个才是单文件。
> 但你不会php用不了，会php你可以参考他的或我的都行。

你的也是调用/disk/Onedrive.php来进行操作的，但是又需要调用其他的文件代码，他的是调用/src/functions.inc.php的来操作，我就想要像他这样的一个扩展操作，他的部分代码太旧了，没法用，你的调用的其他文件的代码太多，我自己只研究出循环更新refresh_token

**Comment by qkqpttgf** [comment]
我对onedrive的操作全在这个文件里面啊，就这个class，没有调用其它（哦用了curl之类共用的，你可以直接抄的）。
