### ISSUE TITLE
蘑菇大佬，希望可以增加ftp/sftp的挂载！

### ISSUE THREAD

**Issue by kpzy** [qkqpttgf/OneManager-php#231]
ftp/sftp还是用的很多，希望可以支持一波！

**Comment by qkqpttgf** [comment]
我这个程序只是生成直链，客户直接从目标下载的。流量不从我程序中转。
FTP的话，你想告诉游客目标FTP的IP与帐密吗？

**Comment by kpzy** [comment]
就是把ftp的账户跟密码转换一下啊~~~ftp直接下载的话，容易暴露。
如果通过你的程序转换一下，这样别人只能下载，不能知道账号密码，不就挺好的？

**Comment by qkqpttgf** [comment]
> 就是把ftp的账户跟密码转换一下啊~~~ftp直接下载的话，容易暴露。
> 如果通过你的程序转换一下，这样别人只能下载，不能知道账号密码，不就挺好的？

…………我并不想流量从我程序走。

**Comment by raindrops2005** [comment]
。。。。一个网盘目录列表程序我觉得没必要支持ftp，因为ftp/sftp不是网盘

**Comment by kpzy** [comment]
就走一下嘛，程序走一下流量又不会怀孕！

**Comment by Nchyn** [comment]
> 就走一下嘛，程序走一下流量又不会怀孕！

那你为何不直接使用现成的程序将onedrive挂载到vps的硬盘上？
什么?你走的是SCF?流量资费会让你的钱包怀孕哦~
