### ISSUE TITLE
Nchyn_grey主题上传文件不能保留原文件名

### ISSUE THREAD

**Issue by Xm798** [qkqpttgf/OneManager-php#233]
Nchyn_grey主题，上传文件不能保留原文件名，会将其直接命名为`.扩展名`，无法正常使用。 @Nchyn

**Comment by qkqpttgf** [comment]
我有空看看

**Comment by qkqpttgf** [comment]
直接把classic的js复制过来了，应该能用了。
你更新看看有没有引起其它毛病。

**Comment by Xm798** [comment]
可以用了！十分感谢！目前暂时没发现其他问题，辛苦大佬
