### ISSUE TITLE
点击了设置里面的升级，然后就打不开网站了

### ISSUE THREAD

**Issue by zjboy1984** [qkqpttgf/OneManager-php#235]
点击了设置里面的升级，然后就打不开网站了

**Comment by qkqpttgf** [comment]
可能你太久没升级，以前的配置现在用不了了，所以报错，重装吧。

**Comment by zjboy1984** [comment]
我发现升级里面没有升级到V3的版本，只有个V2 last

**Comment by qkqpttgf** [comment]
> 我发现升级里面没有升级到V3的版本，只有个V2 last

.................多来几次就理解了，你现在转不过弯，

重装吧
