### ISSUE TITLE
无法显示静态网页

### ISSUE THREAD

**Issue by CuteCatXiao** [qkqpttgf/OneManager-php#238]
![image](https://user-images.githubusercontent.com/62191675/110197102-1c450400-7e84-11eb-9f8c-933b18b35088.png)
![image](https://user-images.githubusercontent.com/62191675/110197105-1e0ec780-7e84-11eb-846b-915d94bf9ec3.png)
重命名为index,html后无法访问？
实测删除.html后的?preview后即可访问...

**Comment by qkqpttgf** [comment]
实测我的index.html正常工作，你的index.html可能编码错误？？我访问你的网站没有这个目录，我没法实测。

**Comment by CuteCatXiao** [comment]
@qkqpttgf  https://cpcs.ximengao.ml/%E4%B8%80%E8%A8%80%E5%8D%95%E9%A1%B5%E7%89%88/
![image](https://user-images.githubusercontent.com/62191675/110201047-0c391e80-7e9c-11eb-9ebd-555387a617ee.png)
HTML文件本地没问题

**Comment by qkqpttgf** [comment]
> @qkqpttgf https://cpcs.ximengao.ml/%E4%B8%80%E8%A8%80%E5%8D%95%E9%A1%B5%E7%89%88/
> ![image](https://user-images.githubusercontent.com/62191675/110201047-0c391e80-7e9c-11eb-9ebd-555387a617ee.png)
> HTML文件本地没问题

我打开了那个一言，但我觉得你套的CF好麻烦。
