### ISSUE TITLE
如何增加游客文件夹

### ISSUE THREAD

**Issue by qq22784647** [qkqpttgf/OneManager-php#24]
后台只能指定一个文件夹名称，请问如何增加多个游客文件夹，谢谢

**Comment by qkqpttgf** [comment]
有一个上传已经够了，只是作为一个途径，
反正上传上去也不列清单，一个目录就好了。

**Comment by yue12345678** [comment]
> 有一个上传已经够了，只是作为一个途径，
> 反正上传上去也不列清单，一个目录就好了。

请问要怎么调用head.md和readme.md文件在界面显示
