### ISSUE TITLE
请问支持webdav方式访问吗？

### ISSUE THREAD

**Issue by dzhl** [qkqpttgf/OneManager-php#241]
请问挂载出的列表支持webdav方式访问吗？如果可以的话，挂载的视频我可以直接用播放器进行播放了

**Comment by qkqpttgf** [comment]
请在issue里面搜索一下webdav

**Comment by dzhl** [comment]
可惜

**Comment by dzhl** [comment]
> 请在issue里面搜索一下webdav

那请问，是否可以增加个选项，来控制是否打开webdav呢，实在觉得这个功能很好用，实现这样功能，手机上app连接视频很方便

**Comment by qkqpttgf** [comment]
> > 请在issue里面搜索一下webdav
> 
> 那请问，是否可以增加个选项，来控制是否打开webdav呢，实在觉得这个功能很好用，实现这样功能，手机上app连接视频很方便

??我说不能做，你理解成能做？？

**Comment by dzhl** [comment]
> > > 请在issue里面搜索一下webdav
> > 
> > 
> > 那请问，是否可以增加个选项，来控制是否打开webdav呢，实在觉得这个功能很好用，实现这样功能，手机上app连接视频很方便
> 
> ??我说不能做，你理解成能做？？

我找到了那个issue，我的理解是webdav的有些特征或用到的函数在一些环境中不能用，所以我才问是否可以有个控制选项，在不符合webdav条件的环境中关闭webdav，在符合webdav的环境中可以由用户打开。也许我是理解错了你的意思，如果是的话，抱歉

**Comment by qkqpttgf** [comment]
> > > > 请在issue里面搜索一下webdav
> > > 
> > > 
> > > 那请问，是否可以增加个选项，来控制是否打开webdav呢，实在觉得这个功能很好用，实现这样功能，手机上app连接视频很方便
> > 
> > 
> > ??我说不能做，你理解成能做？？
> 
> 我找到了那个issue，我的理解是webdav的有些特征或用到的函数在一些环境中不能用，所以我才问是否可以有个控制选项，在不符合webdav条件的环境中关闭webdav，在符合webdav的环境中可以由用户打开。也许我是理解错了你的意思，如果是的话，抱歉

是的，webdav在SCF/FC/FG/CFC这些就没法用，所以我没打算做一个只能在VPS上使用的功能。

**Comment by dzhl** [comment]
> > > > > 请在issue里面搜索一下webdav
> > > > 
> > > > 
> > > > 那请问，是否可以增加个选项，来控制是否打开webdav呢，实在觉得这个功能很好用，实现这样功能，手机上app连接视频很方便
> > > 
> > > 
> > > ??我说不能做，你理解成能做？？
> > 
> > 
> > 我找到了那个issue，我的理解是webdav的有些特征或用到的函数在一些环境中不能用，所以我才问是否可以有个控制选项，在不符合webdav条件的环境中关闭webdav，在符合webdav的环境中可以由用户打开。也许我是理解错了你的意思，如果是的话，抱歉
> 
> 是的，webdav在SCF/FC/FG/CFC这些就没法用，所以我没打算做一个只能在VPS上使用的功能。

理解，不过就是觉得太可惜了，这么好的一个应用，却不太适合自己
