### ISSUE TITLE
这种文档或者ppt或者excal打不开是什么原因

### ISSUE THREAD

**Issue by anderson-ryen** [qkqpttgf/OneManager-php#243]
期间未更新过，也是最近的版本了，本来能打开，然后突然就这样了，不是账号问题，换了账号一样的
![QQ截图20210309224847](https://user-images.githubusercontent.com/51238895/110488982-f3de3380-8129-11eb-8d4e-c810293a912d.png)

**Comment by qkqpttgf** [comment]
上次有这个问题，还没修复。
