### ISSUE TITLE
弱弱的问下，上传、下载、播放。走的是服务器流量还是onedrive

### ISSUE THREAD

**Issue by 503bug** [qkqpttgf/OneManager-php#244]

**Comment by qkqpttgf** [comment]
readme.md不看的？【太长不看】

**Comment by 503bug** [comment]
哈哈，太高估我了，理解不来。
________________________________
发件人: qkqpttgf <notifications@github.com>
发送时间: 2021年3月10日 18:23
收件人: qkqpttgf/OneManager-php <OneManager-php@noreply.github.com>
抄送: Jessica Cain <503bug@jle5.onmicrosoft.com>; Author <author@noreply.github.com>
主题: Re: [qkqpttgf/OneManager-php] 弱弱的问下，上传、下载、播放。走的是服务器流量还是onedrive (#244)


readme.md不看的？【太长不看】

―
