### ISSUE TITLE
升级之后部分虚拟主机无法登陆

### ISSUE THREAD

**Issue by langvs** [qkqpttgf/OneManager-php#246]
升级之后部分虚拟主机无法登陆，设置完密码后，登陆一直在新登录框那输入密码登陆没反应~
xxx.com/?admin
在这里输入密码登陆 之后还是这个界面，缓存也已经删除，还是这样 
php版本7.2

**Comment by qkqpttgf** [comment]
经查看，是服务器时间与电脑时间差太多导致。

**Comment by sduwfc** [comment]
,同问,以前没有这个问题.

**Comment by langvs** [comment]
> ，同问，以前没有这个问题。

可能是服务器时间和你电脑时间差的太多~
之前我用的虚拟主机就是这样 调整下本地时间试试吧

**Comment by qkqpttgf** [comment]
> ,同问,以前没有这个问题.

刚更新了登录提示，更新一下，登录看看报什么提示。

**Comment by sduwfc** [comment]
> > ,同问,以前没有这个问题.
> 
> 刚更新了登录提示，更新一下，登录看看报什么提示。

The timestamp in server is 1615472264 (2021-03-11T14:17:44Z),
and your posted timestamp is 1615471514 (2021-03-11T14:05:14Z)
这个只能改自己时间了吗

**Comment by qkqpttgf** [comment]
> > > ,同问,以前没有这个问题.
> > 
> > 
> > 刚更新了登录提示，更新一下，登录看看报什么提示。
> 
> The timestamp in server is 1615472264 (2021-03-11T14:17:44Z),
> and your posted timestamp is 1615471514 (2021-03-11T14:05:14Z)
> 这个只能改自己时间了吗

你如果能让服务器时间正确那就去弄服务器时间，如果服务器时间你操作不了，或不会改，那就改你本地时间跟它一致。
（注意提示里面的是UTC时间，你看好时间差来改就好）

**Comment by sduwfc** [comment]
> > > > ,同问,以前没有这个问题.
> > > 
> > > 
> > > 刚更新了登录提示，更新一下，登录看看报什么提示。
> > 
> > 
> > The timestamp in server is 1615472264 (2021-03-11T14:17:44Z),
> > and your posted timestamp is 1615471514 (2021-03-11T14:05:14Z)
> > 这个只能改自己时间了吗
> 
> 你如果能让服务器时间正确那就去弄服务器时间，如果服务器时间你操作不了，或不会改，那就改你本地时间跟它一致。
> （注意提示里面的是UTC时间，你看好时间差来改就好）

okok，非常感谢作者的耐心解答
