### ISSUE TITLE
升级完后无法登录后台

### ISSUE THREAD

**Issue by Nikeguo** [qkqpttgf/OneManager-php#247]
更新之后登录后台提示密码错误，密码没有改过，总是登录不上。不知道为社么
我是在腾讯云函数里部署的，密码在腾讯云函数文件里有明文存储吗？

**Comment by qkqpttgf** [comment]
有的，去SCF的官方后台，查看环境变量。

**Comment by bigQY** [comment]
> 有的，去SCF的官方后台，查看环境变量。

今天我也突然登录不上了，密码是正确的，好像是renexmoe这个主题的问题，我从配置文件里面改成classic主题就能用了

**Comment by Nikeguo** [comment]
对对对，就是那主题坏了。我换成otf最后一个了。还蛮好看的。不打算renexmoe了

发送自 Windows 10 版邮件应用

发件人: zejxmin
发送时间: 2021年3月11日 19:49
收件人: qkqpttgf/OneManager-php
抄送: 郭柯廷; Author
主题: Re: [qkqpttgf/OneManager-php] 升级完后无法登录后台 (#247)

有的，去SCF的官方后台，查看环境变量。
今天我也突然登录不上了，密码是正确的，好像是renexmoe这个主题的问题，我从配置文件里面改成classic主题就能用了

**Comment by Nikeguo** [comment]
大佬，这个背景图变清晰点的是哪个参数呀，tfo主题。我都快改了一遍了还是没找到这个参数

发送自 Windows 10 版邮件应用

发件人: zejxmin
发送时间: 2021年3月11日 19:49
收件人: qkqpttgf/OneManager-php
抄送: 郭柯廷; Author
主题: Re: [qkqpttgf/OneManager-php] 升级完后无法登录后台 (#247)

有的，去SCF的官方后台，查看环境变量。
今天我也突然登录不上了，密码是正确的，好像是renexmoe这个主题的问题，我从配置文件里面改成classic主题就能用了
