### ISSUE TITLE
更新后无法登录的问题

### ISSUE THREAD

**Issue by sadlay** [qkqpttgf/OneManager-php#248]
看其他Issues是因为时间不同步的问题，准确地说是服务器的机器时间和系统时间不同步导致的。
但是我的服务器是利用Linux Deploy部署在手机上的，我尝试各种办法修改，但是最终由于牵扯到时钟和内核问题，设置不了系统时间，导致依旧无法登录，希望可以优化下不要求时间同步，谢谢！

**Comment by qkqpttgf** [comment]
> 看其他Issues是因为时间不同步的问题，准确地说是服务器的机器时间和系统时间不同步导致的。
> 但是我的服务器是利用Linux Deploy部署在手机上的，我尝试各种办法修改，但是最终由于牵扯到时钟和内核问题，设置不了系统时间，导致依旧无法登录，希望可以优化下不要求时间同步，谢谢！

呃，你有用昨晚的最新版本？登录出错时会提示哪里问题，可以确认一下服务器跟浏览器差多少时间。
服务器时间改不了，那就改手机时间，我前天就是这样的。

**Comment by djnwzs** [comment]
同样遇到这问题
