### ISSUE TITLE
请问可以增加一个看图模式，而不是只能看缩略图吗

### ISSUE THREAD

**Issue by dahuajiz** [qkqpttgf/OneManager-php#25]
![Screenshot_2020-03-07-08-44-15-680_com coolapk market](https://user-images.githubusercontent.com/47171177/76132983-68443b00-5fdb-11ea-8cd4-fc0ffad4fb3c.jpg)

**Comment by qkqpttgf** [comment]
前端后端技能不足，等我有空学会再做。
