### ISSUE TITLE
不支持这种HEVC格式视频播放

### ISSUE THREAD

**Issue by yfnok** [qkqpttgf/OneManager-php#251]
BluRay 1080p DTS-HD MA 5.1 x265.10bit
如果网页不支持播放，能否调用手机播放器播放呢？

**Comment by qkqpttgf** [comment]
前面有人提到，只能播放8bit的。

**Comment by yfnok** [comment]
大佬，那这个能做到跟
goindex-theme-acrou
一样在视频界面调用 客户端软件播放视频吗？
这样是不是就解决了 很多视频不能播放的问题了

**Comment by qkqpttgf** [comment]
我，不会……
