### ISSUE TITLE
無法進行新增盤操作

### ISSUE THREAD

**Issue by CuteCatXiao** [qkqpttgf/OneManager-php#253]
點擊添加盤后跳轉至首頁
![OneManager-设置-和另外-8-个页面-小萌猫CuteCat-Microsoft_-Edge-Canary-2021-03-14-15-08-54](https://user-images.githubusercontent.com/62191675/111060373-61e27c00-84d7-11eb-8eb1-54e18ea9da02.gif)

**Comment by qkqpttgf** [comment]
我有理由认为你的CF缓存在起作用，
你要不直接访问源站操作？？

**Comment by CuteCatXiao** [comment]
@qkqpttgf  
![OneManager-设置-和另外-5-个页面-小萌猫CuteCat-Microsoft_-Edge-Canary-2021-03-14-15-55-17](https://user-images.githubusercontent.com/62191675/111061436-5e9ebe80-84de-11eb-9eb9-7bab7b73b48f.gif)
源站操作也是如此
