### ISSUE TITLE
renexmoe主题没有分页，单文件夹最多显示172个文件左右，并且登录需要两次登录才可以登录上去

### ISSUE THREAD

**Issue by office365E5** [qkqpttgf/OneManager-php#254]

**Comment by qkqpttgf** [comment]
分页问题再说，我跟186确认下。
#252  登录2次的问题，在这个issue里有，你看下 。

**Comment by office365E5** [comment]
> 分页问题再说，我跟186确认下。
> [＃252](https://github.com/qkqpttgf/OneManager-php/issues/252) 登录2次的问题，在这个问题里有，你看下。

好的
