### ISSUE TITLE
添加SharePoint盘返回500错误

### ISSUE THREAD

**Issue by MiaoLuoNa** [qkqpttgf/OneManager-php#256]
添加SharePoint盘时出现500错误
![https___cpcs-2 herokuapp](https://user-images.githubusercontent.com/62191675/111075023-eefdf300-8520-11eb-94b1-5bdab95a752d.gif)

**Comment by qkqpttgf** [comment]
更新，用新版本试试

**Comment by qkqpttgf** [comment]
还有这问题吗？url私我我有空试试
