### ISSUE TITLE
flv格式视频无法显示

### ISSUE THREAD

**Issue by CuteCatXiao** [qkqpttgf/OneManager-php#257]
![image](https://user-images.githubusercontent.com/62191675/111076420-312a3300-8527-11eb-8882-c4bad8e17cb6.png)
flv格式视频显示视频加载失败

**Comment by YidaozhanYa** [comment]
俺这边可以正常播放
https://pan.yidaozhan.gq/drive2/Never%20Gonna%20Give%20You%20Up.flv?preview

**Comment by qkqpttgf** [comment]
flv只有手机上的某些【国产浏览器】可以播放。

**Comment by zzjjbb** [comment]
> 
> 
> flv只有手机上的某些【国产浏览器】可以播放。

您好，我用火狐浏览器，发现播放flv文件的时候前几分钟可以播放，到之后的部分浏览器就会说“跨域请求被拦截”。本人没有web开发的经验，用浏览器自带的调试器玩了半天也一头雾水，很好奇为什么，可以请教一下吗？谢谢！

**Comment by qkqpttgf** [comment]
> > flv只有手机上的某些【国产浏览器】可以播放。
> 
> 您好，我用火狐浏览器，发现播放flv文件的时候前几分钟可以播放，到之后的部分浏览器就会说“跨域请求被拦截”。本人没有web开发的经验，用浏览器自带的调试器玩了半天也一头雾水，很好奇为什么，可以请教一下吗？谢谢！

啊，这我也不太熟了
