### ISSUE TITLE
onedrive阿里云盘游客上传文件命名乱码

### ISSUE THREAD

**Issue by echsfxy** [qkqpttgf/OneManager-php#261]

**Comment by qkqpttgf** [comment]
?????????图呢？？？

**Comment by echsfxy** [comment]
哇哦ʘʚʘ嘎？有邮箱提醒?
另外其他网盘也是，在游客状态下上传文件无法保持原文件名



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年3月19日(周五) 下午3:06
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [qkqpttgf/OneManager-php] onedrive阿里云盘游客上传文件命名乱码 (#261)




 
?????????图呢？？？

**Comment by qkqpttgf** [comment]
这个问题回答过很多遍了，请在issue里搜索游客2字
