### ISSUE TITLE
阿里云盘目录以及文件夹中文件只能显示50个

### ISSUE THREAD

**Issue by echsfxy** [qkqpttgf/OneManager-php#262]

**Comment by qkqpttgf** [comment]
嗯，还没对这个做处理。

**Comment by echsfxy** [comment]
像这个能解决吗？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年3月19日(周五) 下午3:06
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [qkqpttgf/OneManager-php] 阿里云盘目录以及文件夹中文件只能显示50个 (#262)




 
嗯，还没对这个做处理。

**Comment by qkqpttgf** [comment]
做了个分支GBKpreview，你更新到这个分支看下，应该可以突破50了，看下有没有其它问题。
