### ISSUE TITLE
doxc,pptx等格式无法预览

### ISSUE THREAD

**Issue by jizizr** [qkqpttgf/OneManager-php#263]
![image](https://user-images.githubusercontent.com/78908842/111734161-83b37880-88b4-11eb-9c51-9a211442f6bb.png)
doxc,pptx等格式无法预览

**Comment by qkqpttgf** [comment]
这个问题我还没解决。

**Comment by qkqpttgf** [comment]
点更新后试试

**Comment by jizizr** [comment]
> 点更新后试试

最近好像没有更新

**Comment by qkqpttgf** [comment]
> > 点更新后试试
> 
> 最近好像没有更新

。。。。。。。。。。。。一定要提示更新才能点吗？？？？？？？？

**Comment by jizizr** [comment]
> > > 点更新后试试
> > 
> > 
> > 最近好像没有更新
> 
> 。。。。。。。。。。。。一定要提示更新才能点吗？？？？？？？？

问题是好像点了也没用

**Comment by qkqpttgf** [comment]
> > > > 点更新后试试
> > > 
> > > 
> > > 最近好像没有更新
> > 
> > 
> > 。。。。。。。。。。。。一定要提示更新才能点吗？？？？？？？？
> 
> 问题是好像点了也没用

https://herooneindex.herokuapp.com/E5/Theme/%E6%8B%9B%E6%A0%87%E8%A6%81%E6%B1%821101.doc?preview ，我demo已经可以了呀
