### ISSUE TITLE
Unable to retrieve user's mysite URL

### ISSUE THREAD

**Issue by 676077263** [qkqpttgf/OneManager-php#264]
429{ "error": { "code": "BadRequest", "message": "Unable to retrieve user's mysite URL.", "innerError": { "date": "2021-03-19T12:55:08", "request-id": "881030ae-a341-4440-b816-6534ccdaf4d8", "client-request-id": "881030ae-a341-4440-b816-6534ccdaf4d8" } } }
连接onedrive错误，国际版，这该怎么弄？

**Comment by qkqpttgf** [comment]
未知原因，猜测是：你最开始登录Onedrive时是一个邮箱后缀，但现在换了一个后缀。
比如最开始时是微软默认的那个长长的，然后现在你用的你自己的域名。
就可能会导致这样的情况出现。
