### ISSUE TITLE
 renexmoe 主题上传目录没有上传选项

### ISSUE THREAD

**Issue by Lier16** [qkqpttgf/OneManager-php#265]
![image](https://user-images.githubusercontent.com/69004069/111875022-a0de6900-89d2-11eb-9c30-90130ab67c06.png)
![image](https://user-images.githubusercontent.com/69004069/111875076-cf5c4400-89d2-11eb-9ca6-b6e064c6848d.png)
请问作者这是还未开发还是我这边的原因？

**Comment by qkqpttgf** [comment]
这个主题是oneindex那边移植过来的，没有上传功能，不做。
