### ISSUE TITLE
关于解决.docx .pptx文件不能在线预览的问题

### ISSUE THREAD

**Issue by lksin** [qkqpttgf/OneManager-php#266]
原本可以正常预览.docx .pptx文件，自3月更新后任何主题都无法在线预览docx .pptx文件。

本人使用heroku进行部署，使用的renexmoe主题

我将主题文件``renexmoe.html``里iframe office中的
```php

src="https://view.officeapps.live.com/op/view.aspx?src=<!--FileEncodeDownUrl-->

```
中的``<!--FileEncodeDownUrl-->``改为``https://xxxxxx.herokuapp.com<!--FileEncodeReplaceUrl-->``
就可以正常显示了

但是使用这种方法，预览速度比以前慢了不少，希望大神可以尽快修复。

**Comment by lksin** [comment]
![a.PNG](https://i.loli.net/2021/03/21/MALHZEuaWVgNji9.png)

**Comment by YidaozhanYa** [comment]
俺也一样

**Comment by jssycszyj** [comment]
@qkqpttgf 传给微软在线预览地址的文件参数传错了，传成了相对地址
`<iframe id="office-a" src="https://view.officeapps.live.com/op/view.aspx?src=%2FE3%2F1110133001.doc" style="width: 100%;height: 800px" frameborder="0"></iframe>`
应该传带域名的完整地址
common.php里我看你注释了第一种处理方法，实测第一种有效，换成这个就行
```
第一种//$html = str_replace('<!--FileEncodeDownUrl-->', urlencode($files['url']), $html);
第二种while (strpos($html, '<!--FileEncodeDownUrl-->')) $html = str_replace('<!--FileEncodeDownUrl-->', urlencode(path_format($_SERVER['base_disk_path'] . '/' . $path)), $html);
```

**Comment by qkqpttgf** [comment]
> @qkqpttgf 传给微软在线预览地址的文件参数传错了，传成了相对地址
> `<iframe id="office-a" src="https://view.officeapps.live.com/op/view.aspx?src=%2FE3%2F1110133001.doc" style="width: 100%;height: 800px" frameborder="0"></iframe>`
> 应该传带域名的完整地址
> common.php里我看你注释了第一种处理方法，实测第一种有效，换成这个就行
> 
> ```
> 第一种//$html = str_replace('', urlencode($files['url']), $html);
> 第二种while (strpos($html, '')) $html = str_replace('', urlencode(path_format($_SERVER['base_disk_path'] . '/' . $path)), $html);
> ```

上次就是第一种出问题了才改的，现在好像好了？
那我先改回去了。
