### ISSUE TITLE
部署到Glitch之后登录不能选主题

### ISSUE THREAD

**Issue by 12123ads** [qkqpttgf/OneManager-php#273]
新版的我部署到Glitch之后登录不能选主题，后台设置了别的主题返回主页也是默认主题，退出登录看就是后台选的主题

**Comment by qkqpttgf** [comment]
是的，昨天新增的功能。
因为其它主题的管理功能有可能跟不上版本了，上次有人删一个文件，误删当前目录。
所以管理操作全以默认主题来操作。

**Comment by 12123ads** [comment]
哦
