### ISSUE TITLE
请问添加阿里云盘下载报错403怎么办

### ISSUE THREAD

**Issue by 12123ads** [qkqpttgf/OneManager-php#275]

**Comment by qkqpttgf** [comment]
去掉CDN如果没问题的话，那说明OneManager中的no-reffer工作正常。
套上CDN那我就没办法了。

**Comment by 12123ads** [comment]
额，我用的glitch部署的，应该没有cdn



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年3月29日(周一) 上午8:55
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [qkqpttgf/OneManager-php] 请问添加阿里云盘下载报错403怎么办 (#275)




 
去掉CDN如果没问题的话，那说明OneManager中的no-reffer工作正常。
 套上CDN那我就没办法了。

**Comment by qkqpttgf** [comment]
那你去我glitch的demo看看，我这边正常。

**Comment by 12123ads** [comment]
你的这个也不行，是不是不能用第三方下载器
![QQ截图20210329192049](https://user-images.githubusercontent.com/69107029/112829756-28f3fb00-90c4-11eb-8ada-14b4a466d57f.png)

**Comment by qkqpttgf** [comment]
那应该大概可能也许就是你这个下载器的锅了。
几秒前我去点了一下下载，正常弹出文件保存窗口。

**Comment by am-abudu** [comment]
> 那应该大概可能也许就是你这个下载器的锅了。
> 几秒前我去点了一下下载，正常弹出文件保存窗口。
现在貌似真的不行了，我这也不行
![image](https://user-images.githubusercontent.com/51912589/112939707-863c8a80-915e-11eb-9d96-870465625aec.png)
有什么方法解决吗，目前看到的只有伪造Referer
'Referer: https://www.aliyundrive.com/'

**Comment by qkqpttgf** [comment]
嗯，刚刚也发现了，目前没有办法，等有人想到吧。

**Comment by 12123ads** [comment]
好吧



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年3月30日(周二) 下午3:24
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [qkqpttgf/OneManager-php] 请问添加阿里云盘下载报错403怎么办 (#275)




 
嗯，刚刚也发现了，目前没有办法，等有人想到吧。

**Comment by DaYePython** [comment]
都出现了这个问题, 包括[sharelist](https://github.com/reruin/sharelist/)也出现, 我就是从哪里转过来的, 应该是共有的问题.
![问题截图](https://user-images.githubusercontent.com/31787077/113003720-93c93300-91a5-11eb-9e4b-399fb15b800c.png)

**Comment by am-abudu** [comment]
https://github.com/Xhofe/alist
alist貌似已经修复，

**Comment by qkqpttgf** [comment]
已经去看过alist了，@122cygf 用了手机版的东西，试过目前可以工作，不知道我可不可以抄？

**Comment by 12123ads** [comment]
还是下载不了，我这个点击下载直接跳转到这个页面
![QQ截图20210331204129](https://user-images.githubusercontent.com/69107029/113146332-1a434a80-9262-11eb-98e1-6875fc381fc8.png)

**Comment by qkqpttgf** [comment]
> 还是下载不了，我这个点击下载直接跳转到这个页面

那我不知道你什么问题了，我demo已经好了，刚刚几秒前点下载可以弹出文件保存窗口。

**Comment by leganck** [comment]
貌似又出问题了

**Comment by 122cygf** [comment]
> 貌似又出问题了

确实，但是在客户端抓了一下还是没有referer，回来看看是什么原因

**Comment by 122cygf** [comment]
经过尝试，换成客户端抓的refresh_token可以暂时解决问题，剩下的我有空再看

**Comment by qkqpttgf** [comment]
> 经过尝试，换成客户端抓的refresh_token可以暂时解决问题，剩下的我有空再看

好，辛苦了

**Comment by 122cygf** [comment]
有一个稍微简单点的方法，可以在浏览器控制台抓登录时候的包，登录有一个包是https://pass port.aliyundr ive.com/newlogin/sms/login.do，返回值json里有个bizExt，base64解码之后最底下有个refresh_token，用那个token下载就正常了
