### ISSUE TITLE
这怎么办

### ISSUE THREAD

**Issue by cuijianzhuang** [qkqpttgf/OneManager-php#278]
![Snipaste_2021-03-29_23-25-20](https://user-images.githubusercontent.com/31424401/112860122-1be80380-90e6-11eb-840a-28bb6a50d1d4.png)

**Comment by qkqpttgf** [comment]
一个  【测试中的google client】，最多100个用户，前几天就满了。
要么等我去弄弄google审核，要么你先自建。

**Comment by cuijianzhuang** [comment]
好的，谢谢解惑
