### ISSUE TITLE
上传和下载过慢

### ISSUE THREAD

**Issue by 888haobing** [qkqpttgf/OneManager-php#281]
部署在heroku上的，但是上传只有100多kb，下载500左右，可不可以通过用cloudflare worker中转流量了提升速度？

另可不可以只分享指定路径？
（还有，大佬，阿里云盘的refresh token 怎么获取啊）

**Comment by qkqpttgf** [comment]
中转也许可以提升下载速度，上传是你直接对话微软，不中转。
指定路径？慢慢看readme吧，还有设置里面慢慢看。
阿里的自行百度【输入框里都写了去百度】。
