### ISSUE TITLE
添加onedrive时出现401错误

### ISSUE THREAD

**Issue by HongjieCN** [qkqpttgf/OneManager-php#284]
![image](https://user-images.githubusercontent.com/57511284/113429313-e6575900-940a-11eb-88fa-acb0ad55ff84.png)

**Comment by HongjieCN** [comment]
找到原因了，是云函数里面的模板版本太旧所致，更新到最新的release就解决了

**Comment by qkqpttgf** [comment]
> 找到原因了，是云函数里面的模板版本太旧所致，更新到最新的release就解决了

写作release，读作archive。
