### ISSUE TITLE
谷歌网盘无法观看视频和下载文件

### ISSUE THREAD

**Issue by Dragon-son** [qkqpttgf/OneManager-php#286]
用自己申请的api后，可以读取文件夹内容，但是所有视频都无法观看，
![image](https://user-images.githubusercontent.com/55612871/113508447-a915d700-9582-11eb-8d3b-b4786d48f71d.png)
申请的web应用凭据，重定向是https://scfonedrive.github.io，不知道哪里出了问题，大佬能解答吗

**Comment by qkqpttgf** [comment]
可以列表的话，说明应该工作正常了。
不能下载的话，报的什么错？

**Comment by cuijianzhuang** [comment]
我也是，挂vpn才行

**Comment by jssycszyj** [comment]
> 我也是，挂vpn才行

文件流量不经过服务器，列表返回的谷歌盘源地址，是墙的

**Comment by LiJinChang** [comment]
> 可以列表的话，说明应该工作正常了。
> 不能下载的话，报的什么错？

点下载后会跳转到 Google Drive 的病毒扫描页面
![2021-04-09_125409](https://user-images.githubusercontent.com/1154661/114130482-3f574d80-9933-11eb-8f8c-fdb50db2b524.png)

**Comment by Dragon-son** [comment]
> 我也是，挂vpn才行

挂全局也播放不了，可以下载小文件，大文件直接跳到谷歌病毒扫描页

**Comment by qkqpttgf** [comment]
> > 我也是，挂vpn才行
> 
> 挂全局也播放不了，可以下载小文件，大文件直接跳到谷歌病毒扫描页

好吧，有空去参观学习一下其它程序的解决方案（不要是我猜的中转……）。

**Comment by zjboy1984** [comment]
谷歌挂载出现这个403{ "error": { "errors": [ { "domain": "usageLimits", "reason": "accessNotConfigured", "message": "Access Not Configured. Drive API has not been used in project 401736447968 before or it is disabled. Enable it by visiting https:\/\/console.developers.google.com\/apis\/api\/drive.googleapis.com\/overview?project=401736447968 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.", "extendedHelp": "https:\/\/console.developers.google.com\/apis\/api\/drive.googleapis.com\/overview?project=401736447968" } ], "code": 403, "message": "Access Not Configured. Drive API has not been used in project 401736447968 before or it is disabled. Enable it by visiting https:\/\/console.developers.google.com\/apis\/api\/drive.googleapis.com\/overview?project=401736447968 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry." } }

**Comment by qkqpttgf** [comment]
> 谷歌挂载出现这个403{ "error": { "errors": [ { "domain": "usageLimits", "reason": "accessNotConfigured", "message": "Access Not Configured. Drive API has not been used in project 401736447968 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/drive.googleapis.com/overview?project=401736447968 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.", "extendedHelp": "https://console.developers.google.com/apis/api/drive.googleapis.com/overview?project=401736447968" } ], "code": 403, "message": "Access Not Configured. Drive API has not been used in project 401736447968 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/drive.googleapis.com/overview?project=401736447968 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry." } }

你只复制了不看的？？里面都有方法了啊！！

**Comment by zjboy1984** [comment]
> > 谷歌挂载出现这个403{ "error": { "errors": [ { "domain": "usageLimits", "reason": "accessNotConfigured", "message": "Access Not Configured. Drive API has not been used in project 401736447968 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/drive.googleapis.com/overview?project=401736447968 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.", "extendedHelp": "https://console.developers.google.com/apis/api/drive.googleapis.com/overview?project=401736447968" } ], "code": 403, "message": "Access Not Configured. Drive API has not been used in project 401736447968 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/drive.googleapis.com/overview?project=401736447968 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry." } }
> 
> 你只复制了不看的？？里面都有方法了啊！！

我按他说的试了，但还是出这个错误

**Comment by zjboy1984** [comment]
已经挂载上了，但是挂梯子播放视频也是一卡一卡的，其他网盘正常
