### ISSUE TITLE
统计代码在哪添加

### ISSUE THREAD

**Issue by eeolive** [qkqpttgf/OneManager-php#287]
在后台customScript添加了统计代码，然而并不能统计网站访问量，添加的是百度统计的代码。

**Comment by qkqpttgf** [comment]
为了对付阿里云盘的防盗链，使用了no referer，所以统计不到。
你不用阿里云盘的话，可以自行删除no referer。

**Comment by haoduck** [comment]
> 为了阿里云盘的防盗链，使用了无参考，所以统计不到。 你不用阿里云盘的话，可以自行删除无参考。



> 为了对付阿里云盘的防盗链，使用了no referer，所以统计不到。 你不用阿里云盘的话，可以自行删除no referer。

你好，请问一下，在什么地方"删除no referer"

**Comment by qkqpttgf** [comment]
> 
> 你好，请问一下，在什么地方"删除no referer"

如果你是onedrive，那就没这东西，不用删
如果你是ali盘，那你删了这东西你就不能下载跟预览了。
