### ISSUE TITLE
管理页面css显示好像有点问题？

### ISSUE THREAD

**Issue by Aquaakuma** [qkqpttgf/OneManager-php#288]
![image](https://user-images.githubusercontent.com/31891793/113808232-2a928280-9798-11eb-9a01-ee3c03c9cc2c.png)
如图，这个对不上，平台变量那边没问题，就这边改密码的设置会对不上。

**Comment by qkqpttgf** [comment]
这边就没有css（拍腿笑

**Comment by Aquaakuma** [comment]
> 这边就没有css（拍腿笑

不懂前端，之前碰过类似的，还以为这个也是css有问题。。。只是我会这样吗？可以适配一下吗，应该就是改下位置吧
