### ISSUE TITLE
如何让文件按文件名排序

### ISSUE THREAD

**Issue by Aquaakuma** [qkqpttgf/OneManager-php#289]
有些文件夹内的文件按文件名排序比较好索引，但是默认的只有按修改时间和大小排序，不知道哪一行代码是和文件排序相关的，Issues里面好像没有人问，我提一下。🤡

**Comment by qkqpttgf** [comment]
没看懂

**Comment by Aquaakuma** [comment]
> 没看懂

就是文件夹下有01.mp4 02.mp4 03.mp4 04.mp4, 从上到下按照文件名进行排序。现在不是只能点修改时间或大小来排序吗？

**Comment by qkqpttgf** [comment]
> > 没看懂
> 
> 就是文件夹下有01.mp4 02.mp4 03.mp4 04.mp4, 从上到下按照文件名进行排序。现在不是只能点修改时间或大小来排序吗？

谁说的？？你没点过文件名排序？？

**Comment by Aquaakuma** [comment]
> > > 没看懂
> > 
> > 
> > 就是文件夹下有01.mp4 02.mp4 03.mp4 04.mp4, 从上到下按照文件名进行排序。现在不是只能点修改时间或大小来排序吗？
> 
> 谁说的？？你没点过文件名排序？？

貌似不行，我把我的站点发你吧，http://drive.aqualink.top/%E8%BD%BB%E5%B0%8F%E8%AF%B4/%E6%AC%A2%E8%BF%8E%E6%9D%A5%E5%88%B0%E5%AE%9E%E5%8A%9B%E8%87%B3%E4%B8%8A%E4%B8%BB%E4%B9%89%E7%9A%84%E6%95%99%E5%AE%A4/

**Comment by qkqpttgf** [comment]
> > > > 没看懂
> > > 
> > > 
> > > 就是文件夹下有01.mp4 02.mp4 03.mp4 04.mp4, 从上到下按照文件名进行排序。现在不是只能点修改时间或大小来排序吗？
> > 
> > 
> > 谁说的？？你没点过文件名排序？？
> 
> 貌似不行，我把我的站点发你吧，http://drive.aqualink.top/%E8%BD%BB%E5%B0%8F%E8%AF%B4/%E6%AC%A2%E8%BF%8E%E6%9D%A5%E5%88%B0%E5%AE%9E%E5%8A%9B%E8%87%B3%E4%B8%8A%E4%B8%BB%E4%B9%89%E7%9A%84%E6%95%99%E5%AE%A4/

请去备案……

**Comment by Aquaakuma** [comment]
> > > > > 没看懂
> > > > 
> > > > 
> > > > 就是文件夹下有01.mp4 02.mp4 03.mp4 04.mp4, 从上到下按照文件名进行排序。现在不是只能点修改时间或大小来排序吗？
> > > 
> > > 
> > > 谁说的？？你没点过文件名排序？？
> > 
> > 
> > 貌似不行，我把我的站点发你吧，http://drive.aqualink.top/%E8%BD%BB%E5%B0%8F%E8%AF%B4/%E6%AC%A2%E8%BF%8E%E6%9D%A5%E5%88%B0%E5%AE%9E%E5%8A%9B%E8%87%B3%E4%B8%8A%E4%B8%BB%E4%B9%89%E7%9A%84%E6%95%99%E5%AE%A4/
> 
> 请去备案……

打不开吗？我可以呀
![image](https://user-images.githubusercontent.com/31891793/113879274-eda4ab00-97ec-11eb-98c3-69cff27bd73d.png)

**Comment by qkqpttgf** [comment]
以我demo为准，可以点的

**Comment by Aquaakuma** [comment]
调试网页源代码中的index发现: 按文件名排序与按修改时间或按大小的实现方式好像不同，那两个直接用for循环处理了，按文件名这个跳到了别的js文件，猜测是按照网盘给的默认数据，我用的是阿里网盘，它默认是按修改时间排序的，所以在onemanager上点击效果和按修改时间一样，不知道说的对不对（不懂js）

**Comment by qkqpttgf** [comment]
> 调试网页源代码中的index发现: 按文件名排序与按修改时间或按大小的实现方式好像不同，那两个直接用for循环处理了，按文件名这个跳到了别的js文件，猜测是按照网盘给的默认数据，我用的是阿里网盘，它默认是按修改时间排序的，所以在onemanager上点击效果和按修改时间一样，不知道说的对不对（不懂js）

点文件是恢复默认排序，点大小跟时间可以正向反向排序。
仔细去看了下，好吧，阿里真的是时间排序。
【来学程序吧】
