### ISSUE TITLE
502 Bad Gateway nginx

### ISSUE THREAD

**Issue by qq22784647** [qkqpttgf/OneManager-php#29]
之前用免费的虚拟主机安装很顺利，现在用阿里云装了宝塔，新建网站把源码上传后，点击安装出现502 Bad Gateway，nginx，装oneindex又没问题，请问是php的配置有什么问题吗？

**Comment by qq22784647** [comment]
有人说是伪静态的设置问题，但是宝塔里面我就选的默认的，难道有专门的规则吗？我选了wordpress也不行

**Comment by qkqpttgf** [comment]
看readme，谢谢
