### ISSUE TITLE
文件夹名包含%导致文件夹下文件400错误

### ISSUE THREAD

**Issue by jssycszyj** [qkqpttgf/OneManager-php#291]
文件夹名包含%会导致文件夹下面的文件400错误

**Comment by jssycszyj** [comment]
更正下，文件名没事，文件夹名不行

**Comment by jssycszyj** [comment]
更正下，不是文件名，文件夹名包含%会导致文件夹下面的文件400错误

**Comment by qkqpttgf** [comment]
可以工作？

**Comment by jssycszyj** [comment]
> 可以工作？

我改过了，正常使用了
[DEMO](https://demo-od.plus.workers.dev/)
