### ISSUE TITLE
缓存刷新的速度太慢了怎么办

### ISSUE THREAD

**Issue by nodesire7** [qkqpttgf/OneManager-php#292]
RT
缓存刷新的太慢了 不管是换主题还是修改foot.omf都要等很久才能刷新到最新的配置

**Comment by qkqpttgf** [comment]
不不不，这个程序不刷新缓存，除非你手动点刷新。
因为是真缓存，并不保存在文件或数据库中。
这个程序是等缓存死掉，不久，才1小时。

**Comment by nodesire7** [comment]
> 不不不，这个程序不刷新缓存，除非你手动点刷新。
> 因为是真缓存，并不保存在文件或数据库中。
> 这个程序是等缓存死掉，不久，才1小时。

好吧 那那个管理登录后的主题与未登录的主题不统一 这个有办法调整么

**Comment by qkqpttgf** [comment]
> > 不不不，这个程序不刷新缓存，除非你手动点刷新。
> > 因为是真缓存，并不保存在文件或数据库中。
> > 这个程序是等缓存死掉，不久，才1小时。
> 
> 好吧 那那个管理登录后的主题与未登录的主题不统一 这个有办法调整么

不是不统一，管理固定用默认主题来管理操作，游客就只能用指定的主题来访问。

**Comment by nodesire7** [comment]
> > > 不不不，这个程序不刷新缓存，除非你手动点刷新。
> > > 因为是真缓存，并不保存在文件或数据库中。
> > > 这个程序是等缓存死掉，不久，才1小时。
> > 
> > 
> > 好吧 那那个管理登录后的主题与未登录的主题不统一 这个有办法调整么
> 
> 不是不统一，管理固定用默认主题来管理操作，游客就只能用指定的主题来访问。

好的 谢谢解惑
