### ISSUE TITLE
阿里云盘的解析好像又挂了

### ISSUE THREAD

**Issue by onelxzy** [qkqpttgf/OneManager-php#293]
阿里云盘的解析好像又挂了。更新token也不行
报错：At least one of AdditionalHeaders is not in request headers.

**Comment by qkqpttgf** [comment]
看英文啊，解析没挂，只是不能直接从阿里下载了，除非弄个反代中转。

**Comment by Shensuyang** [comment]
引用ALIST项目的解决办法：web端token已失效，请参考这个issue通过手机端抓包/查找日志（Android/data/com.alicloud.databox/files/logs/trace/）来获取refresh_token[https://github.com/Xhofe/alist/issues/88](url)
