### ISSUE TITLE
添加OneDrive出错

### ISSUE THREAD

**Issue by BA7JCM** [qkqpttgf/OneManager-php#298]
添加OneDrive提示”No refresh_token config, please AddDisk again or wait minutes.“，重试用相同标签添加几次了都还是这样

**Comment by qkqpttgf** [comment]
这样描述一个结果，完全不知道问题出在哪里。
请详细过程。

**Comment by BA7JCM** [comment]
> 这样描述一个结果，完全不知道问题出在哪里。
> 请详细过程。

我就一步步按照说明，用它自己建立的“应用”，用国际版onedrive e5网盘，腾讯云函数，一路下来都没有报错，最后refresh_token也能显示出来，但是再跳转之后就是我前面说的那个报错了，另外就是现在azure那边新注册应用，密码无法设置永久了，最多只能两年

**Comment by qkqpttgf** [comment]
> > 这样描述一个结果，完全不知道问题出在哪里。
> > 请详细过程。
> 
> 我就一步步按照说明，用它自己建立的“应用”，用国际版onedrive e5网盘，腾讯云函数，一路下来都没有报错，最后refresh_token也能显示出来，但是再跳转之后就是我前面说的那个报错了，另外就是现在azure那边新注册应用，密码无法设置永久了，最多只能两年

盘太多了？超过SCF限制了所以添加不上？

**Comment by BA7JCM** [comment]
> > > 这样描述一个结果，完全不知道问题出在哪里。
> > > 请详细过程。
> > 
> > 
> > 我就一步步按照说明，用它自己建立的“应用”，用国际版onedrive e5网盘，腾讯云函数，一路下来都没有报错，最后refresh_token也能显示出来，但是再跳转之后就是我前面说的那个报错了，另外就是现在azure那边新注册应用，密码无法设置永久了，最多只能两年
> 
> 盘太多了？超过SCF限制了所以添加不上？

就一个盘，之前用的好好的，我改了我帐号的域，然后那边就失效了，我就把那个盘删了，重新按照流程添加，就报错这个，我一个朋友他之前首次添加也是出现这个问题

**Comment by qkqpttgf** [comment]
有空远程瞅瞅吧……

**Comment by BA7JCM** [comment]
> 有空远程瞅瞅吧……

感觉这是个玄学问题，因为有时候它提示这个，但是我把它丢在那不管，过会再去看就发现已经添加成功了，各项功能也都正常，但就是在添加的时候会报错，然后当时去看就显示叫我重新添加这个盘，但是我不管它，过一阵子就发现已经可以了……但如果一直按他说的去添加，那永远都是这个报错

**Comment by LELOUCH-LI** [comment]
400报错
{
    "error": "invalid_grant",
    "error_description": "AADSTS54005: OAuth2 Authorization code was already redeemed, please retry with a new valid code or use an existing refresh token.\r\nTrace ID: f039b83d-1923-4b99-ba24-dd2b06ba8101\r\nCorrelation ID: c2dbd788-69cd-4c3f-96d5-5aaf5c6dbd72\r\nTimestamp: 2021-04-29 04:43:09Z",
    "error_codes": [
        54005
    ],
    "timestamp": "2021-04-29 04:43:09Z",
    "trace_id": "f039b83d-1923-4b99-ba24-dd2b06ba8101",
    "correlation_id": "c2dbd788-69cd-4c3f-96d5-5aaf5c6dbd72"
}

**Comment by qkqpttgf** [comment]
> 400报错
> {
> "error": "invalid_grant",
> "error_description": "AADSTS54005: OAuth2 Authorization code was already redeemed, please retry with a new valid code or use an existing refresh token.\r\nTrace ID: f039b83d-1923-4b99-ba24-dd2b06ba8101\r\nCorrelation ID: c2dbd788-69cd-4c3f-96d5-5aaf5c6dbd72\r\nTimestamp: 2021-04-29 04:43:09Z",

你这是code被用过了，可能是CDN或运营商什么的在你访问的同时帮你访问看看这个连接有没有危险。
换个环境看看？

**Comment by BA7JCM** [comment]
现在又遇到这个问题了，现在只要涉及到添加盘的操作，就会遇到这个问题，附上录屏文件

[添加盘录屏.zip](https://github.com/qkqpttgf/OneManager-php/files/6467871/default.zip)

文件有点套娃，但没办法，我直接上传原始文件，GitHub说大于10mb不让上传，我压了7z，它又说不支持这个文件格式，我只好再套一层zip之后再上传了。。。

**Comment by qkqpttgf** [comment]
看完视频，SCF的机制跟不上了。
写入配置后，以前的配置还在运行，并没有载入新配置，所以会这样。
要不换一家？FC、FG、CFC？或heroku？或者VPS自己弄？

**Comment by qkqpttgf** [comment]
看完视频，SCF的机制跟不上了。写入配置后，以前的配置还在运行，并没有载入新配置，所以会这样。
你可以试着在选择onedrive还是sharepoint的界面等1分钟左右再点确定看看，让它冷静一下。

要不换一家？FC、FG、CFC？或heroku？或者VPS自己弄？

**Comment by BA7JCM** [comment]
> 看完视频，SCF的机制跟不上了。
> 写入配置后，以前的配置还在运行，并没有载入新配置，所以会这样。
> 要不换一家？FC、FG、CFC？或heroku？或者VPS自己弄？

我朋友他开一个新的函数重头来过也是这样，我看了环境变量，东西已经写进去了，但程序仍然报错说没有配置到东西，叫再添加一次，不管添加多少次都是这样，目前玄学偶尔能添加成功，但这个问题是最近几个月才出现的

**Comment by BA7JCM** [comment]
> 看完视频，SCF的机制跟不上了。写入配置后，以前的配置还在运行，并没有载入新配置，所以会这样。
> 你可以试着在选择onedrive还是sharepoint的界面等1分钟左右再点确定看看，让它冷静一下。
> 
> 要不换一家？FC、FG、CFC？或heroku？或者VPS自己弄？

“冷静”大法真**管用……（吐血.JPG）有时候显示完token之后会直接error，说是没有配置token，刷新一下就能进选择onedrive/sharepoint的页面，然后我试着按照你说的让它“冷静冷静”，就添加成功了，不过heroku之前我也试过，忘了是什么原因，好像注册不上，就用了腾讯云
