### ISSUE TITLE
renexmoe主题相关问题

### ISSUE THREAD

**Issue by xX-Hacbox-Xx** [qkqpttgf/OneManager-php#299]
- 使用renexmoe主题后设置 _电脑端背景为图片API_ 和 _移动端背景为另一张静态图片_ 后访客状态将只能看到设置的 _静态图片_ ，无法根据设备自动选择
- 主题的侧边栏目内容能否进行增加删减等自定义操作？

**Comment by xX-Hacbox-Xx** [comment]
### 测试更新：
**无论如何设置，访客状态下均只能看到手机端设置的图片，在登录管理状态下可以正常工作**

**Comment by qkqpttgf** [comment]
@186526 出来挨打。
对侧边修改，只能自己手动了，应该。

**Comment by jssycszyj** [comment]
fork修改了一份，需要自取
[renexmoe-mod](https://github.com/jssycszyj/renexmoe-cdn)
