### ISSUE TITLE
change setting for encrypt

### ISSUE THREAD

**Issue by Morning3tar** [qkqpttgf/OneManager-php#3]
Hi, thanks for this project.
can you change the setting for the encrypt index directory to download direct links with no login required? (still need encrypt index to anyone)

**Comment by qkqpttgf** [comment]
Hi,
In my thought, someone can not download the files if he do not kown the password.
The encrypt function is protect the whole folder.
If you want that, someone do not kown what files in my folder but he can download a file via a url you give, you have 2 way: 
  1, set the folder as guestup_path, so others can only see a upload button but don't kown files;
  2, create a file 'index.html' in the folder, then others can see the html page and don't kown files.

**Comment by Morning3tar** [comment]
> 
> 
> Hi,
> In my thought, someone can not download the files if he do not kown the password.
> The encrypt function is protect the whole folder.
> If you want that, someone do not kown what files in my folder but he can download a file via a url you give, you have 2 way:
> 1, set the folder as guestup_path, so others can only see a upload button but don't kown files;
> 2, create a file 'index.html' in the folder, then others can see the html page and don't kown files.

it's not work if user crwal links ex : herokuapp.com/xxxx/files/test.txt
user just can't see herokuapp.com/xxxx but can see herokuapp.com/xxxx/files/ in directory

**Comment by qkqpttgf** [comment]
you close the issue.
I mean you do the operate in /files/, the folder of the file, not in /xxx/. the parent.

**Comment by Morning3tar** [comment]
yes sorry, I didn't think about crawling.
u mean i must create index.html in all directories?

**Comment by qkqpttgf** [comment]
sorry, u may do that all dirs u want.
I stick to my point that the password protect all files and folders in its path.
I think, if all files can be download, you can just show the files to everyone, and you can move the private files to another folder.

PS. do u use the public_path setting?

**Comment by Morning3tar** [comment]
yes  i used public_path but index.html better for me.
another question, can you add redirect errors like 302 to setup?
example i want redirect to index.html not itemNotFound.

**Comment by qkqpttgf** [comment]
you may mean customize the 404 page?
now I just show the response of microsoft office, and it maybe not 404 not found sometime.

PS. where are you come from? I mean your country and how you kown this project.
you kown, I am chinese, talk to you with chinglish, the users may chinese, how can you find here?(laugh)

**Comment by Morning3tar** [comment]
i mean redirect this error :
![image](https://user-images.githubusercontent.com/48289034/73586901-3f56f480-44c9-11ea-8806-92c7cfdc1830.png)

ps. i'm from iran :)) can we talk with email? morning3tar@pm.me
