### ISSUE TITLE
已配置好的网盘突然被初始化

### ISSUE THREAD

**Issue by BA7JCM** [qkqpttgf/OneManager-php#300]
我一个朋友的网盘，之前是已经完成设置并正常使用的，今天他的网盘突然变成了还没有配置过的状态（如图）
![Screenshot_2021-04-15-08-56-39-172_com microsoft emmx](https://user-images.githubusercontent.com/79561519/114802011-7f08b400-9dcf-11eb-81ed-718204ab26dd.jpg)
我一开始以为是他那边进行了什么误操作导致的，但我问了他，他说他啥也没干（如图）
![-3bc77ce49dbb05dc](https://user-images.githubusercontent.com/79561519/114802064-9c3d8280-9dcf-11eb-96da-d0bb558e8b94.png)
他也是用腾讯云函数的。我想问下，这是啥情况

**Comment by qkqpttgf** [comment]
看看环境变量里面有啥（记得打码）

**Comment by BA7JCM** [comment]
> 看看环境变量里面有啥（记得打码）
这是他给的图，环境变量里面就这些东西
![QQ图片20210423234350](https://user-images.githubusercontent.com/79561519/115896733-4f704080-a48e-11eb-92db-bbbf7fc9d20c.jpg)

**Comment by qkqpttgf** [comment]
应该早就修好了呀，现在还会这样吗？

**Comment by BA7JCM** [comment]
> 应该早就修好了呀，现在还会这样吗？

他是在出现这个问题的前几天部署的，部署的时候他更新了程序，然后过了几天就出现了上面说的问题

**Comment by qkqpttgf** [comment]
> > 应该早就修好了呀，现在还会这样吗？
> 
> 他是在出现这个问题的前几天部署的，部署的时候他更新了程序，然后过了几天就出现了上面说的问题

这个问题应该是修好了的，请重装，再观察几天

**Comment by BA7JCM** [comment]
> > > 应该早就修好了呀，现在还会这样吗？
> > 
> > 他是在出现这个问题的前几天部署的，部署的时候他更新了程序，然后过了几天就出现了上面说的问题
> 
> 这个问题应该是修好了的，请重装，再观察几天

是把整个云函数删了重新部署还是直接在当前情况下直接安装（他现在是变成了还没安装的样子）

**Comment by qkqpttgf** [comment]
请更新程序先

算了删了吧，从头开始弄

**Comment by BA7JCM** [comment]
> 请更新程序先
> 
> 算了删了吧，从头开始弄

他部署的时候更新过程序的……

我去叫他删了从头开始部署吧

**Comment by BA7JCM** [comment]
@OtoyaLee
当事人在这
