### ISSUE TITLE
请问登录报错这个怎么解决

### ISSUE THREAD

**Issue by 12123ads** [qkqpttgf/OneManager-php#301]
Timestamp not Number
![Screenshot_20210415-170414.png](https://i.loli.net/2021/04/15/yLpED64fCnPS2oX.png)

**Comment by 12123ads** [comment]
Glitch部署的，之前可以正常登录，不知道为啥就不行了

**Comment by qkqpttgf** [comment]
你按F12看看是不是某个js没加载成功导致的

**Comment by 12123ads** [comment]
用手机就报错这个，电脑登录就正常(・・;)

**Comment by 12123ads** [comment]
emmmm，好像是浏览器的问题，edge登录就正常，x浏览器 via浏览器登录就报错，Iceraven浏览器弹出了个这个
![IMG_20210416_130750_252.jpg](https://sc01.alicdn.com/kf/Ue18c1b8244b6468da66e9fac7176ab1fI.jpg)

**Comment by BA7JCM** [comment]
我也遇到这个问题，在学校机房的电脑登录也报错这个，旧版edge和IE都报错这个，f12看了没有没加载出来的东西

**Comment by BA7JCM** [comment]
> Glitch部署的，之前可以正常登录，不知道为啥就不行了

我也遇到这个问题，在学校机房的电脑登录也报错这个，旧版edge和IE都报错这个，f12看了没有没加载出来的东西![IMG_20210506_083241.jpg](https://user-images.githubusercontent.com/79561519/117225760-a9d1af80-ae45-11eb-8766-eead7e814b4c.jpg)

**Comment by qkqpttgf** [comment]
> > Glitch部署的，之前可以正常登录，不知道为啥就不行了
> 
> 我也遇到这个问题，在学校机房的电脑登录也报错这个，旧版edge和IE都报错这个，f12看了没有没加载出来的东西


那我也不知道哪里问题了。

**Comment by BA7JCM** [comment]
> > > Glitch部署的，之前可以正常登录，不知道为啥就不行了
> > 
> > 
> > 我也遇到这个问题，在学校机房的电脑登录也报错这个，旧版edge和IE都报错这个，f12看了没有没加载出来的东西
> 
> 那我也不知道哪里问题了。

我部署在腾讯云函数上面的，自己电脑的浏览器和手机浏览器访问正常，能登录，但是学校机房的电脑就登不上去，另外国外区域的云函数部署都会出一些奇奇怪怪的问题，在国内（含港区）就能部署成功，原因未知，我最开始在硅谷区的腾讯云函数部署，到需要访问GitHub那一步就一直不行，好像是500error还是啥的我忘了，后来换了港区的就顺利部署成功，就是最近需要添加网盘的时候会有一些问题，就是之前我提的那个issue( #298  ),那个问题我和我朋友( @OtoyaLee )都遇到过，他是在首次添加的时候遇到的问题，我是在我更改了我账号的域之后重新添加的时候出的问题
