### ISSUE TITLE
登陆按钮没反应

### ISSUE THREAD

**Issue by Qa70601234** [qkqpttgf/OneManager-php#304]
![image](https://user-images.githubusercontent.com/74185784/115946574-bb858f80-a4f4-11eb-8a95-dd8596065ceb.png)
就像个文本一样

**Comment by qkqpttgf** [comment]
不是像，它就是个文本，这个主题还是【dev】，或许永远也不做下去了。

**Comment by Qa70601234** [comment]
加了个?admin就行了
不挑，能用就行！！
