### ISSUE TITLE
添加新的onedrive盘，安装程序之后就会报错401

### ISSUE THREAD

**Issue by liao666brant** [qkqpttgf/OneManager-php#305]
具体就是
在管理界面添加新的onedrive盘，填写好便签、名称选择使用默认的MS: 国际版（商业版与个人版），之后登录office选择账户然后提示安装，跳转页面后就401报错。具体报错如下：
401
{
    "error": "invalid_client",
    "error_description": "AADSTS7000222: The provided client secret keys are expired. Visit the Azure Portal to create new keys for your app, or consider using certificate credentials for added security: https:\/\/docs.microsoft.com\/azure\/active-directory\/develop\/active-directory-certificate-credentials\r\nTrace ID: 8e04b9ca-b2f4-40cd-aff7-12e27c184e00\r\nCorrelation ID: 2a47f3d4-f73e-4f83-890d-94bc3e7890c3\r\nTimestamp: 2021-04-24 12:10:20Z",
    "error_codes": [
        7000222
    ],
    "timestamp": "2021-04-24 12:10:20Z",
    "trace_id": "8e04b9ca-b2f4-40cd-aff7-12e27c184e00",
    "correlation_id": "2a47f3d4-f73e-4f83-890d-94bc3e7890c3",
    "error_uri": "https:\/\/login.microsoftonline.com\/error?code=7000222"
}

**Comment by qkqpttgf** [comment]
The provided client secret keys are expired  <<----请自行翻译

你用的默认的client还是自建的，有没有更新程序

**Comment by liao666brant** [comment]
> The provided client secret keys are expired <<----请自行翻译
> 
> 你用的默认的client还是自建的，有没有更新程序

我用的是默认的client，至于更新程序，我是用的是腾讯云scf总是更新失败。我首先在管理后台点击更新，但是腾讯云函数哪里显示更新失败，我在隐函数哪里再点击重新部署，然后再去onemanager网页中查看，但是还是显示我需要更新。

**Comment by qkqpttgf** [comment]
嗯，旧代码中的secret过期了的，所以要新代码
你手动上传新代码上到SCF上吧。
