### ISSUE TITLE
添加谷歌网盘出错，返回200

### ISSUE THREAD

**Issue by jing5460** [qkqpttgf/OneManager-php#306]
![image](https://user-images.githubusercontent.com/38358681/116326223-816b0500-a7f6-11eb-9041-a3cca9f0f930.png)

**Comment by rootwhois** [comment]
我也有这个情况，你解决了吗

**Comment by qkqpttgf** [comment]
这个可能是因为我的应用没有审核，所以只有第1次有refresh token（但以前的还能一直用），这次就只有access token。
你可以去google帐号找到第三方程序取消授权，再重装一次，
也可以自己新建一个应用，用自己的应用。

**Comment by annkoxx** [comment]
> 我也有这个情况，你解决了吗

这个可能是因为我的应用没有审核，所以只有第1次有refresh token（但以前的还能一直用），这次就只有access token。
你可以去google帐号找到第三方程序取消授权，再重装一次，
也可以自己新建一个应用，用自己的应用。





作者说的  这个办法可以解决

**Comment by 269987183** [comment]
此应用已被阻止
此应用试图访问您 Google 帐号中的敏感信息。为确保您的帐号安全，Google 阻止了此次访问。

**Comment by orangejx** [comment]
> 此应用已被阻止
> 此应用试图访问您 Google 帐号中的敏感信息。为确保您的帐号安全，Google 阻止了此次访问。

同样遇到了该问题

**Comment by ZXD990129** [comment]
怎么解决？
