### ISSUE TITLE
跑index.html似乎有点问题？

### ISSUE THREAD

**Issue by BA7JCM** [qkqpttgf/OneManager-php#310]
我往里面丢了一套index.html和它配套的js、css到一个文件夹里，跑起来之后有些js加载不出来，在浏览器开发者选项里显示“（已阻止：原点）”
![image](https://user-images.githubusercontent.com/79561519/117046617-79095180-ad43-11eb-85ee-1e7ddf049401.png)
但是这套东西在本地用localhost访问的时候是没问题的。。。不知道是啥情况

**Comment by qkqpttgf** [comment]
打包给我，我丢demo上

**Comment by BA7JCM** [comment]
> 打包给我，我丢demo上

[unlock-music.zip](https://github.com/qkqpttgf/OneManager-php/files/6588946/unlock-music.zip)

**Comment by qkqpttgf** [comment]
已经丢在demo上了，
1，我发现，ixarea-stats.js 为0字节文件。
2，你这里面js真大。
3，html中没有引用woff，应该是某个js中引用的，在precache-mxxxxxxxxxxxxxxxx.js中找到了这个woff的引用，用了相对路径。

即，引用的js，它里面引用了其它文件，然后，因为是302去微软的，所以这个js认为它所在的网站是微软，所以它引用的文件就去微软找了。
js从我们网站引用微软的文件，产生了CORS报错。【不过就算不报CORS，也引用不到的】

所以，这样跑html，只能是一次引用，这样能正常运行，不能在js里面再来引用文件。
当然，你可以去手动修改js里面，把相对路径引用加上域名之类，应该就可以用了，当然可能是个大工程。

**Comment by qkqpttgf** [comment]
另一个方法，我项目中有CF workers的代码，
通过这个似乎可以正常跑了（不给你看）。
【虽然还有个remove报错，但肯定不是我的问题了】

**Comment by BA7JCM** [comment]
> 已经丢在demo上了，
> 1，我发现，ixarea-stats.js 为0字节文件。
> 2，你这里面js真大。
> 3，html中没有引用woff，应该是某个js中引用的，在precache-mxxxxxxxxxxxxxxxx.js中找到了这个woff的引用，用了相对路径。
> 
> 即，引用的js，它里面引用了其它文件，然后，因为是302去微软的，所以这个js认为它所在的网站是微软，所以它引用的文件就去微软找了。
> js从我们网站引用微软的文件，产生了CORS报错。【不过就算不报CORS，也引用不到的】
> 
> 所以，这样跑html，只能是一次引用，这样能正常运行，不能在js里面再来引用文件。
> 当然，你可以去手动修改js里面，把相对路径引用加上域名之类，应该就可以用了，当然可能是个大工程。

我这个也是拿别人的源码（https://github.com/unlock-music/unlock-music ）直接编译部署的，另外是把所有引用js的地方都改成绝对路径吗

**Comment by BA7JCM** [comment]
> 另一个方法，我项目中有CF workers的代码，
> 通过这个似乎可以正常跑了（不给你看）。
> 【虽然还有个remove报错，但肯定不是我的问题了】

这。。。那我干脆直接丢cloudflare workers里可以的吗

**Comment by qkqpttgf** [comment]
来，现在试试demo里面，好像可以跑了

**Comment by BA7JCM** [comment]
> 来，现在试试demo里面，好像可以跑了

刚刚测试了一下，可以跑了，多谢大佬

**Comment by qkqpttgf** [comment]
最新版本，设置程序中转大小跟时间，就可以达到这样的目的了。
