### ISSUE TITLE
绑定的阿里网盘无法预览/下载文件

### ISSUE THREAD

**Issue by jstar0** [qkqpttgf/OneManager-php#312]
错误信息：下载文件，指向直链：******.cn-beijing.data.alicloudccp.com，提示
`<Error>
<Code>InvalidArgument</Code>
<Message>At least one of AdditionalHeaders is not in request headers.</Message>
<RequestId>********************</RequestId>
<HostId>******.cn-beijing.data.alicloudccp.com</HostId>
</Error>`
安装参数：使用阿里云函数(FC)的HTML模板，选择php7.2，上传OneManager程序，使用了自定义域名，未修改触发器相关设置（默认的POST和GET）

**Comment by qkqpttgf** [comment]
修过一次，然后阿里又修复了这个修复。
不想跟阿里斗智斗勇了。
