### ISSUE TITLE
有几个主题，换了之后进游客模式就没有登录后台的界面了，就再也找不到管理界面了

### ISSUE THREAD

**Issue by MRDOCTOROO** [qkqpttgf/OneManager-php#314]

**Comment by qkqpttgf** [comment]
?admin

这就是登录地址，除非你改了。

**Comment by tcg123** [comment]
@qkqpttgf  Hi, 加 '?admin' 登陆后又进到原来的界面了，并没进入管理界面

**Comment by qkqpttgf** [comment]
> @qkqpttgf Hi, 加 '?admin' 登陆后又进到原来的界面了，并没进入管理界面

截图，确定你登录了，
另外，是最新代码吗？

**Comment by tcg123** [comment]
![Uploading image.png…]()
输入密码登陆，提示login success，然后跳转如下页面
![Uploading image.png…]()

**Comment by MRDOCTOROO** [comment]
嗷嗷，不好意思哈，可以了。那个onedrive的主题登陆按钮没用，通过地址栏应该可以但还没试

发自我的iPhone

**Comment by qkqpttgf** [comment]
这个登录只是文字并不是按钮，
另外，有登录字样说明你没更新到最新代码，
