### ISSUE TITLE
能不能允许游客批量上传并查看？

### ISSUE THREAD

**Issue by shadowsocke** [qkqpttgf/OneManager-php#316]

**Comment by qkqpttgf** [comment]
本身就允许的啊

**Comment by shadowsocke** [comment]
游客可以吗 上传的按钮都没有 一开始以为是主题不支持 更换回原始主题也没有 设置里面也没有

**Comment by qkqpttgf** [comment]
> 游客可以吗 上传的按钮都没有 一开始以为是主题不支持 更换回原始主题也没有 设置里面也没有

你没设置……请去读我的readme，请以我demo为准。

**Comment by shadowsocke** [comment]
> > 游客可以吗 上传的按钮都没有 一开始以为是主题不支持 更换回原始主题也没有 设置里面也没有
> 
> 你没设置……请去读我的readme，请以我demo为准。

读了啊 你说的是游客路径吗 那个只上传不显示 并且只能上传一个吧

**Comment by qkqpttgf** [comment]
> > > 游客可以吗 上传的按钮都没有 一开始以为是主题不支持 更换回原始主题也没有 设置里面也没有
> > 
> > 
> > 你没设置……请去读我的readme，请以我demo为准。
> 
> 读了啊 你说的是游客路径吗 那个只上传不显示 并且只能上传一个吧 我直接迷糊了

游客就是游客，上传之后就自己知道上传了啥，不列表的，不给其它人看。
可以上传多个。

**Comment by shadowsocke** [comment]
> > > > 游客可以吗 上传的按钮都没有 一开始以为是主题不支持 更换回原始主题也没有 设置里面也没有
> > > 
> > > 
> > > 你没设置……请去读我的readme，请以我demo为准。
> > 
> > 
> > 读了啊 你说的是游客路径吗 那个只上传不显示 并且只能上传一个吧 我直接迷糊了
> 
> 游客就是游客，上传之后就自己知道上传了啥，不列表的，不给其它人看。
> 可以上传多个。

好吧 我希望可以显示

**Comment by shadowsocke** [comment]
> > > > 游客可以吗 上传的按钮都没有 一开始以为是主题不支持 更换回原始主题也没有 设置里面也没有
> > > 
> > > 
> > > 你没设置……请去读我的readme，请以我demo为准。
> > 
> > 
> > 读了啊 你说的是游客路径吗 那个只上传不显示 并且只能上传一个吧 我直接迷糊了
> 
> 游客就是游客，上传之后就自己知道上传了啥，不列表的，不给其它人看。
> 可以上传多个。

或者可以把很多盘合在一个页面显示吗

**Comment by qkqpttgf** [comment]
？？？？

**Comment by shadowsocke** [comment]
> ？？？？
就是几个空间放在同一标签下

**Comment by shadowsocke** [comment]
> ？？？？

大佬 游客上传后文件名是乱的 能不能改成原文件名

**Comment by qkqpttgf** [comment]
> > ？？？？
> 
> 大佬 游客上传后文件名是乱的 能不能改成原文件名

不是乱的，md5，不能。
游客就是游客，说过很多次了。

**Comment by YidaozhanYa** [comment]
> > ？？？？
> 
> 大佬 游客上传后文件名是乱的 能不能改成原文件名

可以自己fork一个仓库然后改代码。重命名成md5的地方在"disk/（网盘名字如onedrive）.php"和主题"themes/classic.html"中，查找filemd5相关然后修改就行
