### ISSUE TITLE
文件夹链接有误 打开变为下载其他文件

### ISSUE THREAD

**Issue by pipixia244** [qkqpttgf/OneManager-php#317]
例子：
网址 https://od.srpr.cc/new/%E5%BD%B1%E5%AE%85/season%201/ 具有以下文件夹：
![image](https://user-images.githubusercontent.com/56287117/117913709-6dee8c80-b314-11eb-8b4f-f863c45cc369.png)
当我点开5这个文件夹的时候，他不会打开这个文件夹，反而会给我下载下面的season.nfo文件
![image](https://user-images.githubusercontent.com/56287117/117913790-99717700-b314-11eb-96e1-3826354e5e9c.png)
但是实际上这个文件夹内确实有文件，并且由于这个文件夹链接有无，我无法进入那个文件夹的页面。
并且只有最后一个文件夹5有问题，其他的1，2，3，4都没有问题。

**Comment by qkqpttgf** [comment]
嗯，我上次自己这边也遇到了，但后来我弄没了，
请TG或QQ上联系我，我远程研究下

**Comment by pipixia244** [comment]
复现条件
最后一个文件夹(设他是这个列表的第x个文件夹)名称为数字x 并且下面存在其他文件的时候, 会下载下面的第一个文件.
如果将下面的文件删掉并重新上传, 错误消失.
例如: 
![image](https://user-images.githubusercontent.com/56287117/117968682-09095580-b359-11eb-87e0-e1c0bd4c74be.png)
最后一个文件夹是第六个文件夹, 命名为6, 则会下载下面的第一个文件.
或者:
![image](https://user-images.githubusercontent.com/56287117/117968761-20e0d980-b359-11eb-8997-5c6ce833d2f2.png)
当其他文件随便命名时,只要最后一个文件夹命名为总文件夹个数的数字(这里是5)就会下载下面的文件.

但是如果最后一个文件夹的数字不是文件夹总数, 则不会出现错误.
![image](https://user-images.githubusercontent.com/56287117/117968955-5ab1e000-b359-11eb-9a03-e0eb7198de85.png)
此处的"4"不会出现错误, 如果改成5则出现错误.

文件夹不是数字形式时, 不会出现错误. 如
![image](https://user-images.githubusercontent.com/56287117/117969408-f04d6f80-b359-11eb-8143-cf5217d37eb8.png)


并且所有的错误在把文件删掉重新上传后全部消失. 无法复现.
