### ISSUE TITLE
今天在设置里点了一键更新后，阿里云盘下载会有一个错误页面，下载不了

### ISSUE THREAD

**Issue by ttt789-ppo** [qkqpttgf/OneManager-php#318]
![Screenshot_2021-05-12-19-35-16-561_com android browser](https://user-images.githubusercontent.com/72877282/117986359-28739480-b2ff-11eb-988e-3a0be21c7fc3.jpg)

**Comment by mengtaixiao** [comment]
同样,我也是点了那个一键更新,然后Aliyun的盘里面的东西都看不到了,但目录结构还能看得到(阿里云盘传东西,结构会更新),而OneDrive盘就正常,和更新前一样能看能下载.

**Comment by qkqpttgf** [comment]
因为我去掉no-referrer了，现在加回去了，你再更新试试。
【其实没打算继续玩Aliyundrive了，斗智斗勇容易出事】
