### ISSUE TITLE
设置出错后如何回到管理界面

### ISSUE THREAD

**Issue by tcg123** [qkqpttgf/OneManager-php#319]
部署完设置后出现如下提示
Tenant does not have a SPO license.

请问怎么进入管理界面重新设置呢？

**Comment by qkqpttgf** [comment]
上面有个返回首页

**Comment by tcg123** [comment]
@qkqpttgf 点了返回首页还是在这个报错页面上

**Comment by qkqpttgf** [comment]
> @qkqpttgf 点了返回首页还是在这个报错页面上

那自己重新打开吧……我这边点了就会回首页。

**Comment by tcg123** [comment]
谢谢，不知道啥原因，把app删掉重建了一个正常，这个issue关了
