### ISSUE TITLE
No refresh_token

### ISSUE THREAD

**Issue by dlytang** [qkqpttgf/OneManager-php#322]
国际版office 365 e5 开发者账号
用自己申请的应用ID与机密或OneManager默认的都没有跳转到授权界面，直接返回`应该已写入`
`
Driver | Onedrive
0No refresh_token
`

**Comment by qkqpttgf** [comment]
可能你平台不太对，在哪装的，换一个看看。

**Comment by dlytang** [comment]
> 可能你平台不太对，在哪装的，换一个看看。

Heroku，新安装点更新程序还是不行，在无痕模式添加也没有跳转到登录授权界面，填不填自己的应用ID和机密都是这样。

**Comment by qkqpttgf** [comment]
那判断不出你问题了，能录个屏吗？

**Comment by dlytang** [comment]
用Onemanager默认的应用ID和机密以及用自己的ID和机密：[视频地址](https://pan.dlytang9.workers.dev/hmk/OnemanagerInHeroku.mp4?preview)
用自己的ID和机密并且授权API权限：[视频地址](https://pan.dlytang9.workers.dev/hmk/OnemanagerInHeroku2.mp4?preview)

**Comment by qkqpttgf** [comment]
你为什么不等他跳，就点返回首页？？？

**Comment by qkqpttgf** [comment]
2:19的时候跟4:30的时候，让你等3s，你直接就返回首页？？
你打断安装过程了啊！！！

**Comment by dlytang** [comment]
啊 这样啊，
