### ISSUE TITLE
glitch自定义域名的强制https无效

### ISSUE THREAD

**Issue by BA7JCM** [qkqpttgf/OneManager-php#325]
用glitch部署的，添加自定义域名默认是HTTP，在onemanager设置里开了强制https之后仍然能通过HTTP:// 访问，之前在腾讯云函数部署的时候直接在api网关那里开强制https就可以只能以https访问，http访问都不用等加载出页面就能跳https了，而在glitch部署的时候我在设置里开了强制https，却能直接用HTTP访问而不会跳到https，另外就是我添加了一个顶级域名和几个子域名到glitch，按照网上的说法加了全局http跳https的JavaScript之后子域名打开是会正常跳转，但顶级域名访问的话却会导致打不开，报错”返回了无效的响应“，删掉HTTP跳https的全局JavaScript之后就恢复了

**Comment by qkqpttgf** [comment]
这个设置是302跳，腾讯SCF那边如果只开了https不开http，那就不能http访问（就是只开了443没开80）。
glitch我没自定义域名，但它自带的子域名是可以http访问的，我设置强跳后，能正常跳到https上。

**Comment by BA7JCM** [comment]
> 这个设置是302跳，腾讯SCF那边如果只开了https不开http，那就不能http访问（就是只开了443没开80）。
> glitch我没自定义域名，但它自带的子域名是可以http访问的，我设置强跳后，能正常跳到https上。

现在glitch那边开强制https之后是还能http访问且不跳https，腾讯那边我是开了http+https，同时在添加自定义域名的时候还开了强制https，访问http的时候会直接重定向到https， 腾讯那边我80和443都开了，并且在添加自定义域名的地方打开了强制https开关

**Comment by BA7JCM** [comment]
> 这个设置是302跳，腾讯SCF那边如果只开了https不开http，那就不能http访问（就是只开了443没开80）。
> glitch我没自定义域名，但它自带的子域名是可以http访问的，我设置强跳后，能正常跳到https上。

另外有些浏览器在你访问过一个网站的https://之后会“帮你”强制https，并不会管网站是否开启了强制https，比如谷歌内核的edge，只要我访问过一次某个网站的https链接，当我再次试图访问那个网站的http链接时，它会帮我强行跳到https，但ie不会，所以不知道你说的有效是不是浏览器在帮忙，腾讯云函数那边我开强制https之后，我访问http链接时，我连网站内容都没看到就跳到https去加载了

**Comment by qkqpttgf** [comment]
经IE测试，onemanager.glitch.me 会跳https，请以demo为准

**Comment by BA7JCM** [comment]
> 经IE测试，onemanager.glitch.me 会跳https，请以demo为准

我刚刚去试了下，glitch给我的域名的确实也会跳，但现在的问题是我自己添加到glitch的域名不会跳https……麻烦作者试试自定义域名？毕竟……glitch给的默认域名实在是太长太难记……也许没几个人会用吧……

**Comment by BA7JCM** [comment]
大佬能解决下这个问题吗。。。。。。glitch给的域名能跳，但是设置的自定义域名就不行

**Comment by qkqpttgf** [comment]
我没自定义域名，不好试

**Comment by qkqpttgf** [comment]
刚刚去自定义域名了，怎么https？好像只能http。

**Comment by BA7JCM** [comment]
> 刚刚去自定义域名了，怎么https？好像只能http。

直接输入https协议头的域名就行，刚搞完可能要等一会，等它给你搞证书

**Comment by qkqpttgf** [comment]
好了，应该可以了，你更新下看看
【不知道VPS上会不会有其它问题】

**Comment by BA7JCM** [comment]
> 好了，应该可以了，你更新下看看
> 【不知道VPS上会不会有其它问题】

可以了，多谢大佬

**Comment by iuiurun** [comment]
> 

嗨 兄弟glitch自定义的域名好搞https吗？ 我绑定解析完 自定义域名，发现https无法访问

**Comment by BA7JCM** [comment]
> > 
> 
> 嗨 兄弟glitch自定义的域名好搞https吗？ 我绑定解析完 自定义域名，发现https无法访问

好像绑定域名之后等一会再访问https就行了

**Comment by iuiurun** [comment]
> > > 
> > 
> > 
> > 嗨 兄弟glitch自定义的域名好搞https吗？ 我绑定解析完 自定义域名，发现https无法访问
> 
> 好像绑定域名之后等一会再访问https就行了

好的，非常感谢。我已经做好了cname到glitch.edgeapp.net 等待两个小时，我再看看。

**Comment by BA7JCM** [comment]
> > > > 
> > > 
> > > 
> > > 嗨 兄弟glitch自定义的域名好搞https吗？ 我绑定解析完 自定义域名，发现https无法访问
> > 
> > 好像绑定域名之后等一会再访问https就行了
> 
> 好的，非常感谢。我已经做好了cname到glitch.edgeapp.net 等待两个小时，我再看看。

我记得我当初弄完之后等几分钟十几分钟就行了
