### ISSUE TITLE
研究了半天不知道这个怎么填，能教一下吗

### ISSUE THREAD

**Issue by wxydejoy** [qkqpttgf/OneManager-php#326]
![image](https://user-images.githubusercontent.com/81625961/118542011-fe015b80-b784-11eb-968d-8e27264914f8.png)

**Comment by wxydejoy** [comment]
picgo可以用吗

**Comment by qkqpttgf** [comment]
这啥？？
用不了，不能对接。

**Comment by wxydejoy** [comment]
这是picgo的自定义图床。。。。。。不支持就算了
