### ISSUE TITLE
阿里网盘挂在后视频无法播放，也不能下载

### ISSUE THREAD

**Issue by koukouxiaoyao** [qkqpttgf/OneManager-php#328]
阿里网盘挂在后视频无法播放，加载失败，
下载进入页面也是失败的，不能下载，提示下面代码
`This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>InvalidArgument</Code>
<Message>At least one of AdditionalHeaders is not in request headers.</Message>
<RequestId>60A4A828B8F8773833498E92</RequestId>
<HostId>bj29.cn-beijing.data.alicloudccp.com</HostId>
</Error>` 

有没有好的解决办法  ，列表可以列出来，但是文件不能预览，也不能下载（所有类型文件都不能下载）

**Comment by qkqpttgf** [comment]
不可说，我不提供解决方案。
（你可以去酷安找相关操作）

**Comment by Anemone0** [comment]
> 不可说，我不提供解决方案。
> （你可以去酷安找相关操作）

求大佬指条明路

**Comment by YidaozhanYa** [comment]
> > 不可说，我不提供解决方案。
> > （你可以去酷安找相关操作）
> 
> 求大佬指条明路

我来提供一个解决方法吧，https://blog.yidaozhan.gq/2021/04/10/onemgr-fix-aliyundrive-token/
