### ISSUE TITLE
Must visit from designated host

### ISSUE THREAD

**Issue by love2wind** [qkqpttgf/OneManager-php#330]
今天更新了以后，所有盘都进不去了，只有首页和设置能进，其他都显示Must visit from designated host

**Comment by love2wind** [comment]
![image](https://user-images.githubusercontent.com/11996852/119374422-242a7c80-bcec-11eb-8b0b-fd80857fa083.png)

**Comment by qkqpttgf** [comment]
你怎么才更新，弄好久了这个。
这个应该是你代理了一下吧？你去设置里reffer填上你中转那个地方向程序所在地请求时使用的域名。应该就好了。

**Comment by love2wind** [comment]
> 你怎么才更新，弄好久了这个。
> 这个应该是你代理了一下吧？你去设置里reffer填上你中转那个地方向程序所在地请求时使用的域名。应该就好了。

感谢，弄好了。是的，我在CF里中转了一下。

**Comment by cy-j** [comment]
> 你怎么才更新，弄好久了这个。 这个应该是你代理了一下吧？你去设置里reffer填上你中转那个地方向程序所在地请求时使用的域名。应该就好了。

请问，在微信里打开也会这样，要填上什么域名呢？

**Comment by qkqpttgf** [comment]
> > 你怎么才更新，弄好久了这个。 这个应该是你代理了一下吧？你去设置里reffer填上你中转那个地方向程序所在地请求时使用的域名。应该就好了。
> 
> 请问，在微信里打开也会这样，要填上什么域名呢？

可能是某“open.qq”吧，具体的不记得了
