### ISSUE TITLE
子目录设置

### ISSUE THREAD

**Issue by EvenCu** [qkqpttgf/OneManager-php#332]
domain.com/A --> /onedrive/A
domain.com/B --> /onedrive/B

请问可以这样设置吗 如果可以，如何设置

**Comment by qkqpttgf** [comment]
这不用设置啊

**Comment by EvenCu** [comment]
这回复，更懵了

需要的效果
qq.com/aaa访问的是/od/aaa/
qq.com/bbb访问的是/od/bbb/

**Comment by qkqpttgf** [comment]
对啊，现在不就是这样？

**Comment by qkqpttgf** [comment]
???
