### ISSUE TITLE
新增

### ISSUE THREAD

**Issue by xiaocao666tzh** [qkqpttgf/OneManager-php#333]
能否新增对反向代理onedrive的支持，设置onedrive的反向代理域名，像这样
https://zhuanlan.zhihu.com/p/262285628

**Comment by qkqpttgf** [comment]
你是要，
1，文件下载流量从程序走，
还是要，
2，填一个域名，文件下载从那个域名走？

**Comment by xiaocao666tzh** [comment]
其实两种都有需要，求大大能不能两种都做

**Comment by qkqpttgf** [comment]
第1种不做，第2种早就做了。
