### ISSUE TITLE
阿里云盘添加token失败

### ISSUE THREAD

**Issue by akyomi** [qkqpttgf/OneManager-php#334]
{"code":"InvalidParameter.RefreshToken","message":"The input parameter refresh_token is not valid. Please refer to document."}

**Comment by qkqpttgf** [comment]
你的token可能拿错了，请百度一下，或酷安上找找方法。

**Comment by zjboy1984** [comment]
能挂载上阿里云盘，但是不能直接读取内容，比如不能在线播放，看图这些

**Comment by qkqpttgf** [comment]
> 能挂载上阿里云盘，但是不能直接读取内容，比如不能在线播放，看图这些

我不想从我这传播方法
