### ISSUE TITLE
能否设置隐藏某些目录？

### ISSUE THREAD

**Issue by sunnynctu** [qkqpttgf/OneManager-php#338]
首先感谢大佬辛苦开发程序。如题，例如根目录下有10个文件夹，只想展示其中7个，目前虽然可以通过加密来阻止访问，但是另外3个文件夹的名字仍然被暴露引人遐想，说不定就有人暴力破解，能不能干脆隐藏这些目录呢？

**Comment by roadwide** [comment]
把展示的7个放到同一个文件夹，设置public_path

**Comment by sunnynctu** [comment]
> public_path

黑白名单各有各的好处和用途，目前的public_path相当于白名单，能不能再加一个隐藏目录（secret_path）的黑名单呢？

**Comment by qkqpttgf** [comment]
不想做，你可以给目录改名，以 . 开头的默认不显示

**Comment by sunnynctu** [comment]
> 不想做，你可以给目录改名，以 . 开头的默认不显示

好的，谢谢大佬，这也差不多实现了黑名单不显示的功能。
