### ISSUE TITLE
部分视频播放没有声音

### ISSUE THREAD

**Issue by sunnynctu** [qkqpttgf/OneManager-php#345]
Onedrive里面有一套央视版四大名著全集，mkv格式，chrome和360极速播放只有画面没有声音，edge播放正常，下载后用potplayer本地播放正常，复制链接用potplayer在线播放正常。有没有人遇到过类似情况？不知道是不是Dplayer的问题？

**Comment by qkqpttgf** [comment]
其它issue有人说过，很多播放不了。

**Comment by zzjjbb** [comment]
> 
> 
> Onedrive里面有一套央视版四大名著全集，mkv格式，chrome和360极速播放只有画面没有声音，edge播放正常，下载后用potplayer本地播放正常，复制链接用potplayer在线播放正常。有没有人遇到过类似情况？不知道是不是Dplayer的问题？

你需要看看你的mkv里面封装的是什么编码，很可能是浏览器不兼容。这个网站可以查看编码支持（比如H.265/HEVC）https://caniuse.com/?search=hevc
