### ISSUE TITLE
谷歌网盘挂载后，无法播放mkv，显示视频加载失败，挂梯子也不行

### ISSUE THREAD

**Issue by zjboy1984** [qkqpttgf/OneManager-php#346]
谷歌网盘挂载后，无法播放mkv，显示视频加载失败，挂梯子也不行

**Comment by zzjjbb** [comment]
你需要看看你的mkv里面封装的是什么编码，很可能是浏览器不兼容，在这里可以查看编码支持https://caniuse.com/?search=hevc
另外这个问题你应该去问[DPlayer](https://github.com/DIYgod/DPlayer)

**Comment by cfandora** [comment]
我几天也遇到了这个问题，不管mkv或者mp4都不能播放，封装的编码是H264和AAC。
貌似是跨域问题？下面是chrome的console截图，期待解决

![Image text](https://img.pterclub.com/images/2021/12/14/QQ20211214210836.png)
