### ISSUE TITLE
请教一个关于theme/classic.html的问题

### ISSUE THREAD

**Issue by zzjjbb** [qkqpttgf/OneManager-php#347]
这个[`$operatediv`](https://github.com/qkqpttgf/OneManager-php/blob/86ba05b5be361602d842c9e5143f9da9bbe20b91/theme/classic.html#L1463)在这里是希望实现什么逻辑呢？在最终的html上好像并没有name为`operatediv`的东西，这里的`document.getElementsByName`是否应该是`document.getElementsByClassName`？

**Comment by qkqpttgf** [comment]
咦，好像是哦，应该是class唉
不过，它为什么能正常运行 OvO !?
【当它能运行时就不要改了】
