### ISSUE TITLE
svg位置

### ISSUE THREAD

**Issue by liuluping0106** [qkqpttgf/OneManager-php#349]
出现了手机端能够正常加载，电脑端无法加载svg图标的问题，用的是VPS。

**Comment by liuluping0106** [comment]
GET https://onemanager.glitch.me/E5/hsvg/md-log-in.svg 404
运行你的demo也有同样的问题

**Comment by qkqpttgf** [comment]
> GET https://onemanager.glitch.me/E5/hsvg/md-log-in.svg 404
> 运行你的demo也有同样的问题

我的e5里面就没这个文件，你为什么会来GET这个文件
