### ISSUE TITLE
大文件夹报错

### ISSUE THREAD

**Issue by panxiaoguang** [qkqpttgf/OneManager-php#35]
我在onedrive里面上传了一个2G左右的文件夹，然后在SCF搭建的浏览端无法打开，每次打开该文件夹都报以下错误
```
{"errno":403,"error":"Invalid scf response format. please check your scf response format."}
```

**Comment by qkqpttgf** [comment]
其它文件夹呢？
是目录大小大，还是目录里面文件多？
我SCF的demo里面，Photos这个文件夹，能正常打开，它18G了，里面某个文件夹3000个文件。

**Comment by panxiaoguang** [comment]
> 其它文件夹呢？
> 是目录大小大，还是目录里面文件多？
> 我SCF的demo里面，Photos这个文件夹，能正常打开，它18G了，里面某个文件夹3000个文件。

对，是文件很多

**Comment by qkqpttgf** [comment]
我都说了，我的能正常打开
你能不能确定出错在哪里？
