### ISSUE TITLE
无法解析带[]的文件名

### ISSUE THREAD

**Issue by Guochengjie** [qkqpttgf/OneManager-php#351]
环境：阿里云函数计算
储存后端：SharePointCN
无法解析的文件名举例：
[图灵程序设计丛书].Flask Web开发‛：基于Python的Web应用开发实战.pdf
[图灵程序设计丛书].Ext JS实战.第2版.pdf
[异步图书].Python机器学习实践指南.pdf

基本确定是因为[]的原因

**Comment by Guochengjie** [comment]
另：文件夹名字如果包含&，路径显示也会炸

**Comment by qkqpttgf** [comment]
> 另：文件夹名字如果包含&，路径显示也会炸

带&的话，我上次修过，我DEMO根目录就有个jpg带&。
你用的哪个主题？

**Comment by Guochengjie** [comment]
> > 另：文件夹名字如果包含&，路径显示也会炸
> 
> 带&的话，我上次修过，我DEMO根目录就有个jpg带&。
> 你用的哪个主题？

用的renexmoe这个主题，感谢！

**Comment by zzjjbb** [comment]
还有一些其他问题，比如
- 文件夹名为`folder%20test`，文件夹本身可以打开，但是里面的文件会路径错误
- 例如文件/文件夹名字里带有`&quot;`，会被反转义，然后报这个错误：
> <h1>itemNotFound</h1>
> <a href="">返回首页</a>
> <p></p><div style="margin:8px;"><pre>The resource could not be found.</pre></div><a href="">返回</a>

**Comment by qkqpttgf** [comment]
这些奇怪的字符就不修了吧……

**Comment by qkqpttgf** [comment]
> 
> [图灵程序设计丛书].Ext JS实战.第2版.pdf
> 

我在demo创建了一个txt，我看起来没问题？

**Comment by qkqpttgf** [comment]
根据其它人的issue，[]文件名的问题，只在阿里FC上出现，刚刚修了下，你更新看看修好没。
