### ISSUE TITLE
google drive 上传报错

### ISSUE THREAD

**Issue by zzzqu** [qkqpttgf/OneManager-php#356]
![image](https://user-images.githubusercontent.com/77374843/122738011-2fa1a100-d2b4-11eb-92f5-9a61a7d31261.png)
怎么解决呢

**Comment by qkqpttgf** [comment]
。。。。。。请翻译一下这句………

**Comment by zzzqu** [comment]
什么token？在哪里添加？

**Comment by qkqpttgf** [comment]
................
 google上传时不能不带token，但不可能把token发送到浏览器，会出事，所以浏览器这边无法上传，只能在服务器上上传。
.................

**Comment by qkqpttgf** [comment]
都让你stop了，你还想前进……
