### ISSUE TITLE
报了一个很奇怪的错误。不像是程序错误，像是OD的错误。

### ISSUE THREAD

**Issue by SKIYET** [qkqpttgf/OneManager-php#358]
500{ "error": { "code": "generalException", "message": "General exception while processing"
返回首页发现OD成功添加，可以成功上传文件，但sharepoint不能成功挂载，后台网盘切换会报同样的错误。
用你的API和我自己的API都报这个错。
Microsoft Graph的files权限已经全部给出，还有sharepoint site 的readwrite权限。能否请开发者帮我看一下问题出在哪里呢?

**Comment by willy880305** [comment]
一样遇到这个问题

**Comment by qkqpttgf** [comment]
没遇到过
