### ISSUE TITLE
关于世纪互联版申请应用ID与机密的问题

### ISSUE THREAD

**Issue by wekingchen** [qkqpttgf/OneManager-php#36]
请问想使用自己申请的应用ID与机密，在世纪互联版申请应用注册时，重定向 URI的地址应该怎样填写？

**Comment by qkqpttgf** [comment]
（首先，世纪互联不要直接点那个链接，那个是国际版用的）
在azure.cn里面，回调地址填： https://scfonedrive.github.io

**Comment by wekingchen** [comment]
好的，我去试试，谢谢！

**Comment by qkqpttgf** [comment]
最近一小时内，这个https://scfonedrive.github.io/ 各种访问不了

**Comment by wekingchen** [comment]
我已经设置好了
