### ISSUE TITLE
请问php7.4不能跑吗？

### ISSUE THREAD

**Issue by fansuregrin** [qkqpttgf/OneManager-php#361]
请问php7.4不能跑吗？我php从7.3升级到7.4, php-fpm也是7.3换成了7.4，nginx的配置没动，之前7.3的时候能跑，7.4就访问不了了。我也不知道哪里出了问题，所以问下。

**Comment by qkqpttgf** [comment]
从centos7自带的5.4.16，到heroku的php8，都可以跑。
需要 curl 模块。
