### ISSUE TITLE
GoogleDrive加密文件夹

### ISSUE THREAD

**Issue by alvincheang** [qkqpttgf/OneManager-php#362]
打扰了，因为搜了很久没搜到相关解决方案。
我试了挂od 加密文件夹正常 输入密码然后可进入
gd挂正常了 但就是卡在加密文件夹这里 一样方式加密 可是输入密码 就是进不入文件夹 一直要我输入密码。但明明已经输入了对的密码。这个是哪里出问题了呀？

**Comment by qkqpttgf** [comment]
呃，我这个gd方案不太对劲，有的人下载不了。
但一直没改，要不gd先用用其它程序

**Comment by alvincheang** [comment]
哦好明白。那onemanager暂时只用od吧 gd的我找找其他的，谢谢你:)
