### ISSUE TITLE
是否可以增加降权功能

### ISSUE THREAD

**Issue by SKIYET** [qkqpttgf/OneManager-php#363]
开发者你好：

在使用面板时，发现倘若给某个用户提为Global管理员，那么就无法对这个用户进行禁止登录，删除操作。是否可以增加降用户为普通用户的功能，官方是有API的说明https://docs.microsoft.com/en-us/graph/api/directoryrole-delete-member?view=graph-rest-1.0&tabs=http

仅提出建议哈。

**Comment by SKIYET** [comment]
写错项目了

**Comment by qkqpttgf** [comment]
不是有取消管理按钮？？这个不能做自动，万一点错了呢。
