### ISSUE TITLE
添加盘，登陆的时候出现的错误。

### ISSUE THREAD

**Issue by Max-tgz** [qkqpttgf/OneManager-php#364]
用的腾讯SCF!在输入密码，，登陆后就不行了
[$PQBC%NWF$W9GR7X7KOF8RR](https://user-images.githubusercontent.com/80143806/123519971-f072b600-d6e0-11eb-993d-dd66c6ea6983.png)

**Comment by qkqpttgf** [comment]
这个跟我无关，
在操作之前，有红字你都不看一眼的？？
![image](https://user-images.githubusercontent.com/45693631/123534129-6dd41000-d74d-11eb-8880-37df2a5ee3d0.png)

那我应该要弹个窗你们才会看吗？？

**Comment by Max-tgz** [comment]
抱歉，我拉腾讯云别人的模板没有红字

**Comment by qkqpttgf** [comment]
> 抱歉，我拉腾讯云别人的模板没有红字

SCF上模板作者就是我，但，它太久远了，最好还是用新代码。

**Comment by Max-tgz** [comment]
嗯，抱歉打扰到你了
