### ISSUE TITLE
希望支持文本文件的直链显示

### ISSUE THREAD

**Issue by zxjzxj0010** [qkqpttgf/OneManager-php#365]
希望支持文本文件（txt，md，等等）的直链显示

就像这样https://raw.githubusercontent.com/qkqpttgf/OneManager-php/master/readme.md

谢谢大佬！

**Comment by qkqpttgf** [comment]
做不到呢，
要这样显示的话，content type要是text/plain，
但我们只是302跳去微软，微软只会是下载，
除非在程序中转一下，但我们不做中转。
