### ISSUE TITLE
使用腾讯云函数 无法更新

### ISSUE THREAD

**Issue by DoyoDia** [qkqpttgf/OneManager-php#367]
![image](https://user-images.githubusercontent.com/79502694/125152578-eb514480-e17f-11eb-9b40-c9c1e58bd07b.png)
更新失败，重新创建后仍无法更新

**Comment by DoyoDia** [comment]
此时访问出现504错误
![image](https://user-images.githubusercontent.com/79502694/125152610-34a19400-e180-11eb-9213-52196dc81c3d.png)

**Comment by DoyoDia** [comment]
#305 把目录装进src文件夹后重新打包至SCF就能更新了

**Comment by DoyoDia** [comment]
还是希望能修一下这个bug

**Comment by qkqpttgf** [comment]
> 还是希望能修一下这个bug

经测试，不用src啊
另外更新的代码已经修改好了，下载最新代码就可以了，
SCF的模板里我也修改了，但腾讯还没更新，估计要等一段时间。
