### ISSUE TITLE
这种情况是我没有添加环境变量吗

### ISSUE THREAD

**Issue by blankmiss** [qkqpttgf/OneManager-php#37]
<img src="http://picture.blankmiss.club/images/2020/03/26/PJGM647V67X2RWVR.png" alt="PJGM647V67X2RWVR.png" border="0" />
同时我也不知道环境变量怎么添加   ap-hongkong
期待您的回答

**Comment by qkqpttgf** [comment]
是的，去环境变量添加就好了

**Comment by blankmiss** [comment]
十分感谢
