### ISSUE TITLE
一个错误

### ISSUE THREAD

**Issue by xxx854** [qkqpttgf/OneManager-php#370]
InvalidParameterValue.EnvironmentExceededLimit
环境变量大小超限，请保持在 4KB 以内。

function_name:one-drive
Region:ap-hongkong
namespace:default

**Comment by qkqpttgf** [comment]
这不是写了吗……

**Comment by xxx854** [comment]
是写了，可是我只添加了2块盘啊

**Comment by xxx854** [comment]
怎么就不行了呢

**Comment by qkqpttgf** [comment]
可能你添加了其它设置，
你没看到是说环境变量大小吗？你就算1个盘，加了很多其它配置，环境变量不是一样会大！

**Comment by xxx854** [comment]
我设置了一些平台变量

**Comment by xxx854** [comment]
这个也会导致它变大的吗

**Comment by xxx854** [comment]
得，现在是无法访问这个了https://scfonedrive.github.io/

**Comment by qkqpttgf** [comment]
> 得，现在是无法访问这个了https://scfonedrive.github.io/

TMD我要骂人了，标红的字不看吗？？？
![https://herooneindex.herokuapp.com/E5/GuestUpload/a44128706592c398a9eec990c974ee23.jpg](https://herooneindex.herokuapp.com/E5/GuestUpload/a44128706592c398a9eec990c974ee23.jpg)

**Comment by xxx854** [comment]
呃，不好意思，这个我知道怎么解决，主要是觉得问题太多了，吐槽一下，见谅。

**Comment by xxx854** [comment]
实在不好意思

**Comment by xxx854** [comment]
我想设置一个游客上传目录，在环境变量中写了这个 guestup_path=one/game/ 
请教一下为何无法出现上传按钮

**Comment by qkqpttgf** [comment]
> 我想设置一个游客上传目录，在环境变量中写了这个 guestup_path=one/game/
> 请教一下为何无法出现上传按钮

无图言X，
猜1：你就没这个目录
猜2：你用的主题没有上传功能

**Comment by xxx854** [comment]
![屏幕截图 2021-07-15 092843](https://user-images.githubusercontent.com/77531464/125713893-98e2b8a4-3024-4bbd-ae58-ec5e71e60bf4.png)
![image](https://user-images.githubusercontent.com/77531464/125713998-57d9a48f-2c15-418b-8373-abf96e9852b8.png)

**Comment by xxx854** [comment]
就是这样的

**Comment by xxx854** [comment]
猜想1

**Comment by xxx854** [comment]
猜想2

**Comment by xxx854** [comment]
![image](https://user-images.githubusercontent.com/77531464/125714147-60001f6a-93b9-434e-aea7-602a50d736e1.png)
链接https://xiabor.com/ded5.html#%E5%87%86%E5%A4%87%E5%B7%A5%E4%BD%9C

**Comment by qkqpttgf** [comment]
这主题就不能上传

**Comment by xxx854** [comment]
我弄好了，谢谢帮助




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年7月16日(星期五) 上午9:41
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [qkqpttgf/OneManager-php] 一个错误 (#370)





 
这主题就不能上传

**Comment by xxx854** [comment]
[新建文本文档 (2).txt](https://github.com/qkqpttgf/OneManager-php/files/6831087/2.txt)
帮忙看下，我就添加了两块盘，属性就必要的那几个，怎么就超过4kb了
