### ISSUE TITLE
挂盘问题

### ISSUE THREAD

**Issue by zhl111** [qkqpttgf/OneManager-php#371]
![image](https://user-images.githubusercontent.com/29135984/125492628-1b7bdccc-38ee-4ca0-9266-a9ffad2fa139.png)
挂盘挂不上。选单用户出现：Error! 有误！No code from MS! 微软code为空！
选多个组织的则如图，不能个人账户登陆，学校的需管理员批准，
在这卡住了

**Comment by qkqpttgf** [comment]
前后语言乱七八糟，我猜到你想说啥，
关键在于学校账号没有管理员，不能用
