### ISSUE TITLE
优化上传文件命名

### ISSUE THREAD

**Issue by 201853910** [qkqpttgf/OneManager-php#375]
之前有人想通过网站上传分发文件，说文件名最好不要更改，不然到时候下载都不知道什么文件是什么文件了。  
不过这个自动改文件名也有很多好处，也建议保留。  

建议：每次上传时自动新建一个文件夹，文件上传至该文件夹内。并且上传时可选择自动修改文件名或者保留文件名。  
当一次性上传多个文件，最好只建立一个文件夹，不然管理的时候就会非常混乱。  

例：我上传一个a.jpg，选择不改名时路径文件为xxx/a.jpg；选择自动改名时为xxx/akjfjkjgadf.jpg  
这样既兼得了识别文件，又兼得了文件隐私保护，可以根据上传者的需要自行选择上传方式。  

例2：我在页面上一次性上传了多个文件，1.jpg、2.jpg  
这种情况最好只建立一个文件夹，只要用户没刷新网页，就不重新建立文件夹，这个功能的话比较方便管理，如果文件夹里面都是违规文件啥的，可以直接删文件夹了事（不知道您用过YukiDrive没，他的上传建立文件夹是每个文件创建一个，检查文件的时候脑壳痛）

**Comment by qkqpttgf** [comment]
不想做，说过很多遍了，游客就是游客，我不想做多人帐号上传，更不想做作业上传点，只是用来临时上传用的。

游客上传只上传到这个目录，不新建目录。
雪家的没用过，但oneindex我用过，是按日期来创建的，我也不喜欢创建这么多目录，所以我不是【创建一个上传目录】，我是【指定一个目录为游客上传目录】
