### ISSUE TITLE
No refresh_token

### ISSUE THREAD

**Issue by W4J1e** [qkqpttgf/OneManager-php#378]
您好，我是部署在支持php环境的vps上面的， 此前用oneindex在绑定账号之后会提示程序安装失败，所以用了OneManager-php。
我也是自己注册的开发者E5，和已经关闭的issue里面有一位是一样的情况，但是我没有自己点返回首页，是等待它自动跳转的，请问可能是什么问题，谢谢。
![1](https://user-images.githubusercontent.com/74824162/126104674-21102fa1-ee45-49f5-95b3-38b448574ccc.jpg)

**Comment by qkqpttgf** [comment]
就没绑上，
请一步一截图，打个码

**Comment by W4J1e** [comment]
首先是git clone了仓库，除了.git文件夹都上传到了虚拟主机。在截图四那一步也尝试了使用onemanager默认的，授权后就是图13的界面。
![访问该路径](https://user-images.githubusercontent.com/74824162/126190634-b3980569-8bb2-442e-b7f8-5fe7759ca969.jpg)
![2](https://user-images.githubusercontent.com/74824162/126190657-eba55703-7afb-4f67-a0e0-6a34bce80e82.jpg)
![3](https://user-images.githubusercontent.com/74824162/126190663-d17144d5-c740-47ba-9fc6-a65f183af25f.jpg)
![4](https://user-images.githubusercontent.com/74824162/126190666-f99ef09b-7f6e-4a1a-abdd-8c88ef57e436.jpg)
![5](https://user-images.githubusercontent.com/74824162/126190675-8af64ab0-cf75-41b5-a1ff-96d9aa3b38c4.jpg)
![6](https://user-images.githubusercontent.com/74824162/126190686-d4671feb-4e02-44c4-84a6-4d2cc0287549.jpg)
![7](https://user-images.githubusercontent.com/74824162/126190692-53bc6eac-bcdf-4422-a44d-ffcf94a1c6e8.jpg)
![8](https://user-images.githubusercontent.com/74824162/126190699-ece2d31a-3512-4631-8eec-ab24aea3975b.jpg)
![9](https://user-images.githubusercontent.com/74824162/126190704-de2cba42-34d2-43f0-8ad1-e41b3b29721b.jpg)
![10](https://user-images.githubusercontent.com/74824162/126190713-d0c02dc3-6adf-430f-89f7-91448e98c4ff.jpg)
![11](https://user-images.githubusercontent.com/74824162/126190725-45312bbe-bc6b-4099-b6e3-93df20308688.jpg)
![12](https://user-images.githubusercontent.com/74824162/126190731-e4b83b34-7571-4bf9-bce6-ec80d59d9a6a.jpg)
![13](https://user-images.githubusercontent.com/74824162/126190744-73c5d0e0-825d-4d37-a513-c0edb766f8f2.jpg)
![首页](https://user-images.githubusercontent.com/74824162/126191410-803bff5e-e44b-4b62-9b44-a08862c17dd4.jpg)

**Comment by qkqpttgf** [comment]
0，是连不上目标url，可能程序那一下连不上微软了。

上传出现又一层首页，我觉得可能是代码哪里不对了，你重新下最新代码看看（不要release！）

**Comment by meng-luo** [comment]
我昨天晚上尝试的时候也遇到了一模一样的错误，我是php虚拟主机，同样是报错0，null，我也是微软e5账号

**Comment by W4J1e** [comment]
> 我昨天晚上尝试的时候也遇到了一模一样的错误，我是php虚拟主机，同样是报错0，null，我也是微软e5账号

感觉是部分虚拟主机的问题。此前我用oneindex的时候也是不行，但是在服务器上部署就没问题。

**Comment by sunnynctu** [comment]
> 我昨天晚上尝试的时候也遇到了一模一样的错误，我是php虚拟主机，同样是报错0，null，我也是微软e5账号

我也遇到了同样的错误，请问你解决了吗？

**Comment by nodesire7** [comment]
google drive同样的问题

**Comment by Xunflash** [comment]
> > 我昨天晚上尝试的时候也遇到了一模一样的错误，我是php虚拟主机，同样是报错0，null，我也是微软e5账号
> 
> 我也遇到了同样的错误，请问你解决了吗？

我也是一样的问题，请问解决了吗

**Comment by Xunflash** [comment]
> 0，是连不上目标url，可能程序那一下连不上微软了。
> 
> 上传出现又一层首页，我觉得可能是代码哪里不对了，你重新下最新代码看看（不要release！）

我使用默认，自己申请都不行，重新clone代码安装程序依然行不通，安装就出现0 null 到底是出了什么问题啊

**Comment by qkqpttgf** [comment]
> > 0，是连不上目标url，可能程序那一下连不上微软了。
> > 上传出现又一层首页，我觉得可能是代码哪里不对了，你重新下最新代码看看（不要release！）
> 
> 我使用默认，自己申请都不行，重新clone代码安装程序依然行不通，安装就出现0 null 到底是出了什么问题啊

不是说了，0就是程序连不上目标盘。

你------程序----X----微软

**Comment by meng-luo** [comment]
> > > 我昨天晚上尝试的时候也遇到了一模一样的错误，我是php虚拟主机，同样是报错0，null，我也是微软e5账号
> > 
> > 
> > 我也遇到了同样的错误，请问你解决了吗？
> 
> 我也是一样的问题，请问解决了吗

可以尝试换个虚拟主机
