### ISSUE TITLE
在 glitch 上部署成功后一直跳这个弹窗

### ISSUE THREAD

**Issue by gd1214b** [qkqpttgf/OneManager-php#379]
![image](https://user-images.githubusercontent.com/37929478/126170948-ce41e118-c9f5-4b8a-899b-756428f7a08f.png)

**Comment by gd1214b** [comment]
点了确定后又会马上弹出来

**Comment by qkqpttgf** [comment]
你去后台设置一下时区啊

**Comment by gd1214b** [comment]
> 你去后台设置一下时区啊

关键是这个弹窗关掉后又会马上弹出来, 根本点不到登录按钮.

**Comment by qkqpttgf** [comment]
TG上PM我，网址跟密码

**Comment by gd1214b** [comment]
> TG上PM我，网址跟密码

其实在Heroku上部署就没有这个问题。

**Comment by qkqpttgf** [comment]
不，我在glitch上也没这问题！

**Comment by gd1214b** [comment]
> 不，我在glitch上也没这问题！

这就奇怪了

**Comment by gd1214b** [comment]
close
