### ISSUE TITLE
希望能增加评论插件模块

### ISSUE THREAD

**Issue by ZKsolar** [qkqpttgf/OneManager-php#38]
希望可以增加valine评论插件，自己改了代码后作者大大一更新就要重装然后改代码（主要是自己菜，一更新就改不来了），希望可以加入“是否启用valine评论插件”的选项，插件的appid和secret用环境变量在/admin处管理，或者开发一个插件接入模块，像加入新网盘一样，然后以环境变量的形式在管理台下进行对插件进行自定义。

**Comment by qkqpttgf** [comment]
试试test分支
可以创建foot.omf文件，里面放上valine所有代码。
