### ISSUE TITLE
貌似aili更新了token

### ISSUE THREAD

**Issue by ghost** [qkqpttgf/OneManager-php#380]
，refreshToken不固定了，刚安装完，部分文件夹进不去，获取不到数据

**Comment by ayasa520** [comment]
现在好像是完全失效了

**Comment by BloveDawn** [comment]
好像确实是，看其它repo的refreshToken搞的都变成了自动更新

**Comment by qkqpttgf** [comment]
> 好像确实是，看其它repo的refreshToken搞的都变成了自动更新

????
我这项目一直是自动更新token……

**Comment by BloveDawn** [comment]
> > 好像确实是，看其它repo的refreshToken搞的都变成了自动更新
> 
> ????
> 我这项目一直是自动更新token……

啊呃抱歉抱歉，又发现好像缓存刷新有点问题，就是添加过的标签和名称如果删除重复添加（首次添加类型为Aliyun但出错）的情况下，会直接添加成功，填写refreshtoken页面被跳过，回到主页面直接返回空页面（这是第二个盘，阿里云函数计算）
