### ISSUE TITLE
你好请问一下缓存处理怎么处理，程序自动处理吗？

### ISSUE THREAD

**Issue by hipteromyini** [qkqpttgf/OneManager-php#381]

**Comment by qkqpttgf** [comment]
本项目的缓存是 真 缓存，过半小时它就死掉了，这也是serverless的无状态特性决定的。
不像其它项目，把目录结构都保存到本地的数据库或文件，相当于写死了。
他们不执行 刷新缓存 这个操作的话，几个月都不会改变。
而本项目，半小时后缓存就死掉了，程序会去找微软问。

**Comment by km-file** [comment]
> 本项目的缓存是 真 缓存，过半小时它就死掉了，这也是serverless的无状态特性决定的。
> 不像其它项目，把目录结构都保存到本地的数据库或文件，相当于写死了。
> 他们不执行 刷新缓存 这个操作的话，几个月都不会改变。
> 而本项目，半小时后缓存就死掉了，程序会去找微软问。

所以这个项目是每半个小时调用一次接口获取数据吗？

**Comment by qkqpttgf** [comment]
>
> 所以这个项目是每半个小时调用一次接口获取数据吗？

他们是在刷新的时候，一层一层的，把所有的目录结构全保存下来，
这个程序只是你请求哪个目录，就只向微软请求这个目录的信息。
并不是固定半小时。
