### ISSUE TITLE
百度的CFC貌似只能弄三个啊

### ISSUE THREAD

**Issue by ilhsyysyk** [qkqpttgf/OneManager-php#384]

**Comment by ilhsyysyk** [comment]
第四个直接error

**Comment by qkqpttgf** [comment]
经尝试，添加第4个是会error，具体原因我有空看看，不过我猜应该跟SCF、FG类似，限制了环境变量大小了

**Comment by qkqpttgf** [comment]
"Code": "InvalidParameterValueException",
  "Cause": "Environment Size is Illegal",
   "Message": "One of the parameters in the request is invalid",
   "Status": 400,

没错，环境变量大小的问题，具体限制多少没写，估计是4k。
