### ISSUE TITLE
文本编辑页面 svg 404

### ISSUE THREAD

**Issue by 1-1-2** [qkqpttgf/OneManager-php#390]
![image](https://user-images.githubusercontent.com/50569812/127792584-3dd25b30-612b-4996-a633-2483fa1751e5.png)

路径为 https://example.domain.com/hsvg/md-download.svg

**Comment by qkqpttgf** [comment]
哪个主题……似乎不是默认主题~~~~~

**Comment by 1-1-2** [comment]
> 哪个主题……似乎不是默认主题~~~~~

ncnyn_grey，原来是与主题相关的？

**Comment by qkqpttgf** [comment]
> > 哪个主题……似乎不是默认主题~~~~~
> 
> ncnyn_grey，原来是与主题相关的？

以默认主题为准，其它主题都有不同程度的滞后（甚至不再更新）
