### ISSUE TITLE
更新程序之后OneDrive出现400问题，不知道是我账号问题还是怎么的，难道是我启用双重验证引起的吗？请问我该如何解决问题？

### ISSUE THREAD

**Issue by guangsudalao** [qkqpttgf/OneManager-php#394]
400
{ "error": "invalid_grant", "error_description": "AADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access '00000003-0000-0000-c000-000000000000'.\r\nTrace ID: ***********\r\nCorrelation ID: ***********\r\nTimestamp: 2021-08-05 03:17:51Z", "error_codes": [ 50076 ], "timestamp": "2021-08-05 03:17:51Z", "trace_id": "************", "correlation_id": "************", "error_uri": "https:\/\/login.microsoftonline.com\/error?code=50076", "suberror": "basic_action" }\nfailed to get [Onedrive2] access_token

**Comment by qkqpttgf** [comment]
重新添加一个新的盘看看

**Comment by goden-er** [comment]
加盘也是一样得错误
