### ISSUE TITLE
Error 返回首页 unauthorized Invalid credentials provided.  function_name:

### ISSUE THREAD

**Issue by goden-er** [qkqpttgf/OneManager-php#396]
Error
返回首页
unauthorized
Invalid credentials provided.

function_name:
刷新

这是为什么呢，点击更新

**Comment by goden-er** [comment]
> Error
> 返回首页
> unauthorized
> Invalid credentials provided.
> 
> function_name:
> 刷新
> 
> 这是为什么呢，点击更新

**Comment by Posuomen** [comment]
> Error 返回首页 unauthorized Invalid credentials provided.
> 
> function_name: 刷新
> 
> 这是为什么呢，点击更新

为什么呢
