### ISSUE TITLE
希望能添加对js，json和css的隐藏

### ISSUE THREAD

**Issue by saoxiaoyu** [qkqpttgf/OneManager-php#398]
如题，麻烦作者大大了

**Comment by qkqpttgf** [comment]
???没懂

**Comment by saoxiaoyu** [comment]
大佬，其实我是想问能不能隐藏上面这三种后缀的文件

**Comment by ayasa520** [comment]
部署在服务器的话，可以设置 nginx；部署在vercel，可以在 vercel.json 写 rewrites 或者 routes

**Comment by qkqpttgf** [comment]
> 部署在服务器的话，可以设置 nginx；部署在vercel，可以在 vercel.json 写 rewrites 或者 routes

 你这是被访问的时候来控制，他是想列表时不显示。

**Comment by ayasa520** [comment]
> > 部署在服务器的话，可以设置 nginx；部署在vercel，可以在 vercel.json 写 rewrites 或者 routes
> 
> 你这是被访问的时候来控制，他是想列表时不显示。

喔，那确实得单独单独放一个目录
