### ISSUE TITLE
阿里云盘的refresh_token已经不可用

### ISSUE THREAD

**Issue by EXStevens** [qkqpttgf/OneManager-php#399]
获取到的Token只能查看文件夹，无法读取文件，无法下载文件

——另：希望添加对186网盘的支持

**Comment by qkqpttgf** [comment]
以demo为准，
你自己的问题，自行百度。

186？
189它自己不支持API玩了。

**Comment by EXStevens** [comment]
感谢回复。已换用移动端Token，可以访问。

请问能否让登录后依旧使用游客主题，感觉游客主题更好。

**Comment by qkqpttgf** [comment]
其它主题会有滞后性，在管理操作上跟不上新代码，操作可能会出现问题 ，有人就出现了【删一个文件把整个目录都删了】这样的事件，所以管理操作就用默认主题。

**Comment by EXStevens** [comment]
感谢耐心解答
