### ISSUE TITLE
Tenant does not have a SPO license.

### ISSUE THREAD

**Issue by 01Studio-mwb** [qkqpttgf/OneManager-php#40]
按视频教程操作，点击添加OneDrive盘，登录onedrive后跳转，显示
Tenant does not have a SPO license.
![image](https://user-images.githubusercontent.com/41248002/77855643-4168d580-7224-11ea-93e8-f7bab7f8fefe.png)
我应该有这个license。
![image](https://user-images.githubusercontent.com/41248002/77855720-c227d180-7224-11ea-8e89-75aa23315b2b.png)

请问如何解决？

**Comment by qkqpttgf** [comment]
过了几个月，现在猜是：你最开始登录Onedrive时是一个邮箱后缀，但现在换了一个后缀。
比如最开始时是微软默认的那个长长的，然后现在你用的你自己的域名。
就可能会导致这样的情况出现。
