### ISSUE TITLE
SCF无法升级

### ISSUE THREAD

**Issue by Rhythmicc** [qkqpttgf/OneManager-php#400]
我尝试过用腾讯云模板、上传release里的源码、上传当前仓库的源码，在配置页面都会提示要求更新，首次点击更新后有响应，并让我刷新页面，点击刷新后，依然是更新前状态，再次点击更新就会触发504错误
![image](https://user-images.githubusercontent.com/29839231/128818539-06d1a393-1b62-4749-b7e8-746d5615fe16.png)

**Comment by qkqpttgf** [comment]
release???
不看readme的？？

**Comment by Rhythmicc** [comment]
> release???
> 不看readme的？？

看了啊，我全都试了啊。。都是504

**Comment by qkqpttgf** [comment]
> 看了啊，我全都试了啊。。都是504

话说，我原来部署的，打不开了……也是504，腾讯内部毛病？过几天我看看。

**Comment by yujianyasuo** [comment]
同样的问题..

**Comment by qkqpttgf** [comment]
> 同样的问题..

SCF的模板太旧了，直接手动上传新的
