### ISSUE TITLE
云函数执行时间过长

### ISSUE THREAD

**Issue by Kyle-Mao** [qkqpttgf/OneManager-php#402]
![image](https://user-images.githubusercontent.com/69608005/128877303-f075bce1-4101-40f4-8229-c9d6f0bd3783.png)
有时加载时间长达数秒，云函数执行时间也很长，这是否属于正常情况？

**Comment by qkqpttgf** [comment]
我的SCF好像打不开了，504……过几天有空我看看，可能腾讯的毛病
