### ISSUE TITLE
对于Sharelink希望可以直接进入目录

### ISSUE THREAD

**Issue by cnjn** [qkqpttgf/OneManager-php#403]
由于学校的域名没有设置管理员，所以不能直接挂载。只能间接的使用Sharelink。对于Sharelink，大多会选择直接分享一个目录，只有目录里面才有读写权限， 可以跳过目录名本身直接进到目录内吗？
![image](https://user-images.githubusercontent.com/30923815/130005620-dff8502a-ca3f-43e5-9ff0-c5e66440aea8.png)

**Comment by qkqpttgf** [comment]
自己设置这个目录不就好了？？？


【算了淡定，你，去后台，设置public path，为这个目录，就只展示这个目录了】
