### ISSUE TITLE
游客上传文件

### ISSUE THREAD

**Issue by zrmugua** [qkqpttgf/OneManager-php#409]
为什么游客上传的文件会重命名啊,登录之后就不会

**Comment by qkqpttgf** [comment]
因为游客就是游客，解释过很多遍了

**Comment by xiaoheimaoo** [comment]
> 为什么游客上传的文件会重命名啊,登录之后就不会

都给你源码了，自己改改就行吧，我这么改的，目前还没发现有啥问题
disk/Onedrive.php文件里修改
`        if ($_SERVER['admin']) {
            $filename = spurlencode($_POST['upbigfilename'], '/');
        } else {
            $tmp1 = splitlast($fileinfo['name'], '.');
            if ($tmp1[0]==''||$tmp1[1]=='') $filename = $_POST['filemd5'];
            else $filename = $_POST['filemd5'] . '.' . $tmp1[1];
        }`
替换为
`$filename = spurlencode($_POST['upbigfilename'], '/');`

**Comment by qkqpttgf** [comment]
你们都不给个star！

**Comment by xiaoheimaoo** [comment]
> 你们都不给个star！

我老白嫖怪了，下次一定！

**Comment by lslqtz** [comment]
除了 disk/onedrive.php 内，classic 的主题也需要修改不将 upbigfilename 设定为 md5 后的名称
