### ISSUE TITLE
带有方括号的路径会出现404错误

### ISSUE THREAD

**Issue by heartnn** [qkqpttgf/OneManager-php#414]
带有方括号的路径会出现404错误，可能是`[]`没有转义的原因吧。

**Comment by Dough-su** [comment]
其实不只是这样，我发现我的文件中很多文件夹中带()，带空格的，带@的都报错了，半年前重新部署过一次好了，然后过了一个月还是这样。后来就没管了

**Comment by heartnn** [comment]
> 其实不只是这样，我发现我的文件中很多文件夹中带()，带空格的，带@的都报错了，半年前重新部署过一次好了，然后过了一个月还是这样。后来就没管了

是这样，我也发现了，需要修改的地方太多

**Comment by qkqpttgf** [comment]
我demo首页有个[]，没问题的

**Comment by heartnn** [comment]
比如我有这么个目录

`[银魂][S1][01-49][1080P][BDRip][HEVC-10bit][FLAC][MKV]`

目录下有这个文件

`[DBD-Raws][银魂][01-02][1080P][BDRip][HEVC-10bit][FLAC].mkv`

这个时候假设这个目录是有深度的，也就是不是在根目录下，寻找文件的时候就会出现

itemNotFound

然后地址栏的路径里会出现混乱。

**Comment by qkqpttgf** [comment]
> 比如我有这么个目录
> 
> `[银魂][S1][01-49][1080P][BDRip][HEVC-10bit][FLAC][MKV]`
> 
> 目录下有这个文件
> 
> `[DBD-Raws][银魂][01-02][1080P][BDRip][HEVC-10bit][FLAC].mkv`
> 
> 这个时候假设这个目录是有深度的，也就是不是在根目录下，寻找文件的时候就会出现
> 
> itemNotFound
> 
> 然后地址栏的路径里会出现混乱。

请看demo，已经新建了这个目录与这个文件，（内容为asdf），可以下载。
能再提供点其它的吗，可以复现的那种，我才能找到问题

**Comment by heartnn** [comment]
换了个平台没问题了，原来是用的阿里云，应该是阿里云的问题

**Comment by Dough-su** [comment]
> 换了个平台没问题了，原来是用的阿里云，应该是阿里云的问题

我换到百度了。没这个问题了，本来我就在百度的但是域名要备案，就切到阿里云香港了，这回换回去就好了。

**Comment by qkqpttgf** [comment]
> 换了个平台没问题了，原来是用的阿里云，应该是阿里云的问题

好的，我最近去确认下啥问题

**Comment by qkqpttgf** [comment]
刚刚修复了一下[]的问题，更新看看其它问题还在不在
