### ISSUE TITLE
背景图片加载与缓存

### ISSUE THREAD

**Issue by Seryta** [qkqpttgf/OneManager-php#415]
现象：
+ 每次打开新页面背景图片似乎都会重新加载一次，速度比较慢

期望：
+ 能够通过缓存或其他方法，不用每次都重新加载

**Comment by qkqpttgf** [comment]
好的，考虑一下

**Comment by qkqpttgf** [comment]
新建了一个explorerCahce的分支，加了一个设置项，你测试下。

**Comment by Seryta** [comment]
查询分支出现了一点问题，这个是我来生成 token 吗？
```
("message":"API rate limit exceeded for 185.242.5.150. (But here's
the good news: Authenticated requests get a higher rate limit.
Check out the documentation for more
details.)","documentation url":"https://docs.qithub.com/rest/
overview/resources-in-the-rest-api#rate-limiting"
```

**Comment by Seryta** [comment]
没有报错了，我试试

**Comment by Seryta** [comment]
看着还是在重新加载，我试了 renexmoe.html 这个主题，看着是没有重新加载的（master分支）

**Comment by qkqpttgf** [comment]
> 看着还是在重新加载，我试了 renexmoe.html 这个主题，看着是没有重新加载的（master分支）

？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？
我前面怎么写的你完全没看清？？？

**Comment by Seryta** [comment]
> > 看着还是在重新加载，我试了 renexmoe.html 这个主题，看着是没有重新加载的（master分支）
> 
> ？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？
> 我前面怎么写的你完全没看清？？？

我试了更新到 explorerCahce 分支，然后没发现有什么变化（设置项），后面说的renexmoe主题只是跟你说个参考

**Comment by Seryta** [comment]
我看了一下explorerCahce分支更新是生效了的，从文件里面可以看到已经修改成分支里面的代码

**Comment by Seryta** [comment]
不好意思，我找到了那个新增项，我再试一下

**Comment by Seryta** [comment]
试了一下，还是会重新加载，从F12开发者工具里面可以看到加载背景图片花费的时间，本身文件大小是224.93KB。另外看了下代码，这个逻辑似乎只有在请求文件并且不是preview的时候才会生效，切换目录的时候是不是并没有调用它？

**Comment by qkqpttgf** [comment]
> 试了一下，值设置为和background一样的路径，还是会重新加载，从F12开发者工具里面可以看到加载背景图片花费的时间，本身文件大小是224.93KB。但似乎只有一次索引的时间，发起程序：索引，这样就是没有重新加载了吗？索引会花费一些时间。有时候加载页面的时候是一次索引，还有一次是磁盘缓存

是的，后面7200s内都会从浏览器的缓存中读取了。【这个是个开关，取值是0或1，或许，改成时间？想缓存多久就填多久？】

**Comment by Seryta** [comment]
那这不太对，每次切换目录都会有一次 index索引请求，而不是从缓存读取。
缓存读取的话，可以改成时间，0就是不缓存

**Comment by qkqpttgf** [comment]
那我不知道你在做什么了，你可以看我demo，那个背景图片，完全没问题。

**Comment by Seryta** [comment]
看到了，效果很棒，那我自己再看看吧。
