### ISSUE TITLE
提交一个BUG改善 文件名带'的问题

### ISSUE THREAD

**Issue by nodesire7** [qkqpttgf/OneManager-php#418]
应该是没转义吧
带单引号之类的文件名会不能在线播放
![image](https://user-images.githubusercontent.com/63827263/132157255-4b366331-f84e-41fe-baf2-bb3dbb796da3.png)

改好后可以正常播放了
![image](https://user-images.githubusercontent.com/63827263/132157446-0c218607-6e51-41f4-81f8-9a1a8fc91616.png)

需要修改主题文件里的
`(['<!--FileEncodeUrl-->'])`
这一段
把单引号改成双引号

**Comment by qkqpttgf** [comment]
已改
