### ISSUE TITLE
部署在vercel上，现在显示 Failed to open stream了

### ISSUE THREAD

**Issue by W4J1e** [qkqpttgf/OneManager-php#422]
十几天前部署在vercel，能正常访问和使用。最近两天也没改动啥，访问就显示：
Warning: Unknown: Failed to open stream: No such file or directory in Unknown on line 0
Fatal error: Failed opening required '/var/task/user/index.php' (include_path='.:/opt/remi/php80/root/usr/share/pear:/opt/remi/php80/root/usr/share/php:/usr/share/pear:/usr/share/php') in Unknown on line 0
请问是需要重新部署吗？

**Comment by W4J1e** [comment]
在Deployments记录里访问此前的部署成功了，并且触发了三次新的部署，现在正常访问了。
但尚不知道原因。

**Comment by qkqpttgf** [comment]
是的，上个月就发现了，然后我向vercel-php作者提issue了，现在应该大概也许可能似乎好像好了
