### ISSUE TITLE
希望网站预览视频时可以支持.avi格式视频的预览

### ISSUE THREAD

**Issue by Zichen3317** [qkqpttgf/OneManager-php#424]
![image](https://user-images.githubusercontent.com/76838041/133984638-599c2d5c-718b-4758-bc9b-930ec9a17307.png)
如图，如果能加入.avi视频预览就太好了！

**Comment by qkqpttgf** [comment]
这要看dplayer的，我没办法

**Comment by shundebo** [comment]
> 这要看dplayer的，我没办法

dplayer不是有弹幕的吗
