### ISSUE TITLE
谷歌网盘怎么授权

### ISSUE THREAD

**Issue by 10362227** [qkqpttgf/OneManager-php#429]
自己建的app，
提示：
`错误 400： redirect_uri_mismatch

您无法登录此应用，因为它不符合 Google 的 OAuth 2.0 政策的规定。

如果您是此应用的开发者，请在 Google Cloud Console 中注册重定向 URI。`

重定向 URI应该怎么填？

**Comment by qkqpttgf** [comment]
我不是写在上面了？

你填的时候就看不到那行字？？？？？？？？？？？？？？？
