### ISSUE TITLE
网页上出现一行警告

### ISSUE THREAD

**Issue by blankmiss** [qkqpttgf/OneManager-php#43]
Warning: file_get_contents(https://raw.githubusercontent.com/qkqpttgf/OneManager-php/master/version): failed to open stream: Connection refused in /www/wwwroot/OneManager-php-master/common.php on line 685

网页界面出现上方的警告不知道怎么解决
国内阿里轻量搭建
宝塔面板直接弄的

**Comment by qkqpttgf** [comment]
raw.githubusercontent.com这个在国内连不上，所以程序报错
程序检测更新用的。
普通游客看不到的，只有登录后才会有。

**Comment by blankmiss** [comment]
嗯好的 谢谢了
