### ISSUE TITLE
接入阿里云盘 最近有问题

### ISSUE THREAD

**Issue by guangsudalao** [qkqpttgf/OneManager-php#430]
不管是加密还是未加密就是这样的
![屏幕截图 2021-09-25 152325](https://user-images.githubusercontent.com/73008998/134762832-cfd0ced1-3518-4bd9-849f-bceee1a75758.jpg)

**Comment by qkqpttgf** [comment]
你，，，不翻译一下看看？？

**Comment by guangsudalao** [comment]
建议接入扫码登陆，找REFRESH_TOKEN找不到啊

**Comment by qkqpttgf** [comment]
找不到我也没办法，这玩意就是在跟阿里斗智斗勇，我还是怂点好
而且扫码好像做不了吧，以alist为准
