### ISSUE TITLE
阿里云下载提示这个

### ISSUE THREAD

**Issue by shanhai2333** [qkqpttgf/OneManager-php#431]
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>InvalidArgument</Code>
<Message>At least one of AdditionalHeaders is not in request headers.</Message>
<RequestId>6150940E952A833737A8EF1A</RequestId>
<HostId>bj29.cn-beijing.data.alicloudccp.com</HostId>
</Error>

**Comment by qkqpttgf** [comment]
我不传播如何对抗阿里防盗链，你可以自行查找方法
