### ISSUE TITLE
能不能发一个早期版本，升级后 html 没办法预览了

### ISSUE THREAD

**Issue by platoer** [qkqpttgf/OneManager-php#44]
我主要是想预览一个静态 html 文件，作为展示用。之前很完美，升级后不行了。麻烦了:)

**Comment by qkqpttgf** [comment]
上次动了下，现在已修复，请更新

**Comment by platoer** [comment]
> 上次动了下，现在已修复，请更新

谢谢回复:) 
升级了一下，出现如下错误提示：
`{"errno":403,"error":"Invalid scf response. expected scf response valid JSON."}`

**Comment by qkqpttgf** [comment]
这边测试没有这个情况，index.html已经正常显示了。
（可能你的版本比较老？升级前有看到红字标明？要不把环境变量删光试试？你加Q群啊……）

**Comment by platoer** [comment]
> 这边测试没有这个情况，index.html已经正常显示了。
> （可能你的版本比较老？升级前有看到红字标明？要不把环境变量删光试试？你加Q群啊……）

嗯，版本比较老。刚才把整个函数服务全删重建，依然如此：文件夹下带.html 会报错。
PS.好久不用 Q，无法登陆了：）电报群，我在里面。

**Comment by platoer** [comment]
我进一步做了测试，在herokuapp上解析正常，在SCF报错

**Comment by qkqpttgf** [comment]
我也测试过了哇，https://service-pgxgvop2-1258064400.ap-hongkong.apigateway.myqcloud.com/test/abcdef/%E5%AF%86%E7%A0%81%E6%98%AFy/a/ 这个就是一个index.html，密码是y。
