### ISSUE TITLE
master版本无法保存设置

### ISSUE THREAD

**Issue by gouku** [qkqpttgf/OneManager-php#442]
例如修改标签、diskname点击保存后都会出现Need login，please login again的报错

**Comment by gouku** [comment]
啊，明白了，没太看懂意思，开始还以为缓存之类的，不如升级之后直接强制登出，这样就不会有这个问题了。。

**Comment by qkqpttgf** [comment]
> 重新登录也无法保存设置

不要用renexmoe自带的登录，手动输入登录页面来登录。

**Comment by PackageInstaller** [comment]
> > 重新登录也无法保存设置
> 
> 不要用renexmoe自带的登录，手动输入登录页面来登录。

**Comment by PackageInstaller** [comment]
怎么手动输入登录页面啊，我懵了

**Comment by qkqpttgf** [comment]
'adminloginpage' => '如果设置，登录按钮及页面隐藏。管理登录的页面不再是  ?admin  ，而是  ?此设置的值  。',

**Comment by PackageInstaller** [comment]
感谢大大，终于搞好了:)
