### ISSUE TITLE
添加阿里云盘refreshtoken填写后报错400

### ISSUE THREAD

**Issue by ZhcnPanda** [qkqpttgf/OneManager-php#444]
![Screenshot_2021-10-16-13-14-18-048_com android chrome](https://user-images.githubusercontent.com/57992344/137574796-1ad96235-339c-49f7-abee-3402fccfe369.jpg)
![Screenshot_2021-10-16-13-14-34-323_com android chrome](https://user-images.githubusercontent.com/57992344/137574803-1334c8b4-dd3f-458d-b612-7fe373815adf.jpg)

![qq_pic_merged_1634361301743](https://user-images.githubusercontent.com/57992344/137574821-c687cd4c-31fd-4294-a258-4fdd7671378d.jpg)

添加阿里云盘,refreshtoken填写后报错400

**Comment by qkqpttgf** [comment]
> 我这个是从安桌app的log提取的 我试试win的谷歌浏览器提取 谢谢大哥提醒

就是要从日志提啊，要么你复制的不对，要么阿里改什么东西了？实在不行，去我demo里阿里盘下载阿里老版本apk。

**Comment by ZhcnPanda** [comment]
好的，感谢
