### ISSUE TITLE
posted timestamp 

### ISSUE THREAD

**Issue by Winyer** [qkqpttgf/OneManager-php#445]
The timestamp in server is 1634390622 (2021-10-16 13:23:42 UTC),
and your posted timestamp is 1634389932 (2021-10-16 13:12:12 UTC)
 一直都是这样应该怎么处理呢，进不去管理员界面

**Comment by qkqpttgf** [comment]
其它的看不懂，也不翻译，
但2021-10-16 13:23:42也看不懂吗？？
上下对比这么明显，你觉得要怎么处理？？？
