### ISSUE TITLE
foot.omf

### ISSUE THREAD

**Issue by 91en** [qkqpttgf/OneManager-php#45]
foot.omf是直接在目录下新建文件？然后输入valine的代码就行了？

**Comment by qkqpttgf** [comment]
首先，你要用test分支。
然后，你可以直接下载我的foot.omf看看~

**Comment by 91en** [comment]
> 首先，你要用test分支。
> 然后，你可以直接下载我的foot.omf看看~

请问，在哪里下载foot.omf，我没有找到下载的地方。٩(Ü)۶♥٩(Ü)۶

**Comment by yuxiaoyecf** [comment]
foot.omf
head.md
head.omf
这三个文件怎么用啊

**Comment by qkqpttgf** [comment]
> foot.omf head.md head.omf 这三个文件怎么用啊

……就丢进去就好了
