### ISSUE TITLE
Glitch部署自定义域名后更改程序设置一直提示需要重新登录

### ISSUE THREAD

**Issue by SaKongA** [qkqpttgf/OneManager-php#452]
Glitch部署自定义域名后更改程序设置一直提示需要重新登录 刷新缓存 重新登录 都不行
![25E196B9-9D17-44C3-90A7-789F5C4A1FDC](https://user-images.githubusercontent.com/57992344/138212781-1c1581cd-3f51-499f-addf-0370c97a6911.png)

**Comment by qkqpttgf** [comment]
#451 手动登录
