### ISSUE TITLE
请求添加https://www.divio.com/部署支持

### ISSUE THREAD

**Issue by 8ty** [qkqpttgf/OneManager-php#459]
https://www.divio.com/

**Comment by qkqpttgf** [comment]
没看懂怎么部署的，似乎要ssh到它自己的git上去，但它拒绝我ssh过去，
另外，不能点点点，只能命令行操作的，可能不太适合我的风格。

**Comment by qkqpttgf** [comment]
刚看一眼，只能试用30天
