### ISSUE TITLE
debian buster传统方式安装php部署onemanager失败

### ISSUE THREAD

**Issue by minlearn** [qkqpttgf/OneManager-php#462]
onemanager从空的debian开始安装，apt-get install php同时完装apache2和php73，启用a2enmod rewrite，/etc/apache2/apache2.conf中AllowOverride None 改为  AllowOverride All，

git clone到/var/www/html，chmod 666 .data/config.php。

访问安装，设置密码过后，无法访问，失联！
权限已chown -R www-data:www-data
apache log 显示无errors，access也看不到啥，唉

**Comment by minlearn** [comment]
apt-get install php-curl
systemctl restart apache2
正常

**Comment by qkqpttgf** [comment]
好的，我研究一下怎么在安装时检测有没有curl
