### ISSUE TITLE
无法加密唉

### ISSUE THREAD

**Issue by HenryHe613** [qkqpttgf/OneManager-php#463]
![image](https://user-images.githubusercontent.com/59521292/139574171-8b0404c0-54ea-420c-865d-ab6bb254b0a5.png)

**Comment by qkqpttgf** [comment]
经在demo上尝试，没有出现这个情况，
请研究一下，怎么能复现

**Comment by qkqpttgf** [comment]
你是不是在左上角点的加密？？
你试下更新到test分支，试下解决了没

**Comment by qkqpttgf** [comment]
1个多月没有回应，关帖
