### ISSUE TITLE
不带 / 时路径访问错误

### ISSUE THREAD

**Issue by gouku** [qkqpttgf/OneManager-php#465]
举例：

- `https://onemanager.glitch.me/E5/test/` 访问时下面的子目录都可以正常访问，例如 `/E5/test/imya/`
- `https://onemanager.glitch.me/E5/test` 访问时下面的子目录路径都出错，上面的例子会变成 `/E5/imya/`

**Comment by qkqpttgf** [comment]
好的，那有空加个301跳吧

**Comment by qkqpttgf** [comment]
已修，在访问目录时，如果url最后不是以/结尾，就会跳转到以/结尾的url，
看看有没有什么问题。

**Comment by gouku** [comment]
大佬给力，试了下这样应该就没什么问题了！
