### ISSUE TITLE
[Question]阿里云解压部署后提示：“Module '/code/index.php' is missing.”

### ISSUE THREAD

**Issue by DreamUniverse843** [qkqpttgf/OneManager-php#467]
![image](https://user-images.githubusercontent.com/53889721/140712102-e9239ca4-64f5-42fa-af5d-cc8d1b95c4db.png)
![image](https://user-images.githubusercontent.com/53889721/140712185-3d000ce4-5a4f-4e31-90d0-613907e661a5.png)
如上，按照中文 readme 配置，上传代码包后绑定自定义域名，路径配置为 /* ，访问返回 Module '/code/index.php' is missing.

**Comment by qkqpttgf** [comment]
很明显，上传的代码包是直接从github下载的，并没有去掉外层文件夹重新压缩。

**Comment by qkqpttgf** [comment]
另外……你不看readme的吗？？
第一行就说过了，release只是当做存档小黑屋来用的，并不是最新代码，
根本不看readme
