### ISSUE TITLE
Drive_ver Bug

### ISSUE THREAD

**Issue by XiaMoHuaHuo-CN** [qkqpttgf/OneManager-php#468]
![image](https://user-images.githubusercontent.com/79651409/141646799-a0093380-b007-41b1-9ba1-7cfd6dd87c20.png)
![image](https://user-images.githubusercontent.com/79651409/141646833-1b8c69e4-f0ad-4981-bae4-8c4788607491.png)
这个到底出在什么问题，无法安装盘

**Comment by XiaMoHuaHuo-CN** [comment]
补一句，http协议，重写过，见[https://github.com/XiaMoHuaHuo-CN/OneSM](url)

**Comment by qkqpttgf** [comment]
我也不知道唉，你再瞅瞅吧，一步一步来
