### ISSUE TITLE
希望添加自动刷新缓存功能

### ISSUE THREAD

**Issue by hapke24** [qkqpttgf/OneManager-php#472]
希望能够添加定时刷新缓存和上传文件后自动刷新缓存的功能。

**Comment by qkqpttgf** [comment]
强调，本项目基于serverless，只是兼容了一下VPS，所有功能要考虑各serverless平台的特性。所有的serverless平台的设立，就是为了访问时苏醒过来工作一下，没人访问时就休眠，请以此为基础来考虑。
另外，缓存这个东西，访问首页，我就缓存首页的内容，点进去访问某个目录，我就缓存这个目录的内容，你想定时刷新哪个目录的缓存呢？每个目录都定时一下？
【注意，不像其它基于VPS的项目，都是将所有目录结构保存到本地，不刷新就永远是这样。这个项目不是基于VPS，缓存是真缓存，过半小时这个缓存就死掉了，不用你刷新都会去请求的】
上传文件后不刷新这个问题，这个有点麻烦，就等半小时吧……

**Comment by hapke24** [comment]
> 强调，本项目基于serverless，只是兼容了一下VPS，所有功能要考虑各服务器less平台的特性。所有的serverless平台的设立，就是为了访问时苏醒过来工作一下，没人访问时就休眠，请以此为基础来考虑。另外，缓存这个东西，访问首页，我就缓存首页的内容，点进去访问某个目录，我就缓存这个目录的内容，你想定时刷新哪个目录的缓存呢？每个目录都定时一下？ 【注意，不像其它基于VPS的项目，都是将所有目录结构保存到本地，不刷新就永远是这样。这个项目不是基于VPS，缓存是真缓存，过半小时这个缓存就死掉了，不用你刷新都会去请求的】 上传文件后不刷新这个问题，这个有点麻烦，就等半小时吧......

了解了，谢谢解答！
