### ISSUE TITLE
密码不管用了，设置的所有密码都不顶事！

### ISSUE THREAD

**Issue by aiyounilov** [qkqpttgf/OneManager-php#473]
好像是更新之后出的问题，以前每个文件夹的txt文件存了个密码，现在都不行了，输入进去直接白屏或者没反应

**Comment by qkqpttgf** [comment]
没有出现问题，以demo为准，这边都正常的。
我这边没法出现的问题，没法复现，帮不到你。
密码功能这边没改东西呀

**Comment by qkqpttgf** [comment]
#481 ~
