### ISSUE TITLE
最新版阿里云盘无法下载

### ISSUE THREAD

**Issue by iwrt** [qkqpttgf/OneManager-php#476]
如题，点击文件下载后，出现：
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>InvalidArgument</Code>
<Message>At least one of AdditionalHeaders is not in request headers.</Message>
<RequestId>61A956A1BEEEA73030936930</RequestId>
<HostId>bj29.cn-beijing.data.alicloudccp.com</HostId>
</Error>

**Comment by qkqpttgf** [comment]
只能告诉你token问题，具体的我不能传播。
