### ISSUE TITLE
onedrive url无应答

### ISSUE THREAD

**Issue by iwrt** [qkqpttgf/OneManager-php#477]
大佬如题，求解。设置好了。onedrive那边的url地址访问过来也就是自己域名这边的网站。但是输入id和机密的时候，提示无应答。我是二级域名。类似https：//pan.xxx.com    是不是url设置不对。onedrive那边url的也是 https：//pan.xxx.com/api/ 这样的格式。是不是哪里出错了

**Comment by qkqpttgf** [comment]
无图猜不到
