### ISSUE TITLE
腾讯云函数搭建成功，onemanager后台登陆不进去

### ISSUE THREAD

**Issue by iwrt** [qkqpttgf/OneManager-php#479]
如题。sfc搭建好了。上传最新的onemanager也安装好了。就是输入后台密码，显示成功跳转，一直处在登陆界面，后台进不去。换用采用模板创建，能登陆到后台，只要程序一升级。就进不去了。

**Comment by iwrt** [comment]
已解决。必须后缀添加/?admin

**Comment by qkqpttgf** [comment]
没看懂，有个图吗
