### ISSUE TITLE
能否添加docker支持

### ISSUE THREAD

**Issue by coppea** [qkqpttgf/OneManager-php#480]
其他部署不是速度慢就是云函数超载，是否支持docker快速部署

**Comment by qkqpttgf** [comment]
1，我对docker不熟，
2，本项目基于serverless，并没有针对VPS进行启动速度、查询效率这些上的优化，因为从来不保存文档结构。
3，虽然有些免费平台是基于docker的，但我没有找到在它们上面保存配置的方法，所以我不会研究这些平台。

你会正常部署的话，直接正常运行一个网站就好了啊，
或者你可以自行构建一个docker自己用。
