### ISSUE TITLE
密码无效

### ISSUE THREAD

**Issue by jiuliking** [qkqpttgf/OneManager-php#481]
设置的访问密码无效，其它一切正常。

**Comment by qkqpttgf** [comment]
哦，知道了（朕已阅）

【我只能这样回你了，你这不是来寻求解决的，就是来通知我一声你那边有问题，就没打算让我帮你解决，反正我这边一切正常】

**Comment by jiuliking** [comment]
要不我把网站发你，你测试一下。。。（谢皇上操劳）

**Comment by qkqpttgf** [comment]
> 要不我把网站发你，你测试一下。。。（谢皇上操劳）

QQ或TG上PM我

**Comment by qkqpttgf** [comment]
缓存问题，最多半小时就好了
