### ISSUE TITLE
dplayer 太旧了吧

### ISSUE THREAD

**Issue by qian9008** [qkqpttgf/OneManager-php#482]

**Comment by qkqpttgf** [comment]
那换什么呢？帮我换一下呗

**Comment by cfcx** [comment]
> 那换什么呢？帮我换一下呗

https://plyr.io/
html5播放器非常美观好用
接入简单强推

**Comment by foxdodo** [comment]
mov格式直接不能预览, 另外很多视频因为编码的问题点了播放也是黑屏, 搜了下issues好像大家都知道😂

**Comment by qkqpttgf** [comment]
做了个分支，改成了artplayer，试试看（其实我没看出来跟dp区别在哪里）

**Comment by foxdodo** [comment]
> 做了个分支，改成了artplayer，试试看（其实我没看出来跟dp区别在哪里）

试了下只有管理员登录才能调用artplayer, 以前用dplayer播放黑屏的视频左下角会显示"视频加载失败", 这次artplayer直接加载播放器失败, 进入视频预览网页后显示了加载播放器转圈动画, "重新连接"5次就自动停止了

**Comment by foxdodo** [comment]
黑屏有声音的视频也跟以前一样, 播放器变成了音乐播放器那种只有进度条没黑屏的界面

**Comment by qkqpttgf** [comment]
> > 做了个分支，改成了artplayer，试试看（其实我没看出来跟dp区别在哪里）
> 
> 试了下只有管理员登录才能调用artplayer, 以前用dplayer播放黑屏的视频左下角会显示"视频加载失败", 这次artplayer直接加载播放器失败, 进入视频预览网页后显示了加载播放器转圈动画, "重新连接"5次就自动停止了

不是只能管理员登录…… 是只给默认主题改了而已

**Comment by qkqpttgf** [comment]
> 黑屏有声音的视频也跟以前一样, 播放器变成了音乐播放器那种只有进度条没黑屏的界面

所以我也觉得换不换artplayer没啥区别。
