### ISSUE TITLE
请教一下加密的逻辑

### ISSUE THREAD

**Issue by W4J1e** [qkqpttgf/OneManager-php#483]
您好，我已经翻阅了readme和大部分相关的issue。有一个小小的疑惑。
我上传了密码文件，aaaa.txt到根目录，然后在设置的passfile里面填写了该文件名称，然后发现整个根目录的都被加密了，导致访客无法直接访问内容，我将该文件移动到要加密的目录test下，然后点击左边的管理，加密，输入了密码，但是再次访问发现该目录还是可以直接进入。
请问是我的理解和设置出了问题还是什么，非常感谢。

**Comment by W4J1e** [comment]
刷新一次发现问题已解决。

**Comment by qkqpttgf** [comment]
加密操作，请直接用程序的加密，因为自己上传那个file的话，可能会遇到编码问题导致密码不对。

另外，在某个盘的设置里面 ，有个【downloadencrypt】可能你会需要。

**Comment by W4J1e** [comment]
@qkqpttgf 明白，感谢解答。
