### ISSUE TITLE
sha1.js not loaded

### ISSUE THREAD

**Issue by Xunflash** [qkqpttgf/OneManager-php#485]
sha1.js not loaded
在学校远古机器 xp系统 登录的时候弹窗这句话，导致无法登录。

**Comment by qkqpttgf** [comment]
既然弹出来了，就跟系统无关。
这句话看不懂吗？？？？？？？？？？？？？？？？？
js文件没加载啊！！！！！！！！
可能是你们网络不接那个cdn

**Comment by Xunflash** [comment]
> 既然弹出来了，就跟系统无关。 这句话看不懂吗？？？？？？？？？？？？？？？？？ js文件没加载啊！！！！！！！！ 可能是你们网络不接那个cdn

接的，上次后台更新onemanager之后出这个情况了，我又不是第一次在机房用

**Comment by Xunflash** [comment]
> 既然弹出来了，就跟系统无关。 这句话看不懂吗？？？？？？？？？？？？？？？？？ js文件没加载啊！！！！！！！！ 可能是你们网络不接那个cdn

并且我使用手机可以正常登录，现在人在机房用不了onemanager 有点急（手动狗头）

**Comment by Xunflash** [comment]
> 既然弹出来了，就跟系统无关。 这句话看不懂吗？？？？？？？？？？？？？？？？？ js文件没加载啊！！！！！！！！ 可能是你们网络不接那个cdn

是否是tls，或者是机器浏览器内核太旧了的原因？这条机器是Windows xp sp3  浏览器用的360，换了chrome连onemanager登录界面都打不开

**Comment by qkqpttgf** [comment]
> 是否是tls，或者是机器浏览器内核太旧了的原因？这条机器是Windows xp sp3 浏览器用的360，换了chrome连onemanager登录界面都打不开
不知道了，没有这种环境，不知道怎么解决……
你更新一下程序，我刚刚换成jsdelivr的cdn了，你再试试。

**Comment by Xunflash** [comment]
> 
> > 是否是tls，或者是机器浏览器内核太旧了的原因？这条机器是Windows xp sp3 浏览器用的360，换了chrome连onemanager登录界面都打不开
> 不知道了，没有这种环境，不知道怎么解决……
> 你更新一下程序，我刚刚换成jsdelivr的cdn了，你再试试。
> 

还是alert了一个sha1.js not loaded   
太难了，最近这些版本是不是有更改什么东西啊，上周二手残点了下更新

**Comment by Xunflash** [comment]
> 
> > 是否是tls，或者是机器浏览器内核太旧了的原因？这条机器是Windows xp sp3 浏览器用的360，换了chrome连onemanager登录界面都打不开
> 不知道了，没有这种环境，不知道怎么解决……
> 你更新一下程序，我刚刚换成jsdelivr的cdn了，你再试试。
> 

兄弟打扰了，我刚刚chmod777全部文件然后更新了一遍，现在好了，可能是我上次更新失败了。
