### ISSUE TITLE
把密码忘了怎么办？（滑稽）

### ISSUE THREAD

**Issue by our-windows** [qkqpttgf/OneManager-php#5]
rt

**Comment by qkqpttgf** [comment]
如果是文件夹密码，设置一个新的密码（左上角再点一下刷新缓存）就好。
如果是admin密码，SCF去环境变量那里改，heroku去Config Var那里改，VPS或php空间就改config.php文件。

**Comment by our-windows** [comment]
老哥🐂🍺 给颗star

**Comment by Nikeguo** [comment]
glitch的密码在哪里看呢

**Comment by qkqpttgf** [comment]
> glitch的密码在哪里看呢

glitch的配置在.data/config.php，但这个在它网页编辑器上不可见，你要点它的tool里面的命令行，然后cat .data/config.php。

**Comment by FlyingStarlight** [comment]
如何是vercel呢

**Comment by qkqpttgf** [comment]
> 如何是vercel呢

#488 ，
