### ISSUE TITLE
添加 世纪互联的onedrive失败

### ISSUE THREAD

**Issue by royccg** [qkqpttgf/OneManager-php#50]
大佬，我使用的 是 世纪互联的 for stu的账号，
1.使用 自带的绑定方式，登录的[网址](https://login.live.com/login.srf?wa=wsignin1.0&rpsnv=13&ct=1588408428&rver=7.1.6819.0&wp=SAPI_LONG&wreply=https%3a%2f%2fapps.dev.microsoft.com%2fLoginPostBack%3fru%3dhttps%253a%252f%252fapps.dev.microsoft.com%253a443%252f%253fdeepLink%253d%25252fquickstart%25252fgraphIO%25253fpublicClientSupport%25253dfalse%252526appName%25253dOneManager%252526redirectUrl%25253dhttps%25253a%25252f%25252fscfonedrive.github.io%252526allowImplicitFlow%25253dfalse%252526ru%25253dhttps%2525253A%2525252F%2525252Fdeveloper.microsoft.com%2525252Fzh-cn%2525252Fgraph%2525252Fquick-start%2525253FappID%2525253D_appId_%25252526appName%2525253D_appName_%25252526redirectUrl%2525253Dhttps%2525253A%2525252F%2525252Fscfonedrive.github.io%25252526platform%2525253Doption-php%2526referrer%253dhttps%25253a%25252f%25252fheroku-olaindex.herokuapp.com%25252fone-china%25252f%25253fAddDisk%2523%252fquickstart%252fgraphIO%253fpublicClientSupport%253dfalse%2526appName%253dOneManager%2526redirectUrl%253dhttps%253a%252f%252fscfonedrive.github.io%2526allowImplicitFlow%253dfalse%2526ru%253dhttps%25253A%25252F%25252Fdeveloper.microsoft.com%25252Fzh-cn%25252Fgraph%25252Fquick-start%25253FappID%25253D_appId_%252526appName%25253D_appName_%252526redirectUrl%25253Dhttps%25253A%25252F%25252Fscfonedrive.github.io%252526platform%25253Doption-php&lc=2052&id=293053&aadredir=1) 显示没有账号不存在。
我通过 世纪互联的https://portal.azure.cn/ 可以登录的。

2. 我自己申请 microsoft azure应用的话，总是跳出来错误：
```
AADSTS50011: The reply URL specified in the request does not match the reply URLs configured for the application
```
请问 ，有解决的办法吗，或者自己 申请应用的话，有相应的教程吗？
谢谢

**Comment by lbcz-tian** [comment]
老哥，请问你是怎么解决的呀？我这里提示请输入正确的域。。但是也可以在portal登录
![image](https://user-images.githubusercontent.com/62131027/81278123-d6fb4e80-9087-11ea-8939-f23730342e2f.png)
