### ISSUE TITLE
更新时出现“返回首页 Need login please login again”   （处于登录状态）

### ISSUE THREAD

**Issue by Adsryen** [qkqpttgf/OneManager-php#502]
处于登录状态，已尝试切换   无痕，浏览器，电脑    ，均显示以下内容   ，无法更新

![image](https://user-images.githubusercontent.com/51238895/147475765-70486a4f-9ac0-4ca4-a9f6-a43f585e66bf.png)

**Comment by qkqpttgf** [comment]
肯定是remoenex的主题
关掉所有无痕，重新开一个无痕，不要点主题自带的登录，手动在url后面加上"?admin"来登录，然后去更新，就没这事了。
【或者你其它方法直接先更新】

**Comment by Adsryen** [comment]
对  实锤了  就是主题的原因  已解决谢谢
