### ISSUE TITLE
Failed to write config.

### ISSUE THREAD

**Issue by cqash** [qkqpttgf/OneManager-php#503]
Error
failed
Failed to write config.
安装弹出这个提示后config文件里面的内容被清空了，变成了一个0b文件
vps宝塔部署的
之前弄好了一段时间，不知道为啥突然无法使用了，打开就是安装页面

**Comment by qkqpttgf** [comment]
宝塔不熟，不知道宝塔做了什么让程序认为不可写。是不是有什么保护机制或延后机制。

我程序是写入一个临时tmp配置，然后读取，如果读取到的正确，说明正常写入。
如果你某个其它程序保护了网站文件，那我写入不了，或当时写入后读取时还是以前的数据，并不是新的，那也会认为config不可写。

**Comment by cqash** [comment]
我查看了config文件，里面原有的内容被删掉了，多次重新上传原始文件尝试，都是如此

**Comment by qkqpttgf** [comment]
> 我查看了config文件，里面原有的内容被删掉了，多次重新上传原始文件尝试，都是如此

删掉？那不知道了，可能跟你啥东西冲突了吧。

**Comment by zgll** [comment]
> 我查看了config文件，里面原有的内容被删掉了，多次重新上传原始文件尝试，都是如此

我也是宝塔，一样的错误现象。然后我发现的空间不足了，清理之后，安装成功了。
