### ISSUE TITLE
Vercel部署安装出现Bad_Request

### ISSUE THREAD

**Issue by XiaMoHuaHuo-CN** [qkqpttgf/OneManager-php#505]
![image](https://user-images.githubusercontent.com/79651409/148640889-e4d093e0-53ef-4d88-afa2-0f91904eee6b.png)

**Comment by XiaMoHuaHuo-CN** [comment]
已查明问题：
覆盖原有部署时才会出现此问题

**Comment by qkqpttgf** [comment]
我为了测试代码，经常覆盖啊，没这样过

**Comment by XiaMoHuaHuo-CN** [comment]
不知道，可能是Vercel的一个Bug吧

**Comment by qkqpttgf** [comment]
肯定不是人家的bug，因为我经常覆盖，从来没出现过，我更新其实也是覆盖啊，操作配置其实也是覆盖啊，没出现过问题。
