### ISSUE TITLE
Allow Preview downloadencrypt

### ISSUE THREAD

**Issue by kuyhaa** [qkqpttgf/OneManager-php#506]
I set password each folder, downloadencrypt=1 , when download without preview page, its work normal no need passwrd, but when with Preview page, it need password ,

Can you allow preview page without passwrd when downloadencrypt=1 ?

我为每个文件夹设置了密码，downloadencrypt=1，当下载没有预览页面时，它的工作正常不需要密码，但是当有预览页面时，它需要密码，

 当 downloadencrypt=1 时，您可以允许没有密码的预览页面吗？

**Comment by qkqpttgf** [comment]
Added
