### ISSUE TITLE
scf部署时秘钥验证失败

### ISSUE THREAD

**Issue by Winyer** [qkqpttgf/OneManager-php#507]
RT，删除过密钥还是一样的，重新部署过SCF，也是一样，一直都是现实：
Error
AuthFailure.SignatureFailure
The provided credentials could not be validated. Please check your signature is correct.

function_name:pan
Region:ap-hongkong
namespace:default

**Comment by qkqpttgf** [comment]
那肯定你秘钥不对，程序拿着你输入的东西才能保存进去，

请仔细查看，特别是前后空格

**Comment by Winyer** [comment]
重新生成密钥，逐字符检查了还是这样，会不会是https://blog.csdn.net/weixin_42273457/article/details/105701877

**Comment by Winyer** [comment]
找到问题了，可能是因为开启了base64导致的，此问题终结。

**Comment by qkqpttgf** [comment]
> 找到问题了，可能是因为开启了base64导致的，此问题终结。

啊，啥意思？在哪开？

**Comment by Huiaei** [comment]
> > 找到问题了，可能是因为开启了base64导致的，此问题终结。
> 
> 啊，啥意思？在哪开？

触发器的base64编码吧
