### ISSUE TITLE
作者好，部署在glitch上面，日志出现如下异常

### ISSUE THREAD

**Issue by merlinHan** [qkqpttgf/OneManager-php#510]
你好，作者大大。部署在glitch上面，然后在它的logs里面出现这个日志：
/opt/watcher/app-types/custom/install.sh: line 9: null: command not found

**Comment by qkqpttgf** [comment]
没遇到过，这个install.sh不是我代码内容。
你有按照我的操作来部署？？

**Comment by merlinHan** [comment]
> 没遇到过，这个install.sh不是我代码内容。 你有按照我的操作来部署？？

有按照步骤来部署，况且glitch步骤很简单。重新部署以后出现的日志也还是这个。

**Comment by qkqpttgf** [comment]
录个视频吧，完全没遇到过
