### ISSUE TITLE
前几天在Issues里看到有人推荐新的播放器Plyr

### ISSUE THREAD

**Issue by Winyer** [qkqpttgf/OneManager-php#512]
测试了下，Plyr确实比Dplayer流畅得多，很多Dplayer加载失败的视频它也都能加载，无论是加载速度还是对视频的处理速度都要好得多。大佬有计划下个版本换成Plyr吗？

**Comment by Winyer** [comment]
测试了下，Plyr确实比Dplayer流畅得多，很多Dplayer加载失败的视频它也都能加载，无论是加载速度还是对视频的处理速度都要好得多。大佬有计划下个版本换成Plyr吗？

**Comment by qkqpttgf** [comment]
有空再看

**Comment by weizai408** [comment]
支持。目前的播放器经常加载失败。希望大佬抽空更换下。

**Comment by qkqpttgf** [comment]
看了一眼，我似乎不会弄……

**Comment by foxdodo** [comment]
> 测试了下，Plyr确实比Dplayer流畅得多，很多Dplayer加载失败的视频它也都能加载，无论是加载速度还是对视频的处理速度都要好得多。大佬有计划下个版本换成Plyr吗？

放4k会卡顿吗? 现在的播放器放4k会卡顿, 我看了cpu gpu占用都很低但就是卡
