### ISSUE TITLE
宝塔设置了反代，下载会起作用，但上传怎么不走反代？

### ISSUE THREAD

**Issue by weizai408** [qkqpttgf/OneManager-php#513]
宝塔设置了反代，下载会起作用，但上传怎么不走反代？
使用的默认主题，是哪里设置出问题了吗？

**Comment by qkqpttgf** [comment]
啥叫“宝塔设置了反代”？

正常上传下载都是你直接对接微软，我程序里面有一个可以替换域名成你反代域名的设置，这也只是download proxy，跟上传无关。

**Comment by weizai408** [comment]
恩 我在后台程序里填了反代的域名；你的意思是 这个反代只对下载有效，上传本来就不起作用？
