### ISSUE TITLE
具体页里显示的路径不正确

### ISSUE THREAD

**Issue by Orange-Summer** [qkqpttgf/OneManager-php#516]
![屏幕截图 2022-01-18 003225](https://user-images.githubusercontent.com/61171207/149807312-242ae9ee-4c85-4696-85d2-1e33bf3feebb.jpg)
部署在Vercel
如图所示，具体页里的路径是直接根目录加文件名的，不知道是什么原因

**Comment by qkqpttgf** [comment]
你没更新吧？是onemoe主题？我这边显示正常

**Comment by Orange-Summer** [comment]
啊，抱歉，刚刚发现是因为同时设置了customTheme和theme选项导致的，把customTheme里面清空就好了，打扰您了
