### ISSUE TITLE
新版本访问站点页面空白，旧版本正常。

### ISSUE THREAD

**Issue by fansuregrin** [qkqpttgf/OneManager-php#518]
- 搭建环境: Deian11 vps
- php版本: 7.4
- web-server: nginx 1.18.0-6.1

作者你好，我使用最新版本（v3.4）搭建时，访问站点只有空白页面，无法安装。nginx也没有报错，在index.php添加了phpinfo()函数也能正常显示phpinfo的页面。

尝试换成v3.3版本后，一切正常。

**Comment by qkqpttgf** [comment]
请编辑index.php
把前几行那个error啥的2行注释掉，或者干脆删了，再访问看下报什么错。【有那句就不显示任何报错】

**Comment by fseteen** [comment]
> * 搭建环境: Deian11 vps
> * php版本: 7.4
> * web-server: nginx 1.18.0-6.1
> 
> 作者你好，我使用最新版本（v3.4）搭建时，访问站点只有空白页面，无法安装。nginx也没有报错，在index.php添加了phpinfo()函数也能正常显示phpinfo的页面。
> 
> 尝试换成v3.3版本后，一切正常。

请问最后最怎么解决的？？

**Comment by qkqpttgf** [comment]
> 请问最后最怎么解决的？？

你说你问题看看~

**Comment by fseteen** [comment]
谢谢！我是新手。现在在 vps 上面部署 OneManager

**Comment by fseteen** [comment]
我在本地计算机上部署成功了的，这次是在 vps 上部署
vps 上面运行环境可能存在问题，要不我重新部署吧？！

**Comment by fseteen** [comment]
> 
谢谢回复！

运行环境：
PHP 7.4.3 (fpm-fcgi) (built: Nov 25 2021 23:16:22)
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.3, Copyright (c), by Zend Technologies

nginx version: nginx/1.21.4

注释 php.ini 的 error 相关语句：
//error_reporting(E_ALL & ~E_NOTICE);
//error_reporting(0);

浏览器显示如下：
Notice: Undefined index: language in /www/OneManager-php/common.php on line 973

Notice: Undefined index: base_path in /www/OneManager-php/common.php on line 978

Notice: Undefined index: language in /www/OneManager-php/common.php on line 748

Notice: Undefined index: in /www/OneManager-php/common.php on line 748

Notice: Undefined index: language in /www/OneManager-php/common.php on line 748

Notice: Undefined index: in /www/OneManager-php/common.php on line 748

**Comment by fseteen** [comment]
> 

谢谢！我试试

**Comment by qkqpttgf** [comment]
> > 我现在用v3.5没这问题了
> 
> 还是一样的问题，我还是重新来过吧
> 
> Notice: Undefined index: language in /www/OneManager-php/common.php on line 946
> 
> Notice: Undefined index: base_path in /www/OneManager-php/common.php on line 951
> 
> Notice: Undefined index: language in /www/OneManager-php/common.php on line 721
> 
> Notice: Undefined index: in /www/OneManager-php/common.php on line 721
> 
> Notice: Undefined index: language in /www/OneManager-php/common.php on line 721
> 
> Notice: Undefined index: in /www/OneManager-php/common.php on line 721

这些Notice只是通知，你看下有没有error，这个才是出错。
