### ISSUE TITLE
设置guestup_path后未登录访问该目录有警告提示

### ISSUE THREAD

**Issue by cqsn558** [qkqpttgf/OneManager-php#52]
在后台guestup_path设置了一个目录，如果在未登录的情况下进入该设置的目录会在页面顶部提示：
Warning: Invalid argument supplied for foreach() in D:\common.php on line 1564
Warning: Invalid argument supplied for foreach() in D:\common.php on line 1583
如果登录后再进入这个目录就没有提示。
common.php文件中以上两行代码相同：
`foreach ($files['children'] as $file) {`

**Comment by qkqpttgf** [comment]
你可能是宝塔的受害者？
我觉得你可以调一下php警告等级（报警级别）。
另，D:\ ？？

**Comment by cqsn558** [comment]
是用的宝塔，因为我网站没显示过警告，以为是程序有bug
