### ISSUE TITLE
游客上传报错

### ISSUE THREAD

**Issue by MuziShaoxing** [qkqpttgf/OneManager-php#522]
今天有啥变动吗？
游客上传没变化 不出成功失败，也看不出来问题

**Comment by MuziShaoxing** [comment]
![14:59-hukUvi](https://cdn.jsdelivr.net/gh/muzishaoxing/picture@main/shaoxing/20220126/14:59-hukUvi.png)

**Comment by qkqpttgf** [comment]
这是哪个主题，我明天测试一下

**Comment by MuziShaoxing** [comment]
截至下午8点，莫名修复了


 
---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年1月26日 22:40:53
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [qkqpttgf/OneManager-php] 游客上传报错 (Issue #522)




 
这是哪个主题，我明天测试一下
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by qkqpttgf** [comment]
估计是bootcss坏掉了的锅
