### ISSUE TITLE
Bootcss 资源失效，导致无法登录

### ISSUE THREAD

**Issue by ygbhf** [qkqpttgf/OneManager-php#523]
![image](https://user-images.githubusercontent.com/9164101/151128058-7f37ac49-6fc4-41bd-8c63-99484793ac5f.png)
![image](https://user-images.githubusercontent.com/9164101/151128414-0a2e172a-831e-4ea6-9f5b-a3445d7830ff.png)

建议更换所有 bootcss 静态资源引用。

**Comment by sudoskys** [comment]
同样的问题，升级后解决了，进不去可以试试刷新？

**Comment by qkqpttgf** [comment]
呃，我能打开它……

**Comment by qkqpttgf** [comment]
bootcss好像好了，
要换的话，换啥好呢，jsd也是时通时断

**Comment by ygbhf** [comment]
> bootcss好像好了， 要换的话，换啥好呢，jsd也是时通时断

以下几个我觉得都还是比较稳

* 字节 https://cdn.bytedance.com/
* 360 https://cdn.baomitu.com/
* 知乎（unpkg 反代） https://unpkg.zhimg.com/

**Comment by ygbhf** [comment]
再补一张图， Bootcss 每年都要挂一次

![image](https://user-images.githubusercontent.com/9164101/151286898-1c792fb1-bb47-43d0-a29d-1752c59786f6.png)

**Comment by ygbhf** [comment]
又又又挂了
![image](https://user-images.githubusercontent.com/9164101/151689895-b05597bd-4e06-4ec8-9e8f-0a02b8770726.png)
