### ISSUE TITLE
作者能不能美化一下登录页面啊

### ISSUE THREAD

**Issue by SYSTEMWindows11** [qkqpttgf/OneManager-php#526]
修改common.php
$html .= '
    <style>body{background-image:linear-gradient(60deg,#343b44 0%,#485563 100%);background-attachment:fixed;color:#343b44}body>div{position:absolute;text-align:center;background-color:rgba(221,221,221,.5);border-radius:20px;width:75vw;max-width:500px;height:350px;margin:auto;top:25%;bottom:50%;left:0;right:0}body>div:hover{box-shadow:3px 3px 6px 3px rgba(0,0,0,.3)}h4{font-size:40px}input{font-size:20px;margin:2%auto;border:#343b44 2px solid;border-radius:10px;padding:10px;height:50px;text-align:center}input:last-of-type{color:#343b44;height:50px;width:80px;font-weight:800}input:hover:last-of-type{cursor:pointer;color:#ddd;background-color:#485563}</style>
    <body>
    <div>
      <center><h4>'.getconstStr('InputPassword').'</h4>
      <form action="" method="post">
          <div>
            <input name="password1" type="password"/>
            </br>
            <input type="submit" value="'.getconstStr('Login').'">
          </div>
      </form>
      </center>
    </div>
';

**Comment by qkqpttgf** [comment]
这不是黑化嘛~~

**Comment by SYSTEMWindows11** [comment]
e

**Comment by SYSTEMWindows11** [comment]
去看看我魔改的OneManager
github.com/SYSTEMWindows11/OneManager

**Comment by qkqpttgf** [comment]
> 去看看我魔改的OneManager github.com/SYSTEMWindows11/OneManager

太长不看！<-_<-
