### ISSUE TITLE
目录文件过多会报错

### ISSUE THREAD

**Issue by meng-luo** [qkqpttgf/OneManager-php#528]
![image](https://user-images.githubusercontent.com/79274361/151568256-e3daf8d7-821b-4875-bad0-4ec01f88fd5e.png)

**Comment by qkqpttgf** [comment]
只有aliyunpan会这样吧？

**Comment by meng-luo** [comment]
> 只有aliyunpan会这样吧？

onedrive，目录里有2000多个文件

**Comment by syxf** [comment]
我的onedrive同样遇到此问题

**Comment by qkqpttgf** [comment]
啊，真不知道，已经 unknown了……
