### ISSUE TITLE
Rewrite Engine 重写（伪静态）解释

### ISSUE THREAD

**Issue by Crazy-White** [qkqpttgf/OneManager-php#53]
Platform: VPS/Apache
when I use this `.htaccess`  below
```
RewriteEngine On
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*) index.php?/$1 [L]
```
This should works, but when installing, it returns a 200 error and does not show the password form.
It seems there are some problem when checking the Rewrite Engine.

**Comment by qkqpttgf** [comment]
I had a .htaccess file, use it!
Your code mean viewer can access your local files, like xxxx.com/theme or xxxx.com/config.php , you must read my readme.md in github, 
In my .htaccess, viewer can not visit any local files.
The 200 http code mean you can visit config.php, if the right Rewrite works, it must 201 (the 'click to install' page).
我有一个.htaccess文件你不看，你不用？？还要自己弄一个。
你的重写代码意思是，不存在这个文件（夹）的时候，才会重写，才会给程序处理，这样会暴露程序文件。当onedrive中正好也有这个文件（夹）的时候，你永远访问不了onedrive中的那个，你只能访问到代码中的文件（夹），这样会造成安全隐患。
200的意思是你正常访问到了config.php，说明没有经过重写，这对我程序来说是不可原谅的，我需要所有的访问都交由index.php来处理，按程序要求，安装时访问config.php应该要201状态码（这正是“点击安装”页面的状态码）。

**Comment by Crazy-White** [comment]
The fact is, after installing I changed `.htaccess` to my own, It did works. (If I have local files, I can view my own but not files in onedrive. I can add more Rewrite Rules to avoid exposing files for the program.)
In your codes, you check the `config.php` to check the Rewrite Engine(You give both js and php method then use js). This is inappropriate in some cases. You need to give users some choices(Like A button to skip the check).
If you want to avoid safety problems, I'd recommend you not using cookies(replace with localStorage/sessionStorage).

**Comment by qkqpttgf** [comment]
No, I think everything the viewer can visit is in onedrive，I will hide local files.
The xxxxx.com/folder/file  only point to the file in onedrive, that is conformable to thought.

**Comment by Crazy-White** [comment]
I must say that your `.htaccess` is a bit strange, because usually route is to give priority to local files.

**Comment by qkqpttgf** [comment]
> I must say that your `.htaccess` is a bit strange, because usually router is to give priority to local files.

I say, any visit must point to onedrive !!!
