### ISSUE TITLE
关于 customScript 的BUG

### ISSUE THREAD

**Issue by xihale** [qkqpttgf/OneManager-php#534]
`平台变量` 中的 `customScript`设置后在每个页面都有，会使部分前端调用后端api时的代码误判
Example: 调用 `?WaitFunction=1` 这个api时会传回 `customScript` 中的值，导致前端判断 `data=='ok'` 时出现问题(因为多传了值，所以data=`"ok"`+`customScript中的值`)
建议:  把 `customScript` 的 `作用范围` 缩小到 `文件浏览` 页面

**Comment by xihale** [comment]
我自己的临时的解决方案是把需要加入的 `javascript` 加入到主题文件中(源码太复杂，对于我来说，就懒得去剖析源码了)

**Comment by xihale** [comment]
> 我自己的临时的解决方案是把需要加入的 `javascript` 加入到主题文件中(源码太复杂，对于我来说，就懒得去剖析源码了)
刚刚发现用这种方法只要手动更新，主题文件就会被覆盖...然后有得重新修改

**Comment by qkqpttgf** [comment]
在我印象中这个只是在每个目录页与预览页会有，
测试后，确实在管理操作中不可能出现这个东西。
你确定在WaitFunction=1时会带上它？我这边没带上。

**Comment by xihale** [comment]
我也不知道为什么，今天去测试又没了，可能是昨天手贱改主题文件的缘故吧
