### ISSUE TITLE
文件搜索功能实现假设

### ISSUE THREAD

**Issue by 8yn** [qkqpttgf/OneManager-php#537]
可不可以这样：
就是生成一个search.xml文件但是对访客不可见也不可下载，只有admin可以管理
然后每次上传或删除就在后台编辑
就相当于是静态的搜索。
又或者是只允许admin使用（毕竟大部分的都是'自用）

**Comment by qkqpttgf** [comment]
文件少可以遍历一下然后保存在这里面，
但文件多呢？比如他们经常一个目录里面几千个文件，拿着这些文件名保存一下都可能会产生一个很大的文件，到时读取好办，更改怎么办？
特别地，文件少还用不上搜索呢，是吧？
这搜索功能就只能是把结构弄本地再搜索的，反正我没打算在serverless里弄了
