### ISSUE TITLE
关于说明文件失效的问题

### ISSUE THREAD

**Issue by MuziShaoxing** [qkqpttgf/OneManager-php#544]
哦不，不能说失效，应该说渲染失败？
<img width="496" alt="image" src="https://user-images.githubusercontent.com/76191512/154640114-1f67eee2-b072-4307-af0d-375ceb4bd80e.png">
此功能还回修复吗？

**Comment by qkqpttgf** [comment]
我这并没有问题

**Comment by MuziShaoxing** [comment]
真的没有问题吗？ 能够识别出来说明文件，但是里面的内容不显示好吧 Github上面的程式就无法预览内容
难道是我眼花？


 
---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年2月18日 17:57:00
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [qkqpttgf/OneManager-php] 关于说明文件失效的问题 (Issue #544)




 
我这并没有问题
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by lslqtz** [comment]
一个 typo，onedrive.php 里面的 $ 打成 $$ 了导致在文件夹里预览时会发生错误，和之前我提的新加的 UTF-16LE 编码支持这个 feature 有关，我之前测试的时候 MD 文件都还在缓存期内，因此没有出现问题。。
建议临时手动替换一下。

**Comment by qkqpttgf** [comment]
> 一个 typo，onedrive.php 里面的 $ 打成 $$ 了导致在文件夹里预览时会发生错误 (这个问题仅限于在文件夹内预览，直接打开是没有问题的)，和之前我提的新加的 UTF-16LE 编码支持这个 feature 有关，我之前测试的时候 MD 文件都还在缓存期内，因此没有出现问题。。 建议临时手动替换一下。

他这个issue是22 hours ago，我Onedrive.php的修改是在21 hours ago……跟这个$$无关，肯定是他其它的问题。

**Comment by MuziShaoxing** [comment]
咳咳。根据上述解答，问题已解决。
