### ISSUE TITLE
无法登录后台

### ISSUE THREAD

**Issue by fansuregrin** [qkqpttgf/OneManager-php#546]
作者，你好！我搭建好后，通过正确的密码无法登录后台，请问是哪里出现问题了吗？谢谢！

**Comment by qkqpttgf** [comment]
请提供正常的信息，你这提供的都是废话。

**Comment by qkqpttgf** [comment]
1，你说正确的密码，万一你记错了，或者输错了，甚至当时设的时候就输错了呢？
2，怎么样个“无法”法？
3，前台有没有报错或提示？后台的报错呢？


就一句   [你好，我今天吃不下饭，是哪里出问题了呢？]  我哪知道哪里问题。

**Comment by fansuregrin** [comment]
实在抱歉啊！作者大大！我有事情没有留意github的邮件通知，也是我说的太简单了，给你的工作带来了麻烦，非常抱歉！

说正确的密码是因为我看了.data/config.json（好像是这个配置文件，记不太清楚了）里面的内容，里面有passwd的，也跟我记住的密码一样。我输入密码后，页面跳转到未登录之前一样的页面，相当于刷新了一样，没进入后台，显示没登录（就是说左上角还是登录按钮，点进去还是需要输入密码登录）。

搭建环境
｀｀｀
nginx 1.18.0
php 7.4.25
os: debian bullseye
```
谢谢你的耐心回复！

**Comment by qkqpttgf** [comment]
你，代码从哪个地方点的下载的？

**Comment by fansuregrin** [comment]
你的仓库的release里面最新版本的那个包。

**Comment by fansuregrin** [comment]
抱歉，我知道原因了！

**Comment by fansuregrin** [comment]
作者大大，点击左上角的登录按钮是直接跳到?admin页面的，为啥不改成跳到?login=admin页面呀。

**Comment by qkqpttgf** [comment]
> 你的仓库的release里面最新版本的那个包。

？？？？？
readme完全不看呗？

**Comment by qkqpttgf** [comment]
> 作者大大，点击左上角的登录按钮是直接跳到?admin页面的，为啥不改成跳到?login=admin页面呀。

因为你不是最新版本

**Comment by fansuregrin** [comment]
嗯，好的，谢谢作者！给你制造麻烦了！对不起🙏
