### ISSUE TITLE
希望增加隐藏文件及目录功能

### ISSUE THREAD

**Issue by coolwjl** [qkqpttgf/OneManager-php#548]
希望增加隐藏文件及目录功能，希望可以隐藏指定文件和文件夹，或者根据命名规则隐藏文件和文件夹

**Comment by qkqpttgf** [comment]
以 . 开头的文件或目录，不会显示。

**Comment by Posuomen** [comment]
> 以 . 开头的文件或目录，不会显示。

可不可以隐藏整盘呢

**Comment by qkqpttgf** [comment]
> > 以 . 开头的文件或目录，不会显示。
> 
> 可不可以隐藏整盘呢

请更新，更新了就有了

**Comment by qkqpttgf** [comment]
> > > > 以 . 开头的文件或目录，不会显示。
> > > 
> > > 
> > > 可不可以隐藏整盘呢
> > 
> > 
> > 请更新，更新了就有了
> > 好像没有哇 在哪里设置呢

你没更新……更新完了慢慢找……
