### ISSUE TITLE
阿里云盘出现无法下载

### ISSUE THREAD

**Issue by Eric-Qiu1994** [qkqpttgf/OneManager-php#549]
出现

`
This XML file does not appear to have any style information associated with it. The document tree is shown below.

<Error>
<Code>InvalidArgument</Code>
<Message>At least one of AdditionalHeaders is not in request headers.</Message>
<RequestId>6218427A4679EE323593D4DF</RequestId>
<HostId>bj29.cn-beijing.data.alicloudccp.com</HostId>
</Error>
`

**Comment by qkqpttgf** [comment]
不看readme的？？？能不能在issue里面先搜索一下这个问题？？

你token权限问题，我不传播方法，不跟阿里斗智斗勇。

**Comment by qkqpttgf** [comment]
#399 ， #275 ，issue里一堆，阿里万一学pandown我怎么办

**Comment by woshichenghaibo** [comment]
> #399 ， #275 ，issue里一堆，阿里万一学pandown我怎么办

https://d.fewknown.com/alicloud/OneManager-php-3.5.zip
能列表，但是不弹出下载，也没错误提示，什么原因

**Comment by woshichenghaibo** [comment]
顺便说下，我用的手机获取的令牌
