### ISSUE TITLE
能否增加复制当前目录下已选择的文件链接

### ISSUE THREAD

**Issue by cqsn558** [qkqpttgf/OneManager-php#55]
OD网盘如果是用迅雷等下载软件进行下载速度会快很多，需然程序有复制所有下载链接功能，但有时只需要下载当前目录下部分文件，能否增加复制选择的文件链接或者在每个文件名后的下载图标后面再增加一个复制当前文件链接？

**Comment by qkqpttgf** [comment]
部分就不考虑了
下载图标就有链接啊，为什么还要加
