### ISSUE TITLE
some typos

### ISSUE THREAD

**Issue by zzjjbb** [qkqpttgf/OneManager-php#554]
感觉这个`<!--xxxxxx-->`结尾是不是少了`--`？
https://github.com/qkqpttgf/OneManager-php/blob/6eb6a826cf53782cff4a85fb60af182533ac2442/theme/classic.html#L97

应该是The Releases page is或者The Releases are
https://github.com/qkqpttgf/OneManager-php/blob/6eb6a826cf53782cff4a85fb60af182533ac2442/readme.md?plain=1#L5

**Comment by zzjjbb** [comment]
感觉英文介绍写得有点奇怪:joy:不过我英文也不太好，算了

**Comment by zzjjbb** [comment]
第一个好像是我看错了，结束符在很远的后面，抱歉！

**Comment by qkqpttgf** [comment]
> 感觉英文介绍写得有点奇怪joy不过我英文也不太好，算了 建议用Grammarly检查一下

我英文不好，大概意思就行hhh
