### ISSUE TITLE
大佬有更新播放器的计划吗

### ISSUE THREAD

**Issue by itsCheney** [qkqpttgf/OneManager-php#555]
很多编码的视频用旧版的dplayer播放黑屏，也没法看到视频内嵌的字幕。现在dplayer也有了1.26的版本，请问下大佬有没有更新计划

**Comment by qkqpttgf** [comment]
dp 1.26更新了啥 ？

**Comment by XILEJ** [comment]
推荐html视频播放器：https://github.com/DIYgod/DPlayer
html音频播放器：https://github.com/DIYgod/APlayer

**Comment by foxdodo** [comment]
> 很多编码的视频用旧版的dplayer播放黑屏，也没法看到视频内嵌的字幕。现在dplayer也有了1.26的版本，请问下大佬有没有更新计划

新版一样发黑鬼畜, 最实用的方法是调用外部播放器. mxplayer还没遇到过不能放的
