### ISSUE TITLE
游客上传目录无法复制出直链

### ISSUE THREAD

**Issue by Huiaei** [qkqpttgf/OneManager-php#558]
RT，后台已经更新到最新版本了。具体表现上传完成后点击复制链接没有反应。

浏览器：Firefox 97.0.2 64位
系统：Windows 10 IoT 企业版 LTSC 21H2

**Comment by qkqpttgf** [comment]
是用的默认主题吗？
刚刚修了，请更新。

**Comment by Huiaei** [comment]
> 是用的默认主题吗？ 刚刚修了，请更新。

是的，使用的默认主题。
已经更新测试了，可以正常复制链接了。谢谢！
