### ISSUE TITLE
【提问】网页在线播放器支持什么格式？

### ISSUE THREAD

**Issue by Huiaei** [qkqpttgf/OneManager-php#559]
RT，好像MKV格式放不出来，一直黑屏的，另外的MP4文件就没多久就可以了。不怎么清楚能支持什么协议。

**Comment by TW527E** [comment]
MKV 好像是因為 他可以把多種格式封裝在一起 所以他非常有可能因為封裝的格式不同 因而造成播放器無法播放
想是可能 有聲音 沒畫面   或   有畫面 沒聲音  甚至是  沒畫面 沒聲音
但大部分情況下 "通常" 還是正常的
除非就你跟我一樣很衰 
都拿到這種鬼檔案
(尤其是 HEVC 問題一大堆 因為他要錢 所以沒人想支持他

**Comment by TW527E** [comment]
我都儘量找mp4 的檔案
但是如果使用HEVC編碼格式的
就有可能會因為 瀏覽器、裝置、檔案大小 等等的變因
進而造成無法播放

如果你的電腦測試過可以播放
那就用吧

因為HEVC在同等畫質下 容量砍半
所以HEVC實際上更好

（轉換格式的話 你的內掛字幕 可能要想個辦法 把他用另外的方式 加進去

**Comment by Huiaei** [comment]
参考了https://caniuse.com/?search=video%20format
我的浏览器不支持HEVC，safari倒是能支持，但是我没有苹果设备。所以我得考虑把视频转码了
