### ISSUE TITLE
新建文件夹无法上传文件

### ISSUE THREAD

**Issue by worldlineme** [qkqpttgf/OneManager-php#56]
问题复现：
管理-新建-文件夹-新建-进入文件夹-上传文件->点上传 无反应

![2020-05-07-14-35-07](https://user-images.githubusercontent.com/64463113/81262292-259cee80-9070-11ea-9eb0-fdd75c623e24.gif)

我在heroku和vps部署都存在这个问题
我现在是先上传到首页，然后再等上传结束移动到目标文件夹，希望可以修复:memeda

**Comment by qkqpttgf** [comment]
空目录时js出错，已经修复，请更新
