### ISSUE TITLE
Vercel添加github git 后出现错误

### ISSUE THREAD

**Issue by XILEJ** [qkqpttgf/OneManager-php#560]
Vercel添加github git 后出现错误，一访问直接下载index，原因只是想添加个favicon.ico，想着用github git ，比较方便

**Comment by XILEJ** [comment]
大佬，怎么添加favicon.ico呀？

**Comment by TW527E** [comment]
> 大佬，怎么添加favicon.ico呀？

在 "平台設定" 選項 "customCss" 加上 `<link rel="icon" href="你的圖標連結" type="image/x-icon">`
(話說其實 customCss 和 customScript 這兩格放反也沒差w)

**Comment by XILEJ** [comment]
发现customCss添加<link rel="icon" href="你的圖標連結" type="image/x-icon">可以显示图标，而customScript不行

**Comment by TW527E** [comment]
那我就不清楚了 好像跟不同的主題有關係

**Comment by TW527E** [comment]
我知道了 預設主題的 customScript 是放在最下面的
但是我在用的 renexmoe 是放在上面的 (因為預設沒放w 所以別人修改的在customcss旁邊

**Comment by XILEJ** [comment]
好像跟主题无关

**Comment by XILEJ** [comment]
感兴趣，大佬可以看看
https://nicexl.glitch.me/
密码：Aa12345678

**Comment by TW527E** [comment]
![image](https://user-images.githubusercontent.com/37478187/158016760-dd5b7f96-54df-4f01-9820-4ebba44f0f4d.png)
這甚麼情況 沒有選主題

**Comment by TW527E** [comment]
> 感兴趣，大佬可以看看 https://nicexl.glitch.me/ 密码：Aa12345678

先加好友好了

**Comment by TW527E** [comment]
你要加好友嗎?w

**Comment by qkqpttgf** [comment]
1，不看readme，2，连favicon在正常网站上怎么工作的都不知道吗？？

浏览器打开一个网站，比如  exp.com ，之后会看head里有没有指定favicon，有就去找，如果没有指定，那么，浏览器就去尝试 exp.com/favicon.ico ， 
所以，你想要有favicon，目标就是 exp.com/favicon.ico 能正常下载就好了， 例如  https://herooneindex.herokuapp.com/favicon.ico .

**Comment by TW527E** [comment]
(不然我們這個Github打字很像智障

**Comment by XILEJ** [comment]
favicon这我当然知道，只是只能在customCss添加，不能再customScript使用，有些页面不显示，强迫症患者表示介绍不了

**Comment by qkqpttgf** [comment]
> favicon这我当然知道，只是只能在customCss添加，不能再customScript使用，有些页面不显示，强迫症患者表示介绍不了

谁让你在customCss里加了，我哪句话提到customCss了？？关它屁事

**Comment by TW527E** [comment]
他應該還照著我本來告訴他的方法w (我就怪
他沒理解你的做法w

**Comment by XILEJ** [comment]
理解大佬意思了，主要是网站有很多教程让设置customCss，但是favicon文件放在哪呢？

**Comment by TW527E** [comment]
> 理解大佬意思了，主要是网站有很多教程让设置customCss，但是favicon文件放在哪呢？

根目錄
網站在伺服器上的根目錄

**Comment by XILEJ** [comment]
![image](https://user-images.githubusercontent.com/75837117/158019115-f25866e3-651f-4df0-b4a3-256fed7ef335.png)
https://xilej.eu.org/onedrive/favicon.ico,显示为找到，但是可以下载

**Comment by XILEJ** [comment]
如果我用的是vercel，怎么添加favicon呢？

**Comment by qkqpttgf** [comment]
> 如果我用的是vercel，怎么添加favicon呢？

1，不看readme，2，连favicon在正常网站上怎么工作的都不知道
3，demo也不看

你打开 https://onemanager-php.vercel.app/ ，F12看一眼，啥都知道了

**Comment by XILEJ** [comment]
看到了<link rel="icon" href="/favicon.ico" type="image/x-icon">
    <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">

**Comment by XILEJ** [comment]
<link rel="icon" href="/favicon.ico" type="image/x-icon">
    <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">

**Comment by XILEJ** [comment]
`<link rel="icon" href="/favicon.ico" type="image/x-icon">
    <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">`

**Comment by XILEJ** [comment]
但是索引文件是部署和生成的，没法改<link，而我直接在根目录放favicon.ico，又无法显示出来。。

**Comment by XILEJ** [comment]
在 "平台設定" 選項 "customCss" 加上 <link rel="icon" href="你的圖標連結" type="image/x-icon">,重新部署一遍后这个方法成功，谢谢两位大佬。
（虽然还没有领悟qkqpttgf大佬的意思）

**Comment by qkqpttgf** [comment]
所以我说了几遍了，你还是不看readme呗？？？

功能性文件
favicon.ico
放在第一个盘的显示目录（不一定是onedrive根目录）。

真就看不到？？我强调2遍readme了都不看！！

**Comment by XILEJ** [comment]
> 所以我说了几遍了，你还是不看readme呗???
> 
> 功能性文件 favicon.ico 放在第一个盘的显示目录（不一定是onedrive根目录）。
> 
> 真就看不到？？我强调2遍readme了都不看！！

直接上传favicon.ico到第一个盘的显示目录没用，一访问就下载，readme看了没明白，我是通过添加css添加的https://panshe.vercel.app/

**Comment by qkqpttgf** [comment]
> > 所以我说了几遍了，你还是不看readme呗???
> > 功能性文件 favicon.ico 放在第一个盘的显示目录（不一定是onedrive根目录）。
> > 真就看不到？？我强调2遍readme了都不看！！
> 
> 直接上传favicon.ico到第一个盘的显示目录没用，一访问就下载，readme看了没明白，我是通过添加css添加的https://panshe.vercel.app/

#561 ，啥叫没用？肯定有用，你去看看这个。
一访问就下载，肯定啊，你访问不下载浏览器怎么下载显示出来。

**Comment by XILEJ** [comment]
@qkqpttgf 大佬可以了，之前我用的是vercel可能与缓存有关系，不显示，现在用glitch（https://nicexl.glitch.me/），按照你的方法可行。（其实之前我也看了readme，试了你说的方法，可就是不成功）

**Comment by qkqpttgf** [comment]
好耶
