### ISSUE TITLE
favicon doesn't work right

### ISSUE THREAD

**Issue by liblaf** [qkqpttgf/OneManager-php#561]
After putting my `favicon.ico` under `/public/`, I tested that `xxx.com/favicon.ico` can be accessed (directly downloaded), but the website displays no favicon.
The theme I'm using is `renexmoe.html`.

**Comment by liblaf** [comment]
My `favicon.ico` is generated by https://favicon.io/

**Comment by qkqpttgf** [comment]
where is your "/public/"?? 
favicon.ico should put in your onedrive.
it work fine in my demo when using renexmoe.

**Comment by liblaf** [comment]
`/public/` is my `public_path` setup option.

**Comment by liblaf** [comment]
see my deployment [here](cloud.liblaf.top)

**Comment by liblaf** [comment]
I'm terribly sorry to bother you.
Firefox was able to display the favicon, but Edge can't?!
This seems to be a problem with Edge.

**Comment by liblaf** [comment]
Safari didn't show the favicon as well. >_<

**Comment by liblaf** [comment]
My apologies once again.
I finally figured out that the very reason I couldn't see my favicon was that I didn't clear my browser's cache. 😓
