### ISSUE TITLE
可否建议修改jsd的地址

### ISSUE THREAD

**Issue by W4J1e** [qkqpttgf/OneManager-php#563]
开发者您好，
    cdn.jsdelivr.net 在国内个别省市遭到不同程度的DNS污染，而目前fastly.jsdelivr.net正常。貌似fork更新触发的部署不会升级？（因为我一直用的pull来自动拉取更新，但是即便如此更新之后在后台还是能看到版本更新提示）所以自行修改了还是得等您这边发版。
    因此请问能否考虑修改cdn的地址。

**Comment by qkqpttgf** [comment]
jsd我这边已经不在用了呀，现在都用的unpkg.com。
不知道你的fork跟pull怎么做的，你部署在哪里的，如果可以的话，直接在后台点更新。

**Comment by W4J1e** [comment]
@qkqpttgf 抱歉，我之前没仔细看。我用的github那个叫pull的应用拉取更新的，部署在vercel。刚才去看了一下，是主题renexmoe引用的jsd。
我此前把这个主题下载下来修改替换成自己反代的jsd之后出现过无法登陆的问题，就是点击登陆不会跳转到程序本身的登录框，是主题弹出的登录框，然后就登陆不上。
我现在去fork一份这个主题替换一下链接再试试，谢谢啦。

**Comment by W4J1e** [comment]
@qkqpttgf 问题出现啦，我在自定义主题里面填入替换地址后的主题链接，显示无异常，登陆还是主题自带的登录框，输入密码登陆后会刷新网页，然后仍旧是未登录状态，控制台无报错。是不是程序自带的这个主题您
pan.7in.ren

**Comment by qkqpttgf** [comment]
vercel的话，直接拿github的过去用会出问题哦！当场不能用

**Comment by W4J1e** [comment]
我明白了，仔细看了一下您提交的更新在vercel那边是部署成了预览而非生产，所以git这边的提交通常是不会影响到按照文档里的方式部署到vercel的。
