### ISSUE TITLE
想要通过 Github Pages 部署前端，请问对应您的安装脚本，静态index.html怎么写

### ISSUE THREAD

**Issue by tingyue-wu** [qkqpttgf/OneManager-php#565]
想要通过 Github Pages 部署前端，这样可以用Github的域名访问，短一些，
国内绑定域名需要备案，太麻烦了。
请问对应您的安装脚本，静态index.html怎么写
方便的话能上传一个写好的index.html文件吗？

**Comment by qkqpttgf** [comment]
前后分离太高级了…我不会，
所以，没有前端。

**Comment by tingyue-wu** [comment]
[FODI-FRONT-END-master.zip](https://github.com/qkqpttgf/OneManager-php/files/8310517/FODI-FRONT-END-master.zip)
这是别人写的静态网页，就是主题太丑了。
