### ISSUE TITLE
能否做一个调用本地播放器的按钮

### ISSUE THREAD

**Issue by foxdodo** [qkqpttgf/OneManager-php#567]
能否做一个调用本地播放器的按钮, 就像alist那样在播放页面下方增加几个调用potplayer, mxplayer pro播放器按钮? 也免得折腾在线播放器了

**Comment by TW527E** [comment]
算推銷也不算推銷?

我的主題可以w
https://github.com/TW527E/renexmoe-tw527e-edition

**Comment by TW527E** [comment]
算是推銷嗎? 也不算吧w

我的主題可以呼叫本地播放器 (大概w
https://github.com/TW527E/renexmoe-tw527e-edition

**Comment by foxdodo** [comment]
> 算是推銷嗎? 也不算吧w
> 
> 我的主題可以呼叫本地播放器 (大概w https://github.com/TW527E/renexmoe-tw527e-edition

大佬你这好像没有适配手机端，这侧边栏设计用起来挺方便

**Comment by TW527E** [comment]
> > 算是推銷嗎? 也不算吧w
> > 我的主題可以呼叫本地播放器 (大概w https://github.com/TW527E/renexmoe-tw527e-edition
> 
> 大佬你这好像没有适配手机端，这侧边栏设计用起来挺方便

沒有適配手機端的部分是? 側欄顏色部分嗎? 或是哪個部分?w

**Comment by foxdodo** [comment]
> 喔抱歉ww 我看到了 我修復一下w

感谢大佬, 大陆这里打开jsdelivr gstatic的资源有点难受🤣

**Comment by TW527E** [comment]
那該怎麼改善ww

**Comment by foxdodo** [comment]
> 那該怎麼改善ww

没事, 应该是我本地网络问题

**Comment by GreenTeodoro839** [comment]
> 那該怎麼改善ww

调用jsdelivr时，网址开头的cdn改成fastly，cdn那个在大陆被污染了

**Comment by TW527E** [comment]
(我的主題早就改了w
