### ISSUE TITLE
油客上传后缀会自动加上scfupload?preview

### ISSUE THREAD

**Issue by Ks2s** [qkqpttgf/OneManager-php#57]
https://pan.saopan.tk/hk-disk//Images/q.JPG.scfupload?preview  变成这样了
你试试吧 
管理员上传是正常的
![a](https://user-images.githubusercontent.com/54312049/81477318-c692d180-9249-11ea-9ef7-c17ece2e4f48.JPG)

**Comment by qkqpttgf** [comment]
换主题

**Comment by Ks2s** [comment]
现在更新好了  谢谢
