### ISSUE TITLE
文件预览有问题

### ISSUE THREAD

**Issue by EXStevens** [qkqpttgf/OneManager-php#571]
游客模式（主题：Onedrive-dev.html）除图片以外预览无法显示
管理模式下视频预览无法显示

**Comment by qkqpttgf** [comment]
这个主题，不继续写了

**Comment by EXStevens** [comment]
@qkqpttgf 但是默认主题无法播放视频是什么鬼呀

**Comment by qkqpttgf** [comment]
> @qkqpttgf 但是默认主题无法播放视频是什么鬼呀

那就是格式或码率不支持了

**Comment by EXStevens** [comment]
> > @qkqpttgf 但是默认主题无法播放视频是什么鬼呀
> 
> 那就是格式或码率不支持了

连播放器框架都没显示，任何视频都是，包括旧版本可播放的

**Comment by qkqpttgf** [comment]
播放器没有动过，以我demo为准，你F12看看加载了没有。

**Comment by EXStevens** [comment]
是以前Jsdelivr被污染的问题，换cdnjs.cloudflare.com或者fastly.jsdelivr.com就解决了。
