### ISSUE TITLE
小建议，能支持自定义把目录单独做寿命长一点的缓存吗？

### ISSUE THREAD

**Issue by haoduck** [qkqpttgf/OneManager-php#572]
![QQ图片20220404044453](https://user-images.githubusercontent.com/56804964/161447868-b8b82380-8fbd-4640-9e79-2f009ab62a48.png)

像远古的OneIndex这样是非常好的，目录做了1天的缓存，减少了很多api调用

OneDrive的文件比较多的话，很容易就API超限了。我的就是文件比较多的，使用了自己在Azure注册的应用API，观察了我的统计记录，出现429状态码的频率高达三分之一，可以说是影响挺大了。

![QQ截图20220404044707](https://user-images.githubusercontent.com/56804964/161447941-750b8e5d-f48e-4525-9a24-9ef8d42fa474.png)

其实在很久以前就想提了，根据习惯搜了一下Issues，发现开发者大佬已经说过了，表示这个项目主要是适配Serverless环境，不做这个打算。

我觉得这个挺重要的，不知道能不能考虑一下做一下这个缓存呢？

**Comment by qkqpttgf** [comment]
嗯，不考虑，特别我这边是获取目录的同时 获取文件信息，两个是缓存在一起的。
[你可以魔改]
