### ISSUE TITLE
加密文件夹时出错应该如何处理

### ISSUE THREAD

**Issue by syxf** [qkqpttgf/OneManager-php#573]
作者你好，请问加密文件夹时一直出错，应该如何处理？
浏览器弹窗错误信息如下：
400
{"error":{"code":"invalidRequest","message":"A potentially dangerous Request.Path value was detected from the client (*).","innerError":{"code":"badArgument","date":"2022-04-05T14:55:05","request-id":"91e13ff3-cbaf-451f-9e9b-7b4c61137b1d","client-request-id":"91e13ff3-cbaf-451f-9e9b-7b4c61137b1d"}}}

**Comment by syxf** [comment]
已解决。可能是我设置的passfile有问题，换了个名字就好了

**Comment by qkqpttgf** [comment]
你设置了什么 dangerous 的名字？能说说吗

**Comment by syxf** [comment]
> 

*****.***
