### ISSUE TITLE
添加世纪互联显示onemanager is disable

### ISSUE THREAD

**Issue by coppea** [qkqpttgf/OneManager-php#575]
是否已经不可以添加世纪互联了,我使用的是同济大学校友版,无api

**Comment by coppea** [comment]
Request Id: b3dbdb6a-5cd0-416b-8323-76587f48ae01
Correlation Id: 148bf728-080b-4b0b-985a-95d9fe2873b0
Timestamp: 2022-04-10T04:37:46Z
Message: AADSTS700016: Application with identifier '04c3ca0b-8d07-4773-85ad-98b037d25631' was not found in the directory '同济大学'. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You may have sent your authentication request to the wrong tenant.

**Comment by GreenTeodoro839** [comment]
世纪互联sust，siit，同济，所有api都已经禁用，以后只能用官方客户端

**Comment by coppea** [comment]
> 世纪互联sust，siit，同济，所有api都已经禁用，以后只能用官方客户端

是所有的世纪互联都不能使用api了吗，还是单单同济的

**Comment by Silentely** [comment]
> > 世纪互联sust，siit，同济，所有api都已经禁用，以后只能用官方客户端
> 
> 是所有的世纪互联都不能使用api了吗，还是单单同济的

国内高校用世纪互联的 api权限都被撤了，除非你是用商业版用户

**Comment by qkqpttgf** [comment]
首先，继续强调，API是API（请去百度什么叫API），自建的client是client，API是接口，你建不了的，你能建的只是client。

然后，各高校的世纪大概都删除或禁用了AAD列表里的client，你自己拿空全局新建一个client的话，授权页会提示你要管理员允许，说明，API没有禁用，只是client被禁用了而已。

**Comment by abiglee** [comment]
> 首先，继续强调，API是API（请去百度什么叫API），自建的client是client，API是接口，你建不了的，你能建的只是client。
> 
> 然后，各高校的世纪大概都删除或禁用了AAD列表里的client，你自己拿空全局新建一个client的话，授权页会提示你要管理员允许，说明，API没有禁用，只是client被禁用了而已。

原来是这样，我折腾了一天没成功哈哈
