### ISSUE TITLE
请问如何不使用网页上传，有API可以使用吗

### ISSUE THREAD

**Issue by wyh137815840** [qkqpttgf/OneManager-php#576]
我想搭建一个图床，我有写一个爬虫，请问怎么使用API上传文件呢

**Comment by qkqpttgf** [comment]
弄了个小文件的，
`curl -X POST "url?action=upsmallfile" -F "file1=@21.png"`
这是上传到游客上传目录，
如果要上传到其它目录，请自己加上Cookie才能上传，可以参照adminpass2cookie函数计算cookie

**Comment by TW527E** [comment]
老闆發的圖
![photo_2022-04-05_15-07-22](https://user-images.githubusercontent.com/37478187/163659185-d1c97286-bf2b-4127-aa5b-79cf3167b01e.jpg)

**Comment by wyh137815840** [comment]
> 弄了个小文件的，
> `curl -X POST "url?action=upsmallfile" -F "file1=@21.png"`
> 这是上传到游客上传目录，
> 如果要上传到其它目录，请自己加上Cookie才能上传，可以参照adminpass2cookie函数计算cookie

作者你好，我去看了这个函数和他的调用
调用中`$admincookie = adminpass2cookie('admin', getConfig('admin'), $timestamp, $randnum);`给了4个参数，
但是定义中`function adminpass2cookie($name, $pass, $timestamp)
{
    return md5($name . ':' . md5($pass) . '@' . $timestamp) . "(" . $timestamp . ")";
}`但是只定义了3个入参，我有点没看懂，可以给我这个小白讲解一下吗

**Comment by wyh137815840** [comment]
> 老闆發的圖
> ![photo_2022-04-05_15-07-22](https://user-images.githubusercontent.com/37478187/163659185-d1c97286-bf2b-4127-aa5b-79cf3167b01e.jpg)

你好，我参照adminpass2cookie函数，用Python写了一个函数计算cookie，post后并没有返回你图中的json，而是返回给我了这个目录下admin的html，请问可否帮我看看问题出在哪吗？

管理员页面：
<img width="1184" alt="截屏2022-04-16 12 47 07" src="https://user-images.githubusercontent.com/48979107/163661849-dd3a0298-bff4-4c5c-a0a0-e93ae2bef357.png">
返回的html页面：
<img width="1204" alt="截屏2022-04-16 12 47 28" src="https://user-images.githubusercontent.com/48979107/163661861-b30bdfc3-ee3b-44b3-9705-33ea45cd7010.png">
游客的页面：
<img width="1169" alt="截屏2022-04-16 12 48 13" src="https://user-images.githubusercontent.com/48979107/163661885-ab3295de-b96f-4832-a6ce-9a7ceb235bf0.png">

Python代码：
`def md5(string):`
    `hl = hashlib.md5()`
    `hl.update((str(string)).encode(encoding='utf-8'))`
    `return  hl.hexdigest()`
`def adminpass2cookie(adminName,passWord,timesStamp):`
    `md5P=md5(passWord)`
    `return md5(adminName+':'+md5P+'@'+str(timesStamp))+'('+str(timesStamp)+')'`
`if __name__ == '__main__':`
    `timestamp=int(str(time.time()).split('.')[0])+7*24*60*60`
    `print(timestamp)`
    `cookie=adminpass2cookie('admin','137815840',str(timestamp))`
    `respones=requests.post(`
       ` 'https://onemanagerawyh-wyh137815840.vercel.app/downloads/?action=upbigfile',files={'file1':'@/Users/zerorock/PycharmProjects/18Comic/38re.png'},headers={`
           ` 'cookie':'admin='+cookie+'; timezone=8'`
        `}`
    `)`
    `print(cookie)`
    `print(respones.text)`

**Comment by qkqpttgf** [comment]
时间戳会被对比当前时间的，你注意一下时间戳是什么时候的。
你从登录后的网页查看admin的cookie看看能不能算出来。

你代码居然是up BIG file???

**Comment by wyh137815840** [comment]
> 时间戳会被对比当前时间的，你注意一下时间戳是什么时候的。 你从登录后的网页查看admin的cookie看看能不能算出来。
> 
> 你代码居然是up BIG file???

bigfile是因为smallfile没成功我乱尝试的。我按照你截图中的curl写法请求了一次，依然不行，返回给我一个html。cookie是我从网页上复制下来的
<img width="574" alt="截屏2022-04-21 10 13 37" src="https://user-images.githubusercontent.com/48979107/164358097-6f6127d8-742b-4949-a2f3-1503585291f3.png">

**Comment by qkqpttgf** [comment]
小声问一句，你有更新？

**Comment by wyh137815840** [comment]
> 小声问一句，你有更新？

是的我没有更新，更新之后OK了，多谢多谢~

**Comment by qkqpttgf** [comment]
TM专门给你add了一个commit，你都不更新，看不到的吗

**Comment by downloadvideo** [comment]
Hi qkqpttgf 
Can you guide me to upload it for free, but the file name is still the original default name, where to fix it? skip md5

**Comment by qkqpttgf** [comment]
> Hi qkqpttgf Can you guide me to upload it for free, but the file name is still the original default name, where to fix it? skip md5

see the black picture
