### ISSUE TITLE
是否可以增加rss订阅生成的功能？

### ISSUE THREAD

**Issue by wade1998** [qkqpttgf/OneManager-php#579]
譬如：http://myrss.nu/drama ，这种带有层级目录的rss资源订阅源，尤其其中的音视频，可以供媒体订阅客户端方便地食用，譬如 kodi

**Comment by qkqpttgf** [comment]
我不会弄！

**Comment by ZKsolar** [comment]
> 譬如：http://myrss.nu/drama ，这种带有层级目录的rss资源订阅源，尤其其中的音视频，可以供媒体订阅客户端方便地食用，譬如 kodi

提供一个思路，给某个文件夹一个上传文件的权限，然后在这个文件夹里用户可以通过某个文本文件填入邮箱和订阅文件夹的字符串，然后你设置一个批处理程序，将盘子挂在本地，每次上传完成时自动触发这个批处理，检查这个存有用户邮箱和订阅文件夹的文本文件，若和本次上传完成的文件一致，则通过邮箱提醒用户，具体的细节自己琢磨吧没学过php我啥也不会，
