### ISSUE TITLE
用vercel部署的现在 404

### ISSUE THREAD

**Issue by xlenco** [qkqpttgf/OneManager-php#580]
问题站点:https://panta.eu.org/
![Screenshot_20220428_221608_com hiker youtoo](https://user-images.githubusercontent.com/75837117/165773155-881f0c44-e0a4-4c9d-934a-dcb33336814a.jpg)
部署方式vercel
什么也没干就遇到这种情况了。

**Comment by xilej** [comment]
vercel部署没有git库啊！

**Comment by loadingfd** [comment]
+1也遇到问题了

**Comment by foxdodo** [comment]
刚才试了下可以访问, vercel从休眠到启动很慢而已

**Comment by YidaozhanYa** [comment]
并且我无法部署到 Vercel，提示大小超出。
![图片](https://user-images.githubusercontent.com/73830635/165899082-ce2f9e9a-d421-436e-89ce-07bf78905d9c.png)

别人就没有这个问题。

**Comment by YidaozhanYa** [comment]
![图片](https://user-images.githubusercontent.com/73830635/166089736-55f4a4a6-f4a5-47aa-af92-7b54f555fe82.png)

**Comment by Dedicatus5457** [comment]
Vercel又整的什么烂活

**Comment by like977** [comment]
> 问题站点:https://panta.eu.org/ ![Screenshot_20220428_221608_com hiker youtoo](https://user-images.githubusercontent.com/75837117/165773155-881f0c44-e0a4-4c9d-934a-dcb33336814a.jpg) 部署方式vercel 什么也没干就遇到这种情况了。

Your site has   been displayed normally ,how do you fix this problem?

**Comment by Dedicatus5457** [comment]
> > 问题站点:https://panta.eu.org/ ![Screenshot_20220428_221608_com hiker youtoo](https://user-images.githubusercontent.com/75837117/165773155-881f0c44-e0a4-4c9d-934a-dcb33336814a.jpg) 部署方式vercel 什么也没干就遇到这种情况了。
> 
> Your site has been displayed normally ,how do you fix this problem?

找客服，不然还能咋办，vercel的锅

**Comment by TW527E** [comment]
(直接把舊站點刪了 創一個新的 解決

**Comment by BA7JCM** [comment]
现在部署点开始安装，输入token和密码之后一直显示Another building is in progress.

**Comment by qkqpttgf** [comment]
> 现在用默认的项目名部署点开始安装，输入token和密码之后一直显示Another building is in progress.，改个别的名字就正常

那你去vercel看看有没有deployment嘛~

**Comment by BA7JCM** [comment]
> > 现在用默认的项目名部署点开始安装，输入token和密码之后一直显示Another building is in progress.，改个别的名字就正常
> 
> 那你去vercel看看有没有deployment嘛~

看了，啥也没有，换个别的项目名就没这个问题

**Comment by qkqpttgf** [comment]
> 看了，除了最开始那个开始安装的页面以外啥也没有，等了几十分钟都还这样，换个别的项目名就没这个问题

呃，我也是用的这个呀，没有问题的

**Comment by BA7JCM** [comment]
> > 看了，除了最开始那个开始安装的页面以外啥也没有，等了几十分钟都还这样，换个别的项目名就没这个问题
> 
> 呃，我也是用的这个呀，没有问题的

现在变成“bad_request
Invalid request: `project` should be string.”了

**Comment by BA7JCM** [comment]
> > 看了，除了最开始那个开始安装的页面以外啥也没有，等了几十分钟都还这样，换个别的项目名就没这个问题
> 
> 呃，我也是用的这个呀，没有问题的

域名和token我在tg上面私聊发你了

**Comment by like977** [comment]
> > > 问题站点:https://panta.eu.org/ ![Screenshot_20220428_221608_com hiker youtoo](https://user-images.githubusercontent.com/75837117/165773155-881f0c44-e0a4-4c9d-934a-dcb33336814a.jpg) 部署方式vercel 什么也没干就遇到这种情况了。
> > 
> > Your site has been displayed normally ,how do you fix this problem?
> 
> 找客服，不然还能咋办，vercel的锅
How can I contact his official customer service?

**Comment by xiao811** [comment]
vercel部署没有git库

**Comment by leiziwu33** [comment]
我也是这个问题，有没有解决的？

**Comment by qkqpttgf** [comment]
> 我也是这个问题，有没有解决的？

没有问题啊

**Comment by move-brain** [comment]
为啥我部署node服务一直404，这会是什么原因造成 ？

**Comment by qkqpttgf** [comment]
> 为啥我部署node服务一直404，这会是什么原因造成 ？

你这样说真的不知道啥情况

**Comment by TW527E** [comment]
哈哈哈哈哈😂 你至少也要提供你伺服器的環境 日誌文件 等等的吧🤣 不然神來了都不知道是什麼問題On Apr 16, 2024, at 09:07, qkqpttgf ***@***.***> wrote:

为啥我部署node服务一直404，这会是什么原因造成 ？

你这样说真的不知道啥情况
