### ISSUE TITLE
视频无法播放

### ISSUE THREAD

**Issue by 201853910** [qkqpttgf/OneManager-php#581]
当上传一个HEVC(H.265)编码格式的视频时，会出现无法播放的问题，望修复一下

**Comment by TW527E** [comment]
H.265 無法播放之問題，是因為瀏覽器不支援，但是使用本地播放器或是Safari瀏覽器時，則非常正常，則是因為播放器及Safari瀏覽器支持H.265編碼格式，因此此問題無法使用正常方式解決，如非要解決此問題，主題檔案將會非常複雜，且支持在普通瀏覽器播放H.265之播放器非常稀少，所以還是老老實實的使用H.264吧w

**Comment by qkqpttgf** [comment]
我不会！（理直气壮
