### ISSUE TITLE
能否修复一下排序问题

### ISSUE THREAD

**Issue by 201853910** [qkqpttgf/OneManager-php#582]
文件列表，排序是从10开始的。
例如我有一堆文件，开始编号是1，2，3，...，99，100，101
它会将10放最前面，然后是100，101，...，11，110，111
当到了199的时候，下面的文件是20，200，201，...，209，21，210，211

**Comment by qkqpttgf** [comment]
微软就是这么排的，给过来就是这样的，我也没办法。
