### ISSUE TITLE
#Vercel install 404

### ISSUE THREAD

**Issue by like977** [qkqpttgf/OneManager-php#584]

**Comment by like977** [comment]
https://onemanager-php.vercel.app/ 无法打开

**Comment by Dedicatus5457** [comment]
Please see #580 Thanks!

**Comment by qkqpttgf** [comment]
> https://onemanager-php.vercel.app/ 无法打开

好气！

**Comment by Dedicatus5457** [comment]
![Uploading IMG_20220510_130405.jpg…]()
