### ISSUE TITLE
阿里云盘下载失败，请问怎么办

### ISSUE THREAD

**Issue by holyget** [qkqpttgf/OneManager-php#587]
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>InvalidArgument</Code>
<Message>At least one of AdditionalHeaders is not in request headers.</Message>
<RequestId>62805E853A74A63731ADB41A</RequestId>
<HostId>bj29.cn-beijing.data.alicloudccp.com</HostId>
</Error>
data:text/css,html,body,a,div,p,img,textarea{-webkit-touch-callout:text !important;-webkit-user-select:text !important;user-select:text !important;}

**Comment by qkqpttgf** [comment]
#577 ，
#549 ，
#476 ，
真就提issue之前啥也不搜一下？？比我还懒。
