### ISSUE TITLE
用IDM下载提示要登录是什么情况。。

### ISSUE THREAD

**Issue by nodesire7** [qkqpttgf/OneManager-php#588]
有时候文件大需要下很长时间的时候会提示需要登录。。

**Comment by qkqpttgf** [comment]
access token有效期1小时，如果超过了，这个链接就没用了，就要你登录了
浏览器与下载器，都 只保存跳转后的链接，
推荐用`wget -c "url"`，这样可以续下。

**Comment by nodesire7** [comment]
> access token有效期1小时，如果超过了，这个链接就没用了，就要你登录了 浏览器与下载器，都 只保存跳转后的链接， 推荐用`wget -c "url"`，这样可以续下。

这个代码怎么用？没办法解决这个问题嘛…

**Comment by qkqpttgf** [comment]
你不知道 什么叫  wget  我也就没办法了……

**Comment by nodesire7** [comment]
> 你不知道 什么叫 wget 我也就没办法了……

这个不是Linux下用的吗。。Win怎么弄呢

**Comment by nodesire7** [comment]
今天又有新问题了 后台进不去提示js未加载。。
![image](https://user-images.githubusercontent.com/63827263/168630213-50c54497-7c0c-4ab9-a31d-e6ab6f86d054.png)

**Comment by qkqpttgf** [comment]
更新……
