### ISSUE TITLE
onemanager相关按钮都没了，只剩下文件目录结构了

### ISSUE THREAD

**Issue by zjunhe** [qkqpttgf/OneManager-php#589]
我好像是点了退出还是什么按钮，点完之后，onemanager相关的按钮就全没了，只剩下最基础的文件目录结构了。请问这个如何解决？
![1652673033(1)](https://user-images.githubusercontent.com/49190084/168516799-787f9752-bc85-46e1-8701-ecca23d5b556.png)

**Comment by qkqpttgf** [comment]
(我很无语)
这是主题，你自己设置的。
请在url后面加上`?login=admin`登录。
