### ISSUE TITLE
部署出错

### ISSUE THREAD

**Issue by woshichenghaibo** [qkqpttgf/OneManager-php#591]
ERROR
{"error":{"code":"not_found","message":"Deployment not found"}}https://api.vercel.com/v13/deployments/dpl_931CR42Feu5Buup7m5LHJVjtUXxR

打开后页面是空白的，后台都能设置

**Comment by qkqpttgf** [comment]
最近vercel有在调整，可能它调用的哪里不对，你多设置几次试试
等稳定了我找找原因

**Comment by woshichenghaibo** [comment]
> 

测试了好几次，都是同样错误

**Comment by avenir2027** [comment]
Now the prompt error is as follows:
400
bad_request
Project name contains invalid characters. Only lower case alphanumeric characters and hyphens are allowed.

**Comment by qkqpttgf** [comment]
> Now the prompt error is as follows: 400 bad_request Project name contains invalid characters. Only lower case alphanumeric characters and hyphens are allowed.

why ask me?

**Comment by woshichenghaibo** [comment]
查找到原因了吗？我这边还是这个服务器速度快一些

另外，怎么为某些目录设置密码哈？



> 最近vercel有在调整，可能它调用的哪里不对，你多设置几次试试 等稳定了我找找原因
