### ISSUE TITLE
游客上传目录不读取head.md等

### ISSUE THREAD

**Issue by Kevin-2106** [qkqpttgf/OneManager-php#597]
当**游客**访问上传目录时，由于无法看到目录下文件，head.md也无法被读取。
希望在游客上传目录也能使用head.md等为游客添加说明。

**Comment by qkqpttgf** [comment]
是的，游客上传目录，程序直接没去微软问目录结构，所以不知道有没有head与readme。
要加一堆if去问微软要，太麻烦了……

**Comment by Kevin-2106** [comment]
那如果在平台变量里加一个 上传路径独立的head和readme设置
可行不

**Comment by qkqpttgf** [comment]
> 



> 那如果在平台变量里加一个 上传路径独立的head和readme设置 可行不

已经有全局的了……
如果只要这个目录的，你可以自行魔改~

**Comment by Kevin-2106** [comment]
寄 php和html都不会（笑
