### ISSUE TITLE
jsdelivr炸了

### ISSUE THREAD

**Issue by BlueSky01st** [qkqpttgf/OneManager-php#598]
sha1.js加载不出来，登录不上去

**Comment by qkqpttgf** [comment]
你都知道原因了，应该已经知道怎么解决了吧……
另外，请更新~

**Comment by BlueSky01st** [comment]
就是因为不能登录才无法更新啊

**Comment by BlueSky01st** [comment]
可以试试改成
[https://github.elemecdn.com/js-sha1@0.6.0/src/sha1.js](https://github.elemecdn.com/js-sha1@0.6.0/src/sha1.js)

**Comment by qkqpttgf** [comment]
> 就是因为不能登录才无法更新啊

你都知道是【jsd炸了】，你居然不知道怎么解决？？？？？？？？？？？？

**Comment by BlueSky01st** [comment]
我fq过去，登录了，发现是最新的版本……
还有，你依然是用的jsdelivr加载资源
![图片](https://user-images.githubusercontent.com/57856874/172300755-0123632c-9aa7-40ab-bc89-de241fcf8563.png)
我直接fork了一份自己改了

**Comment by DreamOfIce** [comment]
可以看一下这个 https://github.com/PipecraftNet/jsdelivr-auto-fallback
加到自己的网站上或使用浏览器脚本

**Comment by bf179** [comment]
感谢大佬的fork

**Comment by mango57777** [comment]
可以试试在网站目录运行一下这个 `sed -i "s#cdn.jsdelivr.net#fastly.jsdelivr.net#g" $(grep -rn 'cdn.jsdelivr.net' | awk '{print $1}' | awk -F: '{print $1}')`

**Comment by qkqpttgf** [comment]
> 我fq过去，登录了，发现是最新的版本…… 还有，你依然是用的jsdelivr加载资源 ![图片](https://user-images.githubusercontent.com/57856874/172300942-42e522cc-ea32-4dae-9491-b1f5fa17caf3.png)
> 
> 我直接fork了一份自己改了

不是，我看了一眼我github的最新版本，明明是unpkg的，说明你的明明不是最新版本，请更新，谢谢。
