### ISSUE TITLE
建议一个新主题

### ISSUE THREAD

**Issue by cworld1** [qkqpttgf/OneManager-php#6]
只是觉得界面一般般，所以我写了个主题，供大佬参考制作。
https://gitee.com/cworld1/usercss/raw/master/pure_onedrive/onedrive.css

**Comment by qkqpttgf** [comment]
界面我的痛。
你这个怎么用，有示例吗

**Comment by wolf03** [comment]
就一串CSS代码，我写在我博客里了，文末处 https://blog.cworld.top/onedrive-cfs
![image](https://user-images.githubusercontent.com/37377181/74605243-4ef94e80-5101-11ea-9aff-6cbeeeeb813c.png)
但是似乎设置的界面没有调用这个主题，所以没生效，但那不过是点瑕疵罢了
建议重新整合一下重新做个新主题
