### ISSUE TITLE
chrome内核浏览器播放mp4黑屏

### ISSUE THREAD

**Issue by lynnhuel** [qkqpttgf/OneManager-php#60]
用chrome播放，只有声音，没有画面，用手机自带浏览器没问题。

**Comment by qkqpttgf** [comment]
可能你的视频格式不一样，265什么的，你看看我demo里面的？

**Comment by lynnhuel** [comment]
可能是我的mp4格式比较特殊？先这样吧，有空我换个播放器插件试试
