### ISSUE TITLE
希望能够增加一个功能“指定文件夹内的文件只能在线查看不能下载”

### ISSUE THREAD

**Issue by tingyue-wu** [qkqpttgf/OneManager-php#601]
希望能够增加一个功能“指定文件夹内的文件只能在线查看不能下载”

**Comment by qkqpttgf** [comment]
？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？
能“预览图片或视频”说明已经下载到人家电脑了……

**Comment by tingyue-wu** [comment]
> ？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？ 能“预览图片或视频”说明已经下载到人家电脑了……

officer文件呢，起码隐藏那个地址和下载按钮也好。

**Comment by alimalls** [comment]
> ？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？ 能“预览图片或视频”说明已经下载到人家电脑了……



> ？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？ 能“预览图片或视频”说明已经下载到人家电脑了……

其实我的意思，是希望只提供一个list列表，不能打开，也不能下载。

**Comment by qkqpttgf** [comment]
> > ？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？ 能“预览图片或视频”说明已经下载到人家电脑了……
> 
> 其实我的意思，是希望只提供一个list列表，不能打开，也不能下载。

那你其实只用做个excel然后给别人【看】，只能看不能摸那种，哦，excel不好展示，用md吧，其实用不上这个程序……
