### ISSUE TITLE
图床生成的链接问题

### ISSUE THREAD

**Issue by yintao-xu** [qkqpttgf/OneManager-php#605]
图床生成的链接复制到浏览器是直接下载的，能不能改成预览图片。
我试过在链接后面加?preview，可以预览了，但是不能对图片进行放大缩小，每次分享也比较麻烦。

**Comment by woshichenghaibo** [comment]
不如直接提供预览功能多好，就在你下载之前

**Comment by qkqpttgf** [comment]
302跳转后，都是文件，并没有.jpg的东西让浏览器以图片方式浏览。
你可以在盘内设置，开小文件中转，这样应该就能了。

**Comment by qkqpttgf** [comment]
302跳转后，都是文件，并没有.jpg的东西让浏览器以图片方式浏览。
你可以在盘内设置，开小文件中转，这样应该就能了。
