### ISSUE TITLE
爆出木马问题

### ISSUE THREAD

**Issue by MuziShaoxing** [qkqpttgf/OneManager-php#606]
这是我部署在腾讯云上的云盘系统，但是近期出现检测木马出现 请帮我看下是被入侵还是软件正常呢？
以下是源文件-截图
![03:56-ZSIj2Z](https://gcore.jsdelivr.net/gh/muzishaoxing/picture@main/source/shaoxing/20220719/03:56-ZSIj2Z.png)

被检测木马源文件：https://xinglu.xyz/s/zAt0

**Comment by qkqpttgf** [comment]
应该是误报
跟我github文件相比，就是版本旧一点
应该是passthru这个函数，能调用系统命令，所以认为这是危险行为。

**Comment by MuziShaoxing** [comment]
原来如此，非常感谢您的帮助，我已经进行升级操作看看近期还有没

**Comment by qkqpttgf** [comment]
> 原来如此，非常感谢您的帮助，我已经进行升级操作看看近期还有没

升级了这个函数还是在的，估计还是要报~
