### ISSUE TITLE
存在漏洞？网站被黑

### ISSUE THREAD

**Issue by gouku** [qkqpttgf/OneManager-php#607]
这几天突然无法登录，提示密码错误，查看了配置之后发现内容被篡改：

<img width="149" alt="image" src="https://user-images.githubusercontent.com/9361308/180219366-729cdea7-4073-439f-a5cd-d4931571f9a5.png">

并且配置的网盘也已被清空。文件被修改的时间在7月13号

**Comment by qkqpttgf** [comment]
可能或许有漏洞吧，但不知道在哪

**Comment by qkqpttgf** [comment]
下次看一下日志，看对方做了啥操作

**Comment by woshichenghaibo** [comment]
感觉很吓人啊，能删除你网盘里面的东西？

**Comment by woshichenghaibo** [comment]
建议允许删除版权信息，很多人直接在搜索引擎搜索  onemanager 就出来很多网页

**Comment by qkqpttgf** [comment]
> 建议允许删除版权信息，很多人直接在搜索引擎搜索 onemanager 就出来很多网页

明明是这些人不改网站名字……

**Comment by junbluedd** [comment]
我的前几天也被改了，把所有的设置改成默认的删除了网盘，百度都没索引的

**Comment by junbluedd** [comment]
@qkqpttgf 这是改密码那个ip的日志，好像就是图片里请求了那个install1那里开始密码就变了，
![This is an image](https://pan.luweidan.top/upload/up15975a/screenshot-20220828-1414165.jpg)
![This is an image](https://pan.luweidan.top/upload/up15975a/screenshot-20220828-149812.jpg)

**Comment by qkqpttgf** [comment]
> @qkqpttgf 这是改密码那个ip的日志，好像就是图片里请求了那个install1那里开始密码就变了

不，正常请求不到install0的，有密码就不会走install的。
再找找之前的
