### ISSUE TITLE
跨域问题

### ISSUE THREAD

**Issue by Satoing** [qkqpttgf/OneManager-php#609]
在博客中引入字体文件会出现下面的问题：
![image](https://user-images.githubusercontent.com/68995451/180694898-9b5c8ed5-065a-4d81-9abb-98945d6b5666.png)
但是引入图片和视频外链都是没问题的。
我尝试在源码的请求头里面加上`$header['Access-Control-Allow-Origin'] = '*'`，但是问题依然存在。
> 使用的是阿里云盘

**Comment by qkqpttgf** [comment]
那你再去设置一下 fileConduitSize ，让字体从程序下载，请求头你还是加上
