### ISSUE TITLE
游客上传出错，GET https://cdn.bootcss.com/spark-md5/3.0.0/spark-md5.min.js net::ERR_ABORTED 522

### ISSUE THREAD

**Issue by augerjk** [qkqpttgf/OneManager-php#612]
最新版本，世纪互联
游客上传图片失败一直无限重复加载（登录后可以正常上传）
![image](https://user-images.githubusercontent.com/48583975/184477645-8c187f5d-cdae-4e7c-a4c3-5e1e730a3b18.png)

检查网页报错显示：

(index):160 Uncaught ReferenceError: preup is not defined
    at HTMLInputElement.onclick ((index):160:91)
onclick @ (index):160

GET https://cdn.bootcss.com/spark-md5/3.0.0/spark-md5.min.js net::ERR_ABORTED 522

178(index):366 Uncaught ReferenceError: SparkMD5 is not defined
    at getuplink ((index):366:21)
    at (index):320:21

查找了一下issues列表里似乎也有相同的问题
https://github.com/qkqpttgf/OneManager-php/issues/522

**Comment by qkqpttgf** [comment]
你啥主题，更新啊
怎么还在用bootcss

**Comment by augerjk** [comment]
> 


flatcard，和classic ，均出现相同问题，应该是最新版本的
https://image.sylveredukas.com/

**Comment by qkqpttgf** [comment]
> 

flatcard有可能，我没修改过，但classic没可能还是bootcss，
【有没有一种可能，你去看看readme的第1行跟第2行？？】

**Comment by qkqpttgf** [comment]
好的，现在修改在分支testjs中，你试试，没问题我就并主支了。
