### ISSUE TITLE
添加管理员密码后跳转错误界面

### ISSUE THREAD

**Issue by HelloMusician** [qkqpttgf/OneManager-php#613]
{"errorCode":1,"errorMessage":"Process exited before completing request","requestId":"f344aa20c3fa5769696b7800a7a81a4e","statusCode":439}
这个如何处理？新手，求大佬们解惑，谢谢！

**Comment by qkqpttgf** [comment]
哪个平台

**Comment by HelloMusician** [comment]
腾讯云SCF

**Comment by qkqpttgf** [comment]
> 腾讯云SCF

我很久没弄它了，都有最低消费了。
你先换个平台？

**Comment by HelloMusician** [comment]
好的，谢谢
