### ISSUE TITLE
加密网盘的时候出错

### ISSUE THREAD

**Issue by woshichenghaibo** [qkqpttgf/OneManager-php#615]
403错误

![sshot-1](https://user-images.githubusercontent.com/80568737/184874280-8f221c0b-8186-4426-b1e6-0ef408ecd2dd.png)

**Comment by woshichenghaibo** [comment]
加密网盘里面的文件夹就没有问题，直接加密网盘就不行

**Comment by qkqpttgf** [comment]
你不能在网盘外面操作……

**Comment by woshichenghaibo** [comment]
> 你不能在网盘外面操作……

不能加密网盘？而只能加密网盘下面的文件夹？

**Comment by qkqpttgf** [comment]
> > 你不能在网盘外面操作……
> 
> 不能加密网盘？而只能加密网盘下面的文件夹？

你没点过【刷新缓存】跟【设置】吗？？还有【新建】也没点过？？那里有个【加密】看不到？？

**Comment by woshichenghaibo** [comment]
> > > 你不能在网盘外面操作……
> > 
> > 
> > 不能加密网盘？而只能加密网盘下面的文件夹？
> 
> 你没点过【刷新缓存】跟【设置】吗？？还有【新建】也没点过？？那里有个【加密】看不到？？

都能看到，我的意思是，是不是在某个网盘上点加密是用不了的？

看图片

![111](https://user-images.githubusercontent.com/80568737/186071953-115000fa-1efc-4210-bfcb-a00e919a8628.JPG)
![222](https://user-images.githubusercontent.com/80568737/186071940-e2480b6e-e315-4ca7-a4ac-5e6dc2a2460a.JPG)

**Comment by woshichenghaibo** [comment]
我的意思是不是目前网站根目录无法加密，而且网盘根目录也没法加密，只能加密某一个网盘里面的文件夹？

**Comment by qkqpttgf** [comment]
我的意思是【刷新缓存】点过没？？它上面的【加密】你看不到？？？
你能不能理解一下（你不在“盘”里）的意思？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？

**Comment by GloryBoy239** [comment]
加密网盘的正确操作：
进入网盘 —— 点击左上角“管理”，在弹出菜单中选择“加密”——输入密码，确定。
这样整个网盘就加密了！

**Comment by funkyhunty** [comment]
多网盘确实不行，单网盘没有这个问题
