### ISSUE TITLE
腾讯云函数安装出现439

### ISSUE THREAD

**Issue by wxcgeek** [qkqpttgf/OneManager-php#617]
安装过程中
SecretId   SecretKey  配置保存在环境变量
填完管理密码后出现
{"errorCode":1,"errorMessage":"Process exited before completing request","requestId":"1e3107605f6c50f06ebdc38d903a61cd","statusCode":439}
无法完成安装

**Comment by qkqpttgf** [comment]
啊，我的SCF已经停了，（一个月12.9），我没法验证……

**Comment by wxcgeek** [comment]
可以了 用 php 8.0 就会有问题 php 7.4 没问题
