### ISSUE TITLE
登录admin后不能退出 且底部foot.omf加载总是失败

### ISSUE THREAD

**Issue by intleeo** [qkqpttgf/OneManager-php#618]
![图示](http://pan.intlee.cn/huajiao/%E5%BE%AE%E4%BF%A1%E6%88%AA%E5%9B%BE_20220822215238.png)
admin登录后退出按钮失效 加载不出管理菜单的图标

**Comment by qkqpttgf** [comment]
你这图我打不开，所以没法判断你说的是啥。
我这边正常，话说你更新了没，【readme第1句第2句看了没……】

**Comment by intleeo** [comment]
[![v67QHS.png](https://s1.ax1x.com/2022/08/23/v67QHS.png)](https://imgse.com/i/v67QHS)
只有刷新缓存和设置可以点。。。其他点不了【真的看了】

**Comment by intleeo** [comment]
emmmmmm找到原因了 把foot.omf干掉了..一切都清净了

**Comment by qkqpttgf** [comment]
你omf里面js肯定有毛病
