### ISSUE TITLE
更换主题后无法进入管理页面

### ISSUE THREAD

**Issue by fengz72** [qkqpttgf/OneManager-php#620]
今天新搭建的, 没有动过设置, 更改了一下主题, 无法通过`?admin`进入管理页面. 
![image](https://user-images.githubusercontent.com/50742229/187334585-5ca10f44-30bf-4bb0-9f0e-9166f129cbce.png)

**Comment by qkqpttgf** [comment]
你多少年没更新过了？
看一眼这个文件
https://github.com/qkqpttgf/OneManager-php/blob/master/version
第1行，哦不，第3行。

**Comment by qkqpttgf** [comment]
2022年1月就改了，现在9月了！你都不知道。

**Comment by HUANYUESS** [comment]
同样遇到这个问题，感谢，有时候苦恼，如果有个教程就好了。

**Comment by qkqpttgf** [comment]
> 同样遇到这个问题，感谢，有时候苦恼，如果有个教程就好了。

你都找到这个issue了，就看不到上面已经回复过了？？

**Comment by HUANYUESS** [comment]
看到了看到了~
&nbsp;


&nbsp;
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年10月8日(星期六) 上午9:12
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [qkqpttgf/OneManager-php] 更换主题后无法进入管理页面 (Issue #620)





  
同样遇到这个问题，感谢，有时候苦恼，如果有个教程就好了。
  
你都找到这个issue了，就看不到上面已经回复过了？？
