### ISSUE TITLE
你们的apk文件能列表显示吗？

### ISSUE THREAD

**Issue by woshichenghaibo** [qkqpttgf/OneManager-php#621]
1.阿里云的盘，dll exe什么的都没问题，目录下一大堆的apk，打开目录居然是空白？

是我的apk文件100个太多了？我把某个apk挪到根目录下就行了，怎么这么奇怪

2.下载apk出现一大堆的提示错误：

![1254017721](https://user-images.githubusercontent.com/80568737/188251256-cf5cc37d-f7da-4940-b9f5-6758e57b60be.jpg)

**Comment by qkqpttgf** [comment]
我阿里盘有一个别人分享过来的目录，就列不出来文件。
下载出现xml，自行找issue，不传播方法。

**Comment by woshichenghaibo** [comment]
> 我阿里盘有一个别人分享过来的目录，就列不出来文件。 下载出现xml，自行找issue，不传播方法。

我的是文件多了不显示，改成两个文件夹就显示了，分割开
