### ISSUE TITLE
能否请教下引用的unpkg下的ionicons.js在哪修改，想本地引用，没找到，谢谢。

### ISSUE THREAD

**Issue by zjb19981222** [qkqpttgf/OneManager-php#623]
能否请教下引用的unpkg下的ionicons.js在哪修改，想本地引用，没找到，谢谢。

**Comment by qkqpttgf** [comment]
在主题改
问题是它这个js还要加载其它的东西，我现在程序不允许引用本地文件，只是通过`?jsFile=xxx.js`来载入，不适用于它。

**Comment by zjb19981222** [comment]
好的谢谢，看到了，原来是我的本地缓存原因
