### ISSUE TITLE
Sharepoint+华为云FG无法预览文件

### ISSUE THREAD

**Issue by WangWenBin2017** [qkqpttgf/OneManager-php#628]
## 信息
**分支: master**
**版本: [最新版本(截至此issue提交时)](https://github.com/qkqpttgf/OneManager-php/commit/dbb2de5f5076e1ca327e5ae1a09e9ff0d10eb4dc)**
**主题: 默认主题**
**执行入口: index.handler**
**FC超时时间: 30s**
**内存: 128 MB**

## 症状
**所有格式均无法预览，例如mp4、mp3、jpg、png、flac等所有支持预览的文件类型均不能预览，已经添加 `preview=true` 参数仍不工作。**

下载、README.md 预览功能正常，尝试更换浏览器、删除全部数据重装、并依次选择变量和文件方式安装，仍然不起效果。

ps: 在控制台看了一下，是服务器直接返回了不支持预览

mp4:
![mp4 后缀](https://i.imgur.com/xo8Ryou.png)

jpg:
![jpg 后缀](https://i.imgur.com/bJRoQFr.png)

**Comment by qkqpttgf** [comment]
我这边也出现了，有空看看

**Comment by qkqpttgf** [comment]
你更新到这个测试分支试试，没问题我就并主支

**Comment by WangWenBin2017** [comment]
经测试，原来无法预览的文件已经正常。感谢大佬修改~
