### ISSUE TITLE
怎么让链接是属性变为可以直接浏览器打开的而不是打开就下载？

### ISSUE THREAD

**Issue by qian9008** [qkqpttgf/OneManager-php#631]
如题

**Comment by qkqpttgf** [comment]
不好意思，没看懂你的确切意思，请详细描述过程。

**Comment by zzh151223** [comment]
这个是浏览器解析成了文件，你要去改nginx配置让浏览器识别为在线文件

**Comment by woshichenghaibo** [comment]
> 这个是浏览器解析成了文件，你要去改nginx配置让浏览器识别为在线文件

怎么修改？

**Comment by Satoing** [comment]
> 怎么修改？
服务器配置是改不了的，因为文件的服务器是阿里云盘的。使用代理应该可以实现，但你也不想所有文件都中转一下，自己给自己限速吧？
另外可以预览和不能预览也没什么区别吧，都是可以在网站中正常引用的。
