### ISSUE TITLE
Deploy to Vercel Failed

### ISSUE THREAD

**Issue by liblaf** [qkqpttgf/OneManager-php#632]
> Error: The Runtime @vercel/vc-build is using nodejs12.x, which was discontinued by an upstream provider. In turn, we have to ask you to upgrade your Runtime to a more recent version or consult the author for more details. Learn More: https://github.com/vercel/vercel/blob/master/DEVELOPING_A_RUNTIME.md#lambdaruntime

**Comment by liblaf** [comment]
> Starting Monday, October 3, [Node.js 12 will no longer be supported on Vercel](https://vercel.com/changelog/node-js-12-is-being-deprecated).

**Comment by FASUZO** [comment]
![image](https://user-images.githubusercontent.com/77849230/194226014-c3d6c49b-d168-4271-bf08-62a45d692018.png)
需要vercel-php更新而不是onemanager

**Comment by FASUZO** [comment]
https://www.npmjs.com/package/vercel-php
https://github.com/vercel-community/php

**Comment by liblaf** [comment]
啊这

**Comment by hmsjy2017** [comment]
实测用你改的部署页面部署还是会失败，我改的就可以。
![DV$F%LGHYH7E13M4Z@9}8MX](https://user-images.githubusercontent.com/42692274/194764054-4c76bb47-9f59-46e6-8427-8e0349665871.png)
目前我通过此方案部署成功：
部署页面：https://hmsjy2017.github.io/SCFOnedrive.github.io/Vercel/Deploy.html
源码：https://github.com/liblaf/OneManager-php/tree/bump-vercel-php

**Comment by liblaf** [comment]
> 实测用你改的部署页面部署还是会失败，我改的就可以。 ![DV$F%LGHYH7E13M4Z@9}8MX](https://user-images.githubusercontent.com/42692274/194764054-4c76bb47-9f59-46e6-8427-8e0349665871.png) 目前我通过此方案部署成功： 部署页面：https://hmsjy2017.github.io/SCFOnedrive.github.io/Vercel/Deploy.html 源码：https://github.com/liblaf/OneManager-php/tree/bump-vercel-php

是的, 因为 OneManager 内也使用了 `vercel-php`, 所以不仅部署页面需要更新, 源码也需要更新.
