### ISSUE TITLE
vercel部署无法播放视频

### ISSUE THREAD

**Issue by YANGNIGHT** [qkqpttgf/OneManager-php#635]
vercel部署无法播放视频，显示视频加载失败
腾讯云函数运行后在设置页面更新后就无法登录，显示登陆成功然后跳转回首页，但是还是没有登录

**Comment by qkqpttgf** [comment]
视频无法播放，其它文件呢，F12看看问题在哪
SCF现在还有人用？

**Comment by qkqpttgf** [comment]
............我看到了xml
明显这是阿里盘的事情，我不传播解决办法。
