### ISSUE TITLE
Support me upload file = CURL php 

### ISSUE THREAD

**Issue by downloadvideo** [qkqpttgf/OneManager-php#637]
Guide me to post url images on the web = POST use PHP Curl links file
thanks

**Comment by qkqpttgf** [comment]
#576 , see the pic of black

**Comment by downloadvideo** [comment]
> #576 , see the pic of black

You support me = code php ?
i test = php curl error

<?php
$curl = curl_init();
curl_setopt($curl, CURLOPT_URL, $url);
curl_setopt($curl, CURLOPT_POST, true);
curl_setopt($curl, CURLOPT_HTTPHEADER, array("Accept: application/json"));
curl_setopt($curl, CURLOPT_POSTFIELDS, "files={'file1':'@test.png'}");
curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);

$resp = curl_exec($curl);
curl_close($curl);

echo $resp;
?>

support me, thanks

**Comment by qkqpttgf** [comment]
use the shell, in black window.
php can do it , also.

**Comment by downloadvideo** [comment]
> use the shell, in black window. php can do it , also.

yes, you send me code php
thanks
