### ISSUE TITLE
挂载OneDrive 主页不显示 白屏 但是其他目录可以访问

### ISSUE THREAD

**Issue by bhshuya** [qkqpttgf/OneManager-php#639]
![image](https://user-images.githubusercontent.com/77972386/199229307-7b15a647-705d-4612-9365-04609a4aab36.png)
![image](https://user-images.githubusercontent.com/77972386/199229778-43b86b4a-1895-42b8-a92c-4a6732b5535c.png)
![image](https://user-images.githubusercontent.com/77972386/199229455-7720410f-50e8-4e78-852a-fa00bd7503c8.png)

挂载某一个路径主页不显示，但挂载目录下的其他目录可以显示。换个路径就能显示了。。。
挂载的路径也没有错

**Comment by qkqpttgf** [comment]
就算这么描述，我也没办法知道情况……
