### ISSUE TITLE
能不能支持下夸克网盘，大佬

### ISSUE THREAD

**Issue by zjb19981222** [qkqpttgf/OneManager-php#640]
能不能支持下夸克网盘，大佬

**Comment by qkqpttgf** [comment]
不能

**Comment by ning0818** [comment]
> 不能
能不能支持123网盘，大佬,新用户注册2t免费空间，onedrive他才5g

**Comment by qkqpttgf** [comment]
> > 不能
> > 能不能支持123网盘，大佬,新用户注册2t免费空间，onedrive他才5g

跟它大小无关
