### ISSUE TITLE
AAD风险检测报凭据泄露

### ISSUE THREAD

**Issue by Pil0tXia** [qkqpttgf/OneManager-php#644]
![image](https://user-images.githubusercontent.com/41445332/200886898-629aa2e2-a991-4404-a24d-c2c3e824ce96.png)

此页面的“详细信息”指向此链接：https://github.com/cooliceycold/omaliphp/blob/f8e3db2e378ef2be505aa489dc2952de6755b19b/disk/Onedrive.php#L15

请确认是否安全，以及能否消除此风险警告
谢谢！

**Comment by qkqpttgf** [comment]
对啊，这是我默认的secret，又不是【你】的泄露了。

它的意思是，有可能会有人拿着这个client_id跟client_secret，另外写一个有恶意代码的程序，假装是【最新版本】来骗你安装上并绑定，这样，你的onedrive就会被他操纵了。

你只要从我这个github这里下载安装就不会有问题，更新到其它网友的版本也要注意分别。
咦，你这个链接就根本不是我的程序，你要注意风险，担心的话，在你AAD里面删掉对它的授权吧。

**Comment by Pil0tXia** [comment]
谢谢
