### ISSUE TITLE
上传文件的切割可以改吗？

### ISSUE THREAD

**Issue by Winyer** [qkqpttgf/OneManager-php#649]
我发现上传几百兆以上的文件时会在传输10MB后挺一下，像是在切割，然后再继续上传，能不能改一下这个数值呢？不然网速跑不起来就停下了

**Comment by qkqpttgf** [comment]
主题文件里面自己改~

**Comment by qkqpttgf** [comment]
> 找到了，但是上面写的微软建议10M，请问这个有什么说法吗

没有说法，真的是微软文档里面建议的。
