### ISSUE TITLE
如何使用requests实现上传文件

### ISSUE THREAD

**Issue by Satoing** [qkqpttgf/OneManager-php#659]
我打算用python写一个上传文件的脚本，但是不是很懂文件上传是如何实现的。
每上传一个文件发起的请求如下：
![image](https://user-images.githubusercontent.com/68995451/212234000-6dcd57cc-4c09-4f7e-a801-3dfc9cdd59f8.png)
照着中间这个post请求，python代码如下：
```python
import requests

headers = {
    'content-type': 'application/x-www-form-urlencoded',
    'cookie': ''
}
m = {
    'upbigfilename': 'c.jpg',
    'filesize': '84736',
    'filelastModified': 1664969090576,
    'proof_code': 'H51i/Zx6mj4=',
    "filesha1": "728c4e89a46bbdde64af8df27745056952f07dd4",
    'chunksize': 10485760,
    '_admin': ''
}
url = 'https://xxx/?action=upbigfile'
res = requests.post(url, headers = headers, data=m)

print(res.text)
```
但是最后返回的依然是HTML。请问上传文件该携带哪些数据？

**Comment by Vincentzyx** [comment]
建议搭配RClone实现文件上传

**Comment by Satoing** [comment]
> 建议搭配RClone实现文件上传

emm，我认为没必要为了上传文件专门把云盘挂载到本地，不然还不如直接网页上传呢。

**Comment by Vincentzyx** [comment]
> > 建议搭配RClone实现文件上传
> 
> emm，我认为没必要为了上传文件专门把云盘挂载到本地，不然还不如直接网页上传呢。

不用挂载哇，有上传指令的，当cli用，挺好用的

**Comment by Satoing** [comment]
> 不用挂载哇，有上传指令的，当cli用，挺好用的

好，我看看。之前听说过没用过

**Comment by qkqpttgf** [comment]
proof?你这是阿里的啊
应该是少了“x-requested-with: XMLHttpRequest”，另外content type我不知道form能不能行，你再试试

**Comment by WANG-Guangxin** [comment]
> > > 建议搭配RClone实现文件上传
> > 
> > 
> > emm，我认为没必要为了上传文件专门把云盘挂载到本地，不然还不如直接网页上传呢。
> 
> 不用挂载哇，有上传指令的，当cli用，挺好用的

可以给个 demo 吗
