### ISSUE TITLE
部署在vercel的，提示400错误，不显示任何文件了。只会按教程做，现在不懂怎么办了

### ISSUE THREAD

**Issue by tingyue-wu** [qkqpttgf/OneManager-php#661]
显示错误
400
{ "error": "invalid_grant", "error_description": "AADSTS700082: The refresh token has expired due to inactivity.\u00a0The token was issued on 2022-09-26T22:56:36.0420482Z and was inactive for 90.00:00:00.\r\nTrace

现在不知道怎么办了，重新部署，提示：使用的是 nodejs12.x，它已被上游提供商停用。反过来，我们必须要求您将运行时升级到更新的版本或咨询作者以获取更多详细信息。

**Comment by qkqpttgf** [comment]
那个报错是90天内都没写入新的token了，所以过期了。

能不能重新安装【最新版本】？去年早修过了，你不要拿着旧版本往上弄啊。

**Comment by qkqpttgf** [comment]
提示nodejs要18，这个昨天刚刚修了一下，
请删除vercel上的项目，再重新部署，【如果覆盖部署，nodejs版本不会改变】
