### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by ProjectNyaser** [qkqpttgf/OneManager-php#664]
建议在管理后台添加对```client_secret```的修改功能，以便密钥失效时进行更换。
当密钥失效时，获取```access_token```将会返回401错误，导致无法进行其他操作。
当前管理后台不支持修改密钥，只能通过修改源代码来实现密钥修改。

补充信息：
> 使用的是SharePoint，自定义client_id和client_secret。

我的临时解决方案：
> 在```disk/SharePoint.php```中添加以下代码
```
setConfig([ 'client_secret' => '新密钥' ], $tag);
```
> 访问网页，然后删除(注释)上述代码。

**Comment by qkqpttgf** [comment]
有道理，下次有空增加

**Comment by qkqpttgf** [comment]
更新到分支 modifyClientSecret 试试

**Comment by qkqpttgf** [comment]
不理我，那就直接并主支了。

**Comment by ProjectNyaser** [comment]
抱歉，前段时间确实是没空看GitHub。
