### ISSUE TITLE
华为云函数工作流-函数部署完报这个错

### ISSUE THREAD

**Issue by aomn** [qkqpttgf/OneManager-php#667]
{"error_code":"FSS.1206","error_msg":"invalid type of APIG trigger invocation result:[runtime process is exited], type format must be: {\"statusCode\":200,\"isBase64Encoded\":false,\"headers\":{},\"body\":\"\"}"}

{"error_code":"FSS.1206","error_msg":"'statusCode' of APIG trigger invocation result not specified, statusCode can not be 0"}

**Comment by ShuJun-Junical** [comment]
同遇到这个报错，怀疑大概率是没适配华为云 api 网关的集成响应

**Comment by ilxp** [comment]
同样问题  {"error_code":"FSS.1206","error_msg":"'statusCode' of APIG trigger invocation result not specified, statusCode can not be 0"}

**Comment by ilxp** [comment]
换成阿里云就没有这个问题。

**Comment by kinnd1** [comment]
同遇到这个报错，应该是华为云 api那边改了接口，大佬还修复吗

**Comment by qkqpttgf** [comment]
我的欠费打不开了，谁有空让我远程瞅瞅

**Comment by qkqpttgf** [comment]
昨天做了个 FGtest 分支，请大家测试一下。

**Comment by WangWenBin2017** [comment]
刚看到回复😂，使用FGTest分支后，现在功能恢复正常了（测试了后台保存、文件预览和下载、文件目录加密、管理员登陆）。
