### ISSUE TITLE
挂载阿里云盘出现 invalid X-Device-Id

### ISSUE THREAD

**Issue by bhshuya** [qkqpttgf/OneManager-php#668]
听说是官方更改了验证方式？可以修一下吗
![Uploading -4917c0732ed9e4b0.jpg…]()

**Comment by bhshuya** [comment]
![-4917c0732ed9e4b0](https://user-images.githubusercontent.com/77972386/219256086-fafda2d2-ea78-4bc3-9f29-e0e7fa22064b.jpg)

**Comment by Satoing** [comment]
+1

**Comment by qkqpttgf** [comment]
有人pr了，没有算sign。
请更新。
