### ISSUE TITLE
关于自定义上传文件夹

### ISSUE THREAD

**Issue by ZKsolar** [qkqpttgf/OneManager-php#67]
希望能新增一个自定义功能文件（例如“.upload”文件，类似密码功能文件），使得该层文件夹能上传文件。并设置判定，若该文件为空，则该层文件可见，若非空，则该文件内容为密码，输入可见该层文件。

**Comment by qkqpttgf** [comment]
游客上传目录已经满足不了你的S欲了吗！！！
