### ISSUE TITLE
when i config my google drive account appear this message when i login in to the app

### ISSUE THREAD

**Issue by Rigolino1** [qkqpttgf/OneManager-php#672]
![image](https://user-images.githubusercontent.com/106283533/221247174-24d33636-d86a-4a15-a19d-7d2578bd0d3b.png)

**Comment by Rigolino1** [comment]
how to solve that?

**Comment by qkqpttgf** [comment]
sorry for that.
I list GD via SHARE THE FILE , so not suggest add GD.
