### ISSUE TITLE
Replit按照readme步骤部署出错

### ISSUE THREAD

**Issue by saika2077** [qkqpttgf/OneManager-php#673]
按照readme部署会报错nix error: building nix env: exit status 1

**Comment by saika2077** [comment]
部署完成后，在.replit文件末加上一行
channel = "stable-22_11"
再点击“run”按钮，可以解决。

**Comment by saika2077** [comment]
经检查，部署完成后，在.replit文件最末加上两行`[nix]
channel = "stable-22_11"`就可以解决

**Comment by saika2077** [comment]
经检查，在.replit文件最末加上这两行可以解决问题
[nix]
channel = "stable-22_11"

**Comment by sdlkhfksl** [comment]
这个本来就有啊

**Comment by qkqpttgf** [comment]
解决，请试一下。
