### ISSUE TITLE
阿里云盘获取不到文件下载地址

### ISSUE THREAD

**Issue by hejiadong0608** [qkqpttgf/OneManager-php#674]
今天发现添加的阿里云盘，文件点下载出来一个空白页，不能正常下载了。

**Comment by Exisi** [comment]
同上，今天下载链接打开也是空白

**Comment by qkqpttgf** [comment]
刚修了一下，更新试试修好没

**Comment by sunwinbus** [comment]
点击下载后，获取到的文件名不正确

**Comment by Exisi** [comment]
测试了一下，文件名不正确，还丢失文件后缀，手动修改后缀文件正常

**Comment by qkqpttgf** [comment]
文件名这个我弄不了，阿里改新机制了似乎。

**Comment by KiWinger** [comment]
下载提示：This XML file does not appear to have any style information associated with it. The document tree is shown below.
但是文件树可以列出来

**Comment by qkqpttgf** [comment]
> 下载提示：This XML file does not appear to have any style information associated with it. The document tree is shown below. 但是文件树可以列出来 @qkqpttgf 看看这个有没有帮助？https://www.yuque.com/aliyundrive/zpfszx

你是2年前的老问题，自行百度解决。
没有帮助。
