### ISSUE TITLE
replit  部署报错

### ISSUE THREAD

**Issue by sdlkhfksl** [qkqpttgf/OneManager-php#677]
 git clone https://github.com/qkqpttgf/OneManager-php && mv -b OneManager-php/* ./ && mv -b OneManager-php/.[^.]* ./ && rm -rf *~ && rm -rf OneManager-php
Cloning into 'OneManager-php'...
remote: Enumerating objects: 3883, done.
remote: Counting objects: 100% (16/16), done.
remote: Compressing objects: 100% (14/14), done.
remote: Total 3883 (delta 6), reused 7 (delta 2), pack-reused 3867
Receiving objects: 100% (3883/3883), 3.06 MiB | 6.76 MiB/s, done.
Resolving deltas: 100% (2514/2514), done.
Detected change in environment, reloading shell...
nix error: building nix env: exit status 1
Output has been trimmed to the last 20 lines
evaluating file '/nix/store/qkdmqki0dwmm50z81d1cs0pw3f82127k-nixpkgs-legacy-src/pkgs/stdenv/adapters.nix'
evaluating file '/nix/store/qkdmqki0dwmm50z81d1cs0pw3f82127k-nixpkgs-legacy-src/pkgs/build-support/trivial-builders.nix'
evaluating file '/nix/store/qkdmqki0dwmm50z81d1cs0pw3f82127k-nixpkgs-legacy-src/pkgs/top-level/splice.nix'
evaluating file '/nix/store/qkdmqki0dwmm50z81d1cs0pw3f82127k-nixpkgs-legacy-src/pkgs/top-level/all-packages.nix'
evaluating file '/nix/store/qkdmqki0dwmm50z81d1cs0pw3f82127k-nixpkgs-legacy-src/pkgs/top-level/aliases.nix'
evaluating file '/nix/store/yw8dgzxf9hvlwhv0m8drlbq66viizsra-nixpkgs/nixpkgs/overlay.nix'
evaluating file '/nix/store/qkdmqki0dwmm50z81d1cs0pw3f82127k-nixpkgs-legacy-src/pkgs/stdenv/generic/default.nix'
evaluating file '/nix/store/qkdmqki0dwmm50z81d1cs0pw3f82127k-nixpkgs-legacy-src/lib/customisation.nix'
evaluating file '/nix/store/qkdmqki0dwmm50z81d1cs0pw3f82127k-nixpkgs-legacy-src/pkgs/tools/text/gawk/default.nix'
evaluating file '/nix/store/qkdmqki0dwmm50z81d1cs0pw3f82127k-nixpkgs-legacy-src/pkgs/servers/x11/xorg/default.nix'
evaluating file '/nix/store/qkdmqki0dwmm50z81d1cs0pw3f82127k-nixpkgs-legacy-src/pkgs/servers/x11/xorg/overrides.nix'
evaluating file '/nix/store/qkdmqki0dwmm50z81d1cs0pw3f82127k-nixpkgs-legacy-src/pkgs/stdenv/generic/make-derivation.nix'
evaluating file '/nix/store/qkdmqki0dwmm50z81d1cs0pw3f82127k-nixpkgs-legacy-src/pkgs/build-support/mkshell/default.nix'
evaluating file '/home/runner/one/replit.nix'
evaluating file '/nix/store/qkdmqki0dwmm50z81d1cs0pw3f82127k-nixpkgs-legacy-src/pkgs/stdenv/generic/check-meta.nix'
evaluating file '/nix/store/qkdmqki0dwmm50z81d1cs0pw3f82127k-nixpkgs-legacy-src/lib/systems/doubles.nix'
copied source '/nix/store/qkdmqki0dwmm50z81d1cs0pw3f82127k-nixpkgs-legacy-src/pkgs/stdenv/generic/default-builder.sh' -> '/nix/store/9krlzvny65gdc8s7kpb6lkx8cd02c25b-default-builder.sh'
error: attribute 'php82' missing, at /home/runner/one/replit.nix:3:3
(use '--show-trace' to show detailed location information)

**Comment by yzsong06** [comment]
打开replit隐藏文件，把里面的PHP82版本改成74就行了

**Comment by yzsong06** [comment]
隐藏文件replit.nix（补充）

**Comment by qkqpttgf** [comment]
> 打开replit隐藏文件，把里面的PHP82版本改成74就行了

啊，82我应该支持啊

**Comment by yzsong06** [comment]
> > 打开replit隐藏文件，把里面的PHP82版本改成74就行了
> 
> 啊，82我应该支持啊

这里是replit的问题，replit没有找到PHP82的nix文件
