### ISSUE TITLE
在heroku.com上面部署升级到最新版后显示500错误

### ISSUE THREAD

**Issue by keli1973** [qkqpttgf/OneManager-php#68]
在heroku.com上面部署升级到最新版后显示500错误

**Comment by keli1973** [comment]
!     Push rejected, Failed decompressing source code.
Source archive detected as: HTML document, UTF-8 Unicode text, with very long lines
More information: https://devcenter.heroku.com/articles/platform-api-deploying-slugs#create-slug-archive

**Comment by keli1973** [comment]
暂时rollback到可用版本，不敢随便升级了

**Comment by qkqpttgf** [comment]
我demo正常的，或许，你是太久远的版本了，请看置顶issue有写的
