### ISSUE TITLE
customTheme 可能存在bug

### ISSUE THREAD

**Issue by kobe-koto** [qkqpttgf/OneManager-php#680]
部署在 Vercel 上
(2023/03/17 更新， 拉最新（8fadfa5）主分支代码下来在本地和000webhost部署均可复现）
最近想写个 OneManager 的主题，发现 customTheme 不起作用（首页白屏）， 于是换了其他的主题（nexmoe，以前可以用），依旧不起作用。之后复制了Onedrive-dev主题的地址（ https://github.com/qkqpttgf/OneManager-php/raw/master/theme/Onedrive-dev.html ）问题依旧。curl返回内容如下
```
<!--
    OneManager: An index & manager of Onedrive auth by ysun.
    HIT Gitlab: https://git.hit.edu.cn/ysun/OneManager-php
    Github: https://github.com/qkqpttgf/OneManager-php
-->
```
设定theme为Onedrive-dev后显示正常

**Comment by yzsong06** [comment]
貌似我记得有个onemanager主题作者好像在主题文件里写过custom theme不能用（Doge）

**Comment by qkqpttgf** [comment]
刚刚测试发现，https://raw.githubusercontent.com/qkqpttgf/OneManager-php/master/theme/Onedrive-dev.html  用浏览器访问正常，在cmd里curl就是404。不知道是不是跟这个有关。

**Comment by qkqpttgf** [comment]
> 貌似我记得有个onemanager主题作者好像在主题文件里写过custom theme不能用（Doge）

刚改了一下，放在分支 fixCustomTheme 里了，你试试这个分支能用不。

**Comment by yzsong06** [comment]
> > 貌似我记得有个onemanager主题作者好像在主题文件里写过custom theme不能用（Doge）
> 
> 刚改了一下，放在分支 fixCustomTheme 里了，你试试这个分支能用不。

哇，多久以前的评论了，简直挖坟啊（Doge）

**Comment by qkqpttgf** [comment]
> > > 貌似我记得有个onemanager主题作者好像在主题文件里写过custom theme不能用（Doge）
> > 
> > 
> > 刚改了一下，放在分支 fixCustomTheme 里了，你试试这个分支能用不。
> 
> 哇，多久以前的评论了，简直挖坟啊（Doge）

有问题还是要解决的，知识不够不能解决就先留着，会了再修。
快更新到这个分支试试，我好结案。

**Comment by kobe-koto** [comment]
> > 貌似我记得有个onemanager主题作者好像在主题文件里写过custom theme不能用（Doge）
> 
> 刚改了一下，放在分支 fixCustomTheme 里了，你试试这个分支能用不。

已经正常了，感谢修复

**Comment by qkqpttgf** [comment]
> > > 貌似我记得有个onemanager主题作者好像在主题文件里写过custom theme不能用（Doge）
> > 
> > 
> > 刚改了一下，放在分支 fixCustomTheme 里了，你试试这个分支能用不。
> 
> 已经正常了，感谢修复

好，那我并主支了
