### ISSUE TITLE
阿里云盘的下载功能又挂了

### ISSUE THREAD

**Issue by woshichenghaibo** [qkqpttgf/OneManager-php#682]
1.我在网上找方案嗯，有人说是在部署的平台的项目变量里面把那个阿里云盘的令牌重新再编辑一下就行，https://www.bilibili.com/read/mobile?id=10777344
但是很奇怪，我在vercel里面根本就没有找到什么地方能查看我们上传上去的代码，有一个code的那个地方查看都是空的，找不到任何代码，很奇怪，能不能出个如何在vercel上编辑om的代码的教程？

2.问题本身就是嗯，阿里云的下载功能都挂了EXE rar，这些文件全部都挂了，还有就是嗯，图片点下载的话嗯，会直接显示图片本身嗯，好像你的音频也播放不了了嗯，我刚开始以为是我部署的有问题，后来到你的demo里，我去看了一下，发现也是一样的

**Comment by kobe-koto** [comment]
#488 配置保存在哪里？
> # 3, Vercel
> 
> 抱歉，请重装。

**Comment by kobe-koto** [comment]
Vercel 修改代码方面请自己fork一份自己改
配置的话在AdminPanel里面有导出导入功能

**Comment by woshichenghaibo** [comment]
> Vercel 修改代码方面请自己fork一份自己改 配置的话在AdminPanel里面有导出导入功能

你说的是导出现在配置然后修改代码重新在vercel部署吧？但是vercel有编辑代码的功能，我没找到

**Comment by zigou23** [comment]
> > Vercel 修改代码方面请自己fork一部分自己修改配置的话在AdminPanel里面有导出导入功能
> 
> 你说的是现在配置后修改代码重新出现在vercel部吧？但是vercel有编辑代码的功能，我没找到

fork后，在设置里，使用你仓库更新
![image](https://user-images.githubusercontent.com/40587032/230296442-aeb1b083-a849-43f1-a748-be32c6a42275.png)

**Comment by qkqpttgf** [comment]
是的，我的demo里面ali也下载不了

**Comment by woshichenghaibo** [comment]
> > > Vercel 修改代码方面请自己fork一部分自己修改配置的话在AdminPanel里面有导出导入功能
> > 
> > 
> > 你说的是现在配置后修改代码重新出现在vercel部吧？但是vercel有编辑代码的功能，我没找到
> 
> fork并编辑好后，在设置里，使用你仓库更新（**记得更新前先备份一下数据(设置-导出)，以防出错** ![image](https://user-images.githubusercontent.com/40587032/230297492-d6bb2521-5afd-41e8-8497-5f76a0a68054.png)

感谢指点

**Comment by zigou23** [comment]
> 感谢指点

看错了，以为重点在修改代码上。修改key可以设置-导出后再重新导入就可以

**Comment by woshichenghaibo** [comment]
> 是的，我的demo里面ali也下载不了

可否改为阿里的open的API？

**Comment by ehZyiL** [comment]
> 1.我在网上找方案嗯，有人说是在部署的平台的项目变量里面把那个阿里云盘的令牌重新再编辑一下就行，https://www.bilibili.com/read/mobile?id=10777344 但是很奇怪，我在vercel里面根本就没有找到什么地方能查看我们上传上去的代码，有一个code的那个地方查看都是空的，找不到任何代码，很奇怪，能不能出个如何在vercel上编辑om的代码的教程？
> 
> 2.问题本身就是嗯，阿里云的下载功能都挂了EXE rar，这些文件全部都挂了，还有就是嗯，图片点下载的话嗯，会直接显示图片本身嗯，好像你的音频也播放不了了嗯，我刚开始以为是我部署的有问题，后来到你的demo里，我去看了一下，发现也是一样的

这个视频链接挂了 需要改什么呢？

**Comment by qkqpttgf** [comment]
> 这个视频链接挂了 需要改什么呢？

在后台，导出配置，在文本框里直接修改阿里盘对应的refresh token，然后导入配置，等30秒左右部署时间
