### ISSUE TITLE
考虑支持阿里云函数吗

### ISSUE THREAD

**Issue by djnwzs** [qkqpttgf/OneManager-php#69]
如题

**Comment by qkqpttgf** [comment]
都怪你，这两天我都没睡好，
已经支持了，放在alifc分支，你先当几天小白鼠，没问题我再并到主支去

**Comment by djnwzs** [comment]
> 都怪你，这两天我都没睡好，
> 已经支持了，放在alifc分支，你先当几天小白鼠，没问题我再并到主支去

哈哈哈，谢谢大佬

**Comment by djnwzs** [comment]
> 都怪你，两个天我都没睡好，
> 已经支持了，放在alifc分支，你先当几天小白鼠，没问题我再并到主支去

有问题，切换到阿里的函数不会用了
![image](https://user-images.githubusercontent.com/31347434/83587932-cb198400-a582-11ea-9ca1-62744ba74d4a.png)

**Comment by djnwzs** [comment]
> 都怪你，两个天我都没睡好，
> 已经支持了，放在alifc分支，你先当几天小白鼠，没问题我再并到主支去

应该没啥问题
