### ISSUE TITLE
安装失败

### ISSUE THREAD

**Issue by zxjzxj0010** [qkqpttgf/OneManager-php#692]
以前安装过，后来删除，想在、、现在想重新安装，安装时报错如下
![image](https://github.com/qkqpttgf/OneManager-php/assets/63140714/93036857-39a0-468e-8c2c-e88c1c0cf6d8)
![image](https://github.com/qkqpttgf/OneManager-php/assets/63140714/392bab71-5864-46e4-b348-37b56e868954)
![image](https://github.com/qkqpttgf/OneManager-php/assets/63140714/72399f50-4276-4d70-9aad-d5f7a9895694)
![image](https://github.com/qkqpttgf/OneManager-php/assets/63140714/5bd4e6cd-c4b1-4b7b-acc0-652f6defec1c)

**Comment by sucooer** [comment]
一样的问题

**Comment by qkqpttgf** [comment]
呃，不应该是空的啊，我这没遇到过空的，刚刚做了个分支，你试试

**Comment by zxjzxj0010** [comment]
> 呃，不应该是空的啊，我这没遇到过空的，刚刚做了个分支，你试试

可以了！！！
