### ISSUE TITLE
关于修改 `client_secret` 后，刷新 `refresh_token` 的问题

### ISSUE THREAD

**Issue by ProjectNyaser** [qkqpttgf/OneManager-php#694]
上接 #664

经过测试，在`client_secret`过期时，无法对其进行修改。

过期时设置界面不显示`设置`按钮，在未过期时则正常。
在对应的`input`标签中按下回车键，将重新加载页面，但并未发送POST请求。
这导致修改参数的代码并未被触发。
https://github.com/qkqpttgf/OneManager-php/blob/c44677ad5c482641fb6b4c7b032eeb3fa6ecab7e/common.php#L1427-L1477

附图：
![image](https://github.com/qkqpttgf/OneManager-php/assets/61904116/9ae1300a-1809-4e18-b1e3-b98afaaa0e57)

**Comment by ProjectNyaser** [comment]
我将在 2023/07/23 下午返校，届时下次回复*可能在半年后*，见谅！

**Comment by ProjectNyaser** [comment]
据我分析，应该是在执行`$disk_tmp->getDiskSpace()`时，因`client_secret`过期而产生的错误。
> line1720 in common.php

这个错误跳出后导致提交按钮并未成功写入`$frame`变量。
>line1758 to line1759 in common.php

**Comment by ProjectNyaser** [comment]
我将添加提交按钮的代码移动到`if`语块外后，成功显示了提交按钮。
> line 1758 to line 1759

在这之后，我成功地修改了`client_secret`，于是报错变了。
这个错误似乎是由于没有重新获取`refresh_token`而导致的。

附图：
![image](https://github.com/qkqpttgf/OneManager-php/assets/61904116/1afea175-b251-42f9-92cc-94596d880fdc)

**Comment by ProjectNyaser** [comment]
似乎有人遇到过相似的问题：https://github.com/qkqpttgf/OneManager-php/issues/661#issuecomment-1453061968
但我确认已经安装了最新`master`分支的版本，但未能解决问题。

**Comment by ProjectNyaser** [comment]
已推送 #695 和 #696。
可通过修改 `client_secret` 后，点击 `重置此盘` 以刷新 `refresh_token`。
触发 `disktag_reset` 相当于重新执行了一次 'install1' 过程。
https://github.com/qkqpttgf/OneManager-php/blob/33e6b32fbde64daea69e3f10d8ed39a776f2f798/common.php#L1433-L1449
https://github.com/qkqpttgf/OneManager-php/blob/c44677ad5c482641fb6b4c7b032eeb3fa6ecab7e/disk/Onedrive.php#L683-L698

**Comment by ProjectNyaser** [comment]
细想一下，这样似乎不能适用于所有 `disktype`，而是仅仅能用于 `Onedrive` 及其继承类。
请 @qkqpttgf 大佬对 #696 进行修改后再更新。

**Comment by qkqpttgf** [comment]
突然想起这回事，
确认了一下，我原来的代码，添加提交按钮后，任意id跟secret，可以修改secret，

我这边的需求是，当2年期的secret过期的时候，可以修改secret，
你这个似乎是需要在refresh token过期90天后修改，

这个已经跟secret无关了，一个90天一个2年，refresh token过期了secret一般没过期可以继续用的。

授权过期，这时需要的是跟你操作一样，直接删除重新添加。
