### ISSUE TITLE
token报错

### ISSUE THREAD

**Issue by Seryta** [qkqpttgf/OneManager-php#7]
当时是改了很多文件名字，上传文件等操作，然后就突然报错了，但是我看了下报错应该和文件的改动没有关系吧，报错如图
![image](https://user-images.githubusercontent.com/31036794/74400657-91006700-4e59-11ea-9025-48c13e99d132.png)
请问除了重新搞一个SCF之外还有什么办法能及时解决吗？

**Comment by qkqpttgf** [comment]
我代码习惯比较差，这边调用那边，你改了什么我也不太清楚，
所以我只能说，你重装吧。
然后你再慢慢改，改一点保存一点。

**Comment by Seryta** [comment]
> 我代码习惯比较差，这边调用那边，你改了什么我也不太清楚，
> 所以我只能说，你重装吧。
> 然后你再慢慢改，改一点保存一点。

不是，我没有改代码，仅仅是在用oneindex改里面的文件目录之类的，代码没动过

**Comment by qkqpttgf** [comment]
哦，刚刚没看清，有点看错意思。
你再仔细看一眼图片，里面写着，token过期了（可能因为密码改了），你重装吧，重新申请token。

**Comment by Seryta** [comment]
> 哦，刚刚没看清，有点看错意思。
> 你再仔细看一眼图片，里面写着，token过期了（可能因为密码改了），你重装吧，重新申请token。

嗯嗯好的，感谢！我最后直接重装了，我看也是这个，不知道怎么弄就直接重装了，这个token正常情况下是一个月自动换一个吗？

**Comment by qkqpttgf** [comment]
我们保存的是refresh token，每次用它来获取access token，拿着acceess token去访问文件。
access token有效期1小时，前些日子我才发现refresh token有效期90天，以前以为是永久，现在我每30天自动更新一下refresh token保存。

**Comment by Seryta** [comment]
> 我们保存的是refresh token，每次用它来获取access token，拿着acceess token去访问文件。
> access token有效期1小时，前些日子我才发现refresh token有效期90天，以前以为是永久，现在我每30天自动更新一下refresh token保存。

OK，THANKS
