### ISSUE TITLE
游客上传后文件名

### ISSUE THREAD

**Issue by hoohowch** [qkqpttgf/OneManager-php#70]
游客上传文件后，可否显示原来的文件名？现在的上传完后在目录里一堆字母和数字，虽然可以依照时间排序来快速找到，但时间久了就不方便了

**Comment by qkqpttgf** [comment]
#48 , 
这只是给游客上传后引用的，并没打算给其它游客直接看到，
注意，游客就是游客，虽然你并不是游客
你想方便找到的话，你可以移出来，重命名。
