### ISSUE TITLE
Vercel Build Failed

### ISSUE THREAD

**Issue by cv2wx** [qkqpttgf/OneManager-php#701]
`The Runtime "vercel-php@0.5.2" is using "nodejs14.x", which is discontinued. Please upgrade your Runtime to a more recent version or consult the author for more details.`

It seems to need to update dependency `vercel-php`.

**Comment by qkqpttgf** [comment]
#657 ,
Fixed 2 weeks ago.
overlay an old project CAN NOT update nodejs version.
Please delete the old project in vercel, then deploy a new project with latest code (not the Releases).

**Comment by cv2wx** [comment]
Thx, I did so. It works.
