### ISSUE TITLE
当使用手机端打开视频文件时，出现 Error: Can't find flvjs 错误

### ISSUE THREAD

**Issue by Moskic** [qkqpttgf/OneManager-php#704]
系统为iOS16.6，当尝试使用Chrome和Safari打开格式为flv的视频文件时，都出现了下面的错误

> Error: Can't find flvjs.
> Video load failed.

尝试使用电脑，iPad打开相同的视频文件，均未出现此错误，视频可以正常播放

OneManager-php为最新版本，主题为默认主题

**Comment by Moskic** [comment]
补充图片

![pic1](https://github.com/qkqpttgf/OneManager-php/assets/39458557/d29a828f-c7df-4bc9-b0de-4cf44847cf72)
![pic2](https://github.com/qkqpttgf/OneManager-php/assets/39458557/bbf7d90b-cc02-45b2-9f62-23a827825cca)

**Comment by qkqpttgf** [comment]
flv本来就不支持，如果突然支持的话，是浏览器劫持了播放器
