### ISSUE TITLE
请求添加https://domcloud.co/部署支持

### ISSUE THREAD

**Issue by Sayafx** [qkqpttgf/OneManager-php#705]
https://domcloud.co/

**Comment by qkqpttgf** [comment]
看了一眼，这不就是空间嘛，随便你丢上去就行了吧

**Comment by Sayafx** [comment]
这个平台的nginx是通过编写yaml来配置的，我不懂如何去配置伪静态，今天上午尝试了许多次无果。

**Comment by qkqpttgf** [comment]
> 1. Click '+ Add a website' in 'Website List' page;  
> 2. Click `Upload or clone from the Internet`, and 'paste Git Repo/Zip URL' input `https://github.com/qkqpttgf/OneManager-php`, click 'Apply this template', change the domain at right, then click 'Add a Website';  
> 3. Waiting everythings done;  
> 4. Click the menu [Check] at top, and select `Check NGINX`;  
> 5. Delete the [locations] (and delete its children), 3 lines;  
> 6. Input `  rewrite: ^/(?!.well-known)(.*)$ /index.php?/$1 last` instead, click 'Save';  
> 7. Open your url to start.

**Comment by qkqpttgf** [comment]
> > 1. Click '+ Add a website' in 'Website List' page;
> > 2. Click `Upload or clone from the Internet`, and 'paste Git Repo/Zip URL' input `https://github.com/qkqpttgf/OneManager-php`, click 'Apply this template', change the domain at right, then click 'Add a Website';
> > 3. Waiting everythings done;
> > 4. Click the menu [Check] at top, and select `Check NGINX`;
> > 5. Delete the [locations] (and delete its children), 3 lines;
> > 6. Input `  rewrite: ^/(?!.well-known)(.*)$ /index.php?/$1 last` instead, click 'Save';
> > 7. Open your url to start.

平台改了，免费用户要自己带域名了，没有locations了，直接加上rewrite语句。

**Comment by huidaoweilai2024** [comment]
Unable to add OneDrive account, returning to 'no refresh token'.

**Comment by qkqpttgf** [comment]
> Unable to add OneDrive account, returning to 'no refresh token'.

Where? How?
