### ISSUE TITLE
能不能快速定位文件

### ISSUE THREAD

**Issue by 362227** [qkqpttgf/OneManager-php#707]
我测试了阿里云和百度网盘，文件夹下文件数太多，根本无法访问，文件数不多的可以。比如我确定那个目录下有0123456.jpg，我自己修改url，依旧是无法打开，能否快速定位文件呢（例如调用网盘的搜索功能）。其他挂载程序也有同样问题。

**Comment by qkqpttgf** [comment]
没法哦，
阿里跟百度是按id来定位文件，所以要把这个目录下文件全加载了，才能知道确切文件的信息，
除非程序也按id来，然后你知道这个文件的id，这样才能直接输入来定位。
onedrive就不同了，它本身就是按文件名路径来定位的，所以它可以直接输入整条url就能直接定位。
