### ISSUE TITLE
关于管理登录的问题

### ISSUE THREAD

**Issue by Seeger0216** [qkqpttgf/OneManager-php#71]
我使用cloudflare workers套壳了heroku的网址以便加速下载，但是我在cf套壳的网址上无法登录管理，尽管密码是正确的，只能在heroku上面登录，请问是我的操作哪里有问题吗？
纯小白，真的啥都不懂，请见谅

**Comment by qkqpttgf** [comment]
我的登录地址是【任何页面 + ?登录地址】，CDN的似乎只判断前面的路径，不管后面带不带参数，然后就会有点问题，我目前没法解决。
另：你CF加速heroku？可能可以，但，你达不到你想到的【以便加速下载】的目的。

**Comment by Seeger0216** [comment]
目前还没有发现解决方案，但是不是很影响使用。另外heroku对我移动宽带支持很不好，需要很久，反倒是cf能跑满30MB/s的带宽？反正很玄学……谢谢了。
