### ISSUE TITLE
Replit部署开始收费了

### ISSUE THREAD

**Issue by dnasdw** [qkqpttgf/OneManager-php#710]
Replit好像改了新部署,老的模式失效了.

**Comment by qkqpttgf** [comment]
截图，哪一步收费了

**Comment by dnasdw** [comment]
用以前的链接访问(包括你的demo),点击后都会提示:

Replit Legacy Hosting has migrated to Deployments
To host your application, use Replit Deployments.
[Learn more about hosting on Replit](https://replit.com/site/hosting)

点击里面的Deploy按钮,出现的3个选项都是收费相关的.

如果只是Run,目前还可以,但好像没有比较短的repl.co链接了,都是一个长串的uid.global.replit.dev链接.

**Comment by qkqpttgf** [comment]
> 用以前的链接访问(包括你的demo),点击后都会提示:
> 
> Replit Legacy Hosting has migrated to Deployments To host your application, use Replit Deployments. [Learn more about hosting on Replit](https://replit.com/site/hosting)
> 
> 点击里面的Deploy按钮,出现的3个选项都是收费相关的.
> 
> 如果只是Run,目前还可以,但好像没有比较短的repl.co链接了,都是一个长串的uid.global.replit.dev链接.

好气
