### ISSUE TITLE
Rewrite Engine Error

### ISSUE THREAD

**Issue by nadithpro** [qkqpttgf/OneManager-php#711]
![image](https://github.com/qkqpttgf/OneManager-php/assets/116380737/5cdc5d9d-a445-434c-9224-7e6533d3be61)

As you can see in this picture it's shows like this. What should I do?

**Comment by laiaqwq** [comment]
You missed step 2
Make the rewrite works, the rule is in .htaccess file, make sure any query redirect to index.php.
See https://github.com/qkqpttgf/OneManager-php/issues/53#issuecomment-624397288

**Comment by nadithpro** [comment]
This is my .htaccess file. Can you help me to fix this.


# # Apache
# # LoadModule rewrite_module modules/mod_rewrite.so
# # AllowOverride All
RewriteEngine On
# RewriteCond $1 !^(.well-known)
RewriteRule ^(.*) index.php?/$1 [L]

###-----------------------------------
### nginx
# rewrite ^/(?!.well-known)(.*)$ /index.php?/$1 last;
#
### nginx Subdirectory 在子目录中使用
# location /OneManager2/ {
#  rewrite ^/(.*)$ /OneManager2/index.php?/$1 last;
# }
#
### caddy
# rewrite {
#     to index.php?/$1
# }
#
### caddy2 Caddyfile
# @try_files {
#     not path /.well-known/*
#     file {
#         try_files index.php
#     }
# }
# rewrite @try_files {http.matchers.file.relative}
#
###-----------------------------------

**Comment by laiaqwq** [comment]
If your web server is not Apache, you should manually change the configuration file of your web server. The configuration methods of different web servers are different. you should copy the content corresponding with your web server and add it to the configuration file (like nginx.conf in nginx or Caddyfile in Caddy ... )of your web server.
