### ISSUE TITLE
vercel部署失败

### ISSUE THREAD

**Issue by Dreamkaka** [qkqpttgf/OneManager-php#713]
不管是拿vercel-cli部署还是拿教程的网站部署都会提示
`Error: Please install npm before continuing`
想问一下这该怎么办

**Comment by qkqpttgf** [comment]
刚刚测试，没有问题啊

**Comment by qkqpttgf** [comment]
![de68e4e71be5f241cb2b596424ab16a4](https://github.com/qkqpttgf/OneManager-php/assets/45693631/35d223ec-90c5-4dfd-a3bf-210a122aa895)
刚刚有远程一个人，我这边是75，你们是71，npm应该是vercel的事，可能你们新服务器上的vercel-php有点不太对劲。

**Comment by Dreamkaka** [comment]
hmmm，这就很怪了，要不然本地下载一份然后拿`vercel.json`定义一下php的版本然后再拿vercel的cli上传吗？

**Comment by lss53** [comment]
点击开始安装程序后，一片空白
![QQ截图20240128140130](https://github.com/qkqpttgf/OneManager-php/assets/12656589/7439dd4e-97a1-46c7-9750-c6a5eda0cb7f)
![QQ截图20240128140300](https://github.com/qkqpttgf/OneManager-php/assets/12656589/51a721e7-950e-4fb3-b487-1e1c7d4b4480)

**Comment by qkqpttgf** [comment]
> 点击下图中的「点击开始安装程序」后，跳转的地址中有「install0」，且网页是空白 ![QQ截图20240128140130](https://private-user-images.githubusercontent.com/12656589/300240717-7439dd4e-97a1-46c7-9750-c6a5eda0cb7f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1OTM5NjMsIm5iZiI6MTcwNjU5MzY2MywicGF0aCI6Ii8xMjY1NjU4OS8zMDAyNDA3MTctNzQzOWRkNGUtOTdhMS00NmM3LTk3NTAtYzZhNWVkYTBjYjdmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMwVDA1NDc0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ2MjRmY2QyYTYzMjI5MGJlZDFkOTNmYzUzYTcwMWNlMzJlNWU2M2M3MWM0MDQzYzQ5YjY0Y2I0MTc5M2VlYTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Sx1VvqlT5WTBIi6VnbbQsDRF5ogWG7JkFzUBr7kh1S8)

刚更新了vercel-php为0.6.1，你们删了重新部署试试。

**Comment by Dreamkaka** [comment]
已经部署成功了

**Comment by huidaoweilai2029** [comment]
Clicking on 'Click to install the project' does not go to the next step

**Comment by Jerrychenshen** [comment]
和楼上一样，Clicking on 'Click to install the project' does not go to the next step

**Comment by myjwgit** [comment]
和楼上一样

**Comment by YYQK0113** [comment]
![屏幕截图 2024-02-20 181923](https://github.com/qkqpttgf/OneManager-php/assets/82374296/bf0dfd1b-515c-478c-a793-f4ef0a45477f)
![屏幕截图 2024-02-20 181942](https://github.com/qkqpttgf/OneManager-php/assets/82374296/3a000629-579a-40b2-b1f5-64628be8ca8e)
点击下图中的「点击开始安装程序」后，跳转的地址中有「install0」，但网页没变化。多次重新部署情况一样。救救。

**Comment by qkqpttgf** [comment]
> 和楼上一样

应该修复了，重新下载部署试试。

**Comment by qkqpttgf** [comment]
> Clicking on 'Click to install the project' does not go to the next step

fixed now, maybe, plz try again
