### ISSUE TITLE
好像阿里网盘改版了

### ISSUE THREAD

**Issue by funkyhunty** [qkqpttgf/OneManager-php#714]
是不是大家都不能用了？

**Comment by qkqpttgf** [comment]
应该是了

**Comment by qkqpttgf** [comment]
试试AliOpen分支

**Comment by 362227** [comment]
> 试试AliOpen分支

求更新，很需要

**Comment by luxuxl** [comment]
同问，阿里云盘报错Error
No refresh_token config, please AddDisk again or wait minutes.
adrive

**Comment by qkqpttgf** [comment]
> 同问，阿里云盘报错Error No refresh_token config, please AddDisk again or wait minutes. adrive

那你可能就没添加成功吧，再添加一次啊，英文就从来不看呗

**Comment by qkqpttgf** [comment]
> > 试试AliOpen分支
> 
> 求更新，很需要

自己更新啊，又需要，又不试，你不试我怎么知道有没有问题，我怎么并主支
