### ISSUE TITLE
e5开发者添加onedrive，用自己申请的应用ID与机密，回显 401

### ISSUE THREAD

**Issue by lss53** [qkqpttgf/OneManager-php#715]
按[大佬 spencerwooo 教程](https://ovi.swo.moe/zh/docs/advanced)申请的c lient_id 和 client_secret ，其中，Web重定向URI填写的是：`https://scfonedrive.github.io`，client_secret用的明码，回显详细代码如下：

`{
    "error": "invalid_client",
    "error_description": "AADSTS7000215: Invalid client secret provided. Ensure the secret being sent in the request is the client secret value, not the client secret ID, for a secret added to app '734ef928-d74c-4555-8d1b-d942fa0a1a41'. Trace ID: 3d590ddb-ad36-4b84-9139-9947accb2200 Correlation ID: ec6aec5c-aaae-4308-9f45-ee4de8b53e7c Timestamp: 2024-01-31 08:52:02Z",
    "error_codes": [
        7000215
    ],
    "timestamp": "2024-01-31 08:52:02Z",
    "trace_id": "3d590ddb-ad36-4b84-9139-9947accb2200",
    "correlation_id": "ec6aec5c-aaae-4308-9f45-ee4de8b53e7c",
    "error_uri": "https:\/\/login.microsoftonline.com\/error?code=7000215"
}`

使用内置可以正常显示 onedrive 网盘内容，谢谢！

**Comment by qkqpttgf** [comment]
你就不能翻译一下，你肯定填错了
