### ISSUE TITLE
vercel部署失败

### ISSUE THREAD

**Issue by qqlittleice233** [qkqpttgf/OneManager-php#722]
![image](https://github.com/qkqpttgf/OneManager-php/assets/60041789/bc4e36f9-249c-4440-bea0-31fcf12e2c3f)
![image](https://github.com/qkqpttgf/OneManager-php/assets/60041789/d44019e6-02e5-498a-a03c-b4a1d36b07a5)

**Comment by qkqpttgf** [comment]
一、等vercel-php那边修。
二、临时按如下步骤使用：

> 1. 先部署失败一次；  
> 2. 去vercel面板，找到这个失败的项目，点进去，找到Setting里面General里的Nodejs version，下拉改成18；  
> 3. 回到部署页面，再覆盖部署一次。  

应该就好了。
