### ISSUE TITLE
报错页面，UserNotAllowedAccessDrive，请问如何解决

### ISSUE THREAD

**Issue by SmallKunKun** [qkqpttgf/OneManager-php#726]
Error
Array{
    "body": "{\"code\":\"UserNotAllowedAccessDrive\",\"message\":\"user not allowed access drive\",\"data\":null,\"headers\":null,\"requestId\":\*",\"pdsRequestId\":null,\"resultCode\":\"UserNotAllowedAccessDrive\",\"display_message\":null}",
    "stat": 403,
    "error": {
        "stat": 403,
        "code": "Error",
        "message": "{\"code\":\"UserNotAllowedAccessDrive\",\"message\":\"user not allowed access drive\",\"data\":null,\"headers\":null,\"requestId\":\"*",\"pdsRequestId\":null,\"resultCode\":\"UserNotAllowedAccessDrive\",\"display_message\":null}"
    }
}

**Comment by qkqpttgf** [comment]
User Not Allowed Access Drive ，看不懂英文可以翻译……
这个我没法解决，换号吧
