### ISSUE TITLE
vercel方面是否可以添加isr功能

### ISSUE THREAD

**Issue by DSLZL** [qkqpttgf/OneManager-php#728]
[此为介绍](https://vercel.com/docs/incremental-static-regeneration)

**Comment by qkqpttgf** [comment]
我这边应该添加不了，我们的php程序是基于vercel-php的，这个可能是vercel-php那边才能玩的，不过，它似乎是基于nodejs的，大概玩不了nextjs
所以，继续一次配置一次部署吧~
