### ISSUE TITLE
【bug反馈】对游客隐藏的guestup_path路径可通过输入目录名直接访问

### ISSUE THREAD

**Issue by sailcom** [qkqpttgf/OneManager-php#730]
比如某站点 `www.example.com`
网盘目录：`/images` ，此文件夹下包括每年上传的图片：`/2022`、`/2023`、`/2024`
设置了游客上传(隐藏)路径 `guestup_path = /images`
那么，作为一个游客，当访问 `www.example.com` 时，确实是无法看到 `/2022`、`/2023`、`/2024` 这几个文件夹。
但是，当游客直接访问 `www.example.com/2022`、`www.example.com/2023`、`www.example.com/2024` 时，
子目录中的文件全部会暴露出来。

**Comment by qkqpttgf** [comment]
啊是的，是这样设定的。
你可以给游客上传目录加个密码，然后再将 `downloadencrypt` 设置一下就可以`下载文件跳过密码，但目录不可列表`。

**Comment by sailcom** [comment]
> 啊是的，是这样设定的。 你可以给游客上传目录加个密码，然后再将 `downloadencrypt` 设置一下就可以`下载文件跳过密码，但目录不可列表`。

感谢🙏
