### ISSUE TITLE
Vercel部署方式白屏

### ISSUE THREAD

**Issue by GuihongWang** [qkqpttgf/OneManager-php#731]

**Comment by wuyilingwei** [comment]
+1
![{20410277-11EA-46D5-A805-546303CAA5E0}](https://github.com/user-attachments/assets/2da0254d-c66d-408d-a1b9-cc6a99e50413)
注意到有一次自动的部署

**Comment by wuyilingwei** [comment]
回滚到上个版本可以修复

**Comment by qkqpttgf** [comment]
vercel-php有个更新，0.7.2只能20.x但它标着18.19，气晕
在家不方便操作，上个github都麻烦

**Comment by zjw2017** [comment]
> vercel-php有个更新，0.7.2只能20.x但它标着18.19，气晕 在家不方便操作，上个github都麻烦

vercel-php: 0.6.2
Node version: 18.19.18

即可解决问题，感谢提出解决方案

**Comment by zjw2017** [comment]
> vercel-php有个更新，0.7.2只能20.x但它标着18.19，气晕 在家不方便操作，上个github都麻烦

虽然进入了安装页，最后执行结果是ERROR

**Comment by wuyilingwei** [comment]
> > vercel-php有个更新，0.7.2只能20.x但它标着18.19，气晕 在家不方便操作，上个github都麻烦
> 
> 虽然进入了安装页，最后执行结果是ERROR

还是不行吗（？）

**Comment by zjw2017** [comment]
> > > vercel-php有个更新，0.7.2只能20.x但它标着18.19，气晕 在家不方便操作，上个github都麻烦
> > 
> > 虽然进入了安装页，最后执行结果是ERROR
> 
> 还是不行吗（？）

不行（
官方的demo也白了

**Comment by rowink** [comment]
部署了很久的，进入目录也白屏了，只能加载出主界面

**Comment by wuyilingwei** [comment]
能不能对运行环境先进行修改？我之前有个朋友就搞过类似的，对cf pages直接进行环境更新，然后再进行部署？

**Comment by qkqpttgf** [comment]
> > vercel-php有个更新，0.7.2只能20.x但它标着18.19，气晕 在家不方便操作，上个github都麻烦
> 
> 虽然进入了安装页，最后执行结果是ERROR

因为在安装时，OM会读取vercel-php的package.json来更新vercel-php的版本，所以现在会又变成0.7.2，导致还是出错

**Comment by zjw2017** [comment]
> > > vercel-php有个更新，0.7.2只能20.x但它标着18.19，气晕 在家不方便操作，上个github都麻烦
> > 
> > 虽然进入了安装页，最后执行结果是ERROR
> 
> 因为在安装时，OM会读取vercel-php的package.json来更新vercel-php的版本，所以现在会又变成0.7.2，导致还是出错

我尝试回退到0.6.2，似乎修复了这个问题，但可能是临时解决（

**Comment by zjw2017** [comment]
我尝试回退vercel-php至0.6.2，似乎回到了正轨。我将修复方法公布，大家可以试试。


打开：https://scfonedrive.github.io/Vercel/Deploy.html

1.下载修改过的代码包：
https://github.com/zjw2017/OneManager-php/archive/refs/heads/master.zip

2.输入你的Vercel Token和上传代码包

3.选择zip file

4.选择修改过的代码包

5.修改vercrl-php版本为0.6.2
即："runtime": "vercel-php@0.6.2" (Node version: 18.19.18)

6.为你的项目取个名字

7.单击Deploy，等待项目url出现


至此，你应该可以使用项目url进行安装。
选择你的语言，输入你的Vercel Token，输入你的管理密码。
你的OneManager应该正常工作了

**Comment by Emotion04** [comment]
使用vercel部署隔几个月就会出现白屏情况，这是为何

**Comment by qkqpttgf** [comment]
vercel-php已修复，0.7.3，请从vercel那边复制config出来替换后再重新部署。

**Comment by Emotion04** [comment]
> vercel-php已修复，0.7.3，请从vercel那边复制config出来替换后再重新部署。

请问config目录在哪里？我在.data下找到一个，但是那似乎只是密码

**Comment by qkqpttgf** [comment]
> > vercel-php已修复，0.7.3，请从vercel那边复制config出来替换后再重新部署。
> 
> 请问config目录在哪里？我在.data下找到一个，但是那似乎只是密码

啥config目录？你在理解什么…… #488 ，

**Comment by Emotion04** [comment]
> > > vercel-php已修复，0.7.3，请从vercel那边复制config出来替换后再重新部署。
> > 
> > 请问config目录在哪里？我在.data下找到一个，但是那似乎只是密码
> 
> 啥config目录？你在理解什么…… #488 ，

我是部署在服务器上的，看文档说![Screenshot_20241022_095440_com.tencent.mobileqq.jpg](https://github.com/user-attachments/assets/e560da28-254f-4339-b686-f20ab8b1d488)

是.data/config.php里，但是我粘贴后并没有配置数据。我打开文件看发现那只是一个登录密码

**Comment by Emotion04** [comment]
> > > > vercel-php已修复，0.7.3，请从vercel那边复制config出来替换后再重新部署。
> > > 
> > > 请问config目录在哪里？我在.data下找到一个，但是那似乎只是密码
> > 
> > 啥config目录？你在理解什么…… #488 ，
> 
> 我理解的config是包含css设置，环境变量里那些东西，现在有吗？我重新部署重新配置感觉很麻烦，不知道能否导出导入配置？

**Comment by qkqpttgf** [comment]
> 是.data/config.php里，但是我粘贴后并没有配置数据。我打开文件看发现那只是一个登录密码

那你原来就只有密码呗

**Comment by Jacknolfskin** [comment]
vercel重新部署，使用0.73，install没有语言选项
![微信截图_20241024110631](https://github.com/user-attachments/assets/6c2cb28b-7254-4466-bd1f-41dee04e14b2)
