### ISSUE TITLE
域名无法访问主界面，但换个域名就能访问主界面

### ISSUE THREAD

**Issue by nulijiazaizhong** [qkqpttgf/OneManager-php#734]
主域名在edge和chrome上无法访问主界面但在火狐上可以正常访问，副域名就能访问主界面，主域名除无法访问主页面以外，其余页面均可访问，副域名不受影响

**Comment by nulijiazaizhong** [comment]
https://github.com/user-attachments/assets/b65ea699-583a-4c1e-9976-9ccd1bf0271e

**Comment by qkqpttgf** [comment]
程序能正常跑起来，有域名或IP能访问，说明OneManager-php它工作正常，其它别的域名访问不了，那是其它方面的问题了，我觉得不属于程序管。
（视频看不清，你自己在命令行里curl再看看问题在哪吧）
