### ISSUE TITLE
使用edge后台登陆问题

### ISSUE THREAD

**Issue by zy111x** [qkqpttgf/OneManager-php#736]
使用edge后台登陆时出现如图问题
![image](https://github.com/user-attachments/assets/739054d3-d742-44d7-8a59-0029664157cd)
但是在谷歌就不会

**Comment by qkqpttgf** [comment]
首先，你念一下这个提示是啥意思，这个不是【问题】只是【提示】；
然后，我觉得你用的是老版本，几年前就改成全从程序加载不从CDN加载了。
