### ISSUE TITLE
关于阿里云函数计算问题

### ISSUE THREAD

**Issue by zll0823** [qkqpttgf/OneManager-php#74]
安装时，到选择语言那一步，点击确认，显示Error

**Comment by wekingchen** [comment]
我也是一样的问题，填写好 AccessKeyID & AccessKeySecret 之后，点击确认，显示Error

**Comment by qkqpttgf** [comment]
判断的时候语句写错，配置其实已经写进去了，但判断成没写进去，刚刚改好，请试试

**Comment by wekingchen** [comment]
安装ok了，但在添加Onedrive盘那一步，选择世纪互联，填入自己申请应用ID与机密后（跟目前SCF使用的同一个），在跳转到Office获取refresh_token后，再次跳转回来，会显示0 null。

**Comment by qkqpttgf** [comment]
> 安装ok了，但在添加Onedrive盘那一步，选择世纪互联，填入自己申请应用ID与机密后（跟目前SCF使用的同一个），在跳转到Office获取refresh_token后，再次跳转回来，会显示0 null。
> 
> 又试了一下，选用OneManager默认的应用ID与机密，也是返回0 null。
> 
> 国际版没有这个问题，使用默认应用ID与机密添加成功，但点击目录进入报错：
> {"ErrorCode":"DomainRouteNotFound","ErrorMessage":"no route found in domain 'www.mydomain.com' for path '/apk/' and method 'GET'"}

自定义域名时，路径要用 /* 。

**Comment by zll0823** [comment]
可以成功安装了
