### ISSUE TITLE
无法移动文件

### ISSUE THREAD

**Issue by ajax79** [qkqpttgf/OneManager-php#75]
开发者你好，

首先感谢你，很好的开源项目，而且还一直在迭代更新。
我的issues是OneManager-php用的heroku和腾讯云函数方式部署后，一切正常除了无法移动文件，没有错误提示。
然后用您另一个项目herokuOnedrive（https://github.com/qkqpttgf/herokuOnedrive）在heroku部署后，可以移动文件，但无法删除，错误提示：
404
"error":{
"code":"itemNotFound",
"message":"The resource could not be found.",
"innerError":{
"date":"2020-06-13T07:09:05",
"request-id":"cfa5c57a-7f60-4aef-ae0a-309a4c765687"
 }
}
}

谢谢，盼复。

**Comment by qkqpttgf** [comment]
是有特别的字符吗？改为纯字母试试？？

**Comment by ajax79** [comment]
> 是有特别的字符吗？改为纯字母试试？？

试了一个名字简单的文件，也一样。

这次又试了一次，选择点击“移动”后，自动返回刷新，文件却没有动地方。然后赶紧再次做移动操作，会出现以下错误提示：
400
"error":{
"code":"invalidRequest",
"message":"Invalid request",
"innerError":{
"date":"2020-06-13T07:37:42",
"request-id":"c5d84288-b481-4d4c-a5e3-250d56f3138c"
}
}
}

**Comment by qkqpttgf** [comment]
经测试，我demo正常。
请确认，你用的是不是最新版本，以及，是哪个主题，还有，你添加的盘，是不是共享链接。

**Comment by ajax79** [comment]
> 经测试，我demo正常。
> 请确认，你用的是不是最新版本，以及，是哪个主题，还有，你添加的盘，是不是共享链接。

还真是~~根据你的信息，换成classic主题后问题解决！

原信息（最新版，nchyn_grey.html主题，E3/E5盘，非共享链接）
