### ISSUE TITLE
建议：支持华为云函数工作流FunctionGraph搭建OneManager

### ISSUE THREAD

**Issue by XmJwit** [qkqpttgf/OneManager-php#76]
介绍：[链接](https://support.huaweicloud.com/usermanual-functiongraph/functiongraph_01_0201.html)
价格计费：[链接](https://www.huaweicloud.com/pricing.html?tab=detail#/function)
 最后，多谢！😁

**Comment by qkqpttgf** [comment]
啊，为什么又要适配一个
https://console.huaweicloud.com/functiongraph/
没看到流量怎么计费的，只看到100万次0元

**Comment by XmJwit** [comment]
> 啊，为什么又要适配一个
> https://console.huaweicloud.com/functiongraph/
> 没看到流量怎么计费的，只看到100万次0元

大佬有时间就适配一下，**非必要性需求**

总费用 = 请求次数费用 + 计量时间费用。
![image](https://user-images.githubusercontent.com/36185379/85390243-1d930280-b57b-11ea-92df-57993e277d16.png)

**Comment by qkqpttgf** [comment]
有个华为专用分支，去玩玩吧，跟阿里不太兼容，应该不会并主支了，所以一键更新干脆不做了。
