### ISSUE TITLE
踏破铁鞋无觅处，太完美了了这个程序

### ISSUE THREAD

**Issue by 8838** [qkqpttgf/OneManager-php#79]
有一点。初始设置的密码怎么修改呢。设置了一个弱密码。想改一下。谢谢

**Comment by 8838** [comment]
还希望增加一个看图模式。目前的每看一张图都跳一个url。网盘有千万张图……

**Comment by fzlychee2019** [comment]
config.php文件里就可以直接修改密码

**Comment by qkqpttgf** [comment]
> 还希望增加一个看图模式。目前的每看一张图都跳一个url。网盘有千万张图……

查看缩略图不行吗？或者可以勾上原图。

**Comment by 8838** [comment]
> > 还希望增加一个看图模式。目前的每看一张图都跳一个url。网盘有千万张图……
> 
> 查看缩略图不行吗？或者可以勾上原图。

就是这个意思。真心希望能优化这个功能。访客大多不知道点击原图再点击缩略图。希望能有一个按钮。点一下。大图全部就出来了。感谢
