### ISSUE TITLE
OneDriver无管理员绑定失败

### ISSUE THREAD

**Issue by EchoGroot** [qkqpttgf/OneManager-php#80]
Error! 有误！No code from MS! 微软code为空！
error=invalid_client&error_description=AADSTS650051:+Using+application+'OneManager'+is+currently+not+supported+for+your+organization+mails.cqjtu.edu.cn+because+it+is+in+an+unmanaged+state.+An+administrator+needs+to+claim+ownership+of+the+company+by+DNS+validation+of+mails.cqjtu.edu.cn+before+the+application+OneManager+can+be+provisioned. Trace+ID:+be822684-2bf1-40bc-8254-515c9d82b303 Correlation+ID:+d2378cf8-6130-4600-842c-0b63bee223db Timestamp:+2020-06-25+08:26:07Z&state=
请问OneDriver无管理员的话就不能使用吗？因为是学生邮箱，是没有管理员的。

**Comment by qkqpttgf** [comment]
是的，请看里面的英文，你可以通过共享链接的方式来玩。
