### ISSUE TITLE
BadRequest 返回首页 

### ISSUE THREAD

**Issue by 10963273** [qkqpttgf/OneManager-php#83]
heroku 和主机搭建的都出现

BadRequest
返回首页

Unable to retrieve user's mysite URL.
返回

大佬知道哪里出了问题吗？

**Comment by zigou23** [comment]
+1

**Comment by 10963273** [comment]
我的账号出问题了，账号能登录onedrive 打开应用程序出现错误。重新换个onedrive账号就好了。目前还不知道为什么会出现这种情况。

**Comment by qkqpttgf** [comment]
最近几个域下的帐号都这样，帐号能登录office.com，但点onedrive进去是报错的。
