### ISSUE TITLE
希望支持多盘分别绑定自定义域名的功能

### ISSUE THREAD

**Issue by YohoYang** [qkqpttgf/OneManager-php#84]
大概可能是如下的实现
总设置中有个开关，开启后屏蔽界面顶部的多盘切换功能，同时不允许 xxxx.com/盘名/ 访问特定盘符 
然后每个盘中，设置不同的自定义域名，这个域名访问后直接对应到对应的盘内，多盘之间互不可见

感觉和目前的domain_path设置不太一样，目前要完全实现这种功能似乎需要多部署几个程序来分别设置

虽然是有点伸手的请求，但姑且还是提一下哈哈，如果太麻烦不搞也没事。已经是非常棒的程序了，感谢~

**Comment by qkqpttgf** [comment]
啊，以后有空再说，然后等我想到怎么实现再改

**Comment by YohoYang** [comment]
> 啊，以后有空再说，然后等我想到怎么实现再改

好的好的，感谢！
