### ISSUE TITLE
程序十分完善，希望作者能增加反代播放功能

### ISSUE THREAD

**Issue by Telle87** [qkqpttgf/OneManager-php#88]
程序十分完善，希望作者能增加反代播放功能（目前只是设置反代后，下载是反代的，视频播放不是反代地址），还希望能增加.avi等后缀的视频播放功能。
谢谢！

**Comment by qkqpttgf** [comment]
了解，收到，马上安排， one year later

**Comment by qkqpttgf** [comment]
应该是你采用的主题是php后缀的，所以没法控制了，旧主题里面目前不想去动它
