### ISSUE TITLE
无法获取应用ID和机密。

### ISSUE THREAD

**Issue by Micraow** [qkqpttgf/OneManager-php#89]
我现在用的是最新版本的存储库，但是在申请应用机密和ID时，却遇到了错误。
Thu, 16 Jul 2020 01:31:26 GMT | Hijkf | /+KuQ
请问我该如何解决这样子的问题？这是微软的服务器出错了，还是我的配置有误？

**Comment by qkqpttgf** [comment]
个人帐号还是A1？还是E5？
E5有续杯需要才用自己的ID跟SECRET，其它所有的都不需要，没有必要打勾。

**Comment by Micraow** [comment]
是E5.还要用来续期呢。

**Comment by Micraow** [comment]
麻烦帮我看下，有什么要点要注意的，我在想，是不是我配置的时候有问题啊？应该就是按一下那个紫色的按钮，然后再跳转出来的页面，里面填好信息，然后登录后台添加云盘，就好了吧？希望我的步骤没有错误。

**Comment by qkqpttgf** [comment]
#96 看看这个
