### ISSUE TITLE
刷新缓存时跳转前会出现一行乱码以及跳转https的问题

### ISSUE THREAD

**Issue by sunnyhu2003** [qkqpttgf/OneManager-php#9]
鍒锋柊缂撳瓨，强迫症难受，去代码里面改，一更新又复原。。。。
还有就是，每次更新我都要重新补http跳https的代码，能否在下个版本在后台加一个开关，省的麻烦

**Comment by qkqpttgf** [comment]
刷新缓存这几个字，在20200212已经正常了，你更新后应该是正常了啊。
https开关，可以。

**Comment by sunnyhu2003** [comment]
> 刷新缓存这几个字，在20200212已经正常了，你更新后应该是正常了啊。
> https开关，可以。

我更新了啊，依旧不正常。要更到20200215才正常
