### ISSUE TITLE
SFC安装获得token后出错

### ISSUE THREAD

**Issue by tvision08** [qkqpttgf/OneManager-php#92]
提示：{"errorCode":-1,"errorMessage":"user code exception caught","stackTrace":"Exception: failed to get access_token. in /var/user/index.php:215\nStack trace:\n#0 /var/user/index.php(61): list_files('/')\n#1 /var/runtime/php7/bootstrap.php(46): main_handler(Array, Array)\n#2 /var/runtime/php7/bootstrap.php(204): __scf_bootstrap_\\EventHandler-\u003ehandle(Object(stdClass), Object(stdClass))\n#3 /var/runtime/php7/bootstrap.php(227): __scf_bootstrap_\\__main_for_scf()\n#4 {main}"}

**Comment by qkqpttgf** [comment]
当前index.php总共132行，你的报错说215行报的错？？？
请你确定一下你用的代码，谢谢

**Comment by tvision08** [comment]
谢谢，大佬，我检查下

**Comment by tvision08** [comment]
现在文件检查正常了，又出现如下错误，不知道哪里出问题了？
{"errno":403,"error":"Invalid scf response. expected scf response valid JSON."}

**Comment by qkqpttgf** [comment]
要么你用的代码不对，要么你API网关里面集成响应没勾，其它的我也想不到了

**Comment by tvision08** [comment]
终于搞定了，谢谢大佬了！
