### ISSUE TITLE
请问认证的重定向地址是什么

### ISSUE THREAD

**Issue by lhllhx** [qkqpttgf/OneManager-php#94]
现在微软通过向导注册应用出现了问题（所有OneDrive项目都是这样）要手动注册，请问重定向的url是什么
![image](https://user-images.githubusercontent.com/52107206/88122937-68e11500-cbfc-11ea-8748-70edaa17d39a.png)

**Comment by qkqpttgf** [comment]
https://scfonedrive.github.io
