### ISSUE TITLE
建议为 JSON 响应设置适当的 Content-Type 头

### ISSUE THREAD

**Issue by Lemmingh** [qkqpttgf/OneManager-php#95]
## 问题

#73 引入了 JSON 列出目录内容，但似乎没有正确设置响应头：

https://github.com/qkqpttgf/OneManager-php/blob/10ba4218af49f1a1c4f351c550049ca0cae1e04a/common.php#L435

## 建议

建议设置

```http
Content-Type: application/json
```

尽管在遇到文本时，现在的客户端大多能侦测内容，但“侦测”不是一个稳定可靠的方案。

而且正确设置 `Content-Type` 头也是 IETF 建议的行为。

**Comment by qkqpttgf** [comment]
感谢，已经加入
