### ISSUE TITLE
申请应用id和机密出错

### ISSUE THREAD

**Issue by Ecalose** [qkqpttgf/OneManager-php#96]
此服务暂时出现了问题，请重试。如果仍然看到此消息，请稍后再试。

**Comment by Ecalose** [comment]
emmm，试了很多个账号都是这样

**Comment by lhllhx** [comment]
#94

**Comment by tvision08** [comment]
可以手动申请的。

**Comment by Ecalose** [comment]
> 可以手动申请的。

emmm，那得知道重定向url和权限吧

**Comment by lhllhx** [comment]
> 重定向url

权限无非就是filereadwrite，现在重点是重定向url

**Comment by brilliantmister** [comment]
我也是重新定向的Url错误，有没有大佬告诉我们定向的Url是什么。

**Comment by qkqpttgf** [comment]
https://scfonedrive.github.io

**Comment by Ecalose** [comment]
> https://scfonedrive.github.io

okk
