### ISSUE TITLE
上传失败

### ISSUE THREAD

**Issue by Micraow** [qkqpttgf/OneManager-php#99]
我用Sharepoint 链接绑定了一个文件夹，并允许游客上传，但是却遇到了一个问题。
具体如下
`images.jpeg
3.45 KB	{"error":{"code":"accessDenied","message":"Access denied"}}
`
请问我该如何解决？对了，我想知道这个上传的方法是切块上传还是整式上传？也许我术语用的不标准，但我实际上想问的就是它上传的最大限度是多少？我指速度和文件大小。

**Comment by qkqpttgf** [comment]
首先，你应该是共享链接shareurl，并不是sharepoint。
然后，你可能没有允许编辑。
切块，5M，微软推荐10M，最大60M。

**Comment by Micraow** [comment]
我后来确认了一下，是shareurl，共享了onedrive的一个文件夹，而且选择了允许所有人编辑。
你指的切块那个是指我可以上传无限大小的文件吗？
